# Export installed CRAN-package longitudinal / panel example datasets.

output_dir <- file.path("sample", "longitudinal_examples")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

write_example <- function(package, dataset, file, columns = NULL, transform = identity) {
  if (!requireNamespace(package, quietly = TRUE)) {
    stop("Required package is not installed: ", package, call. = FALSE)
  }
  env <- new.env(parent = emptyenv())
  utils::data(list = dataset, package = package, envir = env)
  if (!exists(dataset, envir = env, inherits = FALSE)) {
    stop("Dataset not found in package ", package, ": ", dataset, call. = FALSE)
  }
  data <- get(dataset, envir = env, inherits = FALSE)
  data <- as.data.frame(data)
  data <- transform(data)
  if (!is.null(columns)) {
    data <- data[, columns, drop = FALSE]
  }
  utils::write.csv(data, file.path(output_dir, file), row.names = FALSE, fileEncoding = "UTF-8")
  data.frame(
    file = file,
    package = package,
    dataset = dataset,
    rows = nrow(data),
    columns = ncol(data),
    stringsAsFactors = FALSE
  )
}

exports <- list(
  write_example(
    "geepack",
    "ohio",
    "longitudinal_gee_ohio_binary.csv",
    columns = c("resp", "id", "age", "smoke")
  ),
  write_example(
    "geepack",
    "dietox",
    "longitudinal_gee_dietox_growth.csv",
    columns = c("Pig", "Time", "Weight", "Feed", "Cu", "Evit", "Litter")
  ),
  write_example(
    "geepack",
    "seizure",
    "longitudinal_gee_seizure_count.csv",
    transform = function(data) {
      data$patient <- seq_len(nrow(data))
      long <- stats::reshape(
        data,
        varying = c("y1", "y2", "y3", "y4"),
        v.names = "seizures",
        timevar = "visit",
        times = 1:4,
        idvar = "patient",
        direction = "long"
      )
      long <- long[order(long$patient, long$visit), ]
      row.names(long) <- NULL
      long[, c("patient", "visit", "seizures", "trt", "base", "age"), drop = FALSE]
    }
  ),
  write_example(
    "lme4",
    "sleepstudy",
    "longitudinal_lmm_sleepstudy.csv",
    columns = c("Subject", "Days", "Reaction")
  ),
  write_example(
    "lme4",
    "cbpp",
    "longitudinal_glmm_cbpp_binomial.csv",
    columns = c("herd", "period", "incidence", "size", "non_incidence", "incidence_rate"),
    transform = function(data) {
      data$non_incidence <- data$size - data$incidence
      data$incidence_rate <- data$incidence / data$size
      data
    }
  ),
  write_example(
    "plm",
    "Grunfeld",
    "longitudinal_panel_grunfeld.csv",
    columns = c("firm", "year", "inv", "value", "capital")
  )
)

manifest <- do.call(rbind, exports)
utils::write.csv(manifest, file.path(output_dir, "manifest.csv"), row.names = FALSE, fileEncoding = "UTF-8")

readme <- c(
  "# Longitudinal / Panel Example Data",
  "",
  "These files are exported from installed CRAN package example datasets so validation is reproducible without network access.",
  "",
  "| File | Source | Suggested StatEdu Studio setup |",
  "|---|---|---|",
  "| `longitudinal_gee_ohio_binary.csv` | `geepack::ohio` | GEE / GLMM binary: dependent `resp`, subject `id`, time `age`, independent `smoke`. |",
  "| `longitudinal_gee_dietox_growth.csv` | `geepack::dietox` | GEE / LMM continuous: dependent `Weight`, subject `Pig`, cluster `Litter` optional, time `Time`, independent `Feed`, `Cu`, `Evit`. |",
  "| `longitudinal_gee_seizure_count.csv` | `geepack::seizure` | GEE count: dependent `seizures`, subject `patient`, time `visit`, independent `trt`, `base`, `age`. |",
  "| `longitudinal_lmm_sleepstudy.csv` | `lme4::sleepstudy` | LMM: dependent `Reaction`, subject `Subject`, time `Days`, independent `Days`; random slope can be enabled. |",
  "| `longitudinal_glmm_cbpp_binomial.csv` | `lme4::cbpp` | GLMM/GEE binary-binomial style: dependent `incidence_rate` or `incidence`, subject `herd`, time `period`, exposure/offset `size` only when modeling rates/counts. |",
  "| `longitudinal_panel_grunfeld.csv` | `plm::Grunfeld` | Panel FE/RE: dependent `inv`, subject `firm`, time `year`, independent `value`, `capital`. |",
  "",
  "Generated by `scripts/download_longitudinal_examples.R`."
)
writeLines(readme, file.path(output_dir, "README.md"), useBytes = TRUE)

print(manifest, row.names = FALSE)
