import json,re
from pathlib import Path
rows='''Factor-score quality|因子得点の品質|因子得分质量|Calidad de las puntuaciones factoriales|Qualité des scores factoriels|Qualität der Faktorwerte|Chất lượng điểm nhân tố
Determinacy|決定性|确定性|Determinación|Détermination|Determiniertheit|Tính xác định
Score reliability|得点信頼性|得分信度|Fiabilidad de la puntuación|Fiabilité du score|Score-Reliabilität|Độ tin cậy điểm số
At/above descriptive .90 reference|記述的参考値.90以上|达到或超过描述性参考值.90|Igual o superior a la referencia descriptiva .90|Au moins égal à la référence descriptive .90|Auf/über dem deskriptiven Referenzwert .90|Bằng hoặc trên mức tham khảo mô tả .90
Between descriptive .80 and .90 references|記述的参考値.80以上.90未満|介于描述性参考值.80和.90之间|Entre las referencias descriptivas .80 y .90|Entre les références descriptives .80 et .90|Zwischen den deskriptiven Referenzwerten .80 und .90|Giữa các mức tham khảo mô tả .80 và .90
Below descriptive .80; review score use|記述的参考値.80未満；得点利用を検討|低于描述性参考值.80；请审查得分用途|Por debajo de .80 descriptivo; revise el uso de puntuaciones|Sous la référence descriptive .80 ; examiner l’utilisation du score|Unter dem deskriptiven Wert .80; Score-Nutzung prüfen|Dưới mức mô tả .80; xem xét cách dùng điểm số'''
notes='''Determinacy is the estimated correlation|決定性は適合モデルにおける回帰因子得点と潜在因子の推定相関で、得点信頼性はその二乗です。.80と.90は記述的参考値であり、個人利用の合格基準ではありません。これらはCR、omega、内容・基準関連妥当性、解の許容性、独立標本での再現性に代わるものではありません。|确定性是在拟合模型下回归因子得分与潜因子的估计相关；得分信度为其平方。.80和.90只是描述性参考值，并非个体使用的合格阈值。这些指标不能替代CR、omega、内容/效标效度、模型可接受性或独立重复验证。|La determinación es la correlación estimada entre las puntuaciones factoriales de regresión y el factor latente bajo el modelo ajustado; la fiabilidad del score es su cuadrado. .80 y .90 son referencias descriptivas, no umbrales de aprobación para uso individual. No sustituyen CR, omega, validez de contenido/criterio, admisibilidad del modelo ni replicación independiente.|La détermination est la corrélation estimée entre les scores factoriels de régression et le facteur latent sous le modèle ajusté ; la fiabilité du score est son carré. .80 et .90 sont des références descriptives, pas des seuils de réussite pour un usage individuel. Ces indices ne remplacent pas CR, omega, la validité de contenu/critère, l’admissibilité du modèle ou la réplication indépendante.|Determiniertheit ist die geschätzte Korrelation zwischen Regressionsfaktorwerten und latentem Faktor im angepassten Modell; die Score-Reliabilität ist ihr Quadrat. .80 und .90 sind deskriptive Referenzen, keine Bestehensgrenzen für die individuelle Nutzung. Sie ersetzen weder CR, Omega, Inhalts-/Kriteriumsvalidität, Modellzulässigkeit noch unabhängige Replikation.|Tính xác định là tương quan ước lượng giữa điểm nhân tố hồi quy và nhân tố tiềm ẩn dưới mô hình đã khớp; độ tin cậy điểm số là bình phương của nó. .80 và .90 là mức tham khảo mô tả, không phải ngưỡng đạt cho sử dụng cá nhân. Các chỉ số này không thay thế CR, omega, giá trị nội dung/tiêu chí, tính chấp nhận được của mô hình hay tái lập độc lập.
Factor scores are indeterminate:|因子得点は一意に定まらず、算出法によって値や順位が変わり、回帰得点は平均へ縮小されます。通常の後続回帰で誤差のない観測変数とみなすと不確実性を過小評価する場合があります。潜在変数モデル内で分析するか、因子得点誤差を伝播させる方法を優先してください。|因子得分具有不确定性：数值与排序可随计分方法变化，回归得分会向均值收缩。在后续普通回归中将其视为无误差观测变量可能低估不确定性；宜在潜变量模型内分析，或采用传递因子得分误差的方法。|Las puntuaciones factoriales son indeterminadas: valores y rangos pueden variar según el método, y las puntuaciones de regresión se contraen hacia la media. Tratarlas como variables observadas sin error en una regresión posterior puede subestimar la incertidumbre; prefiera analizar dentro del modelo latente o usar métodos que propaguen el error del score.|Les scores factoriels sont indéterminés : valeurs et classements peuvent varier selon la méthode, et les scores de régression sont ramenés vers la moyenne. Les traiter comme des variables observées sans erreur dans une régression ultérieure peut sous-estimer l’incertitude ; privilégiez le modèle latent ou des méthodes propageant l’erreur des scores.|Faktorwerte sind unbestimmt: Werte und Rangfolgen können je nach Berechnungsmethode variieren; Regressionswerte werden zum Mittelwert hin geschrumpft. Als fehlerfreie beobachtete Variablen in nachfolgenden Regressionen können sie Unsicherheit unterschätzen; bevorzugen Sie Analysen im latenten Modell oder Methoden zur Weitergabe des Faktorwertfehlers.|Điểm nhân tố không được xác định duy nhất: giá trị và thứ hạng có thể thay đổi theo cách tính, còn điểm hồi quy co về trung bình. Xem chúng là biến quan sát không có sai số trong hồi quy tiếp theo có thể đánh giá thấp bất định; nên phân tích trong mô hình biến tiềm ẩn hoặc dùng phương pháp truyền sai số điểm nhân tố.
Determinacy alone is insufficient|診断・選抜・フィードバックなど個人の意思決定には決定性だけでは不十分です。分類精度、公平性、時間的安定性、外部基準、独立検証について別途の証拠が必要です。|仅凭确定性不足以支持诊断、选拔或反馈等个体决策。此类用途还需分类准确性、公平性、时间稳定性、外部效标及独立验证的证据。|La determinación por sí sola no basta para decisiones individuales como diagnóstico, selección o retroalimentación. Se requiere evidencia adicional de precisión de clasificación, equidad, estabilidad temporal, criterios externos y validación independiente.|La détermination seule ne suffit pas aux décisions individuelles telles que diagnostic, sélection ou retour d’information. Ces usages nécessitent des preuves distinctes sur l’exactitude de classification, l’équité, la stabilité temporelle, les critères externes et la validation indépendante.|Determiniertheit allein reicht für individuelle Entscheidungen wie Diagnose, Auswahl oder Rückmeldung nicht aus. Dafür sind gesonderte Nachweise zu Klassifikationsgenauigkeit, Fairness, zeitlicher Stabilität, externen Kriterien und unabhängiger Validierung nötig.|Chỉ tính xác định là chưa đủ cho quyết định cá nhân như chẩn đoán, tuyển chọn hoặc phản hồi. Cần bằng chứng riêng về độ chính xác phân loại, công bằng, ổn định theo thời gian, tiêu chí bên ngoài và kiểm định độc lập.
For ordered indicators, factor-score quality|順序尺度指標の因子得点品質は、適合した潜在反応WLSMVモデルとカテゴリ閾値に条件づけられます。|有序指标的因子得分质量取决于拟合的潜在反应WLSMV模型和类别阈值。|Para indicadores ordinales, la calidad de los scores depende del modelo de respuesta latente WLSMV ajustado y de los umbrales de categoría.|Pour les indicateurs ordinaux, la qualité des scores est conditionnelle au modèle de réponse latente WLSMV ajusté et aux seuils des catégories.|Bei ordinalen Indikatoren hängt die Faktorwertqualität vom angepassten latenten WLSMV-Antwortmodell und den Kategorieschwellen ab.|Với chỉ báo thứ bậc, chất lượng điểm nhân tố phụ thuộc vào mô hình phản hồi tiềm ẩn WLSMV đã khớp và các ngưỡng danh mục.'''
source=Path('R/setup_custom_model_canvas_structural_render_factor_scores.R').read_text(encoding='utf-8')
sources=re.findall(r'tr\("([^"]+)"',source)
data_rows=[row.split('|') for row in rows.splitlines()]
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
