"""Proportion/correlation formula prose, retaining mathematical expressions."""
import json
from pathlib import Path
keys=['risk_difference','risk_ratio','odds_ratio','point_biserial','correlation_f','correlation_r2']
rows={
'en':['Risk difference = p1 - p2.','Risk ratio = p1 / p2.','Odds ratio = [p1 / (1 - p1)] / [p2 / (1 - p2)]; 2x2 tables with a zero cell use a 0.5 continuity correction.','Point-biserial r is Pearson r for a binary and continuous variable; for a two-group contrast, d = 2r / sqrt(1 - r^2).','For a one-degree-of-freedom effect, r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); the sign is not identifiable from R-squared alone.'],
'ko':['위험차 = p1 - p2.','위험비 = p1 / p2.','오즈비 = [p1 / (1 - p1)] / [p2 / (1 - p2)]; 값이 0인 셀이 있는 2x2 표에는 0.5 연속성 보정을 적용합니다.','점이연상관 r은 이분형 변수와 연속형 변수 사이의 Pearson r입니다. 두 집단 대비에서는 d = 2r / sqrt(1 - r^2).','자유도가 1인 효과에서 r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); R-squared만으로는 부호를 알 수 없습니다.'],
'ja':['リスク差 = p1 - p2.','リスク比 = p1 / p2.','オッズ比 = [p1 / (1 - p1)] / [p2 / (1 - p2)]; 値が0のセルを含む2x2表には0.5の連続性補正を適用します。','点双列相関rは二値変数と連続変数のPearson rです。2群の対比では d = 2r / sqrt(1 - r^2)。','自由度1の効果では r = sqrt(F / (F + df_error))。','r = sqrt(R-squared); R-squaredだけでは符号を特定できません。'],
'zh':['风险差 = p1 - p2。','风险比 = p1 / p2。','优势比 = [p1 / (1 - p1)] / [p2 / (1 - p2)]; 含零单元格的2x2表采用0.5连续性校正。','点二列相关r是二分类变量与连续变量之间的Pearson r；对于两组对比，d = 2r / sqrt(1 - r^2)。','对于自由度为1的效应，r = sqrt(F / (F + df_error))。','r = sqrt(R-squared); 仅凭R-squared无法确定符号。'],
'es':['Diferencia de riesgos = p1 - p2.','Razón de riesgos = p1 / p2.','Razón de momios = [p1 / (1 - p1)] / [p2 / (1 - p2)]; las tablas 2x2 con una celda cero usan una corrección de continuidad de 0.5.','La r biserial puntual es la r de Pearson entre una variable binaria y una continua; para un contraste de dos grupos, d = 2r / sqrt(1 - r^2).','Para un efecto con un grado de libertad, r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); el signo no se puede determinar solo a partir de R-squared.'],
'fr':['Différence de risques = p1 - p2.','Rapport de risques = p1 / p2.','Rapport des cotes = [p1 / (1 - p1)] / [p2 / (1 - p2)]; les tableaux 2x2 avec une cellule nulle utilisent une correction de continuité de 0.5.','Le r point-bisérial est le r de Pearson entre une variable binaire et une variable continue ; pour un contraste entre deux groupes, d = 2r / sqrt(1 - r^2).','Pour un effet à un degré de liberté, r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); le signe ne peut pas être déterminé à partir de R-squared seul.'],
'de':['Risikodifferenz = p1 - p2.','Risikoverhältnis = p1 / p2.','Odds Ratio = [p1 / (1 - p1)] / [p2 / (1 - p2)]; bei 2x2-Tabellen mit einer Nullzelle wird eine Kontinuitätskorrektur von 0.5 verwendet.','Das punktbiseriale r ist Pearsons r zwischen einer binären und einer kontinuierlichen Variablen; für einen Zweigruppenkontrast gilt d = 2r / sqrt(1 - r^2).','Für einen Effekt mit einem Freiheitsgrad gilt r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); das Vorzeichen lässt sich aus R-squared allein nicht bestimmen.'],
'vi':['Chênh lệch nguy cơ = p1 - p2.','Tỷ số nguy cơ = p1 / p2.','Tỷ số odds = [p1 / (1 - p1)] / [p2 / (1 - p2)]; bảng 2x2 có ô bằng 0 sử dụng hiệu chỉnh liên tục 0.5.','r lưỡng phân điểm là r Pearson giữa một biến nhị phân và một biến liên tục; với tương phản hai nhóm, d = 2r / sqrt(1 - r^2).','Với hiệu ứng có một bậc tự do, r = sqrt(F / (F + df_error)).','r = sqrt(R-squared); không thể xác định dấu chỉ từ R-squared.'],
}
for lang,values in rows.items():
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+key:value for key,value in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
