import json
from pathlib import Path
keys=['strata_covariate','cluster_covariate','cluster_start','cluster_strata','spline_covariate','spline_df']
rows={
'en':['The stratification variable must not also be entered as a Cox covariate because a stratified Cox model does not estimate its hazard ratio.','The cluster variable must not also be entered as a Cox covariate because it identifies correlated observations rather than an estimated effect.','A separate cluster variable is not available for start-stop Cox models. The required subject ID already defines the robust-variance cluster; multiway clustering is not implemented.','The same variable cannot be used simultaneously as both the stratification variable and the robust-variance cluster.','The spline variable must also be included among the Cox covariates.','Spline degrees of freedom must be 3, 4, or 5.'],
'ko':['층화 Cox 모형은 층화 변수의 위험비를 추정하지 않으므로, 층화 변수를 Cox 공변량으로도 입력할 수 없습니다.','군집 변수는 추정할 효과가 아니라 상관된 관측치를 식별하므로, Cox 공변량으로도 입력할 수 없습니다.','시작·종료 Cox 모형에서는 별도의 군집 변수를 사용할 수 없습니다. 필수 대상자 ID가 이미 강건 분산의 군집을 정의하며, 다중 군집화는 구현되지 않았습니다.','동일한 변수를 층화 변수와 강건 분산의 군집 변수로 동시에 사용할 수 없습니다.','스플라인 변수를 Cox 공변량에도 포함하세요.','스플라인 자유도는 3, 4 또는 5여야 합니다.'],
'ja':['層別Coxモデルでは層別変数のハザード比を推定しないため、層別変数をCox共変量としても入力することはできません。','クラスター変数は推定する効果ではなく相関のある観測を識別するため、Cox共変量としても入力することはできません。','開始・終了形式のCoxモデルでは別のクラスター変数を使用できません。必須の対象者IDが既にロバスト分散のクラスターを定義しており、多方向クラスタリングは未実装です。','同じ変数を層別変数とロバスト分散のクラスター変数として同時に使用することはできません。','スプライン変数をCox共変量にも含めてください。','スプラインの自由度は3、4、5のいずれかにしてください。'],
'zh':['分层 Cox 模型不估计分层变量的风险比，因此不能同时将其作为 Cox 协变量。','聚类变量用于识别相关观测，而非估计效应，因此不能同时将其作为 Cox 协变量。','起止时间 Cox 模型不支持单独的聚类变量。必需的受试者 ID 已定义稳健方差的聚类；尚未实现多维聚类。','同一变量不能同时用作分层变量和稳健方差的聚类变量。','样条变量也必须包含在 Cox 协变量中。','样条自由度必须为 3、4 或 5。'],
'es':['La variable de estratificación no puede incluirse también como covariable de Cox, ya que el modelo estratificado no estima su razón de riesgos.','La variable de agrupación no puede incluirse también como covariable de Cox, ya que identifica observaciones correlacionadas y no un efecto estimado.','Los modelos de Cox con inicio y fin no admiten una variable de agrupación independiente. El ID de sujeto obligatorio ya define los grupos para la varianza robusta; no se ha implementado la agrupación multidimensional.','No se puede usar la misma variable para la estratificación y para los grupos de la varianza robusta.','La variable spline también debe incluirse entre las covariables de Cox.','Los grados de libertad del spline deben ser 3, 4 o 5.'],
'fr':['La variable de stratification ne peut pas aussi être une covariable de Cox, car le modèle stratifié n’estime pas son rapport de risques.','La variable de regroupement ne peut pas aussi être une covariable de Cox, car elle identifie des observations corrélées plutôt qu’un effet estimé.','Les modèles de Cox début-fin ne permettent pas de variable de regroupement distincte. L’identifiant de sujet obligatoire définit déjà les groupes de variance robuste ; le regroupement multidimensionnel n’est pas implémenté.','La même variable ne peut pas servir simultanément à la stratification et au regroupement pour la variance robuste.','La variable spline doit également figurer parmi les covariables de Cox.','Les degrés de liberté de la spline doivent être 3, 4 ou 5.'],
'de':['Die Stratifizierungsvariable darf nicht zugleich als Cox-Kovariate eingegeben werden, da ein stratifiziertes Cox-Modell ihre Hazard Ratio nicht schätzt.','Die Clustervariable darf nicht zugleich als Cox-Kovariate eingegeben werden, da sie korrelierte Beobachtungen und keinen zu schätzenden Effekt kennzeichnet.','Für Start-Stopp-Cox-Modelle ist keine separate Clustervariable verfügbar. Die erforderliche Personen-ID definiert bereits die Cluster für die robuste Varianz; mehrdimensionales Clustering ist nicht implementiert.','Dieselbe Variable kann nicht gleichzeitig zur Stratifizierung und als Cluster für die robuste Varianz verwendet werden.','Die Spline-Variable muss auch zu den Cox-Kovariaten gehören.','Die Spline-Freiheitsgrade müssen 3, 4 oder 5 sein.'],
'vi':['Không được đồng thời dùng biến phân tầng làm hiệp biến Cox vì mô hình Cox phân tầng không ước lượng tỷ số nguy cơ của biến đó.','Không được đồng thời dùng biến cụm làm hiệp biến Cox vì biến này xác định các quan sát tương quan, không phải một hiệu ứng cần ước lượng.','Mô hình Cox bắt đầu–kết thúc không hỗ trợ biến cụm riêng. ID đối tượng bắt buộc đã xác định cụm cho phương sai vững; phân cụm đa chiều chưa được triển khai.','Không thể đồng thời dùng cùng một biến để phân tầng và xác định cụm cho phương sai vững.','Biến spline cũng phải nằm trong các hiệp biến Cox.','Bậc tự do của spline phải là 3, 4 hoặc 5.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
