import json,re
from pathlib import Path
source=Path('R/setup_custom_model_canvas_structural_identification_diagnostics.R').read_text(encoding='utf-8')
rows='''unmeasured_latent	この潜在変数には観測指標も下位因子もありません。	该潜变量既无观测指标也无低阶因子。	La variable latente no tiene indicadores observados ni factores de orden inferior.	La variable latente ne possède ni indicateurs observés ni facteurs d’ordre inférieur.	Die latente Variable besitzt weder beobachtete Indikatoren noch Faktoren niedrigerer Ordnung.	Biến tiềm ẩn không có chỉ báo quan sát hay nhân tố bậc thấp.
single_indicator_auto_fixed	単一指標因子は指標の残差分散を0に自動固定して識別されています。外部の信頼性制約がない場合、完全測定の仮定として扱ってください。	单指标因子通过将指标残差方差自动固定为零来识别；若未提供外部信度约束，应视为完全测量假设。	El factor de indicador único se identifica fijando automáticamente su varianza residual a cero; considérelo una hipótesis de medición perfecta salvo que se aporte una restricción de fiabilidad externa.	Le facteur à indicateur unique est identifié en fixant automatiquement sa variance résiduelle à zéro ; traitez cela comme une hypothèse de mesure parfaite sauf contrainte de fiabilité externe.	Der Ein-Indikator-Faktor wird durch automatische Fixierung der Residualvarianz auf null identifiziert; behandeln Sie dies ohne externe Reliabilitätsrestriktion als Annahme perfekter Messung.	Nhân tố một chỉ báo được định danh bằng cách tự động cố định phương sai phần dư bằng không; xem đây là giả định đo lường hoàn hảo nếu không có ràng buộc độ tin cậy bên ngoài.
single_indicator_constrained	単一指標因子は固定残差分散で識別されています。この制約の外部信頼性根拠を記録してください。	单指标因子通过固定残差方差识别；请记录该约束的外部信度依据。	El factor de indicador único se identifica mediante una varianza residual fija; documente la base de fiabilidad externa de esta restricción.	Le facteur à indicateur unique est identifié par une variance résiduelle fixe ; documentez la justification de fiabilité externe.	Der Ein-Indikator-Faktor wird durch eine fixierte Residualvarianz identifiziert; dokumentieren Sie die externe Reliabilitätsgrundlage.	Nhân tố một chỉ báo được định danh bằng phương sai phần dư cố định; hãy ghi lại căn cứ độ tin cậy bên ngoài cho ràng buộc này.
two_indicators	2指標因子の安定した識別には、追加制約や構造情報が必要な場合があります。	双指标因子可能需要额外约束或结构信息才能稳定识别。	Un factor de dos indicadores puede requerir restricciones adicionales o información estructural para una identificación estable.	Un facteur à deux indicateurs peut nécessiter des contraintes supplémentaires ou des informations structurelles pour une identification stable.	Ein Zwei-Indikator-Faktor kann zusätzliche Restriktionen oder Strukturinformationen für eine stabile Identifikation benötigen.	Nhân tố hai chỉ báo có thể cần ràng buộc bổ sung hoặc thông tin cấu trúc để định danh ổn định.
few_lower_order_factors	現在の自動識別方式では、高次因子ごとに3つ以上の下位因子が必要です。	当前自动识别方案要求每个高阶因子至少有三个低阶因子。	El esquema actual de identificación automática requiere al menos tres factores de orden inferior por factor de orden superior.	Le schéma actuel d’identification automatique exige au moins trois facteurs d’ordre inférieur par facteur d’ordre supérieur.	Das aktuelle automatische Identifikationsverfahren erfordert mindestens drei Faktoren niedrigerer Ordnung je Faktor höherer Ordnung.	Sơ đồ định danh tự động hiện tại yêu cầu mỗi nhân tố bậc cao có ít nhất ba nhân tố bậc thấp.
mixed_measurement_level	この因子には観測指標と下位因子の両方があります。この混合測定指定が意図したものか確認してください。	该因子同时具有观测指标和低阶因子；请确认此混合测量设定是否符合原意。	El factor tiene indicadores observados y factores de orden inferior; verifique que esta especificación híbrida sea intencional.	Le facteur possède des indicateurs observés et des facteurs d’ordre inférieur ; vérifiez que cette spécification hybride est intentionnelle.	Der Faktor besitzt beobachtete Indikatoren und Faktoren niedrigerer Ordnung; prüfen Sie, ob diese hybride Messspezifikation beabsichtigt ist.	Nhân tố có cả chỉ báo quan sát và nhân tố bậc thấp; hãy xác nhận đặc tả đo lường hỗn hợp này là có chủ ý.
multiple_higher_order_parents	この下位因子は複数の高次因子に負荷しています。標準的な高次因子の信頼性要約が適用できない場合があります。	该低阶因子载荷于多个高阶因子；标准高阶信度汇总可能不适用。	El factor de orden inferior carga en varios factores de orden superior; los resúmenes estándar de fiabilidad de orden superior pueden no ser aplicables.	Le facteur d’ordre inférieur charge sur plusieurs facteurs d’ordre supérieur ; les résumés usuels de fiabilité d’ordre supérieur peuvent ne pas s’appliquer.	Der Faktor niedrigerer Ordnung lädt auf mehreren Faktoren höherer Ordnung; standardmäßige Reliabilitätszusammenfassungen höherer Ordnung sind möglicherweise nicht anwendbar.	Nhân tố bậc thấp tải lên nhiều nhân tố bậc cao; tóm tắt độ tin cậy bậc cao tiêu chuẩn có thể không áp dụng.
invalid_fixed_residual	固定残差分散は有限の非負数でなければなりません。	固定残差方差必须为有限非负数。	La varianza residual fija debe ser un número finito no negativo.	La variance résiduelle fixe doit être un nombre fini non négatif.	Eine fixierte Residualvarianz muss endlich und nicht negativ sein.	Phương sai phần dư cố định phải là số hữu hạn không âm.
negative_fixed_residual	残差分散を負の値に固定することはできません。	残差方差不能固定为负值。	No se puede fijar la varianza residual a un valor negativo.	La variance résiduelle ne peut pas être fixée à une valeur négative.	Eine Residualvarianz kann nicht auf einen negativen Wert fixiert werden.	Không thể cố định phương sai phần dư ở giá trị âm.
boundary_fixed_residual	残差分散0の固定は、残差のない完全測定を意味する境界制約です。強い実質的根拠を示してください。	将残差方差固定为零是意味着完全无残差测量的边界约束；请提供充分的实质性依据。	Fijar la varianza residual a cero es una restricción de frontera que implica medición perfecta sin residuos; aporte una justificación sustantiva sólida.	Fixer la variance résiduelle à zéro est une contrainte de frontière impliquant une mesure parfaite sans résidu ; fournissez une justification substantielle solide.	Eine auf null fixierte Residualvarianz ist eine Randrestriktion, die perfekte residualfreie Messung impliziert; liefern Sie eine starke inhaltliche Begründung.	Cố định phương sai phần dư bằng không là ràng buộc biên hàm ý đo lường hoàn hảo không có phần dư; cần căn cứ nội dung vững chắc.
duplicate_path	同じ両端点の間に重複した有向経路があります。	相同端点之间存在重复有向路径。	Se encontraron trayectorias dirigidas duplicadas entre los mismos extremos.	Des chemins dirigés en double ont été trouvés entre les mêmes extrémités.	Zwischen denselben Endpunkten wurden doppelte gerichtete Pfade gefunden.	Có đường dẫn có hướng trùng lặp giữa cùng các đầu mút.
duplicate_covariance	同じ両端点の間に重複した共分散経路があります。	相同端点之间存在重复协方差路径。	Se encontraron trayectorias de covarianza duplicadas entre los mismos extremos.	Des chemins de covariance en double ont été trouvés entre les mêmes extrémités.	Zwischen denselben Endpunkten wurden doppelte Kovarianzpfade gefunden.	Có đường dẫn hiệp phương sai trùng lặp giữa cùng các đầu mút.'''
extra=[['Model identification check failed','モデル識別性チェック失敗','模型识别检查失败','Falló la comprobación de identificación','Échec du contrôle d’identification','Modellidentifikationsprüfung fehlgeschlagen','Kiểm tra định danh mô hình thất bại'],['Identification warning','識別性の警告','识别警告','Advertencia de identificación','Avertissement d’identification','Identifikationswarnung','Cảnh báo định danh']]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==7
  match=re.search('"'+f[0]+'", "([^"]+)"',source);assert match,f[0]
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',match[1].lower()).strip('_')]=f[i]
 for f in extra:data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
