import json,re
from pathlib import Path
rows='''This matches a group-comparison question with one event of interest.|1つの関心イベントについて集団を比較する研究目的に適しています。|这适合针对一个关注事件进行组间比较。|Se ajusta a una comparación de grupos con un evento de interés.|Cela correspond à une comparaison de groupes avec un événement d’intérêt.|Dies passt zu einem Gruppenvergleich mit einem interessierenden Ereignis.|Phù hợp với câu hỏi so sánh nhóm có một biến cố quan tâm.
Kaplan-Meier curves and numbers at risk by group|集団別Kaplan–Meier曲線とリスク集合人数|各组Kaplan–Meier曲线和风险集人数|Curvas de Kaplan–Meier y personas en riesgo por grupo|Courbes de Kaplan–Meier et effectifs à risque par groupe|Kaplan–Meier-Kurven und Risikopersonenzahlen je Gruppe|Đường cong Kaplan–Meier và số người có nguy cơ theo nhóm
Median survival and survival rates at requested times|中央生存時間と指定時点の生存率|中位生存时间和指定时间点的生存率|Mediana de supervivencia y tasas en tiempos solicitados|Survie médiane et taux de survie aux temps demandés|Mediane Überlebenszeit und Überlebensraten zu gewählten Zeitpunkten|Trung vị thời gian sống và tỷ lệ sống tại thời điểm yêu cầu
Log-rank test and restricted mean survival time (RMST)|ログランク検定と制限平均生存時間（RMST）|Log-rank检验和限制平均生存时间（RMST）|Prueba de log-rank y tiempo medio de supervivencia restringido (RMST)|Test du log-rank et temps moyen de survie restreint (RMST)|Log-Rank-Test und eingeschränkte mittlere Überlebenszeit (RMST)|Kiểm định log-rank và thời gian sống trung bình giới hạn (RMST)
Choose Cox regression when adjusted group effects or hazard ratios are required.|調整済み集団効果やハザード比が必要な場合はCox回帰を選択します。|需要调整后的组效应或风险比时，选择Cox回归。|Elija Cox si necesita efectos de grupo ajustados o razones de riesgos.|Choisissez Cox si des effets de groupe ajustés ou des rapports de risques sont nécessaires.|Wählen Sie Cox bei benötigten adjustierten Gruppeneffekten oder Hazard Ratios.|Chọn hồi quy Cox khi cần hiệu ứng nhóm đã hiệu chỉnh hoặc tỷ số nguy cơ.
This matches an adjusted association question between survival time and one or more predictors.|生存時間と1つ以上の予測変数の調整済み関連性を調べる目的に適しています。|这适合研究生存时间与一个或多个预测变量之间的调整后关联。|Se ajusta a una asociación ajustada entre supervivencia y uno o más predictores.|Cela correspond à une association ajustée entre la survie et un ou plusieurs prédicteurs.|Dies passt zur Untersuchung adjustierter Zusammenhänge zwischen Überlebenszeit und Prädiktoren.|Phù hợp để xem xét mối liên hệ đã hiệu chỉnh giữa thời gian sống và một hoặc nhiều biến dự báo.
Hazard ratios, 95% confidence intervals, and p-values|ハザード比、95%信頼区間、p値|风险比、95%置信区间和p值|Razones de riesgos, intervalos de confianza del 95% y valores p|Rapports de risques, intervalles de confiance à 95% et valeurs p|Hazard Ratios, 95%-Konfidenzintervalle und p-Werte|Tỷ số nguy cơ, khoảng tin cậy 95% và giá trị p
Proportional-hazards assumption checks|比例ハザード仮定の確認|比例风险假设检查|Comprobaciones del supuesto de riesgos proporcionales|Vérifications de l’hypothèse des risques proportionnels|Prüfung der Proportional-Hazards-Annahme|Kiểm tra giả định nguy cơ tỷ lệ
Adjusted survival curves for a selected group|選択した集団の調整済み生存曲線|所选组的调整生存曲线|Curvas de supervivencia ajustadas para un grupo seleccionado|Courbes de survie ajustées pour un groupe sélectionné|Adjustierte Überlebenskurven für eine ausgewählte Gruppe|Đường cong sống còn đã hiệu chỉnh cho nhóm được chọn
Choose Kaplan-Meier when only unadjusted group curves and an overall comparison are needed.|未調整の集団別曲線と全体比較のみが必要な場合はKaplan–Meierを選択します。|仅需未调整的组曲线和整体比较时，选择Kaplan–Meier。|Elija Kaplan–Meier si solo necesita curvas sin ajustar y una comparación global.|Choisissez Kaplan–Meier pour des courbes non ajustées et une comparaison globale uniquement.|Wählen Sie Kaplan–Meier für unadjustierte Gruppenkurven und einen Gesamtvergleich.|Chọn Kaplan–Meier khi chỉ cần đường cong nhóm chưa hiệu chỉnh và so sánh tổng thể.
This matches a group comparison where competing events can prevent the event of interest.|競合イベントが関心イベントを妨げる場合の集団比較に適しています。|这适合竞争事件可能阻止关注事件发生时的组间比较。|Se ajusta a comparar grupos cuando eventos competitivos pueden impedir el evento de interés.|Cela convient à une comparaison où des événements concurrents peuvent empêcher l’événement d’intérêt.|Dies passt zu Gruppenvergleichen, bei denen konkurrierende Ereignisse das Zielereignis verhindern können.|Phù hợp để so sánh nhóm khi biến cố cạnh tranh có thể ngăn biến cố quan tâm.
Cumulative incidence functions by event type|イベント種類別の累積発生関数|按事件类型的累积发生函数|Funciones de incidencia acumulada por tipo de evento|Fonctions d’incidence cumulée par type d’événement|Kumulative Inzidenzfunktionen nach Ereignistyp|Hàm tỷ lệ mắc tích lũy theo loại biến cố
Gray test between groups|集団間のGray検定|组间Gray检验|Prueba de Gray entre grupos|Test de Gray entre groupes|Gray-Test zwischen Gruppen|Kiểm định Gray giữa các nhóm
Cumulative incidence at requested times|指定時点の累積発生率|指定时间点的累积发生率|Incidencia acumulada en tiempos solicitados|Incidence cumulée aux temps demandés|Kumulative Inzidenz zu gewählten Zeitpunkten|Tỷ lệ mắc tích lũy tại thời điểm yêu cầu
Consider cause-specific Cox regression for associations with the instantaneous cause-specific hazard.|瞬間的な原因別ハザードとの関連性には原因別Cox回帰を検討します。|研究与瞬时原因别风险的关联时，考虑原因别Cox回归。|Considere Cox específico por causa para asociaciones con el riesgo instantáneo por causa.|Envisagez Cox spécifique à la cause pour les associations avec le risque instantané par cause.|Erwägen Sie ursachenspezifische Cox-Regression für Zusammenhänge mit der momentanen ursachenspezifischen Hazard.|Cân nhắc Cox theo nguyên nhân để xem xét liên hệ với nguy cơ tức thời theo nguyên nhân.
This estimates covariate associations with the cause-specific hazard while treating competing events as separate endpoints.|競合イベントを別の終了として扱い、共変量と原因別ハザードの関連性を推定します。|将竞争事件作为单独终点，估计协变量与原因别风险的关联。|Estima asociaciones con el riesgo por causa tratando los eventos competitivos como desenlaces separados.|Estime les associations avec le risque par cause en traitant les événements concurrents comme des événements terminaux distincts.|Schätzt Kovariatenzusammenhänge mit der ursachenspezifischen Hazard und behandelt konkurrierende Ereignisse als separate Endpunkte.|Ước tính liên hệ giữa hiệp biến và nguy cơ theo nguyên nhân, coi biến cố cạnh tranh là các điểm kết thúc riêng.
Cause-specific hazard ratios and 95% confidence intervals|原因別ハザード比と95%信頼区間|原因别风险比和95%置信区间|Razones de riesgos por causa e intervalos de confianza del 95%|Rapports de risques par cause et intervalles de confiance à 95%|Ursachenspezifische Hazard Ratios und 95%-Konfidenzintervalle|Tỷ số nguy cơ theo nguyên nhân và khoảng tin cậy 95%
Coefficients and p-values by covariate|共変量別の係数とp値|各协变量的系数和p值|Coeficientes y valores p por covariable|Coefficients et valeurs p par covariable|Koeffizienten und p-Werte je Kovariate|Hệ số và giá trị p theo hiệp biến
Proportional-hazards checks|比例ハザード性の確認|比例风险检查|Comprobaciones de riesgos proporcionales|Vérifications des risques proportionnels|Prüfung proportionaler Hazards|Kiểm tra nguy cơ tỷ lệ
Choose Fine-Gray regression when the effect on cumulative incidence probability is the target.|累積発生確率への効果が目的ならFine-Gray回帰を選択します。|目标是累积发生概率的效应时，选择Fine-Gray回归。|Elija Fine-Gray si el objetivo es el efecto sobre la probabilidad de incidencia acumulada.|Choisissez Fine-Gray si la cible est l’effet sur la probabilité d’incidence cumulée.|Wählen Sie Fine-Gray, wenn der Effekt auf die kumulative Inzidenzwahrscheinlichkeit das Ziel ist.|Chọn Fine-Gray khi mục tiêu là hiệu ứng lên xác suất mắc tích lũy.
This estimates covariate effects on cumulative incidence in the presence of competing events.|競合イベントが存在する状況で、共変量の累積発生への効果を推定します。|估计存在竞争事件时协变量对累积发生率的效应。|Estima efectos de covariables sobre la incidencia acumulada con eventos competitivos.|Estime les effets des covariables sur l’incidence cumulée en présence d’événements concurrents.|Schätzt Kovariateneffekte auf die kumulative Inzidenz bei konkurrierenden Ereignissen.|Ước tính hiệu ứng của hiệp biến lên tỷ lệ mắc tích lũy khi có biến cố cạnh tranh.
Subdistribution hazard ratios and 95% confidence intervals|部分分布ハザード比と95%信頼区間|亚分布风险比和95%置信区间|Razones de riesgos de subdistribución e intervalos de confianza del 95%|Rapports de risques de sous-distribution et intervalles de confiance à 95%|Subdistributions-Hazard-Ratios und 95%-Konfidenzintervalle|Tỷ số nguy cơ phân phối phụ và khoảng tin cậy 95%
Interpretation in terms of cumulative incidence|累積発生の観点からの解釈|从累积发生率角度解释|Interpretación en términos de incidencia acumulada|Interprétation en termes d’incidence cumulée|Interpretation anhand der kumulativen Inzidenz|Diễn giải theo tỷ lệ mắc tích lũy
Choose cause-specific Cox regression for etiologic or instantaneous-risk questions.|病因や瞬間的リスクが研究目的なら原因別Cox回帰を選択します。|病因或瞬时风险问题应选择原因别Cox回归。|Elija Cox específico por causa para preguntas etiológicas o de riesgo instantáneo.|Choisissez Cox spécifique à la cause pour des questions étiologiques ou de risque instantané.|Wählen Sie ursachenspezifische Cox-Regression für ätiologische Fragen oder momentane Risiken.|Chọn Cox theo nguyên nhân cho câu hỏi về căn nguyên hoặc nguy cơ tức thời.
This addresses both cause-specific hazard and cumulative-incidence estimands.|原因別ハザードと累積発生の両方の推定対象を扱います。|这同时处理原因别风险和累积发生率两个估计目标。|Aborda tanto el riesgo por causa como la incidencia acumulada.|Cela couvre les estimands du risque par cause et de l’incidence cumulée.|Dies behandelt sowohl ursachenspezifische Hazard als auch kumulative Inzidenz als Zielgrößen.|Đáp ứng cả hai mục tiêu ước lượng: nguy cơ theo nguyên nhân và tỷ lệ mắc tích lũy.
Cause-specific Cox hazard ratios|原因別Coxハザード比|原因别Cox风险比|Razones de riesgos de Cox por causa|Rapports de risques de Cox par cause|Ursachenspezifische Cox-Hazard-Ratios|Tỷ số nguy cơ Cox theo nguyên nhân
Fine-Gray subdistribution hazard ratios|Fine-Gray部分分布ハザード比|Fine-Gray亚分布风险比|Razones de riesgos de subdistribución de Fine-Gray|Rapports de risques de sous-distribution de Fine-Gray|Fine-Gray-Subdistributions-Hazard-Ratios|Tỷ số nguy cơ phân phối phụ Fine-Gray
A side-by-side interpretation of both estimands|両推定対象を並べた比較解釈|并列解释两个估计目标|Interpretación comparada de ambos estimandos|Interprétation comparative des deux estimands|Gegenüberstellung der Interpretation beider Zielgrößen|Diễn giải đối chiếu hai đại lượng ước lượng
If one estimand clearly matches the primary question, select it alone for a simpler report.|1つの推定対象が主な研究課題に明確に合う場合、それだけを選ぶと報告を簡潔にできます。|若一个估计目标明确匹配主要问题，可单独选择以简化报告。|Si un estimando responde claramente a la pregunta principal, selecciónelo solo para simplificar el informe.|Si un estimand répond clairement à la question principale, sélectionnez-le seul pour simplifier le rapport.|Wenn eine Zielgröße klar zur Hauptfrage passt, wählen Sie nur diese für einen einfacheren Bericht.|Nếu một đại lượng phù hợp rõ ràng với câu hỏi chính, chỉ chọn đại lượng đó để báo cáo đơn giản hơn.
This matches start-stop data in which covariates vary across subject intervals.|対象者の区間ごとに共変量が変化するstart-stopデータに適しています。|这适合协变量在受试者不同区间变化的start-stop数据。|Se ajusta a datos start-stop con covariables que varían entre intervalos de cada sujeto.|Cela convient aux données start-stop dont les covariables varient selon les intervalles des sujets.|Dies passt zu Start-Stopp-Daten mit über Personenintervalle variierenden Kovariaten.|Phù hợp với dữ liệu start-stop có hiệp biến thay đổi theo các khoảng của đối tượng.
Hazard ratios for time-dependent covariates|時間依存共変量のハザード比|时间依赖协变量的风险比|Razones de riesgos para covariables dependientes del tiempo|Rapports de risques pour les covariables dépendantes du temps|Hazard Ratios für zeitabhängige Kovariaten|Tỷ số nguy cơ cho hiệp biến phụ thuộc thời gian
Subject-clustered robust standard errors|対象者でクラスタリングした頑健標準誤差|按受试者聚类的稳健标准误|Errores estándar robustos agrupados por sujeto|Erreurs-types robustes regroupées par sujet|Nach Personen geclusterte robuste Standardfehler|Sai số chuẩn vững phân cụm theo đối tượng
Use ordinary Cox regression when covariates do not vary over time.|共変量が時間で変化しない場合は通常のCox回帰を使用します。|协变量不随时间变化时使用普通Cox回归。|Use Cox ordinario cuando las covariables no varíen con el tiempo.|Utilisez Cox ordinaire lorsque les covariables ne varient pas dans le temps.|Verwenden Sie gewöhnliche Cox-Regression bei zeitlich konstanten Kovariaten.|Sử dụng Cox thông thường khi hiệp biến không thay đổi theo thời gian.
This best matches the selected objective, data shape, and event structure.|選択した研究目的、データ形式、イベント構造に最も適しています。|这最符合所选目标、数据形式和事件结构。|Es la opción más adecuada para el objetivo, formato de datos y estructura de eventos seleccionados.|Cela correspond le mieux à l’objectif, au format des données et à la structure des événements sélectionnés.|Dies passt am besten zu Ziel, Datenform und Ereignisstruktur der Auswahl.|Phù hợp nhất với mục tiêu, dạng dữ liệu và cấu trúc biến cố đã chọn.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
