import json
from pathlib import Path
keys='no_rows repeated source dimensions save_dialog groups missing_source indicator'.split()
rows={
'en':['The current data has no rows to reshape.','Select at least one repeated-measure variable.','Move source columns into the repeated columns block first.','For same-object repeated measures, group count x time count must match the number of selected columns.','Data save dialog is not available.','Set at least one wide-to-long variable group.','Configured source columns are not available in the current data.','At least one indicator variable is required.'],
'ko':['현재 데이터에 변환할 행이 없습니다.','반복측정 변수를 하나 이상 선택하세요.','먼저 원본 열을 반복 열 블록으로 이동하세요.','동일 대상 반복측정에서는 집단 수 × 시점 수가 선택한 열 수와 같아야 합니다.','데이터 저장 대화상자를 사용할 수 없습니다.','와이드→롱 변환 변수 그룹을 하나 이상 설정하세요.','설정한 원본 열이 현재 데이터에 없습니다.','지시변수가 하나 이상 필요합니다.'],
'ja':['現在のデータに変換する行がありません。','反復測定変数を1つ以上選択してください。','まず元の列を反復列ブロックに移動してください。','同一対象の反復測定では、群数×時点数が選択した列数と一致する必要があります。','データ保存ダイアログを使用できません。','ワイドからロングに変換する変数グループを1つ以上設定してください。','設定した元の列が現在のデータにありません。','指標変数が1つ以上必要です。'],
'zh':['当前数据中没有可转换的行。','请至少选择一个重复测量变量。','请先将源列移入重复列区块。','同一对象的重复测量中，组数 × 时间点数必须等于所选列数。','数据保存对话框不可用。','请至少设置一个宽转长变量组。','当前数据中没有配置的源列。','至少需要一个指示变量。'],
'es':['Los datos actuales no tienen filas para transformar.','Seleccione al menos una variable de medidas repetidas.','Primero mueva las columnas de origen al bloque de columnas repetidas.','Para medidas repetidas del mismo sujeto, el número de grupos × el número de momentos debe coincidir con el número de columnas seleccionadas.','El diálogo para guardar datos no está disponible.','Configure al menos un grupo de variables para convertir de formato ancho a largo.','Las columnas de origen configuradas no están disponibles en los datos actuales.','Se requiere al menos una variable indicadora.'],
'fr':['Les données actuelles ne contiennent aucune ligne à transformer.','Sélectionnez au moins une variable de mesures répétées.','Déplacez d’abord les colonnes sources dans le bloc des colonnes répétées.','Pour les mesures répétées sur le même sujet, le nombre de groupes × le nombre de temps doit correspondre au nombre de colonnes sélectionnées.','La boîte de dialogue d’enregistrement des données est indisponible.','Configurez au moins un groupe de variables à convertir du format large au format long.','Les colonnes sources configurées ne sont pas disponibles dans les données actuelles.','Au moins une variable indicatrice est requise.'],
'de':['Die aktuellen Daten enthalten keine umzustrukturierenden Zeilen.','Wählen Sie mindestens eine Messwiederholungsvariable.','Verschieben Sie zuerst die Quellspalten in den Block für wiederholte Spalten.','Bei Messwiederholungen am selben Objekt muss die Anzahl der Gruppen × die Anzahl der Zeitpunkte der Anzahl der ausgewählten Spalten entsprechen.','Der Dialog zum Speichern von Daten ist nicht verfügbar.','Richten Sie mindestens eine Variablengruppe für die Umwandlung vom Breit- ins Langformat ein.','Die konfigurierten Quellspalten sind in den aktuellen Daten nicht vorhanden.','Mindestens eine Indikatorvariable ist erforderlich.'],
'vi':['Dữ liệu hiện tại không có dòng nào để chuyển dạng.','Chọn ít nhất một biến đo lặp lại.','Trước tiên, chuyển các cột nguồn vào khối cột lặp lại.','Với phép đo lặp lại trên cùng đối tượng, số nhóm × số thời điểm phải bằng số cột đã chọn.','Hộp thoại lưu dữ liệu không khả dụng.','Thiết lập ít nhất một nhóm biến để chuyển từ dạng rộng sang dạng dài.','Các cột nguồn đã cấu hình không có trong dữ liệu hiện tại.','Cần ít nhất một biến chỉ báo.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'wide_long.error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
