"""Rank, matched-pair and regression formula descriptions."""
import json
from pathlib import Path
keys='rank_biserial paired_rank epsilon kendall matched_counts matched_g matched_probs incremental_f2 logistic_d interaction_f2'.split()
rows={
'en':["Rank-biserial r = 2U / (n1 n2) - 1; this is equivalent to Cliff's delta orientation.","Paired rank-biserial r = (W+ - W-) / (W+ + W-).",'Epsilon squared = (H - k + 1) / (N - k), bounded at 0.',"Kendall's W = Friedman chi-square / [N * (m - 1)].",'Matched-pair odds ratio = b / c for discordant pairs; if either discordant cell is zero, a 0.5 continuity correction is used.',"Cohen's g = p01 / (p01 + p10) - 0.5 for the discordant-pair direction.",'Matched-pair odds ratio = p01 / p10; log odds ratio = log(p01 / p10).',"Incremental Cohen's f2 = (R2_full - R2_reduced) / (1 - R2_full).","log odds ratio = log(OR); approximate Cohen's d = log(OR) * sqrt(3) / pi.","Interaction Cohen's f2 = delta R-squared / (1 - delta R-squared)."],
'ko':["순위이연상관 r = 2U / (n1 n2) - 1; Cliff's delta와 같은 방향을 사용합니다.",'대응 순위이연상관 r = (W+ - W-) / (W+ + W-).','엡실론제곱 = (H - k + 1) / (N - k), 하한은 0입니다.',"Kendall's W = Friedman chi-square / [N * (m - 1)].",'불일치 쌍의 대응 오즈비 = b / c; 불일치 셀 중 하나라도 0이면 0.5 연속성 보정을 적용합니다.',"불일치 쌍의 방향에 대한 Cohen's g = p01 / (p01 + p10) - 0.5.",'대응 오즈비 = p01 / p10; 로그 오즈비 = log(p01 / p10).',"증분 Cohen's f2 = (R2_full - R2_reduced) / (1 - R2_full).","로그 오즈비 = log(OR); 근사 Cohen's d = log(OR) * sqrt(3) / pi.","상호작용 Cohen's f2 = delta R-squared / (1 - delta R-squared)."],
'ja':["順位二系列相関r = 2U / (n1 n2) - 1; Cliff's deltaと同じ方向を用います。",'対応のある順位二系列相関r = (W+ - W-) / (W+ + W-)。','イプシロン二乗 = (H - k + 1) / (N - k)、下限を0とします。',"Kendall's W = Friedman chi-square / [N * (m - 1)]。",'不一致ペアの対応オッズ比 = b / c; いずれかの不一致セルが0の場合、0.5の連続性補正を適用します。',"不一致ペアの方向に対するCohen's g = p01 / (p01 + p10) - 0.5。",'対応オッズ比 = p01 / p10; 対数オッズ比 = log(p01 / p10)。',"増分Cohen's f2 = (R2_full - R2_reduced) / (1 - R2_full)。","対数オッズ比 = log(OR); 近似Cohen's d = log(OR) * sqrt(3) / pi。","交互作用のCohen's f2 = delta R-squared / (1 - delta R-squared)。"],
'zh':["秩二列相关r = 2U / (n1 n2) - 1; 其方向与Cliff's delta一致。",'配对秩二列相关r = (W+ - W-) / (W+ + W-)。','ε平方 = (H - k + 1) / (N - k)，下限为0。',"Kendall's W = Friedman chi-square / [N * (m - 1)]。",'不一致配对的匹配优势比 = b / c; 任一不一致单元格为0时，采用0.5连续性校正。',"不一致配对方向的Cohen's g = p01 / (p01 + p10) - 0.5。",'匹配优势比 = p01 / p10; 对数优势比 = log(p01 / p10)。',"增量Cohen's f2 = (R2_full - R2_reduced) / (1 - R2_full)。","对数优势比 = log(OR); 近似Cohen's d = log(OR) * sqrt(3) / pi。","交互作用Cohen's f2 = delta R-squared / (1 - delta R-squared)。"],
'es':['r biserial de rangos = 2U / (n1 n2) - 1; usa la misma orientación que la delta de Cliff.','r biserial de rangos pareados = (W+ - W-) / (W+ + W-).','Épsilon cuadrado = (H - k + 1) / (N - k), con límite inferior 0.',"W de Kendall = Friedman chi-square / [N * (m - 1)].",'Razón de momios pareados = b / c para pares discordantes; si alguna celda discordante es cero, se aplica una corrección de continuidad de 0.5.','g de Cohen = p01 / (p01 + p10) - 0.5 para la dirección de los pares discordantes.','Razón de momios pareados = p01 / p10; logaritmo de la razón de momios = log(p01 / p10).','f2 incremental de Cohen = (R2_full - R2_reduced) / (1 - R2_full).','Logaritmo de la razón de momios = log(OR); d aproximado de Cohen = log(OR) * sqrt(3) / pi.','f2 de Cohen para la interacción = delta R-squared / (1 - delta R-squared).'],
'fr':['r bisérial de rang = 2U / (n1 n2) - 1 ; son orientation est identique à celle du delta de Cliff.','r bisérial de rang apparié = (W+ - W-) / (W+ + W-).','Epsilon carré = (H - k + 1) / (N - k), avec une borne inférieure de 0.',"W de Kendall = Friedman chi-square / [N * (m - 1)].",'Rapport des cotes apparié = b / c pour les paires discordantes ; si une cellule discordante est nulle, une correction de continuité de 0.5 est appliquée.','g de Cohen = p01 / (p01 + p10) - 0.5 pour la direction des paires discordantes.','Rapport des cotes apparié = p01 / p10 ; logarithme du rapport des cotes = log(p01 / p10).','f2 incrémental de Cohen = (R2_full - R2_reduced) / (1 - R2_full).','Logarithme du rapport des cotes = log(OR) ; d approximatif de Cohen = log(OR) * sqrt(3) / pi.','f2 de Cohen pour l’interaction = delta R-squared / (1 - delta R-squared).'],
'de':['Rangbiseriales r = 2U / (n1 n2) - 1; die Richtung entspricht Cliffs Delta.','Gepaartes rangbiseriales r = (W+ - W-) / (W+ + W-).','Epsilon-Quadrat = (H - k + 1) / (N - k), mit Untergrenze 0.',"Kendalls W = Friedman chi-square / [N * (m - 1)].",'Gepaarte Odds Ratio = b / c für diskordante Paare; ist eine diskordante Zelle null, wird eine Kontinuitätskorrektur von 0.5 angewendet.','Cohens g = p01 / (p01 + p10) - 0.5 für die Richtung diskordanter Paare.','Gepaarte Odds Ratio = p01 / p10; logarithmierte Odds Ratio = log(p01 / p10).','Inkrementelles Cohens f2 = (R2_full - R2_reduced) / (1 - R2_full).','Logarithmierte Odds Ratio = log(OR); approximatives Cohens d = log(OR) * sqrt(3) / pi.','Cohens f2 für die Interaktion = delta R-squared / (1 - delta R-squared).'],
'vi':['r lưỡng phân thứ hạng = 2U / (n1 n2) - 1; cùng hướng với delta của Cliff.','r lưỡng phân thứ hạng ghép cặp = (W+ - W-) / (W+ + W-).','Epsilon bình phương = (H - k + 1) / (N - k), với cận dưới là 0.',"W của Kendall = Friedman chi-square / [N * (m - 1)].",'Tỷ số odds ghép cặp = b / c cho các cặp bất tương hợp; nếu một ô bất tương hợp bằng 0, áp dụng hiệu chỉnh liên tục 0.5.','g của Cohen = p01 / (p01 + p10) - 0.5 theo hướng của các cặp bất tương hợp.','Tỷ số odds ghép cặp = p01 / p10; log tỷ số odds = log(p01 / p10).','f2 gia tăng của Cohen = (R2_full - R2_reduced) / (1 - R2_full).','Log tỷ số odds = log(OR); d xấp xỉ của Cohen = log(OR) * sqrt(3) / pi.','f2 của Cohen cho tương tác = delta R-squared / (1 - delta R-squared).'],
}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+key:value for key,value in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
