import json,re
from pathlib import Path
rows='''Binary or categorical event-code variable; mapped to event/non-event for analysis|二値またはカテゴリ型のイベントコード変数。分析時にイベント／非イベントへ対応付けます。|二分类或分类事件代码变量；分析时映射为事件/非事件。|Variable binaria o categórica de código de evento; se asigna a evento/no evento para el análisis.|Variable binaire ou catégorielle de code d’événement ; associée à événement/non-événement pour l’analyse.|Binäre oder kategoriale Ereigniscodevariable; für die Analyse als Ereignis/Nichtereignis zugeordnet.|Biến mã biến cố nhị phân hoặc phân loại; ánh xạ thành biến cố/không biến cố khi phân tích.
Data structure|データ構造|数据结构|Estructura de datos|Structure des données|Datenstruktur|Cấu trúc dữ liệu
Standard Kaplan-Meier|通常のKaplan–Meier|标准Kaplan–Meier|Kaplan–Meier estándar|Kaplan–Meier standard|Standard-Kaplan–Meier|Kaplan–Meier tiêu chuẩn
Delayed-entry Kaplan-Meier|遅延エントリーKaplan–Meier|延迟进入Kaplan–Meier|Kaplan–Meier con entrada tardía|Kaplan–Meier à entrée retardée|Kaplan–Meier mit verzögertem Eintritt|Kaplan–Meier với thời điểm tham gia trễ
Entry time is when each subject joins the risk set and must be earlier than exit time.|観察開始時間は各対象者がリスク集合に入る時点であり、終了時間より前である必要があります。|进入时间是受试者加入风险集的时点，必须早于退出时间。|El tiempo de entrada indica cuándo cada sujeto entra en el conjunto de riesgo y debe preceder al de salida.|Le temps d’entrée indique quand chaque sujet rejoint l’ensemble à risque et doit précéder le temps de sortie.|Die Eintrittszeit bezeichnet den Eintritt in die Risikomenge und muss vor der Austrittszeit liegen.|Thời gian bắt đầu tham gia là lúc đối tượng vào tập nguy cơ và phải trước thời gian kết thúc.
Cox data structure|Coxのデータ構造|Cox数据结构|Estructura de datos de Cox|Structure des données de Cox|Cox-Datenstruktur|Cấu trúc dữ liệu Cox
Standard Cox|通常のCox|标准Cox|Cox estándar|Cox standard|Standard-Cox|Cox tiêu chuẩn
Delayed-entry Cox|遅延エントリーCox|延迟进入Cox|Cox con entrada tardía|Cox à entrée retardée|Cox mit verzögertem Eintritt|Cox với thời điểm tham gia trễ
Time-dependent Cox|時間依存Cox|时间依赖Cox|Cox dependiente del tiempo|Cox dépendant du temps|Zeitabhängiges Cox-Modell|Cox phụ thuộc thời gian
Use standard Cox for one row per subject, delayed-entry Cox for entry/exit times, and time-dependent Cox for start-stop intervals.|対象者ごとに1行の場合は通常のCox、開始・終了時間がある場合は遅延エントリーCox、start–stop区間の場合は時間依存Coxを使用します。|每位受试者一行时使用标准Cox，有进入/退出时间时使用延迟进入Cox，start–stop区间数据使用时间依赖Cox。|Use Cox estándar para una fila por sujeto, Cox con entrada tardía para tiempos de entrada/salida y Cox dependiente del tiempo para intervalos start–stop.|Utilisez Cox standard pour une ligne par sujet, Cox à entrée retardée pour les temps d’entrée/sortie et Cox dépendant du temps pour les intervalles start–stop.|Standard-Cox für eine Zeile je Person, Cox mit verzögertem Eintritt für Eintritts-/Austrittszeiten und zeitabhängiges Cox für Start–Stopp-Intervalle verwenden.|Dùng Cox tiêu chuẩn cho một dòng mỗi đối tượng, Cox tham gia trễ cho thời gian vào/ra và Cox phụ thuộc thời gian cho các khoảng start–stop.
Schoenfeld residual test|Schoenfeld残差検定|Schoenfeld残差检验|Prueba de residuos de Schoenfeld|Test des résidus de Schoenfeld|Schoenfeld-Residualtest|Kiểm định phần dư Schoenfeld
Tied-event handling|同時イベントの処理|并列事件处理|Tratamiento de eventos empatados|Traitement des événements ex æquo|Behandlung zeitgleicher Ereignisse|Xử lý biến cố trùng thời điểm
Partial-likelihood method|部分尤度の方法|偏似然方法|Método de verosimilitud parcial|Méthode de vraisemblance partielle|Methode der partiellen Likelihood|Phương pháp hợp lý riêng phần
Efron (default)|Efron（既定）|Efron（默认）|Efron (predeterminado)|Efron (par défaut)|Efron (Standard)|Efron (mặc định)
Exact|正確法|精确法|Exacto|Exacte|Exakt|Chính xác
Efron is the default. Use exact partial likelihood cautiously for small discrete-time datasets with substantial ties.|既定はEfronです。正確部分尤度は、同時イベントが多い小規模な離散時間データに慎重に使用してください。|默认为Efron。对于并列事件较多的小型离散时间数据集，请谨慎使用精确偏似然。|Efron es el método predeterminado. Use con cautela la verosimilitud parcial exacta en datos pequeños de tiempo discreto con muchos empates.|Efron est la méthode par défaut. Utilisez avec prudence la vraisemblance partielle exacte pour de petits jeux de données en temps discret avec de nombreux ex æquo.|Efron ist der Standard. Exakte partielle Likelihood bei kleinen zeitdiskreten Datensätzen mit vielen zeitgleichen Ereignissen vorsichtig verwenden.|Mặc định là Efron. Thận trọng khi dùng hợp lý riêng phần chính xác cho dữ liệu thời gian rời rạc nhỏ có nhiều biến cố trùng thời điểm.
Stratified Cox|層別Cox|分层Cox|Cox estratificado|Cox stratifié|Stratifiziertes Cox-Modell|Cox phân tầng
Stratification variable|層別変数|分层变量|Variable de estratificación|Variable de stratification|Stratifizierungsvariable|Biến phân tầng
Allows a separate baseline hazard in each stratum; no hazard ratio is estimated for the stratification variable itself.|層ごとに異なるベースラインハザードを許容します。層別変数自体のハザード比は推定しません。|允许每层具有独立的基线风险；不估计分层变量本身的风险比。|Permite un riesgo basal distinto en cada estrato; no se estima una razón de riesgos para la propia variable de estratificación.|Autorise un risque de base distinct par strate ; aucun rapport de risques n’est estimé pour la variable de stratification elle-même.|Erlaubt eine eigene Baseline-Hazard je Stratum; für die Stratifizierungsvariable selbst wird keine Hazard Ratio geschätzt.|Cho phép nguy cơ nền riêng ở mỗi tầng; không ước lượng tỷ số nguy cơ cho chính biến phân tầng.
Cluster-robust variance|クラスターロバスト分散|聚类稳健方差|Varianza robusta por conglomerados|Variance robuste par grappes|Clusterrobuste Varianz|Phương sai vững theo cụm
Cluster ID variable|クラスターID変数|聚类ID变量|Variable de ID de conglomerado|Variable d’identifiant de grappe|Cluster-ID-Variable|Biến ID cụm
Uses sandwich standard errors for within-cluster correlation (for example, hospitals, schools, or households). Few clusters require additional review.|病院・学校・世帯などのクラスター内相関をサンドイッチ標準誤差で考慮します。クラスター数が少ない場合は追加の検討が必要です。|使用三明治标准误处理聚类内相关性，例如医院、学校或家庭。聚类数较少时需要额外检查。|Usa errores estándar sándwich para la correlación intragrupo, por ejemplo en hospitales, escuelas u hogares. Pocos conglomerados requieren revisión adicional.|Utilise des erreurs standards sandwich pour la corrélation au sein des grappes, par exemple hôpitaux, écoles ou ménages. Un faible nombre de grappes nécessite un examen supplémentaire.|Verwendet Sandwich-Standardfehler für Korrelationen innerhalb von Clustern, etwa Krankenhäusern, Schulen oder Haushalten. Wenige Cluster erfordern zusätzliche Prüfung.|Dùng sai số chuẩn sandwich cho tương quan trong cụm, ví dụ bệnh viện, trường học hoặc hộ gia đình. Cần xem xét thêm khi có ít cụm.
Continuous nonlinear effect|連続変数の非線形効果|连续变量非线性效应|Efecto no lineal continuo|Effet non linéaire continu|Nichtlinearer Effekt stetiger Variablen|Hiệu ứng phi tuyến của biến liên tục
Natural cubic spline covariate|自然三次スプラインの共変量|自然三次样条协变量|Covariable de spline cúbico natural|Covariable de spline cubique naturelle|Kovariate für natürlichen kubischen Spline|Đồng biến spline bậc ba tự nhiên
Spline degrees of freedom|スプラインの自由度|样条自由度|Grados de libertad del spline|Degrés de liberté de la spline|Spline-Freiheitsgrade|Bậc tự do của spline
Compares a linear term with a natural cubic spline and reports an HR curve relative to the median. Use for a prespecified covariate.|線形項と自然三次スプラインを比較し、中央値を基準とするHR曲線を示します。事前に指定した共変量に使用してください。|比较线性项与自然三次样条，并报告以中位数为参照的HR曲线。请用于预先指定的协变量。|Compara un término lineal con un spline cúbico natural e informa una curva de HR respecto a la mediana. Úselo para una covariable preespecificada.|Compare un terme linéaire à une spline cubique naturelle et présente une courbe de HR par rapport à la médiane. À utiliser pour une covariable prédéfinie.|Vergleicht einen linearen Term mit einem natürlichen kubischen Spline und zeigt eine HR-Kurve relativ zum Median. Für eine vorab festgelegte Kovariate verwenden.|So sánh số hạng tuyến tính với spline bậc ba tự nhiên và báo cáo đường HR so với trung vị. Dùng cho đồng biến đã xác định trước.
Time-varying coefficient|時間変動係数|时变系数|Coeficiente variable en el tiempo|Coefficient variant dans le temps|Zeitvariabler Koeffizient|Hệ số thay đổi theo thời gian
Covariate with time-varying HR|HRが時間とともに変わる共変量|HR随时间变化的协变量|Covariable con HR variable en el tiempo|Covariable à HR variant dans le temps|Kovariate mit zeitvariabler HR|Đồng biến có HR thay đổi theo thời gian
HR reporting times|HRの報告時点|HR报告时间点|Tiempos de presentación de HR|Temps de présentation des HR|Berichtszeitpunkte der HR|Thời điểm báo cáo HR
e.g., 1, 5, 10 (blank uses event-time quartiles)|例: 1, 5, 10（空欄ではイベント時点の四分位数）|例如：1, 5, 10（留空使用事件时间四分位数）|p. ej., 1, 5, 10 (en blanco: cuartiles de tiempos de evento)|p. ex., 1, 5, 10 (vide : quartiles des temps d’événement)|z. B. 1, 5, 10 (leer: Quartile der Ereigniszeiten)|VD: 1, 5, 10 (để trống: tứ phân vị thời gian biến cố)
Fits covariate × log(1 + time) through coxph tt() and reports time-specific HRs instead of one constant HR.|coxph tt()で共変量 × log(1 + time)を適合し、一定のHRではなく時点別のHRを報告します。|通过coxph tt()拟合协变量 × log(1 + time)，报告各时间点的HR，而非单一恒定HR。|Ajusta covariable × log(1 + time) mediante coxph tt() e informa HR por tiempo en lugar de un HR constante.|Ajuste covariable × log(1 + time) via coxph tt() et présente des HR propres à chaque temps plutôt qu’un HR constant.|Passt Kovariate × log(1 + time) mit coxph tt() an und berichtet zeitpunktspezifische HR statt einer konstanten HR.|Khớp đồng biến × log(1 + time) bằng coxph tt() và báo cáo HR theo từng thời điểm thay vì một HR cố định.
Adjusted-survival reporting times|調整済み生存確率の報告時点|调整生存概率报告时间点|Tiempos de presentación de supervivencia ajustada|Temps de présentation de la survie ajustée|Berichtszeitpunkte des adjustierten Überlebens|Thời điểm báo cáo sống còn hiệu chỉnh
e.g., 12, 36, 60|例: 12, 36, 60|例如：12, 36, 60|p. ej., 12, 36, 60|p. ex., 12, 36, 60|z. B. 12, 36, 60|VD: 12, 36, 60
e.g., 365|例: 365|例如：365|p. ej., 365|p. ex., 365|z. B. 365|VD: 365
Reports group-specific adjusted survival and pairwise differences/ratios at the specified times with pointwise percentile-bootstrap 95% confidence intervals.|指定時点の群別調整済み生存確率と群間の差・比を、各時点のパーセンタイル・ブートストラップ95%信頼区間とともに報告します。|报告指定时间点各组调整生存概率及组间差值/比值，并给出逐点百分位数bootstrap 95%置信区间。|Informa supervivencia ajustada por grupo y diferencias/razones por pares en los tiempos indicados, con intervalos de confianza puntuales del 95% mediante bootstrap percentil.|Présente la survie ajustée par groupe et les différences/rapports par paires aux temps indiqués, avec des intervalles de confiance ponctuels à 95 % par bootstrap percentile.|Berichtet gruppenspezifisches adjustiertes Überleben und paarweise Differenzen/Verhältnisse zu den angegebenen Zeiten mit punktweisen 95%-Perzentil-Bootstrap-Konfidenzintervallen.|Báo cáo sống còn hiệu chỉnh theo nhóm và chênh lệch/tỷ số từng cặp tại các thời điểm chỉ định, kèm khoảng tin cậy 95% bootstrap phân vị tại từng thời điểm.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');d=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  d['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

if '--connect-ui' in __import__('sys').argv:
 p=Path('R/setup_survival_ui.R');s=p.read_text(encoding='utf-8');start=s.index('survival_event_variable_note <-');part=s[start:]
 part=part.replace('  language <- normalize_app_language(language)','  language <- normalize_app_language(language)\n  text <- function(en, kr) statedu_localized_text(language, en, kr)')
 part=re.sub(r'if \((?:identical\(language, "ko"\)|language == "ko")\) "([^"\n]*)" else "([^"\n]*)"',lambda m:'text('+json.dumps(m[2],ensure_ascii=False)+', '+json.dumps(m[1],ensure_ascii=False)+')',part)
 for ko,en in [('c("일반 Kaplan–Meier", "지연 진입 Kaplan–Meier")','c("Standard Kaplan-Meier", "Delayed-entry Kaplan-Meier")'),('c("일반 Cox", "지연 진입 Cox", "시간의존 Cox")','c("Standard Cox", "Delayed-entry Cox", "Time-dependent Cox")')]:
  part=part.replace('if (language == "ko") '+ko+' else '+en,'text('+en+', '+ko+')')
 part=part.replace('c("None" = "", stats::setNames(covariates, covariates))','c(stats::setNames("", text("None", "선택 안 함")), stats::setNames(covariates, covariates))')
 part=part.replace('c("Efron (default)" = "efron", "Breslow" = "breslow", "Exact" = "exact")','stats::setNames(c("efron", "breslow", "exact"), c(text("Efron (default)", "Efron (기본값)"), "Breslow", text("Exact", "정확법")))')
 part=part.replace('placeholder = "e.g., 365"','placeholder = text("e.g., 365", "예: 365")')
 assert 'if (language == "ko")' not in part
 p.write_text(s[:start]+part,encoding='utf-8')
