import json,re
from pathlib import Path
rows='''Supplementary Table %s: PLS measurement bootstrap|補助表%s：PLS測定モデルのブートストラップ|辅助表%s：PLS测量模型自助法|Tabla suplementaria %s: bootstrap del modelo de medida PLS|Tableau complémentaire %s : bootstrap du modèle de mesure PLS|Ergänzungstabelle %s: Bootstrap des PLS-Messmodells|Bảng bổ sung %s: bootstrap mô hình đo lường PLS
PLS bootstrap inference is unavailable (status: %s). Valid resamples: %s/%s; the minimum reporting ratio is %s%%. Outer-loading and weight bootstrap SE, CI, t, and p values are not reported.|PLSブートストラップ推論を利用できません（状態：%s）。有効再標本：%s/%s；最低報告割合は%s%%です。外部負荷量・重みのブートストラップSE、CI、t、pは表示しません。|PLS自助法推断不可用（状态：%s）。有效重抽样：%s/%s；最低报告比例为%s%%。不报告外部载荷和权重的自助法SE、CI、t和p值。|La inferencia bootstrap PLS no está disponible (estado: %s). Remuestras válidas: %s/%s; proporción mínima para informar: %s%%. No se informan SE, IC, t ni p bootstrap de cargas y pesos externos.|L’inférence bootstrap PLS est indisponible (état : %s). Rééchantillonnages valides : %s/%s ; proportion minimale pour le rapport : %s%%. Les SE, IC, t et p bootstrap des saturations et poids externes ne sont pas affichés.|PLS-Bootstrap-Inferenz ist nicht verfügbar (Status: %s). Gültige Stichproben: %s/%s; Mindestanteil für die Berichterstattung: %s%%. Bootstrap-SE, KI, t und p für äußere Ladungen und Gewichte werden nicht berichtet.|Không có suy luận bootstrap PLS (trạng thái: %s). Mẫu hợp lệ: %s/%s; tỷ lệ báo cáo tối thiểu là %s%%. Không báo cáo SE, CI, t và p bootstrap của tải và trọng số ngoài.
Percentile bootstrap CI, t, raw p values, and family-specific BH-adjusted p values for outer loadings and outer weights use only whole-draw contract-valid resamples.|外部負荷量と外部重みのパーセンタイル・ブートストラップCI、t、未調整p値、検定群別BH調整p値は、統計量全体の要件を満たした再標本のみを使用します。|外部载荷和权重的百分位自助法CI、t、原始p值及检验族特定BH校正p值，仅使用满足整组统计量要求的重抽样。|Los IC bootstrap percentiles, t, valores p sin ajustar y valores p ajustados por BH por familia para cargas y pesos externos usan solo remuestras que cumplen los requisitos del conjunto completo de estadísticas.|Les IC bootstrap percentiles, t, valeurs p brutes et valeurs p ajustées par BH par famille pour les saturations et poids externes utilisent uniquement les rééchantillonnages satisfaisant aux exigences de l’ensemble des statistiques.|Perzentil-Bootstrap-KI, t, rohe p-Werte und familienspezifische BH-adjustierte p-Werte für äußere Ladungen und Gewichte verwenden nur Stichproben, die alle Statistikanforderungen erfüllen.|CI bootstrap phân vị, t, giá trị p gốc và p hiệu chỉnh BH theo nhóm kiểm định cho tải và trọng số ngoài chỉ dùng mẫu đáp ứng yêu cầu của toàn bộ thống kê.'''
rows += '\nOuter loading|外部負荷量|外部载荷|Carga externa|Saturation externe|Äußere Ladung|Tải ngoài\nOuter weight|外部重み|外部权重|Peso externo|Poids externe|Äußeres Gewicht|Trọng số ngoài'
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7 and f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
