import json
from pathlib import Path
keys=['one_condition','condition_length','statistic','no_rows','id_variable','value_variable','no_ids','direct_calls','unsupported_element','parse','unknown_symbol','unavailable_function']
rows={
'en':['Enter one condition expression.','Condition must return one TRUE/FALSE value per row.','Statistic must be one of sum, mean, median, sd, var, min, max, n, count.','The current data has no rows.','Select a valid ID variable.','Select a valid value variable.','No valid ID values were found.','Only direct function calls are allowed.','Unsupported expression element.','Condition could not be parsed: %s','Unknown variable or function: %s','Function is not available here: %s'],
'ko':['조건식을 하나만 입력하세요.','조건식은 각 행에 대해 TRUE/FALSE 값 하나를 반환해야 합니다.','통계량은 sum, mean, median, sd, var, min, max, n, count 중 하나여야 합니다.','현재 데이터에 행이 없습니다.','유효한 ID 변수를 선택하세요.','유효한 값 변수를 선택하세요.','유효한 ID 값이 없습니다.','직접 함수 호출만 사용할 수 있습니다.','지원하지 않는 수식 요소입니다.','조건식을 해석할 수 없습니다: %s','알 수 없는 변수 또는 함수: %s','여기에서 사용할 수 없는 함수: %s'],
'ja':['条件式を1つだけ入力してください。','条件式は各行に対してTRUE/FALSEを1つ返す必要があります。','統計量はsum、mean、median、sd、var、min、max、n、countのいずれかである必要があります。','現在のデータに行がありません。','有効なID変数を選択してください。','有効な値変数を選択してください。','有効なID値がありません。','直接の関数呼び出しのみ使用できます。','対応していない式の要素です。','条件式を解析できません: %s','不明な変数または関数: %s','ここでは使用できない関数: %s'],
'zh':['请输入一个条件表达式。','条件表达式必须为每行返回一个 TRUE/FALSE 值。','统计量必须为 sum、mean、median、sd、var、min、max、n 或 count。','当前数据没有行。','请选择有效的 ID 变量。','请选择有效的值变量。','未找到有效的 ID 值。','仅允许直接调用函数。','不支持的表达式元素。','无法解析条件表达式：%s','未知变量或函数：%s','此处不可用的函数：%s'],
'es':['Introduzca una sola expresión de condición.','La condición debe devolver un valor TRUE/FALSE por fila.','El estadístico debe ser sum, mean, median, sd, var, min, max, n o count.','Los datos actuales no tienen filas.','Seleccione una variable de ID válida.','Seleccione una variable de valores válida.','No se encontraron valores de ID válidos.','Solo se permiten llamadas directas a funciones.','Elemento de expresión no admitido.','No se pudo interpretar la condición: %s','Variable o función desconocida: %s','Función no disponible aquí: %s'],
'fr':['Saisissez une seule expression de condition.','La condition doit renvoyer une valeur TRUE/FALSE par ligne.','La statistique doit être sum, mean, median, sd, var, min, max, n ou count.','Les données actuelles ne contiennent aucune ligne.','Sélectionnez une variable ID valide.','Sélectionnez une variable de valeurs valide.','Aucune valeur ID valide n’a été trouvée.','Seuls les appels directs de fonctions sont autorisés.','Élément d’expression non pris en charge.','Impossible d’analyser la condition : %s','Variable ou fonction inconnue : %s','Fonction indisponible ici : %s'],
'de':['Geben Sie genau einen Bedingungsausdruck ein.','Die Bedingung muss pro Zeile einen TRUE/FALSE-Wert zurückgeben.','Die Statistik muss sum, mean, median, sd, var, min, max, n oder count sein.','Die aktuellen Daten enthalten keine Zeilen.','Wählen Sie eine gültige ID-Variable.','Wählen Sie eine gültige Wertevariable.','Keine gültigen ID-Werte gefunden.','Nur direkte Funktionsaufrufe sind zulässig.','Nicht unterstütztes Ausdruckselement.','Die Bedingung konnte nicht geparst werden: %s','Unbekannte Variable oder Funktion: %s','Hier nicht verfügbare Funktion: %s'],
'vi':['Chỉ nhập một biểu thức điều kiện.','Điều kiện phải trả về một giá trị TRUE/FALSE cho mỗi dòng.','Thống kê phải là sum, mean, median, sd, var, min, max, n hoặc count.','Dữ liệu hiện tại không có dòng nào.','Chọn biến ID hợp lệ.','Chọn biến giá trị hợp lệ.','Không tìm thấy giá trị ID hợp lệ.','Chỉ cho phép gọi hàm trực tiếp.','Thành phần biểu thức không được hỗ trợ.','Không thể phân tích điều kiện: %s','Biến hoặc hàm không xác định: %s','Hàm không khả dụng ở đây: %s']}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'id_aggregate.error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
