import json
from pathlib import Path
keys = ['g_sample','g_means','g_pooled','g_se','g_ci','g_d','g_t','g_rpb','g_type','g_rpb_assumption']
rows = {
'en':['Both group sample sizes must be integers of at least 2.','Enter finite means and standard deviations greater than zero for both groups.','The pooled standard deviation must be greater than zero.',"Enter Hedges' g and an SE greater than zero.",'The 95% CI must satisfy lower < g < upper.',"Enter a finite Cohen's d.",'Enter a finite independent-samples t statistic.','The point-biserial correlation must be strictly between -1 and 1.',"Unsupported Hedges' g input type.",'The reported correlation is a point-biserial correlation between group membership and a continuous outcome.'],
'ko':['두 집단의 표본수는 모두 2 이상의 정수여야 합니다.','두 집단 모두 유한한 평균과 0보다 큰 표준편차를 입력하세요.','합동 표준편차는 0보다 커야 합니다.',"Hedges' g와 0보다 큰 SE를 입력하세요.",'95% CI는 하한 < g < 상한을 만족해야 합니다.',"유한한 Cohen's d를 입력하세요.",'유한한 독립표본 t 통계량을 입력하세요.','점이연상관계수는 -1보다 크고 1보다 작아야 합니다.',"지원하지 않는 Hedges' g 입력 유형입니다.",'보고된 상관계수는 집단 소속과 연속형 결과변수 사이의 점이연상관계수입니다.'],
'ja':['両群の標本サイズは2以上の整数である必要があります。','両群について有限の平均と0より大きい標準偏差を入力してください。','プールした標準偏差は0より大きい必要があります。',"Hedges' gと0より大きいSEを入力してください。",'95% CIは下限 < g < 上限を満たす必要があります。',"有限のCohen's dを入力してください。",'有限の独立標本t統計量を入力してください。','点双列相関係数は-1より大きく1より小さい必要があります。',"サポートされていないHedges' gの入力タイプです。",'報告された相関係数は、群への所属と連続型アウトカムの間の点双列相関係数です。'],
'zh':['两组样本量都必须是至少为 2 的整数。','请为两组输入有限的均值和大于零的标准差。','合并标准差必须大于零。',"请输入 Hedges' g 和大于零的 SE。",'95% CI 必须满足下限 < g < 上限。',"请输入有限的 Cohen's d。",'请输入有限的独立样本 t 统计量。','点二列相关系数必须大于 -1 且小于 1。',"不支持的 Hedges' g 输入类型。",'报告的相关系数是组别归属与连续结局变量之间的点二列相关系数。'],
'es':['Los tamaños de ambas muestras deben ser enteros de al menos 2.','Introduzca medias finitas y desviaciones estándar mayores que cero para ambos grupos.','La desviación estándar combinada debe ser mayor que cero.',"Introduzca la g de Hedges y un EE mayor que cero.",'El IC del 95% debe cumplir límite inferior < g < límite superior.',"Introduzca una d de Cohen finita.",'Introduzca un estadístico t de muestras independientes finito.','La correlación biserial puntual debe ser estrictamente mayor que -1 y menor que 1.',"Tipo de entrada de g de Hedges no compatible.",'La correlación informada es una correlación biserial puntual entre la pertenencia al grupo y un resultado continuo.'],
'fr':['Les tailles des deux échantillons doivent être des entiers d’au moins 2.','Saisissez des moyennes finies et des écarts-types supérieurs à zéro pour les deux groupes.','L’écart-type combiné doit être supérieur à zéro.',"Saisissez un g de Hedges et une erreur-type supérieure à zéro.",'L’IC à 95% doit satisfaire borne inférieure < g < borne supérieure.',"Saisissez un d de Cohen fini.",'Saisissez une statistique t pour échantillons indépendants finie.','La corrélation bisérielle ponctuelle doit être strictement comprise entre -1 et 1.',"Type de saisie du g de Hedges non pris en charge.",'La corrélation rapportée est une corrélation bisérielle ponctuelle entre l’appartenance au groupe et une variable de résultat continue.'],
'de':['Beide Stichprobengrößen müssen ganze Zahlen von mindestens 2 sein.','Geben Sie für beide Gruppen endliche Mittelwerte und Standardabweichungen größer als null ein.','Die gepoolte Standardabweichung muss größer als null sein.',"Geben Sie Hedges' g und einen SE größer als null ein.",'Das 95%-KI muss Untergrenze < g < Obergrenze erfüllen.',"Geben Sie ein endliches Cohen's d ein.",'Geben Sie eine endliche t-Statistik für unabhängige Stichproben ein.','Die punktbiseriale Korrelation muss strikt zwischen -1 und 1 liegen.',"Nicht unterstützter Eingabetyp für Hedges' g.",'Die berichtete Korrelation ist eine punktbiseriale Korrelation zwischen Gruppenzugehörigkeit und einer kontinuierlichen Ergebnisvariable.'],
'vi':['Cỡ mẫu của cả hai nhóm phải là số nguyên ít nhất bằng 2.','Nhập trung bình hữu hạn và độ lệch chuẩn lớn hơn 0 cho cả hai nhóm.','Độ lệch chuẩn gộp phải lớn hơn 0.',"Nhập Hedges' g và SE lớn hơn 0.",'Khoảng tin cậy 95% phải thỏa mãn cận dưới < g < cận trên.',"Nhập Cohen's d hữu hạn.",'Nhập thống kê t hai mẫu độc lập hữu hạn.','Hệ số tương quan điểm nhị phân phải lớn hơn -1 và nhỏ hơn 1.',"Không hỗ trợ kiểu đầu vào Hedges' g này.",'Hệ số tương quan được báo cáo là tương quan điểm nhị phân giữa thành viên nhóm và biến kết quả liên tục.'],
}
for lang, values in rows.items():
    path = Path('i18n') / (lang + '.json')
    obj = json.loads(path.read_text(encoding='utf-8'))
    obj['translations'].update({'meta.input_error.' + k: v for k, v in zip(keys, values)})
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
