import json,re
from pathlib import Path
rows='''Higher-order CFA results|高次因子CFAの結果|高阶CFA结果|Resultados de CFA de orden superior|Résultats de CFA d’ordre supérieur|Ergebnisse der CFA höherer Ordnung|Kết quả CFA bậc cao
Higher-order factor|高次因子|高阶因子|Factor de orden superior|Facteur d’ordre supérieur|Faktor höherer Ordnung|Nhân tố bậc cao
Lower-order factor|低次因子|低阶因子|Factor de orden inferior|Facteur d’ordre inférieur|Faktor niedrigerer Ordnung|Nhân tố bậc thấp
Hierarchical omega (ωh)|階層的omega（ωh）|层级omega（ωh）|Omega jerárquico (ωh)|Oméga hiérarchique (ωh)|Hierarchisches Omega (ωh)|Omega phân cấp (ωh)
Review residual/R² interval|残差/R²区間を確認|检查残差/R²区间|Revisar intervalo residual/R²|Examiner l’intervalle résiduel/R²|Residuen-/R²-Intervall prüfen|Kiểm tra khoảng phần dư/R²
Weak loading review|弱い負荷量を確認|检查较弱载荷|Revisar carga débil|Examiner la faible saturation|Schwache Ladung prüfen|Kiểm tra tải yếu
At/above descriptive .40 reference|記述的参考値.40以上|达到或超过描述性参考值.40|Igual o superior a la referencia descriptiva .40|Au moins égal à la référence descriptive .40|Auf/über dem deskriptiven Referenzwert .40|Bằng hoặc trên mức tham khảo mô tả .40
Review inadmissible coefficient|許容範囲外の係数を確認|检查不可接受的系数|Revisar coeficiente inadmisible|Examiner le coefficient inadmissible|Unzulässigen Koeffizienten prüfen|Kiểm tra hệ số không chấp nhận được
Below common .70 guideline|一般的な目安.70未満|低于常用参考值.70|Por debajo de la guía habitual .70|Sous le repère habituel .70|Unter dem üblichen Richtwert .70|Dưới mức hướng dẫn thường dùng .70
At/above descriptive .70 reference|記述的参考値.70以上|达到或超过描述性参考值.70|Igual o superior a la referencia descriptiva .70|Au moins égal à la référence descriptive .70|Auf/über dem deskriptiven Referenzwert .70|Bằng hoặc trên mức tham khảo mô tả .70'''
data_rows=[x.split('|') for x in rows.splitlines()]
notes='''Lower-order R² is|低次因子のR²は高次因子が説明する分散です。残差分散は標準化された潜在変数尺度で報告します。|低阶因子的R²是高阶因子解释的方差。残差方差按标准化潜变量尺度报告。|El R² de orden inferior es la varianza explicada por el factor de orden superior. La varianza residual se informa en la escala latente estandarizada.|Le R² d’ordre inférieur est la variance expliquée par le facteur d’ordre supérieur. La variance résiduelle est rapportée sur l’échelle latente standardisée.|Das R² niedrigerer Ordnung ist die vom Faktor höherer Ordnung erklärte Varianz. Die Residualvarianz wird auf der standardisierten latenten Skala berichtet.|R² bậc thấp là phương sai được giải thích bởi nhân tố bậc cao. Phương sai phần dư được báo cáo trên thang biến tiềm ẩn chuẩn hóa.
Lower-order R² intervals|低次因子のR²区間は標準化残差分散区間の補数です。†はR²区間が[0, 1]を超える場合も示します。|低阶R²区间是标准化残差方差区间的补区间。†也标记超出[0, 1]的R²区间。|Los intervalos R² de orden inferior complementan los de varianza residual estandarizada. † también indica un intervalo R² fuera de [0, 1].|Les intervalles R² d’ordre inférieur sont les compléments des intervalles de variance résiduelle standardisée. † signale aussi un intervalle R² dépassant [0, 1].|R²-Intervalle niedrigerer Ordnung sind die Komplemente der standardisierten Residualvarianzintervalle. † markiert auch R²-Intervalle außerhalb [0, 1].|Khoảng R² bậc thấp là phần bù của khoảng phương sai phần dư chuẩn hóa. † cũng đánh dấu khoảng R² vượt [0, 1].
Higher-order standardized-loading confidence|高次因子の標準化負荷量の信頼区間は、lavaanによる95%デルタ法区間です。|高阶标准化载荷置信区间是lavaan提供的95% delta方法区间。|Los intervalos de las cargas estandarizadas de orden superior son intervalos del 95% por el método delta de lavaan.|Les intervalles des saturations standardisées d’ordre supérieur sont des intervalles à 95 % par la méthode delta de lavaan.|Konfidenzintervalle standardisierter Ladungen höherer Ordnung sind 95%-Delta-Intervalle aus lavaan.|Khoảng tin cậy tải chuẩn hóa bậc cao là khoảng 95% theo phương pháp delta của lavaan.
B confidence intervals are|Bの信頼区間は非標準化高次負荷量の95%区間です。固定された基準負荷量の区間は、その固定値の一点に縮退します。|B置信区间为非标准化高阶载荷的95%区间；固定参考载荷的区间退化为其固定值。|Los intervalos B son intervalos del 95% para cargas no estandarizadas de orden superior; una carga de referencia fija tiene un intervalo degenerado en su valor fijo.|Les intervalles B sont des intervalles à 95 % pour les saturations non standardisées d’ordre supérieur ; une saturation de référence fixée a un intervalle réduit à sa valeur fixe.|B-Konfidenzintervalle sind 95%-Intervalle für unstandardisierte Ladungen höherer Ordnung; eine fixierte Referenzladung hat ein auf ihren festen Wert reduziertes Intervall.|Khoảng tin cậy B là khoảng 95% cho tải bậc cao chưa chuẩn hóa; tải tham chiếu cố định có khoảng suy biến tại giá trị cố định đó.
ωh estimates the proportion|ωhは、適合した高次因子CFAモデルにおいて、単位重み総得点分散のうち1つの高次一般因子に帰属する割合を推定します。|ωh估计在拟合的高阶CFA模型下，单位加权总分方差中归属于一个高阶一般因子的比例。|ωh estima la proporción de varianza del total con pesos unitarios atribuible a un factor general de orden superior bajo el modelo CFA ajustado.|ωh estime la part de variance du score total à poids unitaires attribuable à un facteur général d’ordre supérieur dans le modèle CFA ajusté.|ωh schätzt im angepassten CFA-Modell höherer Ordnung den Anteil der Varianz des einheitsgewichteten Gesamtscores, der einem allgemeinen Faktor höherer Ordnung zuzurechnen ist.|ωh ước lượng tỷ lệ phương sai tổng điểm có trọng số đơn vị quy cho một nhân tố chung bậc cao trong mô hình CFA bậc cao đã khớp.
In a higher-order model|高次因子モデルでは、一般因子は低次因子を介して指標に間接的に影響します。一般因子と特定因子が指標に直接負荷するbifactorモデルとは異なります。高次因子の適合だけでは、一次元性、一般得点の優位性、bifactor構造は証明されません。|在高阶模型中，一般因子通过低阶因子间接影响指标。这不同于一般因子和特定因子直接加载于指标的bifactor模型；仅拟合高阶因子不能证明单维性、一般分数的优越性或bifactor结构。|En un modelo de orden superior, el factor general influye indirectamente en los indicadores mediante factores inferiores. No equivale a un modelo bifactor, donde los factores general y específicos cargan directamente en los indicadores; ajustar un factor superior no demuestra unidimensionalidad, superioridad de una puntuación general ni estructura bifactor.|Dans un modèle d’ordre supérieur, le facteur général agit indirectement sur les indicateurs via les facteurs inférieurs. Ce modèle n’équivaut pas au modèle bifactor, où les facteurs général et spécifiques saturent directement les indicateurs ; ajuster un facteur supérieur ne démontre ni l’unidimensionnalité, ni la supériorité d’un score général, ni une structure bifactor.|In einem Modell höherer Ordnung wirkt der allgemeine Faktor indirekt über Faktoren niedrigerer Ordnung auf Indikatoren. Dies ist kein Bifaktormodell, in dem allgemeine und spezifische Faktoren direkt auf Indikatoren laden. Die Anpassung eines Faktors höherer Ordnung allein belegt weder Eindimensionalität noch die Überlegenheit eines allgemeinen Scores oder eine Bifaktorstruktur.|Trong mô hình bậc cao, nhân tố chung tác động gián tiếp lên chỉ báo qua các nhân tố bậc thấp. Điều này không tương đương mô hình bifactor, nơi nhân tố chung và riêng tải trực tiếp lên chỉ báo; chỉ khớp nhân tố bậc cao không chứng minh tính đơn chiều, ưu thế của điểm chung hay cấu trúc bifactor.
ωh is conditional|ωhは、指定した単位重み総得点と適合した高次因子モデルに条件づけられます。得点利用の正当化には、内容妥当性、妥当な代替モデル、因子得点決定性、独立標本での再現性も必要です。|ωh以指定的单位加权总分和拟合的高阶模型为条件。支持分数使用还需内容效度、合理替代模型、因子得分确定性和独立重复验证。|ωh depende del total especificado con pesos unitarios y del modelo superior ajustado. Justificar el uso del score también requiere validez de contenido, modelos alternativos plausibles, determinación de puntuaciones factoriales y replicación independiente.|ωh est conditionnel au score total à poids unitaires spécifié et au modèle supérieur ajusté. Justifier l’utilisation des scores exige aussi validité de contenu, modèles alternatifs plausibles, détermination des scores factoriels et réplication indépendante.|ωh gilt bedingt auf den festgelegten einheitsgewichteten Gesamtscore und das angepasste Modell höherer Ordnung. Die Score-Nutzung erfordert außerdem Inhaltsvalidität, plausible Alternativmodelle, Faktorwertdeterminiertheit und unabhängige Replikation.|ωh phụ thuộc vào tổng điểm trọng số đơn vị đã chỉ định và mô hình bậc cao đã khớp. Việc dùng điểm còn cần giá trị nội dung, mô hình thay thế hợp lý, tính xác định điểm nhân tố và lặp lại độc lập.
The .40 loading and .70|負荷量.40とωh .70は記述的な検討目安であり、普遍的な合否基準ではありません。†は利用できない値、または[0, 1]外の係数・残差分散を示します。|载荷.40和ωh .70是描述性审查参考，而非普遍适用的通过/不通过规则。†标记不可用值或超出[0, 1]的系数/残差方差。|La carga .40 y ωh .70 son guías descriptivas de revisión, no reglas universales de aprobación. † indica un valor no disponible o un coeficiente/varianza residual fuera de [0, 1].|Les valeurs .40 pour la saturation et .70 pour ωh sont des repères descriptifs, pas des règles universelles d’acceptation. † signale une valeur indisponible ou un coefficient/une variance résiduelle hors [0, 1].|Die Ladung .40 und ωh .70 sind deskriptive Prüfrichtwerte, keine universellen Bestehensregeln. † markiert fehlende Werte oder Koeffizienten/Residualvarianzen außerhalb [0, 1].|Tải .40 và ωh .70 là hướng dẫn xem xét mang tính mô tả, không phải quy tắc đạt/không đạt phổ quát. † đánh dấu giá trị không có hoặc hệ số/phương sai phần dư ngoài [0, 1].
Fixed reference loadings have|固定された基準負荷量には、推定されたSE、z、p値がありません。|固定参考载荷没有估计的SE、z或p值。|Las cargas de referencia fijas no tienen SE, z ni p estimados.|Les saturations de référence fixées n’ont pas de SE, z ou p estimés.|Fixierte Referenzladungen haben keine geschätzten SE-, z- oder p-Werte.|Tải tham chiếu cố định không có SE, z hoặc p được ước lượng.'''
source=Path('R/setup_custom_model_canvas_structural_render_local_fit.R').read_text(encoding='utf-8');sources=re.findall(r'tr\("([^"]+)"',source)
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 # CI headers retain their statistical symbols and translate lower/upper consistently.
 for prefix in ['B','β','R²']:
  for en,local in [('lower',['下限','下限','inferior','inférieure','Untergrenze','dưới'][i-1]),('upper',['上限','上限','superior','supérieure','Obergrenze','trên'][i-1])]:
   key=prefix+' 95% CI '+en
   data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',key.lower()).strip('_')]=(prefix+' ' if prefix!='β' else '')+'95% CI '+local
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
