import json,re
from pathlib import Path
rows='''PLS/PLSc does not support observed covariates or their targets. Estimation was stopped to avoid omitting control effects.	PLS/PLScは観測共変量とその対象をサポートしません。統制効果の欠落を防ぐため推定を停止しました。	PLS/PLSc不支持观测协变量及其目标。为避免遗漏控制效应，已停止估计。	PLS/PLSc no admite covariables observadas ni sus destinos. Se detuvo la estimación para evitar omitir efectos de control.	PLS/PLSc ne prend pas en charge les covariables observées ni leurs cibles. L’estimation est arrêtée pour éviter d’omettre les effets de contrôle.	PLS/PLSc unterstützt keine beobachteten Kovariaten oder deren Zielvariablen. Die Schätzung wurde gestoppt, um Kontrolleffekte nicht auszulassen.	PLS/PLSc không hỗ trợ hiệp biến quan sát hoặc biến đích của chúng. Đã dừng ước lượng để tránh bỏ sót hiệu ứng kiểm soát.
PLS/PLSc does not support fixed/free constraints, fixed or start values, parameter names, or equality labels. Estimation was stopped to avoid ignoring these settings.	PLS/PLScは固定・自由制約、固定値・開始値、パラメータ名、等値ラベルをサポートしません。設定の無視を防ぐため推定を停止しました。	PLS/PLSc不支持固定/自由约束、固定值或初值、参数名称或相等标签。为避免忽略这些设置，已停止估计。	PLS/PLSc no admite restricciones fijas/libres, valores fijos o iniciales, nombres de parámetros ni etiquetas de igualdad. Se detuvo la estimación para evitar ignorar estos ajustes.	PLS/PLSc ne prend pas en charge les contraintes fixes/libres, valeurs fixes ou initiales, noms de paramètres ou étiquettes d’égalité. L’estimation est arrêtée pour éviter d’ignorer ces réglages.	PLS/PLSc unterstützt keine Fix-/Frei-Beschränkungen, Fix- oder Startwerte, Parameternamen oder Gleichheitslabels. Die Schätzung wurde gestoppt, damit diese Einstellungen nicht ignoriert werden.	PLS/PLSc không hỗ trợ ràng buộc cố định/tự do, giá trị cố định hoặc khởi đầu, tên tham số hay nhãn bằng nhau. Đã dừng ước lượng để tránh bỏ qua các thiết lập này.
PLS/PLSc structural paths must be acyclic. Remove reciprocal paths or feedback loops before estimation.	PLS/PLScの構造経路は非循環でなければなりません。推定前に相互経路やフィードバック循環を除去してください。	PLS/PLSc结构路径必须无环。请在估计前删除互反路径或反馈环。	Las trayectorias estructurales PLS/PLSc deben ser acíclicas. Elimine trayectorias recíprocas o bucles de retroalimentación antes de estimar.	Les chemins structurels PLS/PLSc doivent être acycliques. Supprimez les chemins réciproques ou boucles de rétroaction avant l’estimation.	PLS/PLSc-Strukturpfade müssen azyklisch sein. Entfernen Sie vor der Schätzung reziproke Pfade oder Rückkopplungsschleifen.	Đường dẫn cấu trúc PLS/PLSc phải không có chu trình. Hãy loại bỏ đường dẫn đối ứng hoặc vòng phản hồi trước khi ước lượng.
Each PLS/PLSc indicator must belong to one construct only. Remove duplicate indicator assignments or measurement paths.	各PLS/PLSc指標は1つの構成概念にのみ所属できます。重複した指標割当や測定経路を除去してください。	每个PLS/PLSc指标只能属于一个构念。请删除重复的指标分配或测量路径。	Cada indicador PLS/PLSc debe pertenecer a un solo constructo. Elimine asignaciones de indicadores o trayectorias de medición duplicadas.	Chaque indicateur PLS/PLSc doit appartenir à un seul construit. Supprimez les affectations d’indicateurs ou chemins de mesure en double.	Jeder PLS/PLSc-Indikator darf nur einem Konstrukt zugeordnet sein. Entfernen Sie doppelte Indikatorzuordnungen oder Messpfade.	Mỗi chỉ báo PLS/PLSc chỉ được thuộc một khái niệm. Hãy loại bỏ phân công chỉ báo hoặc đường dẫn đo lường trùng lặp.
PLS/PLSc estimation was stopped because the model contains unsupported settings.	モデルに未対応の設定があるため、PLS/PLSc推定を停止しました。	模型包含不受支持的设置，因此已停止PLS/PLSc估计。	Se detuvo la estimación PLS/PLSc porque el modelo contiene ajustes no admitidos.	L’estimation PLS/PLSc est arrêtée car le modèle contient des réglages non pris en charge.	Die PLS/PLSc-Schätzung wurde gestoppt, da das Modell nicht unterstützte Einstellungen enthält.	Đã dừng ước lượng PLS/PLSc vì mô hình chứa thiết lập không được hỗ trợ.
PLS indicators are missing from the current data: %s. Reassign the highlighted indicators to columns in the current data.	現在のデータにPLS指標がありません：%s。強調表示された指標を現在のデータ列に再割当してください。	当前数据缺少PLS指标：%s。请将突出显示的指标重新分配到当前数据列。	Faltan indicadores PLS en los datos actuales: %s. Reasigne los indicadores resaltados a columnas de los datos actuales.	Des indicateurs PLS sont absents des données actuelles : %s. Réaffectez les indicateurs mis en évidence aux colonnes des données actuelles.	PLS-Indikatoren fehlen in den aktuellen Daten: %s. Ordnen Sie die hervorgehobenen Indikatoren erneut Spalten der aktuellen Daten zu.	Dữ liệu hiện tại thiếu chỉ báo PLS: %s. Hãy gán lại các chỉ báo được đánh dấu vào cột của dữ liệu hiện tại.
PLS indicators do not match the current data columns. Reassign the highlighted indicators to columns in the current data.	PLS指標が現在のデータ列と一致しません。強調表示された指標を現在のデータ列に再割当してください。	PLS指标与当前数据列不匹配。请将突出显示的指标重新分配到当前数据列。	Los indicadores PLS no coinciden con las columnas actuales. Reasigne los indicadores resaltados a columnas de los datos actuales.	Les indicateurs PLS ne correspondent pas aux colonnes actuelles. Réaffectez les indicateurs mis en évidence aux colonnes des données actuelles.	PLS-Indikatoren stimmen nicht mit den aktuellen Datenspalten überein. Ordnen Sie die hervorgehobenen Indikatoren erneut zu.	Chỉ báo PLS không khớp với cột dữ liệu hiện tại. Hãy gán lại các chỉ báo được đánh dấu vào cột của dữ liệu hiện tại.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
