import json
from pathlib import Path

rows = '''missing_time_origin|時間原点を入力してください。|请输入时间起点。|Especifique el origen del tiempo.|Précisez l’origine du temps.|Geben Sie den Zeitursprung an.|Nhập mốc thời gian gốc.
missing_time_unit|時間単位を選択または入力してください。|请选择或输入时间单位。|Seleccione o introduzca una unidad de tiempo.|Sélectionnez ou saisissez une unité de temps.|Wählen Sie eine Zeiteinheit oder geben Sie sie ein.|Chọn hoặc nhập đơn vị thời gian.
event_map_not_confirmed|観測されたすべてのイベントコードの意味を確認してください。|请确认所有观测事件代码的含义。|Confirme el significado de cada código de evento observado.|Confirmez la signification de chaque code d’événement observé.|Bestätigen Sie die Bedeutung jedes beobachteten Ereigniscodes.|Xác nhận ý nghĩa của mọi mã biến cố quan sát.
event_of_interest_count|対象イベントのコードを1つだけ指定してください。|请指定且仅指定一个目标事件代码。|Seleccione exactamente un código de evento de interés.|Sélectionnez un seul code d’événement d’intérêt.|Wählen Sie genau einen Code für das interessierende Ereignis.|Chọn đúng một mã biến cố quan tâm.
missing_competing_event_code|競合イベントのコードを1つ以上指定してください。|请至少指定一个竞争事件代码。|Asigne al menos un código a un evento competitivo.|Attribuez au moins un code à un événement concurrent.|Weisen Sie mindestens einen Code einem konkurrierenden Ereignis zu.|Chỉ định ít nhất một mã biến cố cạnh tranh.
missing_time_role|時間変数を選択してください。|请选择时间变量。|Seleccione una variable de tiempo.|Sélectionnez une variable de temps.|Wählen Sie eine Zeitvariable.|Chọn biến thời gian.
missing_event_role|イベント変数を選択してください。|请选择事件变量。|Seleccione una variable de evento.|Sélectionnez une variable d’événement.|Wählen Sie eine Ereignisvariable.|Chọn biến biến cố.
missing_entry_role|観察開始時間の変数を選択してください。|请选择进入时间变量。|Seleccione una variable de tiempo de entrada.|Sélectionnez une variable de temps d’entrée.|Wählen Sie eine Variable für die Eintrittszeit.|Chọn biến thời gian bắt đầu tham gia.
missing_subject_id|Start–stopデータには対象者IDが必要です。|Start–stop数据需要受试者ID。|Los datos start–stop requieren un ID de sujeto.|Les données start–stop nécessitent un identifiant de sujet.|Start–Stopp-Daten benötigen eine Personen-ID.|Dữ liệu start–stop cần ID đối tượng.
missing_interval_role|区間の開始変数と終了変数を選択してください。|请选择区间起始和结束变量。|Seleccione las variables de inicio y fin.|Sélectionnez les variables de début et de fin.|Wählen Sie die Start- und Stoppvariablen.|Chọn biến bắt đầu và kết thúc khoảng.
conflicting_roles|同じ変数が競合する必須の役割に割り当てられています。|同一变量被分配给相互冲突的必需角色。|La misma variable tiene asignados roles obligatorios incompatibles.|La même variable est affectée à des rôles requis incompatibles.|Dieselbe Variable ist unvereinbaren Pflichtrollen zugewiesen.|Cùng một biến được gán cho các vai trò bắt buộc xung đột nhau.
invalid_time|時間値は有限の0以上の値である必要があります。|时间值必须有限且非负。|Los tiempos deben ser finitos y no negativos.|Les temps doivent être finis et non négatifs.|Zeitwerte müssen endlich und nicht negativ sein.|Giá trị thời gian phải hữu hạn và không âm.
entry_not_before_exit|観察開始時間は終了時間より前である必要があります。|进入时间必须早于退出时间。|El tiempo de entrada debe ser anterior al de salida.|Le temps d’entrée doit précéder le temps de sortie.|Die Eintrittszeit muss vor der Austrittszeit liegen.|Thời gian bắt đầu tham gia phải trước thời gian kết thúc.
invalid_interval_time|区間の時間値は有限の0以上の値である必要があります。|区间时间值必须有限且非负。|Los tiempos de los intervalos deben ser finitos y no negativos.|Les temps des intervalles doivent être finis et non négatifs.|Intervallzeiten müssen endlich und nicht negativ sein.|Thời gian của khoảng phải hữu hạn và không âm.
start_not_before_stop|区間の開始時間は終了時間より前である必要があります。|区间起始时间必须早于结束时间。|El inicio debe ser anterior al fin del intervalo.|Le début de l’intervalle doit précéder sa fin.|Die Startzeit muss vor der Stoppzeit liegen.|Thời gian bắt đầu khoảng phải trước thời gian kết thúc.
missing_subject_id_value|すべてのStart–stop行に対象者IDが必要です。|每个Start–stop行都需要受试者ID。|Cada fila start–stop requiere un ID de sujeto.|Chaque ligne start–stop nécessite un identifiant de sujet.|Jede Start–Stopp-Zeile benötigt eine Personen-ID.|Mỗi dòng start–stop cần ID đối tượng.
invalid_event_map|観測された各イベントコードに有効な役割を1つずつ指定してください。|每个观测事件代码必须对应一个有效角色。|Cada código de evento observado debe tener un único rol válido.|Chaque code d’événement observé doit avoir un seul rôle valide.|Jeder beobachtete Ereigniscode muss genau eine gültige Rolle haben.|Mỗi mã biến cố quan sát phải có đúng một vai trò hợp lệ.
overlapping_intervals|同一対象者のリスク区間が重複しています。|同一受试者的风险区间重叠。|Los intervalos de riesgo de un sujeto se superponen.|Les intervalles à risque d’un même sujet se chevauchent.|Risikointervalle derselben Person überlappen sich.|Các khoảng nguy cơ của cùng một đối tượng chồng lấp nhau.
interval_after_event|対象者のイベント発生後にもリスク区間が残っています。|受试者发生事件后仍存在风险区间。|Quedan intervalos de riesgo después del evento del sujeto.|Des intervalles à risque subsistent après l’événement du sujet.|Nach dem Ereignis einer Person verbleiben Risikointervalle.|Vẫn còn khoảng nguy cơ sau khi đối tượng xảy ra biến cố.
multiple_subject_events|標準の時間依存Cox設定で、同一対象者に複数のイベント行があります。|标准时间依赖Cox设置中，同一受试者有多个事件行。|Un sujeto tiene varias filas de evento en la configuración estándar de Cox dependiente del tiempo.|Un sujet présente plusieurs lignes d’événement dans la configuration standard de Cox à covariables dépendantes du temps.|Eine Person hat mehrere Ereigniszeilen in der standardmäßigen zeitabhängigen Cox-Konfiguration.|Một đối tượng có nhiều dòng biến cố trong thiết lập Cox phụ thuộc thời gian tiêu chuẩn.
intervals_not_source_order|一部の対象者の区間が時系列順に保存されていないため、開始時間順で分析します。|部分受试者的区间未按时间顺序存储；分析将按起始时间排序。|Algunos intervalos no están guardados cronológicamente; el análisis usa el orden de inicio.|Certains intervalles ne sont pas stockés chronologiquement ; l’analyse les ordonne par temps de début.|Einige Intervalle sind nicht chronologisch gespeichert; die Analyse ordnet sie nach Startzeit.|Một số khoảng chưa được lưu theo thứ tự thời gian; phân tích sẽ sắp theo thời gian bắt đầu.
no_analysis_rows|生存分析の変数を適用した後に、分析可能な完全な行が残っていません。|应用生存分析变量后，没有完整有效的行可供分析。|No quedan filas completas y válidas tras aplicar las variables de supervivencia.|Aucune ligne complète et valide ne subsiste après application des variables de survie.|Nach Anwendung der Überlebensvariablen bleiben keine vollständigen gültigen Zeilen übrig.|Không còn dòng đầy đủ và hợp lệ sau khi áp dụng các biến phân tích sống còn.
no_events|選択した対象イベントがデータに見つかりません。|数据中未发现所选目标事件。|No se encontraron eventos del tipo de interés seleccionado.|Aucun événement d’intérêt sélectionné n’a été trouvé.|Für das gewählte interessierende Ereignis wurden keine Ereignisse gefunden.|Không tìm thấy biến cố quan tâm đã chọn trong dữ liệu.
potential_competing_events|従来の設定では、対象外の複数のイベントコードが打ち切りとして扱われました。|旧版设置将多个非目标事件代码视为删失。|La configuración anterior trató varios códigos de eventos no seleccionados como censura.|L’ancienne configuration a traité plusieurs codes d’événements non ciblés comme des censures.|Die bisherige Konfiguration behandelte mehrere nicht interessierende Ereigniscodes als Zensierung.|Thiết lập cũ đã xem nhiều mã biến cố không thuộc loại quan tâm là kiểm duyệt.'''
for i, lang in enumerate(['ja','zh','es','fr','de','vi'],1):
    p=Path('i18n')/(lang+'.json'); data=json.loads(p.read_text(encoding='utf-8'))
    for row in rows.splitlines():
        f=row.split('|'); assert len(f)==7
        data['translations']['survival.setup.issue.'+f[0]]=f[i]
    p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
