"""Survival, equivalence and ROC planning method notes."""
import json
from pathlib import Path
keys='note_plan_survival note_plan_tost_exact note_plan_tost_normal note_plan_ni_normal note_plan_auc'.split()
rows={
'en':['Schoenfeld event-based log-rank/Cox approximation using hazard ratio, allocation ratio, and overall event probability.','Exact t-based two-sample TOST equivalence power using TOSTER::power_t_TOST. The margin and expected true difference are entered on the raw mean-difference scale.','Approximate TOST equivalence sample size using normal approximation for the difference.','Approximate one-sided non-inferiority sample size using normal approximation for the difference.','Hanley-McNeil normal approximation for testing one ROC AUC against a null AUC.'],
'ko':['위험비, 배정비, 전체 사건확률을 사용하는 Schoenfeld 사건 수 기반 로그순위/Cox 근사입니다.','TOSTER::power_t_TOST를 사용하는 t 기반 두 표본 TOST 동등성 검정의 정확 검정력 계산입니다. 한계와 예상 실제 차이는 원래 평균차 척도로 입력합니다.','차이에 대한 정규근사를 사용하여 TOST 동등성 검정의 표본수를 근사합니다.','차이에 대한 정규근사를 사용하여 단측 비열등성 검정의 표본수를 근사합니다.','단일 ROC AUC를 영가설 AUC와 검정하는 Hanley–McNeil 정규근사입니다.'],
'ja':['ハザード比、割付比、全体のイベント確率を用いたSchoenfeldのイベント数に基づくログランク/Cox近似です。','TOSTER::power_t_TOSTを用いたt分布に基づく2標本TOST同等性検定の正確な検出力計算です。マージンと期待される真の差は元の平均差尺度で入力します。','差の正規近似を用いてTOST同等性検定の標本サイズを近似します。','差の正規近似を用いて片側非劣性検定の標本サイズを近似します。','単一のROC AUCを帰無仮説のAUCと検定するHanley–McNeil正規近似です。'],
'zh':['使用风险比、分配比和总体事件概率的Schoenfeld事件数型log-rank/Cox近似。','使用TOSTER::power_t_TOST精确计算基于t分布的两样本TOST等效性检验功效。界值和预期真实差值以原始均值差尺度输入。','使用差值的正态近似计算TOST等效性检验的近似样本量。','使用差值的正态近似计算单侧非劣效性检验的近似样本量。','用于检验单个ROC AUC与零假设AUC的Hanley–McNeil正态近似。'],
'es':['Aproximación log-rank/Cox de Schoenfeld basada en eventos con razón de riesgos, razón de asignación y probabilidad global de evento.','Potencia exacta de equivalencia TOST de dos muestras basada en t con TOSTER::power_t_TOST. El margen y la diferencia verdadera esperada se introducen en la escala original de diferencia de medias.','Tamaño muestral aproximado de equivalencia TOST mediante aproximación normal de la diferencia.','Tamaño muestral aproximado de no inferioridad unilateral mediante aproximación normal de la diferencia.','Aproximación normal de Hanley–McNeil para contrastar un AUC ROC con un AUC nulo.'],
'fr':['Approximation log-rank/Cox de Schoenfeld fondée sur les événements avec rapport de risques, rapport d’allocation et probabilité globale d’événement.','Puissance exacte d’équivalence TOST à deux échantillons fondée sur t avec TOSTER::power_t_TOST. La marge et la différence vraie attendue sont saisies sur l’échelle brute de différence des moyennes.','Taille d’échantillon d’équivalence TOST approchée par approximation normale de la différence.','Taille d’échantillon de non-infériorité unilatérale approchée par approximation normale de la différence.','Approximation normale de Hanley–McNeil pour tester une AUC ROC contre une AUC nulle.'],
'de':['Ereignisbasierte Log-Rank/Cox-Approximation nach Schoenfeld mit Hazard Ratio, Zuteilungsverhältnis und Gesamtwahrscheinlichkeit eines Ereignisses.','Exakte t-basierte Zweistichproben-TOST-Äquivalenzpower mit TOSTER::power_t_TOST. Marge und erwartete wahre Differenz werden auf der ursprünglichen Mittelwertdifferenzskala eingegeben.','Approximierter TOST-Äquivalenzstichprobenumfang mittels Normalapproximation der Differenz.','Approximierter einseitiger Nichtunterlegenheitsstichprobenumfang mittels Normalapproximation der Differenz.','Hanley–McNeil-Normalapproximation zum Test einer ROC-AUC gegen eine Null-AUC.'],
'vi':['Xấp xỉ log-rank/Cox dựa trên số biến cố của Schoenfeld, sử dụng tỷ số nguy cơ, tỷ lệ phân bổ và xác suất biến cố chung.','Công suất tương đương TOST hai mẫu chính xác dựa trên t bằng TOSTER::power_t_TOST. Biên và chênh lệch thực kỳ vọng được nhập trên thang chênh lệch trung bình gốc.','Cỡ mẫu tương đương TOST xấp xỉ bằng xấp xỉ chuẩn cho chênh lệch.','Cỡ mẫu không thua kém một phía xấp xỉ bằng xấp xỉ chuẩn cho chênh lệch.','Xấp xỉ chuẩn Hanley–McNeil để kiểm định một ROC AUC so với AUC giả thuyết không.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
