import json,re
from pathlib import Path
rows='''Unique target-failure times|異なる関心イベント時点数|不同目标事件时点数|Tiempos distintos del evento de interés|Temps distincts de l’événement d’intérêt|Unterschiedliche Zielereigniszeiten|Số thời điểm biến cố quan tâm khác nhau
Exploratory p|探索的p値|探索性p值|p exploratorio|p exploratoire|Explorativer p-Wert|p thăm dò
Holm-adjusted p|Holm補正p値|Holm校正p值|p ajustado por Holm|p ajusté par Holm|Holm-adjustierter p-Wert|p hiệu chỉnh Holm
Review possible time-varying subdistribution effect|時間依存の部分分布効果の可能性を検討|审查可能的时变亚分布效应|Revisar posible efecto de subdistribución variable en el tiempo|Examiner un éventuel effet de sous-distribution variant dans le temps|Möglichen zeitabhängigen Subdistributionseffekt prüfen|Xem xét khả năng hiệu ứng phân phối phụ thay đổi theo thời gian
No monotonic time-pattern signal in this exploratory screen|この探索的検討では単調な時間パターンのシグナルなし|此次探索性筛查中无单调时间模式信号|Sin señal de patrón temporal monótono en este examen exploratorio|Aucun signal de tendance temporelle monotone dans cet examen exploratoire|Kein monotones Zeitmustersignal in dieser explorativen Prüfung|Không có dấu hiệu mẫu hình thời gian đơn điệu trong sàng lọc thăm dò này
Proportional subdistribution hazards review|比例部分分布ハザードの検討|比例亚分布风险审查|Revisión de riesgos proporcionales de subdistribución|Examen des risques proportionnels de sous-distribution|Prüfung proportionaler Subdistributionshazards|Xem xét nguy cơ phân phối phụ tỷ lệ
The crr Schoenfeld-like residual plot is the primary descriptive lack-of-fit review. Spearman correlations and Holm-adjusted p-values are exploratory monotonic-trend screens, not a formal cox.zph-equivalent test and not an automatic assumption pass/fail decision.|crrのSchoenfeld型残差図は、主たる記述的な不適合の検討です。Spearman相関とHolm補正p値は探索的な単調傾向のスクリーニングであり、正式なcox.zph相当の検定や仮定の自動的な合否判定ではありません。|crr的Schoenfeld型残差图是主要的描述性拟合不足检查。Spearman相关和Holm校正p值用于探索性单调趋势筛查，并非正式的cox.zph等效检验，也不是对假设的自动通过或不通过判定。|El gráfico de residuos tipo Schoenfeld de crr es la revisión descriptiva principal de falta de ajuste. Las correlaciones de Spearman y los valores p ajustados por Holm exploran tendencias monótonas; no son una prueba formal equivalente a cox.zph ni una decisión automática sobre el cumplimiento del supuesto.|Le graphique des résidus de type Schoenfeld de crr constitue l’examen descriptif principal du défaut d’ajustement. Les corrélations de Spearman et les valeurs p ajustées par Holm explorent les tendances monotones ; elles ne sont ni un test formel équivalent à cox.zph ni une décision automatique sur le respect de l’hypothèse.|Der Schoenfeld-ähnliche Residuenplot von crr ist die primäre deskriptive Prüfung mangelnder Anpassung. Spearman-Korrelationen und Holm-adjustierte p-Werte prüfen explorativ monotone Trends; sie sind weder ein formaler cox.zph-äquivalenter Test noch eine automatische Entscheidung über die Erfüllung der Annahme.|Đồ thị phần dư kiểu Schoenfeld của crr là công cụ mô tả chính để xem xét sự thiếu phù hợp. Tương quan Spearman và giá trị p hiệu chỉnh Holm là sàng lọc thăm dò xu hướng đơn điệu, không phải kiểm định chính thức tương đương cox.zph hay quyết định tự động về việc đáp ứng giả định.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
