import json,re
from pathlib import Path
rows='''Loading|負荷量|载荷|Carga|Saturation|Ladung|Tải
Formative redundancy analysis|形成型冗長性分析|形成性冗余分析|Análisis de redundancia formativa|Analyse de redondance formative|Formative Redundanzanalyse|Phân tích dư thừa cho mô hình tạo thành
Not assessed: %s|未評価：%s|未评估：%s|No evaluado: %s|Non évalué : %s|Nicht bewertet: %s|Chưa đánh giá: %s
Redundancy analysis was not requested.|冗長性分析は要求されていません。|未请求冗余分析。|No se solicitó el análisis de redundancia.|L’analyse de redondance n’a pas été demandée.|Die Redundanzanalyse wurde nicht angefordert.|Chưa yêu cầu phân tích dư thừa.
no global criterion was selected.|全体的な基準変数が選択されていません。|未选择全局效标变量。|No se seleccionó ningún criterio global.|Aucun critère global n’a été sélectionné.|Es wurde kein globales Kriterium ausgewählt.|Chưa chọn biến tiêu chí tổng thể.
A formative construct and a separate global criterion were not both selected.|形成型構成概念と独立した全体的な基準変数の両方が選択されていません。|未同时选择形成性构念和独立的全局效标。|No se seleccionaron conjuntamente un constructo formativo y un criterio global separado.|Un construit formatif et un critère global distinct n’ont pas tous deux été sélectionnés.|Ein formatives Konstrukt und ein separates globales Kriterium wurden nicht beide ausgewählt.|Chưa chọn đồng thời cấu trúc tạo thành và một tiêu chí tổng thể riêng biệt.
Redundancy analysis requires a formative composite.|冗長性分析には形成型コンポジットが必要です。|冗余分析需要形成性复合变量。|El análisis de redundancia requiere un compuesto formativo.|L’analyse de redondance nécessite un composite formatif.|Die Redundanzanalyse erfordert ein formatives Komposit.|Phân tích dư thừa cần một biến tổng hợp tạo thành.
The global criterion must be separate from the formative indicators.|全体的な基準変数は形成型指標とは別である必要があります。|全局效标必须独立于形成性指标。|El criterio global debe ser distinto de los indicadores formativos.|Le critère global doit être distinct des indicateurs formatifs.|Das globale Kriterium muss von den formativen Indikatoren getrennt sein.|Tiêu chí tổng thể phải tách biệt với các chỉ báo tạo thành.
The selected construct score is unavailable.|選択された構成概念のスコアを利用できません。|所选构念得分不可用。|La puntuación del constructo seleccionado no está disponible.|Le score du construit sélectionné n’est pas disponible.|Der Wert des ausgewählten Konstrukts ist nicht verfügbar.|Không có điểm của cấu trúc đã chọn.
The global criterion must be a numeric variable available to the PLS model.|全体的な基準変数はPLSモデルで利用できる数値変数である必要があります。|全局效标必须是PLS模型中可用的数值变量。|El criterio global debe ser una variable numérica disponible para el modelo PLS.|Le critère global doit être une variable numérique disponible pour le modèle PLS.|Das globale Kriterium muss eine im PLS-Modell verfügbare numerische Variable sein.|Tiêu chí tổng thể phải là biến số có sẵn cho mô hình PLS.
Construct-score and criterion row counts do not match after PLS preprocessing.|PLS前処理後の構成概念スコアと基準変数の行数が一致しません。|PLS预处理后，构念得分与效标的行数不一致。|El número de filas de las puntuaciones del constructo y del criterio no coincide tras el preprocesamiento PLS.|Le nombre de lignes des scores du construit et du critère diffère après le prétraitement PLS.|Die Zeilenzahlen von Konstruktwerten und Kriterium stimmen nach der PLS-Vorverarbeitung nicht überein.|Số dòng điểm cấu trúc và tiêu chí không khớp sau khi tiền xử lý PLS.
At least four complete construct-score/criterion pairs are required.|構成概念スコアと基準変数の完全なペアが少なくとも4組必要です。|至少需要四对完整的构念得分与效标数据。|Se requieren al menos cuatro pares completos de puntuación del constructo y criterio.|Au moins quatre paires complètes de score du construit et de critère sont nécessaires.|Mindestens vier vollständige Paare aus Konstruktwert und Kriterium sind erforderlich.|Cần ít nhất bốn cặp điểm cấu trúc và tiêu chí đầy đủ.
The redundancy relationship could not be estimated because one variable has no variance.|一方の変数に分散がないため、冗長性の関係を推定できませんでした。|由于一个变量没有方差，无法估计冗余关系。|No se pudo estimar la relación de redundancia porque una variable no tiene varianza.|La relation de redondance n’a pas pu être estimée car une variable n’a pas de variance.|Die Redundanzbeziehung konnte nicht geschätzt werden, da eine Variable keine Varianz aufweist.|Không thể ước lượng quan hệ dư thừa vì một biến không có phương sai.
At/above the descriptive .70 redundancy reference; also verify criterion content validity and independence.|記述的な冗長性参考値.70以上です。基準変数の内容的妥当性と独立性も確認してください。|达到或超过描述性冗余参考值.70；还应验证效标的内容效度与独立性。|Alcanza o supera la referencia descriptiva de redundancia de .70; compruebe también la validez de contenido y la independencia del criterio.|La référence descriptive de redondance de .70 est atteinte ou dépassée ; vérifiez aussi la validité de contenu et l’indépendance du critère.|Der deskriptive Redundanzreferenzwert von .70 ist erreicht oder überschritten; prüfen Sie auch Inhaltsvalidität und Unabhängigkeit des Kriteriums.|Đạt hoặc vượt giá trị tham chiếu mô tả .70 cho dư thừa; cũng cần kiểm tra độ giá trị nội dung và tính độc lập của tiêu chí.
Redundancy evidence is below the common descriptive .70 loading reference; review criterion quality and construct specification.|冗長性の根拠は一般的な記述的負荷量参考値.70未満です。基準変数の質と構成概念の指定を検討してください。|冗余证据低于常用的描述性载荷参考值.70；请检查效标质量与构念设定。|La evidencia de redundancia está por debajo de la referencia descriptiva habitual de carga de .70; revise la calidad del criterio y la especificación del constructo.|Les éléments de redondance sont inférieurs à la référence descriptive usuelle de saturation de .70 ; examinez la qualité du critère et la spécification du construit.|Die Redundanzevidenz liegt unter dem üblichen deskriptiven Ladungsreferenzwert von .70; prüfen Sie die Qualität des Kriteriums und die Konstruktspezifikation.|Bằng chứng dư thừa thấp hơn giá trị tham chiếu tải mô tả thông thường .70; cần xem xét chất lượng tiêu chí và đặc tả cấu trúc.
.70 is a descriptive reference, not an automatic pass rule. Also verify that the criterion adequately covers the same concept and was measured independently of the formative indicators.|.70は記述的な参考値であり、自動的な合格基準ではありません。基準変数が同じ概念を十分に網羅し、形成型指標とは独立して測定されたことも確認してください。|.70是描述性参考值，并非自动通过标准。还需确认效标充分涵盖同一概念，且独立于形成性指标测量。|.70 es una referencia descriptiva, no una regla automática de aprobación. Verifique además que el criterio cubra adecuadamente el mismo concepto y se haya medido de forma independiente de los indicadores formativos.|.70 est une référence descriptive, pas une règle automatique de validation. Vérifiez aussi que le critère couvre suffisamment le même concept et a été mesuré indépendamment des indicateurs formatifs.|.70 ist ein deskriptiver Referenzwert, keine automatische Bestehensgrenze. Prüfen Sie auch, ob das Kriterium dasselbe Konzept ausreichend abdeckt und unabhängig von den formativen Indikatoren gemessen wurde.|.70 là giá trị tham chiếu mô tả, không phải ngưỡng tự động đạt. Cũng cần xác minh rằng tiêu chí bao quát đầy đủ cùng khái niệm và được đo độc lập với các chỉ báo tạo thành.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7 and f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
