import json
from pathlib import Path
keys=['competing_covariate','cengroup_model','cengroup_missing','cengroup_role','interest_code','cengroup_min','cengroup_max']
rows={
'en':['Select at least one covariate for competing-risks regression.','Censoring-distribution stratification (cengroup) is available only with Fine-Gray regression.','The selected censoring-distribution stratification variable was not found.','The censoring-distribution stratification variable cannot also be the time or event variable.','Select exactly one event-of-interest code for competing-risks analysis.','Censoring-distribution stratification requires at least two observed levels.','Censoring-distribution stratification must use a categorical variable with no more than 20 observed levels.'],
'ko':['경쟁위험 회귀분석의 공변량을 하나 이상 선택하세요.','검열 분포 층화(cengroup)는 Fine-Gray 회귀분석에서만 사용할 수 있습니다.','선택한 검열 분포 층화 변수를 찾지 못했습니다.','검열 분포 층화 변수를 시간 또는 사건 변수로도 사용할 수 없습니다.','경쟁위험 분석의 관심 사건 코드를 정확히 하나 선택하세요.','검열 분포 층화에는 관측된 수준이 둘 이상 필요합니다.','검열 분포 층화에는 관측된 수준이 20개 이하인 범주형 변수를 사용해야 합니다.'],
'ja':['競合リスク回帰の共変量を1つ以上選択してください。','打ち切り分布の層別化（cengroup）はFine-Gray回帰でのみ使用できます。','選択した打ち切り分布の層別変数が見つかりません。','打ち切り分布の層別変数を時間変数またはイベント変数としても使用することはできません。','競合リスク分析の関心イベントコードを正確に1つ選択してください。','打ち切り分布の層別化には観測された水準が2つ以上必要です。','打ち切り分布の層別化には観測された水準が20以下のカテゴリ変数を使用してください。'],
'zh':['请为竞争风险回归至少选择一个协变量。','检删分布分层（cengroup）仅适用于 Fine-Gray 回归。','未找到所选的检删分布分层变量。','检删分布分层变量不能同时用作时间变量或事件变量。','请为竞争风险分析选择且仅选择一个关注事件编码。','检删分布分层要求至少有两个已观测到的水平。','检删分布分层必须使用已观测水平不超过 20 个的分类变量。'],
'es':['Seleccione al menos una covariable para la regresión de riesgos competitivos.','La estratificación de la distribución de censura (cengroup) solo está disponible con la regresión de Fine-Gray.','No se encontró la variable seleccionada para estratificar la distribución de censura.','La variable de estratificación de la distribución de censura no puede ser también la variable de tiempo o de evento.','Seleccione exactamente un código de evento de interés para el análisis de riesgos competitivos.','La estratificación de la distribución de censura requiere al menos dos niveles observados.','La estratificación de la distribución de censura debe usar una variable categórica con un máximo de 20 niveles observados.'],
'fr':['Sélectionnez au moins une covariable pour la régression des risques concurrents.','La stratification de la distribution de censure (cengroup) est disponible uniquement avec la régression de Fine-Gray.','La variable sélectionnée pour stratifier la distribution de censure est introuvable.','La variable de stratification de la distribution de censure ne peut pas aussi être la variable de temps ou d’événement.','Sélectionnez exactement un code d’événement d’intérêt pour l’analyse des risques concurrents.','La stratification de la distribution de censure nécessite au moins deux niveaux observés.','La stratification de la distribution de censure doit utiliser une variable catégorielle comportant au plus 20 niveaux observés.'],
'de':['Wählen Sie mindestens eine Kovariate für die Regression konkurrierender Risiken aus.','Die Stratifizierung der Zensierungsverteilung (cengroup) ist nur mit der Fine-Gray-Regression verfügbar.','Die ausgewählte Variable zur Stratifizierung der Zensierungsverteilung wurde nicht gefunden.','Die Variable zur Stratifizierung der Zensierungsverteilung darf nicht zugleich die Zeit- oder Ereignisvariable sein.','Wählen Sie für die Analyse konkurrierender Risiken genau einen Code für das interessierende Ereignis aus.','Die Stratifizierung der Zensierungsverteilung erfordert mindestens zwei beobachtete Stufen.','Die Stratifizierung der Zensierungsverteilung muss eine kategoriale Variable mit höchstens 20 beobachteten Stufen verwenden.'],
'vi':['Chọn ít nhất một hiệp biến cho hồi quy rủi ro cạnh tranh.','Phân tầng phân phối kiểm duyệt (cengroup) chỉ khả dụng với hồi quy Fine-Gray.','Không tìm thấy biến phân tầng phân phối kiểm duyệt đã chọn.','Biến phân tầng phân phối kiểm duyệt không được đồng thời là biến thời gian hoặc sự kiện.','Chọn đúng một mã sự kiện quan tâm cho phân tích rủi ro cạnh tranh.','Phân tầng phân phối kiểm duyệt cần ít nhất hai mức được quan sát.','Phân tầng phân phối kiểm duyệt phải dùng biến phân loại có không quá 20 mức được quan sát.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
