import json,re
from pathlib import Path

rows='''Guide for Table 2: Likelihood-based information criteria	表2のガイド：尤度に基づく情報量規準	表2指南：基于似然的信息准则	Guía de la tabla 2: criterios de información basados en la verosimilitud	Guide du tableau 2 : critères d’information fondés sur la vraisemblance	Hinweise zu Tabelle 2: Likelihood-basierte Informationskriterien	Hướng dẫn bảng 2: tiêu chí thông tin dựa trên hợp lý
Lower AIC, BIC, and adjusted BIC indicate better relative expected fit after penalizing complexity; delta values are relative to the smallest criterion in this displayed set.	AIC、BIC、調整済みBICが小さいほど、複雑さへのペナルティを考慮した相対的な期待適合が良好です。差分は表示したモデル集合の最小値を基準とします。	AIC、BIC和调整BIC越小，表示在惩罚复杂度后相对预期拟合越好；差值以所显示模型集合中的最小准则值为基准。	Valores menores de AIC, BIC y BIC ajustado indican mejor ajuste esperado relativo tras penalizar la complejidad; las diferencias se calculan respecto al menor valor del conjunto mostrado.	Des valeurs plus faibles d’AIC, de BIC et de BIC ajusté indiquent un meilleur ajustement attendu relatif après pénalisation de la complexité ; les différences sont calculées par rapport au minimum de l’ensemble affiché.	Kleinere AIC-, BIC- und adjustierte BIC-Werte zeigen nach Berücksichtigung der Komplexitätsstrafe einen besseren relativen erwarteten Fit; Differenzen beziehen sich auf den kleinsten Wert der angezeigten Modelle.	AIC, BIC và BIC hiệu chỉnh thấp hơn cho thấy độ phù hợp kỳ vọng tương đối tốt hơn sau khi phạt độ phức tạp; chênh lệch được tính so với giá trị nhỏ nhất trong tập mô hình hiển thị.
Delta values were suppressed because analyzed observations, observed variables, estimator family, or model admissibility differed across models.	分析対象の観測、観測変数、推定法の系列、またはモデルの許容性がモデル間で異なるため、差分を非表示にしました。	由于模型间的分析观测、观测变量、估计方法类别或模型可容许性不同，差值未显示。	Se omitieron las diferencias porque las observaciones analizadas, variables observadas, familia del estimador o admisibilidad difieren entre modelos.	Les différences sont masquées car les observations analysées, les variables observées, la famille d’estimateurs ou l’admissibilité diffèrent entre modèles.	Differenzen werden nicht angezeigt, da sich analysierte Beobachtungen, beobachtete Variablen, Schätzerfamilie oder Modellzulässigkeit zwischen den Modellen unterscheiden.	Không hiển thị chênh lệch vì các quan sát phân tích, biến quan sát, họ phương pháp ước lượng hoặc tính chấp nhận được khác nhau giữa các mô hình.
Compare information criteria only for models fitted to the same observations and observed variables with the same likelihood and estimator family. They are not absolute goodness-of-fit tests and are not reported for WLSMV models without a comparable likelihood.	情報量規準は、同じ観測と観測変数に対し、同じ尤度と推定法の系列で適合したモデル間でのみ比較してください。絶対的な適合度検定ではなく、比較可能な尤度がないWLSMVモデルでは報告しません。	仅比较使用相同观测和观测变量、相同似然及估计方法类别拟合的模型的信息准则。这些准则不是绝对拟合优度检验；没有可比似然的WLSMV模型不报告这些准则。	Compare los criterios solo entre modelos ajustados a las mismas observaciones y variables observadas, con la misma verosimilitud y familia de estimadores. No son pruebas de ajuste absoluto ni se informan para modelos WLSMV sin verosimilitud comparable.	Comparez ces critères uniquement entre modèles ajustés aux mêmes observations et variables observées, avec la même vraisemblance et famille d’estimateurs. Ce ne sont pas des tests d’ajustement absolu ; ils ne sont pas rapportés pour les modèles WLSMV sans vraisemblance comparable.	Vergleichen Sie Informationskriterien nur für Modelle mit denselben Beobachtungen und beobachteten Variablen sowie derselben Likelihood und Schätzerfamilie. Sie sind keine absoluten Anpassungstests und werden für WLSMV-Modelle ohne vergleichbare Likelihood nicht berichtet.	Chỉ so sánh tiêu chí thông tin giữa các mô hình khớp trên cùng quan sát và biến quan sát, cùng hàm hợp lý và họ phương pháp ước lượng. Đây không phải kiểm định độ phù hợp tuyệt đối và không được báo cáo cho mô hình WLSMV không có hàm hợp lý so sánh được.
Single model; delta not applicable	単一モデル：差分は該当なし	单一模型；差值不适用	Modelo único; diferencia no aplicable	Modèle unique ; différence sans objet	Einzelmodell; Differenz nicht anwendbar	Một mô hình; không áp dụng chênh lệch
Comparable on observations, variables, estimator family, and admissibility	観測・変数・推定法の系列・許容性について比較可能	观测、变量、估计方法类别及可容许性均可比	Comparable en observaciones, variables, familia del estimador y admisibilidad	Comparable pour les observations, variables, famille d’estimateurs et admissibilité	Hinsichtlich Beobachtungen, Variablen, Schätzerfamilie und Zulässigkeit vergleichbar	Có thể so sánh về quan sát, biến, họ phương pháp ước lượng và tính chấp nhận được
Not comparable; inadmissible model; delta suppressed	比較不可：許容できないモデルのため差分非表示	不可比；模型不可容许；不显示差值	No comparable; modelo inadmisible; diferencia omitida	Non comparable ; modèle inadmissible ; différence masquée	Nicht vergleichbar; unzulässiges Modell; Differenz ausgeblendet	Không thể so sánh; mô hình không chấp nhận được; ẩn chênh lệch
Not comparable; delta suppressed	比較不可：差分非表示	不可比；不显示差值	No comparable; diferencia omitida	Non comparable ; différence masquée	Nicht vergleichbar; Differenz ausgeblendet	Không thể so sánh; ẩn chênh lệch'''
rows+='''
Admissible	許容性	可容许性	Admisibilidad	Admissibilité	Zulässigkeit	Tính chấp nhận được
Params	パラメータ数	参数数	N.º de parámetros	Nb de paramètres	Parameterzahl	Số tham số
Adj BIC	調整済みBIC	调整BIC	BIC ajustado	BIC ajusté	Adjustiertes BIC	BIC hiệu chỉnh'''
key=lambda s:'analysis.ui.'+re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  fields=line.split('\t');assert len(fields)==7
  data['translations'][key(fields[0])]=fields[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=Path('i18n/ko.json');data=json.loads(p.read_text(encoding='utf-8'))
for source,value in {'Admissible':'허용성','Params':'모수 수','Adj BIC':'조정 BIC'}.items():
 data['translations'][key(source)]=value
for source,value in zip([line.split('\t')[0] for line in rows.splitlines()][4:],['단일 모형: 차이값 해당 없음','관측치, 변수, 추정량 계열 및 허용성 비교 가능','비교 불가: 허용되지 않는 모형으로 차이값 숨김','비교 불가: 차이값 숨김']):
 data['translations'][key(source)]=value
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
