import json
from pathlib import Path

keys = 'title subtitle heading files csv_header dat_header delimiter variables id rows left inner full cases indicator_name indicator_values common keep preview loaded whitespace tab comma message no_files file rows_header columns choose'.split()
rows = {
'en': ['Merge','Add variables by ID or add cases from multiple files.','Merge data files','Files to merge','CSV first row contains variable names','DAT first row contains variable names','DAT delimiter','Add variables','ID variable','Rows to keep','First file + matched variables','Matched IDs only','All IDs','Add cases','Indicator variable name','Indicator values','Select files with common variable names.','Variables to keep','Preview created: %s row(s), %s variable(s).','Merged data loaded: %s row(s), %s variable(s).','Whitespace','Tab','Comma','Message','No files selected.','File','Rows','Columns','Choose files'],
'ko': ['데이터 병합','ID 기준 변수 추가 또는 여러 파일의 케이스 추가를 수행합니다.','데이터 파일 병합','병합할 파일','CSV 첫 행을 변수명으로 사용','DAT 첫 행을 변수명으로 사용','DAT 구분자','변수 추가','ID 기준변수','유지할 케이스','첫 번째 파일 기준','공통 ID만','모든 ID','케이스 추가','지시변수 이름','지시값','공통 변수명이 있는 파일을 선택하세요.','유지할 변수','미리보기 생성: %s행, 변수 %s개.','병합된 데이터 불러오기 완료: %s행, 변수 %s개.','공백','탭','쉼표','안내','선택한 파일이 없습니다.','파일','행','열','파일 선택'],
'ja': ['データ結合','IDを基準に変数を追加するか、複数のファイルからケースを追加します。','データファイルの結合','結合するファイル','CSVの先頭行を変数名として使用','DATの先頭行を変数名として使用','DATの区切り文字','変数を追加','ID変数','保持する行','最初のファイルに一致する変数を追加','一致するIDのみ','すべてのID','ケースを追加','識別変数名','識別値','共通の変数名を持つファイルを選択してください。','保持する変数','プレビューを作成しました：%s行、%s変数。','結合データを読み込みました：%s行、%s変数。','空白','タブ','カンマ','メッセージ','ファイルが選択されていません。','ファイル','行','列','ファイルを選択'],
'zh': ['数据合并','按 ID 添加变量，或从多个文件添加个案。','合并数据文件','要合并的文件','将 CSV 首行用作变量名','将 DAT 首行用作变量名','DAT 分隔符','添加变量','ID 变量','保留的行','在第一个文件中添加匹配变量','仅匹配的 ID','所有 ID','添加个案','标识变量名','标识值','请选择具有共同变量名的文件。','保留的变量','已创建预览：%s 行，%s 个变量。','已加载合并数据：%s 行，%s 个变量。','空白','制表符','逗号','提示','未选择文件。','文件','行','列','选择文件'],
'es': ['Combinar datos','Añadir variables por ID o añadir casos de varios archivos.','Combinar archivos de datos','Archivos para combinar','La primera fila del CSV contiene nombres de variables','La primera fila del DAT contiene nombres de variables','Delimitador DAT','Añadir variables','Variable ID','Filas que se conservarán','Primer archivo más variables coincidentes','Solo ID coincidentes','Todos los ID','Añadir casos','Nombre de la variable indicadora','Valores del indicador','Seleccione archivos con nombres de variables comunes.','Variables que se conservarán','Vista previa creada: %s filas, %s variables.','Datos combinados cargados: %s filas, %s variables.','Espacio en blanco','Tabulación','Coma','Mensaje','No hay archivos seleccionados.','Archivo','Filas','Columnas','Seleccionar archivos'],
'fr': ['Fusionner les données','Ajouter des variables par ID ou des cas provenant de plusieurs fichiers.','Fusionner des fichiers de données','Fichiers à fusionner','La première ligne du CSV contient les noms des variables','La première ligne du DAT contient les noms des variables','Séparateur DAT','Ajouter des variables','Variable ID','Lignes à conserver','Premier fichier et variables correspondantes','ID correspondants uniquement','Tous les ID','Ajouter des cas','Nom de la variable indicatrice','Valeurs de l’indicateur','Sélectionnez des fichiers ayant des noms de variables communs.','Variables à conserver','Aperçu créé : %s lignes, %s variables.','Données fusionnées chargées : %s lignes, %s variables.','Espace blanc','Tabulation','Virgule','Message','Aucun fichier sélectionné.','Fichier','Lignes','Colonnes','Sélectionner des fichiers'],
'de': ['Daten zusammenführen','Variablen nach ID oder Fälle aus mehreren Dateien hinzufügen.','Datendateien zusammenführen','Zusammenzuführende Dateien','Erste CSV-Zeile enthält Variablennamen','Erste DAT-Zeile enthält Variablennamen','DAT-Trennzeichen','Variablen hinzufügen','ID-Variable','Beizubehaltende Zeilen','Erste Datei plus passende Variablen','Nur übereinstimmende IDs','Alle IDs','Fälle hinzufügen','Name der Indikatorvariable','Indikatorwerte','Wählen Sie Dateien mit gemeinsamen Variablennamen.','Beizubehaltende Variablen','Vorschau erstellt: %s Zeilen, %s Variablen.','Zusammengeführte Daten geladen: %s Zeilen, %s Variablen.','Leerraum','Tabulator','Komma','Hinweis','Keine Dateien ausgewählt.','Datei','Zeilen','Spalten','Dateien auswählen'],
'vi': ['Ghép dữ liệu','Thêm biến theo ID hoặc thêm trường hợp từ nhiều tệp.','Ghép các tệp dữ liệu','Tệp cần ghép','Dòng đầu của CSV chứa tên biến','Dòng đầu của DAT chứa tên biến','Dấu phân cách DAT','Thêm biến','Biến ID','Dòng cần giữ','Tệp đầu tiên cùng các biến khớp','Chỉ ID khớp','Tất cả ID','Thêm trường hợp','Tên biến chỉ báo','Giá trị chỉ báo','Chọn các tệp có tên biến chung.','Biến cần giữ','Đã tạo bản xem trước: %s dòng, %s biến.','Đã tải dữ liệu ghép: %s dòng, %s biến.','Khoảng trắng','Tab','Dấu phẩy','Thông báo','Chưa chọn tệp.','Tệp','Dòng','Cột','Chọn tệp']}
for lang, values in rows.items():
    assert len(keys) == len(values), lang
    path = Path('i18n') / (lang + '.json')
    obj = json.loads(path.read_text(encoding='utf-8'))
    obj['translations'].update({'merge.ui.' + k: v for k, v in zip(keys, values)})
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
