import json
from pathlib import Path
keys=['confounding','dependence','unit_effects','singular']
rows={
'en':['Add measured time-varying confounders and time fixed effects when plausible; consider lagged predictors, IV, or dynamic panel methods for reverse causation.','Use subject-clustered or Driscoll-Kraay standard errors; consider adding time fixed effects or a dynamic structure.','If unit effects may correlate with predictors, prefer fixed effects; consider IV or dynamic panel methods when reverse causation is plausible.','Simplify the random-effects structure, review sparse clusters, or refit with an alternative optimizer before final interpretation.'],
'ko':['타당한 경우 측정된 시간가변 교란변수와 시간 고정효과를 추가하고, 역인과 가능성에는 시차 예측변수·도구변수(IV)·동적 패널 방법을 고려하십시오.','대상자 군집 또는 Driscoll-Kraay 표준오차를 사용하고 시간 고정효과나 동적 구조 추가를 고려하십시오.','개체 효과가 예측변수와 상관될 수 있으면 고정효과를 우선하고, 역인과 가능성이 있으면 도구변수(IV)나 동적 패널 방법을 고려하십시오.','최종 해석 전에 확률효과 구조를 단순화하거나 희소 군집을 검토하거나 다른 최적화 방법으로 다시 적합하십시오.'],
'ja':['妥当な場合は測定済みの時変交絡変数と時間固定効果を追加し、逆因果にはラグ付き予測変数、操作変数（IV）、動的パネル法を検討してください。','対象者でクラスター化した標準誤差またはDriscoll-Kraay標準誤差を使用し、時間固定効果や動的構造の追加を検討してください。','個体効果が予測変数と相関し得る場合は固定効果を優先し、逆因果が想定される場合は操作変数（IV）や動的パネル法を検討してください。','最終的な解釈の前に、ランダム効果構造を簡素化し、疎なクラスターを確認するか、別の最適化手法で再適合してください。'],
'zh':['在合理时加入已测量的时变混杂变量和时间固定效应；针对反向因果，考虑滞后预测变量、工具变量（IV）或动态面板方法。','使用按受试者聚类的标准误或 Driscoll-Kraay 标准误；考虑加入时间固定效应或动态结构。','若个体效应可能与预测变量相关，应优先采用固定效应；若存在反向因果的可能，考虑工具变量（IV）或动态面板方法。','在最终解释前，简化随机效应结构、检查稀疏聚类，或使用其他优化器重新拟合。'],
'es':['Añada factores de confusión medidos que varíen en el tiempo y efectos fijos temporales cuando sea plausible; considere predictores rezagados, variables instrumentales (IV) o métodos de panel dinámico para la causalidad inversa.','Use errores estándar agrupados por sujeto o de Driscoll-Kraay; considere añadir efectos fijos temporales o una estructura dinámica.','Si los efectos individuales pueden correlacionarse con los predictores, prefiera efectos fijos; considere IV o métodos de panel dinámico cuando sea plausible la causalidad inversa.','Simplifique la estructura de efectos aleatorios, revise los conglomerados escasos o reajuste con otro optimizador antes de la interpretación final.'],
'fr':['Ajoutez des facteurs de confusion mesurés variant dans le temps et des effets fixes temporels lorsque cela est plausible ; envisagez des prédicteurs retardés, des variables instrumentales (IV) ou des méthodes de panel dynamique pour la causalité inverse.','Utilisez des erreurs standard regroupées par sujet ou de Driscoll-Kraay ; envisagez des effets fixes temporels ou une structure dynamique.','Si les effets individuels peuvent être corrélés aux prédicteurs, privilégiez les effets fixes ; envisagez des IV ou un panel dynamique si une causalité inverse est plausible.','Simplifiez la structure des effets aléatoires, examinez les grappes peu fournies ou réajustez avec un autre optimiseur avant l’interprétation finale.'],
'de':['Ergänzen Sie gemessene zeitabhängige Störvariablen und Zeitfixeffekte, sofern plausibel; erwägen Sie bei umgekehrter Kausalität verzögerte Prädiktoren, Instrumentvariablen (IV) oder dynamische Panelverfahren.','Verwenden Sie nach Personen geclusterte oder Driscoll-Kraay-Standardfehler; erwägen Sie zusätzliche Zeitfixeffekte oder eine dynamische Struktur.','Wenn individuelle Effekte mit Prädiktoren korrelieren könnten, bevorzugen Sie fixe Effekte; erwägen Sie IV oder dynamische Panelverfahren, wenn umgekehrte Kausalität plausibel ist.','Vereinfachen Sie vor der abschließenden Interpretation die Zufallseffektstruktur, prüfen Sie dünn besetzte Cluster oder passen Sie das Modell mit einem anderen Optimierer erneut an.'],
'vi':['Thêm biến gây nhiễu thay đổi theo thời gian đã đo và hiệu ứng cố định theo thời gian khi hợp lý; cân nhắc biến dự báo trễ, biến công cụ (IV) hoặc phương pháp bảng động cho quan hệ nhân quả ngược.','Dùng sai số chuẩn phân cụm theo đối tượng hoặc Driscoll-Kraay; cân nhắc thêm hiệu ứng cố định theo thời gian hoặc cấu trúc động.','Nếu hiệu ứng cá thể có thể tương quan với biến dự báo, ưu tiên hiệu ứng cố định; cân nhắc IV hoặc phương pháp bảng động khi quan hệ nhân quả ngược có thể xảy ra.','Đơn giản hóa cấu trúc hiệu ứng ngẫu nhiên, xem xét các cụm thưa hoặc khớp lại bằng bộ tối ưu khác trước khi diễn giải cuối cùng.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.panel_recommendation.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
