import json,re
from pathlib import Path
rows='''Top-level HTMT (original items)|上位HTMT（原項目）|顶层HTMT（原题项）|HTMT superior (ítems originales)|HTMT supérieur (items originaux)|HTMT oberster Ebene (Originalitems)|HTMT cấp trên (mục gốc)
Top-level HTMT (subscale scores)|上位HTMT（下位尺度得点）|顶层HTMT（分量表分数）|HTMT superior (puntuaciones de subescalas)|HTMT supérieur (scores de sous-échelles)|HTMT oberster Ebene (Subskalenscores)|HTMT cấp trên (điểm thang con)
%s: not assessed. %s|%s：未評価。%s|%s：未评估。%s|%s: no evaluado. %s|%s : non évalué. %s|%s: nicht bewertet. %s|%s: chưa đánh giá. %s
Multigroup higher-order HTMT is not supported.|多集団の高次HTMTには対応していません。|不支持多组高阶HTMT。|No se admite HTMT de orden superior multigrupo.|HTMT d’ordre supérieur multigroupe n’est pas pris en charge.|Mehrgruppen-HTMT höherer Ordnung wird nicht unterstützt.|Không hỗ trợ HTMT bậc cao đa nhóm.
At least two top-level constructs are required.|少なくとも2つの上位構成概念が必要です。|至少需要两个顶层构念。|Se requieren al menos dos constructos superiores.|Au moins deux construits de niveau supérieur sont nécessaires.|Mindestens zwei Konstrukte oberster Ebene sind erforderlich.|Cần ít nhất hai cấu trúc cấp trên.
The analyzed raw data are unavailable.|分析対象の生データを利用できません。|分析原始数据不可用。|Los datos brutos analizados no están disponibles.|Les données brutes analysées sont indisponibles.|Die analysierten Rohdaten sind nicht verfügbar.|Không có dữ liệu thô đã phân tích.
Analyzed case indices are unavailable.|分析対象ケースのインデックスを利用できません。|分析个案索引不可用。|Los índices de los casos analizados no están disponibles.|Les indices des cas analysés sont indisponibles.|Die Indizes der analysierten Fälle sind nicht verfügbar.|Không có chỉ số trường hợp đã phân tích.
Mixed observed and latent indicators of one construct are not supported.|同じ構成概念で観測指標と潜在指標を混在させることには対応していません。|不支持同一构念混用观测和潜在指标。|No se admite mezclar indicadores observados y latentes en un constructo.|Le mélange d’indicateurs observés et latents dans un construit n’est pas pris en charge.|Gemischte beobachtete und latente Indikatoren eines Konstrukts werden nicht unterstützt.|Không hỗ trợ trộn chỉ báo quan sát và tiềm ẩn trong một cấu trúc.
Only second-order models with observed first-order indicators are supported.|観測された一次指標を持つ二次モデルのみに対応しています。|仅支持具有观测一阶指标的二阶模型。|Solo se admiten modelos de segundo orden con indicadores observados de primer orden.|Seuls les modèles de second ordre avec indicateurs observés de premier ordre sont pris en charge.|Nur Modelle zweiter Ordnung mit beobachteten Indikatoren erster Ordnung werden unterstützt.|Chỉ hỗ trợ mô hình bậc hai có chỉ báo quan sát bậc một.
Some indicator columns are unavailable.|一部の指標列を利用できません。|部分指标列不可用。|Algunas columnas de indicadores no están disponibles.|Certaines colonnes d’indicateurs sont indisponibles.|Einige Indikatorspalten sind nicht verfügbar.|Một số cột chỉ báo không có.
Subscale scoring requires numeric item values.|下位尺度の得点算出には数値の項目値が必要です。|分量表计分需要数值型题项值。|La puntuación de subescalas requiere valores numéricos de ítems.|Le calcul des scores de sous-échelles nécessite des valeurs numériques d’items.|Subskalenscores erfordern numerische Itemwerte.|Tính điểm thang con cần giá trị mục dạng số.
Subscale scoring requires numeric item values; recode category labels first.|下位尺度の得点算出には数値の項目値が必要です。先にカテゴリラベルを再符号化してください。|分量表计分需要数值型题项值；请先重新编码类别标签。|La puntuación de subescalas requiere valores numéricos; recodifique primero las etiquetas de categorías.|Le calcul des sous-échelles nécessite des valeurs numériques ; recodez d’abord les libellés de catégories.|Subskalenscores erfordern numerische Itemwerte; kodieren Sie zuerst die Kategoriebezeichnungen um.|Tính điểm thang con cần giá trị số; hãy mã hóa lại nhãn hạng mục trước.
Fewer than three complete cases are available for top-level indicators.|上位指標で利用可能な完全ケースが3件未満です。|顶层指标的完整个案少于三个。|Hay menos de tres casos completos para los indicadores superiores.|Moins de trois cas complets sont disponibles pour les indicateurs supérieurs.|Für Indikatoren oberster Ebene liegen weniger als drei vollständige Fälle vor.|Có dưới ba trường hợp đầy đủ cho chỉ báo cấp trên.
Select HTMT bootstrap CI in the analysis options for intervals.|区間推定には分析オプションでHTMTブートストラップCIを選択してください。|如需区间，请在分析选项中选择HTMT自助法CI。|Seleccione CI bootstrap HTMT en las opciones para obtener intervalos.|Sélectionnez les IC bootstrap HTMT dans les options pour obtenir des intervalles.|Wählen Sie HTMT-Bootstrap-KI in den Analyseoptionen für Intervalle.|Chọn CI bootstrap HTMT trong tùy chọn phân tích để có khoảng.
Top-level HTMT bootstrap intervals are being computed in the background.|上位HTMTブートストラップ区間をバックグラウンドで計算しています。|正在后台计算顶层HTMT自助法区间。|Los intervalos bootstrap HTMT superiores se calculan en segundo plano.|Les intervalles bootstrap HTMT supérieurs sont calculés en arrière-plan.|HTMT-Bootstrap-Intervalle oberster Ebene werden im Hintergrund berechnet.|Khoảng bootstrap HTMT cấp trên đang được tính nền.
Top-level HTMT bootstrap was canceled; point estimates remain available.|上位HTMTブートストラップは中止されました。点推定は引き続き利用できます。|顶层HTMT自助法已取消；点估计仍可用。|Se canceló el bootstrap HTMT superior; las estimaciones puntuales siguen disponibles.|Le bootstrap HTMT supérieur a été annulé ; les estimations ponctuelles restent disponibles.|Der HTMT-Bootstrap oberster Ebene wurde abgebrochen; Punktschätzungen bleiben verfügbar.|Bootstrap HTMT cấp trên đã hủy; ước lượng điểm vẫn còn.
Top-level HTMT bootstrap intervals could not be estimated.|上位HTMTブートストラップ区間を推定できませんでした。|无法估计顶层HTMT自助法区间。|No se pudieron estimar intervalos bootstrap HTMT superiores.|Les intervalles bootstrap HTMT supérieurs n’ont pas pu être estimés.|HTMT-Bootstrap-Intervalle oberster Ebene konnten nicht geschätzt werden.|Không thể ước lượng khoảng bootstrap HTMT cấp trên.'''
data_rows=[r.split('|') for r in rows.splitlines()]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
