import json,re
from pathlib import Path
rows='''The selected structural paths do not match the current model or fitted multi-group paths exactly. Check the model and select the comparison paths again.|選択した構造経路が現在のモデルまたは推定済み多群モデルの経路と完全には一致しません。モデルを確認し、比較する経路を再選択してください。|选定结构路径与当前模型或已拟合多组模型的路径不完全匹配。请检查模型并重新选择比较路径。|Las trayectorias estructurales seleccionadas no coinciden exactamente con el modelo actual o las trayectorias multigrupo estimadas. Revise el modelo y vuelva a seleccionar las trayectorias de comparación.|Les chemins structurels sélectionnés ne correspondent pas exactement au modèle actuel ou aux chemins multigroupes estimés. Vérifiez le modèle et sélectionnez à nouveau les chemins à comparer.|Die ausgewählten Strukturpfade stimmen nicht genau mit dem aktuellen Modell oder den geschätzten Mehrgruppenpfaden überein. Prüfen Sie das Modell und wählen Sie die Vergleichspfade erneut.|Các đường dẫn cấu trúc đã chọn không khớp chính xác với mô hình hiện tại hoặc các đường dẫn đa nhóm đã ước lượng. Hãy kiểm tra mô hình và chọn lại đường dẫn để so sánh.
PLS-MGA selected-path input has ambiguous columns: %s.|PLS-MGAの選択経路入力に曖昧な列があります：%s。|PLS-MGA选定路径输入包含有歧义的列：%s。|La entrada de trayectorias seleccionadas de PLS-MGA contiene columnas ambiguas: %s.|L’entrée des chemins sélectionnés pour PLS-MGA contient des colonnes ambiguës : %s.|Die Eingabe ausgewählter PLS-MGA-Pfade enthält mehrdeutige Spalten: %s.|Đầu vào đường dẫn đã chọn của PLS-MGA có các cột không rõ ràng: %s.
Selected canvas paths could not be estimated as structural regressions in the multi-group SEM: %s.|多群SEMで選択したキャンバス経路を構造回帰として推定できませんでした：%s。|在多组SEM中，无法将选定画布路径估计为结构回归：%s。|No se pudieron estimar las trayectorias seleccionadas del lienzo como regresiones estructurales en el SEM multigrupo: %s.|Les chemins sélectionnés du canevas n’ont pas pu être estimés comme régressions structurelles dans le SEM multigroupe : %s.|Ausgewählte Pfade der Zeichenfläche konnten im Mehrgruppen-SEM nicht als strukturelle Regressionen geschätzt werden: %s.|Không thể ước lượng các đường dẫn đã chọn trên vùng vẽ dưới dạng hồi quy cấu trúc trong SEM đa nhóm: %s.
Selected path '%s' must have exactly one freely estimated regression coefficient in each group.|選択経路「%s」には、各群で自由推定される回帰係数がちょうど1つ必要です。|选定路径“%s”在每个组中必须恰好有一个自由估计的回归系数。|La trayectoria seleccionada '%s' debe tener exactamente un coeficiente de regresión estimado libremente en cada grupo.|Le chemin sélectionné « %s » doit avoir exactement un coefficient de régression estimé librement dans chaque groupe.|Der ausgewählte Pfad „%s“ muss in jeder Gruppe genau einen frei geschätzten Regressionskoeffizienten haben.|Đường dẫn đã chọn '%s' phải có đúng một hệ số hồi quy được ước lượng tự do trong mỗi nhóm.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  fields=line.split('|');assert len(fields)==7
  assert fields[0].count('%s')==fields[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',fields[0].lower()).strip('_')]=fields[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
