import json
from pathlib import Path
keys=['times_invalid','tv_times_invalid','adjusted_times_invalid','tv_time_range','adjusted_time_range']
rows={
'en':['Time points must contain only nonnegative finite numbers separated by commas, semicolons, or spaces.','Time-varying HR reporting times must contain only nonnegative finite numbers separated by commas, semicolons, or spaces.','Adjusted-survival time points must contain only nonnegative finite numbers separated by commas, semicolons, or spaces.','Time-varying HR reporting times must not exceed the maximum observed follow-up time (%s).','Adjusted-survival time points must not exceed the maximum observed follow-up time (%s).'],
'ko':['시점은 쉼표, 세미콜론 또는 공백으로 구분한 0 이상의 유한한 숫자만 입력해야 합니다.','시간가변 HR 보고 시점은 쉼표, 세미콜론 또는 공백으로 구분한 0 이상의 유한한 숫자만 입력해야 합니다.','조정 생존곡선 시점은 쉼표, 세미콜론 또는 공백으로 구분한 0 이상의 유한한 숫자만 입력해야 합니다.','시간가변 HR 보고 시점은 관측된 최대 추적 시간(%s)을 초과할 수 없습니다.','조정 생존곡선 시점은 관측된 최대 추적 시간(%s)을 초과할 수 없습니다.'],
'ja':['時点には、コンマ、セミコロン、または空白で区切った0以上の有限数のみを入力してください。','時間変動HRの報告時点には、コンマ、セミコロン、または空白で区切った0以上の有限数のみを入力してください。','調整生存曲線の時点には、コンマ、セミコロン、または空白で区切った0以上の有限数のみを入力してください。','時間変動HRの報告時点は、観測された最大追跡時間（%s）を超えることはできません。','調整生存曲線の時点は、観測された最大追跡時間（%s）を超えることはできません。'],
'zh':['时间点只能包含以逗号、分号或空格分隔的非负有限数值。','时变 HR 报告时间点只能包含以逗号、分号或空格分隔的非负有限数值。','调整生存曲线时间点只能包含以逗号、分号或空格分隔的非负有限数值。','时变 HR 报告时间点不得超过已观测到的最大随访时间（%s）。','调整生存曲线时间点不得超过已观测到的最大随访时间（%s）。'],
'es':['Los puntos temporales deben contener solo números finitos no negativos separados por comas, punto y coma o espacios.','Los tiempos de informe de HR variable en el tiempo deben contener solo números finitos no negativos separados por comas, punto y coma o espacios.','Los puntos temporales de supervivencia ajustada deben contener solo números finitos no negativos separados por comas, punto y coma o espacios.','Los tiempos de informe de HR variable en el tiempo no deben superar el tiempo máximo de seguimiento observado (%s).','Los puntos temporales de supervivencia ajustada no deben superar el tiempo máximo de seguimiento observado (%s).'],
'fr':['Les points temporels doivent contenir uniquement des nombres finis non négatifs séparés par des virgules, des points-virgules ou des espaces.','Les temps de présentation du HR variant dans le temps doivent contenir uniquement des nombres finis non négatifs séparés par des virgules, des points-virgules ou des espaces.','Les points temporels de survie ajustée doivent contenir uniquement des nombres finis non négatifs séparés par des virgules, des points-virgules ou des espaces.','Les temps de présentation du HR variant dans le temps ne doivent pas dépasser le temps maximal de suivi observé (%s).','Les points temporels de survie ajustée ne doivent pas dépasser le temps maximal de suivi observé (%s).'],
'de':['Zeitpunkte dürfen nur nichtnegative endliche Zahlen enthalten, getrennt durch Kommas, Semikolons oder Leerzeichen.','Berichtszeitpunkte für zeitvariable HR dürfen nur nichtnegative endliche Zahlen enthalten, getrennt durch Kommas, Semikolons oder Leerzeichen.','Zeitpunkte für adjustiertes Überleben dürfen nur nichtnegative endliche Zahlen enthalten, getrennt durch Kommas, Semikolons oder Leerzeichen.','Berichtszeitpunkte für zeitvariable HR dürfen die maximale beobachtete Nachbeobachtungszeit (%s) nicht überschreiten.','Zeitpunkte für adjustiertes Überleben dürfen die maximale beobachtete Nachbeobachtungszeit (%s) nicht überschreiten.'],
'vi':['Các thời điểm chỉ được chứa số hữu hạn không âm, phân cách bằng dấu phẩy, dấu chấm phẩy hoặc khoảng trắng.','Các thời điểm báo cáo HR thay đổi theo thời gian chỉ được chứa số hữu hạn không âm, phân cách bằng dấu phẩy, dấu chấm phẩy hoặc khoảng trắng.','Các thời điểm sống còn đã điều chỉnh chỉ được chứa số hữu hạn không âm, phân cách bằng dấu phẩy, dấu chấm phẩy hoặc khoảng trắng.','Các thời điểm báo cáo HR thay đổi theo thời gian không được vượt quá thời gian theo dõi tối đa được quan sát (%s).','Các thời điểm sống còn đã điều chỉnh không được vượt quá thời gian theo dõi tối đa được quan sát (%s).'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
