import json,re
from pathlib import Path
rows='''HTMT bootstrap intervals are being|HTMTブートストラップ区間をバックグラウンドで計算しています。完了すると結果表が自動更新されます。|正在后台计算HTMT自助法区间。完成后结果表将自动更新。|Los intervalos bootstrap HTMT se calculan en segundo plano. La tabla se actualizará automáticamente al finalizar.|Les intervalles bootstrap HTMT sont calculés en arrière-plan. Le tableau sera actualisé automatiquement à la fin.|HTMT-Bootstrap-Intervalle werden im Hintergrund berechnet. Die Ergebnistabelle wird nach Abschluss automatisch aktualisiert.|Khoảng bootstrap HTMT đang được tính nền. Bảng kết quả sẽ tự cập nhật khi hoàn tất.
The HTMT bootstrap was stopped|HTMTブートストラップはユーザーの要求で停止しました。点推定値と基本モデルの結果は引き続き利用できます。|HTMT自助法已按用户要求停止。点估计和基础模型结果仍然可用。|El usuario detuvo el bootstrap HTMT. Las estimaciones puntuales y los resultados del modelo base siguen disponibles.|Le bootstrap HTMT a été arrêté par l’utilisateur. Les estimations ponctuelles et les résultats du modèle de base restent disponibles.|Der HTMT-Bootstrap wurde vom Benutzer gestoppt. Punktschätzungen und Ergebnisse des Basismodells bleiben verfügbar.|Bootstrap HTMT đã dừng theo yêu cầu người dùng. Ước lượng điểm và kết quả mô hình cơ sở vẫn còn.
HTMT bootstrap confidence intervals could|選択された指標からHTMTブートストラップ信頼区間を推定できませんでした。|无法根据所选指标估计HTMT自助法置信区间。|No se pudieron estimar los intervalos de confianza bootstrap HTMT a partir de los indicadores seleccionados.|Les intervalles de confiance bootstrap HTMT n’ont pas pu être estimés à partir des indicateurs sélectionnés.|HTMT-Bootstrap-Konfidenzintervalle konnten aus den ausgewählten Indikatoren nicht geschätzt werden.|Không thể ước lượng khoảng tin cậy bootstrap HTMT từ các chỉ báo đã chọn.
Some bootstrap resamples could|一部のブートストラップ標本では許容可能な相関行列を得られませんでした。順序カテゴリの欠落や疎なカテゴリがよくある原因です。有効反復数が減少した区間は慎重に解釈してください。|部分自助重抽样未能产生可接受的相关矩阵，常见原因是有序类别缺失或稀疏。有效重复次数减少时，请谨慎解释区间。|Algunas remuestras bootstrap no produjeron una matriz de correlación admisible, normalmente por categorías ordinales ausentes o escasas. Interprete con cautela los intervalos con menos réplicas válidas.|Certains rééchantillonnages bootstrap n’ont pas produit de matrice de corrélation admissible, souvent à cause d’une catégorie ordinale absente ou rare. Interprétez prudemment les intervalles avec moins de répétitions valides.|Einige Bootstrap-Stichproben ergaben keine zulässige Korrelationsmatrix, häufig wegen fehlender oder schwach besetzter ordinaler Kategorien. Intervalle mit weniger gültigen Wiederholungen sind vorsichtig zu interpretieren.|Một số mẫu bootstrap không tạo được ma trận tương quan chấp nhận được, thường do thiếu hoặc thưa hạng mục thứ bậc. Hãy thận trọng khi diễn giải khoảng có ít lần lặp hợp lệ hơn.
BCa unavailable means|BCa unavailableは、そのペアのバイアス補正またはジャックナイフ加速度を計算できなかったことを意味します。有効反復数を増やすか、報告にパーセンタイル区間を使用することを検討してください。|BCa unavailable表示无法计算该指标对的偏差校正或刀切法加速度。请增加有效重复次数，或考虑使用百分位数区间进行报告。|BCa unavailable indica que no se pudo calcular la corrección de sesgo o la aceleración jackknife para ese par; aumente las réplicas válidas o use intervalos percentiles al informar.|BCa unavailable signifie que la correction du biais ou l’accélération jackknife n’a pas pu être calculée pour cette paire ; augmentez les répétitions valides ou utilisez un intervalle percentile pour le rapport.|BCa unavailable bedeutet, dass Bias-Korrektur oder Jackknife-Beschleunigung für dieses Paar nicht berechnet werden konnte. Erhöhen Sie die Zahl gültiger Wiederholungen oder berichten Sie Perzentilintervalle.|BCa unavailable nghĩa là không tính được hiệu chỉnh độ chệch hoặc gia tốc jackknife cho cặp đó; hãy tăng số lần lặp hợp lệ hoặc dùng khoảng percentile để báo cáo.
HTMT bootstrap status Caution means|HTMTブートストラップのCautionは、要求した再標本の50%以上80%未満だけが有効だったことを示します。区間は不安定なものとして扱い、有効反復数を併記してください。|HTMT自助法状态Caution表示请求重抽样中仅50%至不足80%有效。应将区间视为不稳定，并报告有效重复次数。|El estado Caution del bootstrap HTMT indica que entre el 50% y menos del 80% de las remuestras solicitadas fueron válidas. Considere inestable el intervalo e informe el número de réplicas válidas.|Le statut Caution du bootstrap HTMT signifie que 50 % à moins de 80 % des rééchantillonnages demandés étaient valides. Considérez l’intervalle comme instable et indiquez le nombre de répétitions valides.|Der HTMT-Bootstrap-Status Caution bedeutet, dass 50% bis unter 80% der angeforderten Stichproben gültig waren. Behandeln Sie das Intervall als instabil und berichten Sie die Zahl gültiger Wiederholungen.|Trạng thái Caution của bootstrap HTMT nghĩa là từ 50% đến dưới 80% số mẫu yêu cầu hợp lệ. Xem khoảng là không ổn định và báo cáo số lần lặp hợp lệ.
HTMT bootstrap status Unreliable means|HTMTブートストラップのUnreliableは、有効な再標本が要求数の50%未満だったことを示します。信頼限界と閾値判定は評価せず、弁別的妥当性の根拠として使用しないでください。|HTMT自助法状态Unreliable表示有效重抽样不足请求数的50%。不评估置信限和阈值判断，也不应将其作为区分效度证据。|El estado Unreliable del bootstrap HTMT indica que menos del 50% de las remuestras solicitadas fueron válidas. No se evalúan los límites de confianza ni las decisiones de umbral, y no deben usarse como evidencia de validez discriminante.|Le statut Unreliable du bootstrap HTMT signifie que moins de 50 % des rééchantillonnages demandés étaient valides. Les limites de confiance et les décisions de seuil ne sont pas évaluées et ne doivent pas servir de preuve de validité discriminante.|Der HTMT-Bootstrap-Status Unreliable bedeutet, dass weniger als 50% der angeforderten Stichproben gültig waren. Konfidenzgrenzen und Schwellenentscheidungen werden nicht bewertet und dürfen nicht als Evidenz diskriminanter Validität verwendet werden.|Trạng thái Unreliable của bootstrap HTMT nghĩa là dưới 50% số mẫu yêu cầu hợp lệ. Không đánh giá giới hạn tin cậy và quyết định theo ngưỡng, và không dùng chúng làm bằng chứng giá trị phân biệt.'''
p=Path('R/setup_custom_model_canvas_structural_render_htmt.R');source=p.read_text(encoding='utf-8')
data_rows=[]
for row in rows.splitlines():
 f=row.split('|');assert len(f)==7
 matches=re.findall(r'if \(ko\) "([^"\n]+)" else "('+re.escape(f[0])+r'[^"\n]*)"',source)
 if matches:
  assert len(matches)==1
  ko,en=matches[0];source=source.replace('if (ko) "'+ko+'" else "'+en+'"','statedu_localized_text(statedu_current_language(app_language_fn), "'+en+'", "'+ko+'")')
 else:
  matches=re.findall(r'"('+re.escape(f[0])+r'[^"\n]*)"',source);assert len(matches)==1
  en=matches[0]
 f[0]=en;data_rows.append(f)
p.write_text(source,encoding='utf-8')
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
