"""ANOVA-family planning descriptions."""
import json
from pathlib import Path
keys='note_plan_kw note_plan_friedman note_plan_repeated note_plan_mixed note_plan_two_way note_plan_one_way'.split()
rows={
'en':["Approximate Kruskal-Wallis sample size using Cohen's f and noncentral chi-square distribution.","Approximate Friedman test using Kendall's W and noncentral chi-square distribution.","Approximate one-group repeated-measures ANOVA using Cohen's f, average repeated-measures correlation, epsilon, and noncentral F distribution.","Approximate mixed-design repeated-measures ANOVA using Cohen's f, average repeated-measures correlation, epsilon, and noncentral F distribution.","Balanced fixed-effects two-way ANOVA using Cohen's f and noncentral F distribution.","One-way fixed-effects ANOVA using Cohen's f and noncentral F distribution."],
'ko':['Cohen의 f와 비중심 카이제곱 분포를 사용하여 Kruskal–Wallis 표본수를 근사합니다.','Kendall의 W와 비중심 카이제곱 분포를 사용하는 Friedman 검정 근사입니다.','Cohen의 f, 평균 반복측정 상관, epsilon, 비중심 F 분포를 사용하는 단일집단 반복측정 ANOVA 근사입니다.','Cohen의 f, 평균 반복측정 상관, epsilon, 비중심 F 분포를 사용하는 혼합설계 반복측정 ANOVA 근사입니다.','Cohen의 f와 비중심 F 분포를 사용하는 균형 고정효과 이원 ANOVA입니다.','Cohen의 f와 비중심 F 분포를 사용하는 고정효과 일원 ANOVA입니다.'],
'ja':['Cohenのfと非心カイ二乗分布を用いてKruskal–Wallisの標本サイズを近似します。','KendallのWと非心カイ二乗分布を用いたFriedman検定の近似です。','Cohenのf、平均反復測定相関、epsilon、非心F分布を用いた単一群反復測定ANOVAの近似です。','Cohenのf、平均反復測定相関、epsilon、非心F分布を用いた混合計画反復測定ANOVAの近似です。','Cohenのfと非心F分布を用いた均衡固定効果二元配置ANOVAです。','Cohenのfと非心F分布を用いた固定効果一元配置ANOVAです。'],
'zh':['使用Cohen f和非中心卡方分布近似计算Kruskal–Wallis样本量。','使用Kendall W和非中心卡方分布近似Friedman检验。','使用Cohen f、平均重复测量相关、epsilon及非中心F分布近似单组重复测量ANOVA。','使用Cohen f、平均重复测量相关、epsilon及非中心F分布近似混合设计重复测量ANOVA。','使用Cohen f和非中心F分布的平衡固定效应双因素ANOVA。','使用Cohen f和非中心F分布的固定效应单因素ANOVA。'],
'es':['Tamaño muestral aproximado de Kruskal–Wallis con f de Cohen y la distribución chi-cuadrado no central.','Prueba de Friedman aproximada con W de Kendall y la distribución chi-cuadrado no central.','ANOVA de medidas repetidas de un grupo aproximado con f de Cohen, correlación media entre medidas, epsilon y la distribución F no central.','ANOVA de medidas repetidas de diseño mixto aproximado con f de Cohen, correlación media entre medidas, epsilon y la distribución F no central.','ANOVA equilibrado de dos factores de efectos fijos con f de Cohen y la distribución F no central.','ANOVA de un factor de efectos fijos con f de Cohen y la distribución F no central.'],
'fr':['Taille d’échantillon de Kruskal–Wallis approchée avec le f de Cohen et la loi du chi carré non centrale.','Test de Friedman approché avec le W de Kendall et la loi du chi carré non centrale.','ANOVA à mesures répétées d’un seul groupe approchée avec le f de Cohen, la corrélation moyenne des mesures, epsilon et la loi F non centrale.','ANOVA à mesures répétées à plan mixte approchée avec le f de Cohen, la corrélation moyenne des mesures, epsilon et la loi F non centrale.','ANOVA équilibrée à deux facteurs à effets fixes avec le f de Cohen et la loi F non centrale.','ANOVA à un facteur à effets fixes avec le f de Cohen et la loi F non centrale.'],
'de':['Approximierter Kruskal–Wallis-Stichprobenumfang mit Cohens f und der nichtzentralen Chi-Quadrat-Verteilung.','Approximierter Friedman-Test mit Kendalls W und der nichtzentralen Chi-Quadrat-Verteilung.','Approximierte Ein-Gruppen-Messwiederholungs-ANOVA mit Cohens f, mittlerer Messwiederholungskorrelation, epsilon und nichtzentraler F-Verteilung.','Approximierte Messwiederholungs-ANOVA mit gemischtem Design mit Cohens f, mittlerer Messwiederholungskorrelation, epsilon und nichtzentraler F-Verteilung.','Balancierte zweifaktorielle ANOVA mit festen Effekten, Cohens f und nichtzentraler F-Verteilung.','Einfaktorielle ANOVA mit festen Effekten, Cohens f und nichtzentraler F-Verteilung.'],
'vi':['Cỡ mẫu Kruskal–Wallis xấp xỉ sử dụng f của Cohen và phân phối chi bình phương phi trung tâm.','Kiểm định Friedman xấp xỉ sử dụng W của Kendall và phân phối chi bình phương phi trung tâm.','ANOVA đo lặp một nhóm xấp xỉ sử dụng f của Cohen, tương quan đo lặp trung bình, epsilon và phân phối F phi trung tâm.','ANOVA đo lặp thiết kế hỗn hợp xấp xỉ sử dụng f của Cohen, tương quan đo lặp trung bình, epsilon và phân phối F phi trung tâm.','ANOVA hai yếu tố hiệu ứng cố định cân bằng sử dụng f của Cohen và phân phối F phi trung tâm.','ANOVA một yếu tố hiệu ứng cố định sử dụng f của Cohen và phân phối F phi trung tâm.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
