"""Precision, McNemar and rate-planning method notes."""
import json
from pathlib import Path
keys='note_precision_mean note_precision_proportion note_precision_correlation note_mcnemar_normal note_rate_single note_rate_nb note_rate_poisson'.split()
rows={
'en':['Normal-approximation sample size for estimating a mean with a specified confidence interval half-width.','Wald normal-approximation sample size for estimating a proportion with a specified confidence interval half-width.','Fisher z-transformation sample size for estimating Pearson correlation with an approximate confidence interval half-width.',"Normal approximation for McNemar's paired binary test using discordant pair proportions p01 and p10.",'Normal approximation for estimating one Poisson incidence rate with a specified confidence interval half-width.','Zhu-Lakkis style Wald approximation for comparing two negative binomial rates with overdispersion.','Wald normal approximation for comparing two independent Poisson incidence rates with person-time allocation ratio.'],
'ko':['지정한 신뢰구간 반폭으로 평균을 추정하기 위한 정규근사 표본수입니다.','지정한 신뢰구간 반폭으로 비율을 추정하기 위한 Wald 정규근사 표본수입니다.','근사 신뢰구간 반폭으로 Pearson 상관을 추정하기 위한 Fisher z 변환 표본수입니다.','불일치 쌍 비율 p01과 p10을 사용하는 McNemar 대응 이분형 검정의 정규근사입니다.','지정한 신뢰구간 반폭으로 단일 포아송 발생률을 추정하기 위한 정규근사입니다.','과산포가 있는 두 음이항 발생률을 비교하기 위한 Zhu–Lakkis 방식 Wald 근사입니다.','인시 배정비를 적용하여 독립적인 두 포아송 발생률을 비교하는 Wald 정규근사입니다.'],
'ja':['指定した信頼区間の半幅で平均を推定するための正規近似標本サイズです。','指定した信頼区間の半幅で比率を推定するためのWald正規近似標本サイズです。','近似信頼区間の半幅でPearson相関を推定するためのFisher z変換による標本サイズです。','不一致ペアの比率p01とp10を用いたMcNemar対応二値検定の正規近似です。','指定した信頼区間の半幅で単一のポアソン発生率を推定するための正規近似です。','過分散のある二つの負の二項発生率を比較するZhu–Lakkis型Wald近似です。','人時間の割付比を用いて独立した二つのポアソン発生率を比較するWald正規近似です。'],
'zh':['在指定置信区间半宽下估计均值的正态近似样本量。','在指定置信区间半宽下估计比例的Wald正态近似样本量。','使用Fisher z变换，在近似置信区间半宽下估计Pearson相关的样本量。','使用不一致配对比例p01和p10的McNemar配对二元检验正态近似。','在指定置信区间半宽下估计单个泊松发生率的正态近似。','比较两个存在过度离散的负二项发生率的Zhu–Lakkis型Wald近似。','使用人时分配比比较两个独立泊松发生率的Wald正态近似。'],
'es':['Tamaño muestral por aproximación normal para estimar una media con semiamplitud de intervalo de confianza especificada.','Tamaño muestral por aproximación normal de Wald para estimar una proporción con semiamplitud de intervalo de confianza especificada.','Tamaño muestral mediante transformación z de Fisher para estimar la correlación de Pearson con semiamplitud aproximada del intervalo de confianza.','Aproximación normal para la prueba binaria pareada de McNemar con proporciones discordantes p01 y p10.','Aproximación normal para estimar una tasa de incidencia de Poisson con semiamplitud de intervalo de confianza especificada.','Aproximación de Wald de tipo Zhu–Lakkis para comparar dos tasas binomiales negativas con sobredispersión.','Aproximación normal de Wald para comparar dos tasas de incidencia de Poisson independientes con razón de asignación de tiempo-persona.'],
'fr':['Taille d’échantillon par approximation normale pour estimer une moyenne avec une demi-largeur d’intervalle de confiance spécifiée.','Taille d’échantillon par approximation normale de Wald pour estimer une proportion avec une demi-largeur d’intervalle de confiance spécifiée.','Taille d’échantillon par transformation z de Fisher pour estimer la corrélation de Pearson avec une demi-largeur approximative d’intervalle de confiance.','Approximation normale du test binaire apparié de McNemar avec les proportions de paires discordantes p01 et p10.','Approximation normale pour estimer un taux d’incidence de Poisson avec une demi-largeur d’intervalle de confiance spécifiée.','Approximation de Wald de type Zhu–Lakkis pour comparer deux taux binomiaux négatifs avec surdispersion.','Approximation normale de Wald pour comparer deux taux d’incidence de Poisson indépendants avec un rapport d’allocation du temps-personne.'],
'de':['Normalapproximierter Stichprobenumfang zur Schätzung eines Mittelwerts mit vorgegebener Konfidenzintervall-Halbbreite.','Stichprobenumfang nach Wald-Normalapproximation zur Schätzung eines Anteils mit vorgegebener Konfidenzintervall-Halbbreite.','Stichprobenumfang mittels Fisher-z-Transformation zur Schätzung der Pearson-Korrelation mit approximativer Konfidenzintervall-Halbbreite.','Normalapproximation für McNemars gepaarten binären Test mit diskordanten Paaranteilen p01 und p10.','Normalapproximation zur Schätzung einer Poisson-Inzidenzrate mit vorgegebener Konfidenzintervall-Halbbreite.','Wald-Approximation nach Zhu–Lakkis zum Vergleich zweier negativ-binomialer Raten mit Überdispersion.','Wald-Normalapproximation zum Vergleich zweier unabhängiger Poisson-Inzidenzraten mit Personenzeit-Zuteilungsverhältnis.'],
'vi':['Cỡ mẫu xấp xỉ chuẩn để ước lượng trung bình với nửa độ rộng khoảng tin cậy đã chỉ định.','Cỡ mẫu xấp xỉ chuẩn Wald để ước lượng tỷ lệ với nửa độ rộng khoảng tin cậy đã chỉ định.','Cỡ mẫu qua biến đổi z của Fisher để ước lượng tương quan Pearson với nửa độ rộng khoảng tin cậy xấp xỉ.','Xấp xỉ chuẩn cho kiểm định nhị phân ghép cặp McNemar sử dụng tỷ lệ cặp bất tương hợp p01 và p10.','Xấp xỉ chuẩn để ước lượng một suất mắc Poisson với nửa độ rộng khoảng tin cậy đã chỉ định.','Xấp xỉ Wald kiểu Zhu–Lakkis để so sánh hai suất nhị thức âm có quá phân tán.','Xấp xỉ chuẩn Wald để so sánh hai suất mắc Poisson độc lập với tỷ lệ phân bổ thời gian-người.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
