import json
from pathlib import Path
keys=['process','package','adjusted_design','adjusted_family','adjusted_ids','adjusted_pairs']
rows={
'en':['Unstructured GEE could not complete in its isolated R process. No replacement correlation model was fitted. Details: ','The %s package is required for this model.','Adjusted GEE requires a finite numeric outcome and full-rank design.','Unsupported adjusted GEE family.','Adjusted GEE requires nonmissing subject IDs and times.','Adjusted GEE requires more observed subjects per time pair than regression parameters.'],
'ko':['비구조적 GEE가 별도 R 프로세스에서 완료되지 못했습니다. 다른 상관 모형으로 대체 적합하지 않았습니다. 상세: ','이 모형에는 %s 패키지가 필요합니다.','보정 GEE에는 유한한 숫자형 결과와 완전계수 설계행렬이 필요합니다.','지원하지 않는 보정 GEE 분포 계열입니다.','보정 GEE의 대상자 ID와 시점에는 결측이 없어야 합니다.','보정 GEE는 각 시점 쌍에서 관측된 대상자 수가 회귀 모수 수보다 많아야 합니다.'],
'ja':['非構造化GEEは別のRプロセスで完了できませんでした。代わりの相関モデルは適合していません。詳細：','このモデルには%sパッケージが必要です。','補正GEEには有限の数値アウトカムとフルランクの計画行列が必要です。','補正GEEでサポートされていない分布族です。','補正GEEでは対象者IDと時点に欠測がない必要があります。','補正GEEでは各時点ペアの観測対象者数が回帰パラメータ数を上回る必要があります。'],
'zh':['非结构化 GEE 未能在独立 R 进程中完成。未拟合替代相关模型。详细信息：','此模型需要 %s 软件包。','校正 GEE 需要有限的数值型结局和满秩设计矩阵。','校正 GEE 不支持此分布族。','校正 GEE 要求受试者 ID 和时间无缺失。','校正 GEE 要求每个时间对的观测受试者数大于回归参数数目。'],
'es':['GEE no estructurado no pudo completarse en su proceso R aislado. No se ajustó ningún modelo de correlación alternativo. Detalles: ','Este modelo requiere el paquete %s.','GEE ajustado requiere un resultado numérico finito y una matriz de diseño de rango completo.','Familia no compatible con GEE ajustado.','GEE ajustado requiere identificadores de sujeto y tiempos sin valores faltantes.','GEE ajustado requiere más sujetos observados por par de tiempos que parámetros de regresión.'],
'fr':['GEE non structuré n’a pas pu se terminer dans son processus R isolé. Aucun modèle de corrélation de remplacement n’a été ajusté. Détails : ','Ce modèle nécessite le package %s.','GEE ajusté nécessite un résultat numérique fini et une matrice de conception de rang complet.','Famille non prise en charge par GEE ajusté.','GEE ajusté nécessite des identifiants de sujet et des temps non manquants.','GEE ajusté nécessite plus de sujets observés par paire de temps que de paramètres de régression.'],
'de':['Unstrukturiertes GEE konnte im separaten R-Prozess nicht abgeschlossen werden. Es wurde kein Ersatzkorrelationsmodell angepasst. Details: ','Für dieses Modell ist das Paket %s erforderlich.','Angepasstes GEE erfordert eine endliche numerische Zielvariable und eine Designmatrix mit vollem Rang.','Nicht unterstützte Verteilungsfamilie für angepasstes GEE.','Angepasstes GEE erfordert Personen-IDs und Zeitpunkte ohne fehlende Werte.','Angepasstes GEE erfordert je Zeitpunktpaar mehr beobachtete Personen als Regressionsparameter.'],
'vi':['GEE phi cấu trúc không thể hoàn tất trong tiến trình R riêng biệt. Không khớp mô hình tương quan thay thế. Chi tiết: ','Mô hình này yêu cầu gói %s.','GEE hiệu chỉnh yêu cầu kết quả dạng số hữu hạn và ma trận thiết kế đủ hạng.','GEE hiệu chỉnh không hỗ trợ họ phân phối này.','GEE hiệu chỉnh yêu cầu ID đối tượng và thời điểm không bị thiếu.','GEE hiệu chỉnh yêu cầu số đối tượng quan sát ở mỗi cặp thời điểm lớn hơn số tham số hồi quy.']}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.execution_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
