import json,re
from pathlib import Path
rows='''Research model	研究モデル	研究模型	Modelo de investigación	Modèle de recherche	Forschungsmodell	Mô hình nghiên cứu
Guide for Table 2: Reference-based fit guidance	表2のガイド：参考基準に基づく適合度の案内	表2指南：基于参考标准的拟合指引	Guía de la tabla 2: orientación de ajuste basada en referencias	Guide du tableau 2 : indications d’ajustement fondées sur des références	Hinweise zu Tabelle 2: Referenzbasierte Fit-Beurteilung	Hướng dẫn bảng 2: hướng dẫn độ phù hợp dựa trên mốc tham khảo
Reference-only/review labels locate estimates relative to common approximate ranges; they do not accept or reject the model. Also inspect identification, residuals, parameter plausibility, theory, sample characteristics, and plausible alternative models.	「参考のみ」「要検討」は、推定値が一般的な近似範囲のどこに位置するかを示し、モデルの採択・棄却を決めるものではありません。識別性、残差、パラメータの妥当性、理論、標本特性、妥当な代替モデルも検討してください。	“仅供参考/需审查”标记表示估计值相对于常见近似范围的位置，并不接受或拒绝模型。还应检查可识别性、残差、参数合理性、理论、样本特征及合理的替代模型。	Las etiquetas de referencia o revisión sitúan las estimaciones respecto a rangos aproximados habituales; no aceptan ni rechazan el modelo. Examine también la identificación, los residuos, la plausibilidad de los parámetros, la teoría, las características muestrales y modelos alternativos plausibles.	Les mentions de référence ou d’examen situent les estimations par rapport aux plages approximatives usuelles ; elles n’acceptent ni ne rejettent le modèle. Examinez aussi l’identification, les résidus, la plausibilité des paramètres, la théorie, les caractéristiques de l’échantillon et les modèles alternatifs plausibles.	Die Kennzeichnungen als Referenz oder Prüfbedarf verorten Schätzwerte in üblichen Näherungsbereichen; sie nehmen das Modell weder an noch verwerfen sie es. Prüfen Sie auch Identifikation, Residuen, Parameterplausibilität, Theorie, Stichprobenmerkmale und plausible Alternativmodelle.	Nhãn tham khảo hoặc cần xem xét định vị ước lượng so với các khoảng xấp xỉ thường dùng; chúng không chấp nhận hay bác bỏ mô hình. Cũng cần xem xét tính định danh, phần dư, tính hợp lý của tham số, lý thuyết, đặc điểm mẫu và các mô hình thay thế hợp lý.
Common reference points: CFI/TLI .90/.95, RMSEA .08/.06, and SRMR .10/.08. These are context-dependent reference points, not universal cutoffs.	一般的な参考値：CFI/TLI .90/.95、RMSEA .08/.06、SRMR .10/.08。これらは文脈に依存する参考値であり、普遍的なカットオフではありません。	常见参考点：CFI/TLI .90/.95、RMSEA .08/.06、SRMR .10/.08。这些参考点依赖于具体情境，并非通用截断值。	Referencias habituales: CFI/TLI .90/.95, RMSEA .08/.06 y SRMR .10/.08. Dependen del contexto y no son puntos de corte universales.	Repères usuels : CFI/TLI .90/.95, RMSEA .08/.06 et SRMR .10/.08. Ils dépendent du contexte et ne sont pas des seuils universels.	Übliche Referenzwerte: CFI/TLI .90/.95, RMSEA .08/.06 und SRMR .10/.08. Sie sind kontextabhängig und keine universellen Grenzwerte.	Các mốc tham khảo thường dùng: CFI/TLI .90/.95, RMSEA .08/.06 và SRMR .10/.08. Đây là các mốc phụ thuộc bối cảnh, không phải ngưỡng phổ quát.
Fit guidance is not assessed for saturated models (df = 0) or unavailable fit indices.	飽和モデル（df = 0）または適合度指標を利用できない場合、適合度の案内は評価しません。	对于饱和模型（df = 0）或无法获得拟合指标的情况，不评估拟合指引。	No se evalúa la orientación de ajuste para modelos saturados (df = 0) o índices no disponibles.	Les indications d’ajustement ne sont pas évaluées pour les modèles saturés (df = 0) ou les indices indisponibles.	Bei saturierten Modellen (df = 0) oder nicht verfügbaren Fit-Indizes erfolgt keine Fit-Beurteilung.	Không đánh giá hướng dẫn độ phù hợp cho mô hình bão hòa (df = 0) hoặc khi chỉ số phù hợp không có.'''
rows+='''
Common references: .90/.95	一般的な参考値：.90/.95	常见参考值：.90/.95	Referencias habituales: .90/.95	Repères usuels : .90/.95	Übliche Referenzwerte: .90/.95	Mốc tham khảo thường dùng: .90/.95
Common references: .10/.08	一般的な参考値：.10/.08	常见参考值：.10/.08	Referencias habituales: .10/.08	Repères usuels : .10/.08	Übliche Referenzwerte: .10/.08	Mốc tham khảo thường dùng: .10/.08
Common references: .08/.06	一般的な参考値：.08/.06	常见参考值：.08/.06	Referencias habituales: .08/.06	Repères usuels : .08/.06	Übliche Referenzwerte: .08/.06	Mốc tham khảo thường dùng: .08/.06
Saturated/df <= 0	飽和モデル/df <= 0	饱和模型/df <= 0	Saturado/df <= 0	Saturé/df <= 0	Saturiert/df <= 0	Bão hòa/df <= 0'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  fields=line.split('\t');assert len(fields)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',fields[0].lower()).strip('_')]=fields[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
