import json
from pathlib import Path
keys=['independent','small_cr2','cr_comparison','trim_interpretation','funnel_min']
rows={
'en':['Multiple effects were treated as independent by user selection; standard errors may be too small.','Moderator CR2 inference has few independent studies or low Satterthwaite degrees of freedom; interpret it cautiously.','CR1 and CR3 are sensitivity comparisons; CR2 remains the primary cluster-robust result.','Trim-and-fill is a sensitivity analysis for one assumed selection mechanism, not a definitive correction for publication bias.','Funnel-plot asymmetry diagnostics generally require at least 10 studies. Interpret these results cautiously.'],
'ko':['사용자 선택에 따라 여러 효과를 독립적인 것으로 처리했습니다. 표준오차가 과소 추정될 수 있습니다.','조절효과 CR2 추론의 독립 연구 수가 적거나 Satterthwaite 자유도가 낮으므로 신중하게 해석하세요.','CR1과 CR3은 민감도 비교이며, CR2가 주된 군집 강건 추론 결과입니다.','Trim-and-fill은 가정한 하나의 선택 메커니즘에 대한 민감도 분석이며, 출판편향을 확정적으로 보정하는 방법은 아닙니다.','퍼널 플롯 비대칭 진단에는 일반적으로 최소 10개 연구가 필요합니다. 결과를 신중하게 해석하세요.'],
'ja':['ユーザーの選択により複数の効果を独立として扱いました。標準誤差が過小評価される可能性があります。','調整効果のCR2推論では独立した研究数が少ないかSatterthwaite自由度が低いため、慎重に解釈してください。','CR1とCR3は感度比較であり、CR2が主要なクラスターロバスト推論結果です。','Trim-and-fillは仮定した1つの選択メカニズムに対する感度分析であり、出版バイアスを確定的に補正するものではありません。','ファンネルプロットの非対称性診断には通常、少なくとも10件の研究が必要です。結果は慎重に解釈してください。'],
'zh':['根据用户选择，将多个效应视为独立；标准误可能被低估。','调节效应 CR2 推断的独立研究数较少或 Satterthwaite 自由度较低，请谨慎解释。','CR1 和 CR3 用于敏感性比较；CR2 仍是主要的聚类稳健推断结果。','剪补法是针对一种假定选择机制的敏感性分析，并非对发表偏倚的确定性校正。','漏斗图不对称诊断通常至少需要 10 项研究。请谨慎解释这些结果。'],
'es':['Se trataron múltiples efectos como independientes por elección del usuario; los errores estándar pueden estar subestimados.','La inferencia CR2 del moderador tiene pocos estudios independientes o pocos grados de libertad de Satterthwaite; interprétela con cautela.','CR1 y CR3 son comparaciones de sensibilidad; CR2 sigue siendo el resultado principal robusto por conglomerados.','Trim-and-fill es un análisis de sensibilidad para un mecanismo de selección supuesto, no una corrección definitiva del sesgo de publicación.','Los diagnósticos de asimetría del gráfico de embudo generalmente requieren al menos 10 estudios. Interprete estos resultados con cautela.'],
'fr':['Plusieurs effets ont été traités comme indépendants à la demande de l’utilisateur ; les erreurs-types peuvent être sous-estimées.','L’inférence CR2 du modérateur repose sur peu d’études indépendantes ou de faibles degrés de liberté de Satterthwaite ; interprétez-la avec prudence.','CR1 et CR3 sont des comparaisons de sensibilité ; CR2 reste le résultat principal robuste aux clusters.','Trim-and-fill est une analyse de sensibilité pour un mécanisme de sélection supposé, et non une correction définitive du biais de publication.','Les diagnostics d’asymétrie du graphique en entonnoir nécessitent généralement au moins 10 études. Interprétez ces résultats avec prudence.'],
'de':['Mehrere Effekte wurden auf Wunsch des Nutzers als unabhängig behandelt; die Standardfehler können zu klein sein.','Die CR2-Inferenz für den Moderator beruht auf wenigen unabhängigen Studien oder niedrigen Satterthwaite-Freiheitsgraden; interpretieren Sie sie vorsichtig.','CR1 und CR3 dienen als Sensitivitätsvergleiche; CR2 bleibt das primäre clusterrobuste Ergebnis.','Trim-and-fill ist eine Sensitivitätsanalyse für einen angenommenen Selektionsmechanismus und keine definitive Korrektur des Publikationsbias.','Diagnosen der Funnel-Plot-Asymmetrie erfordern in der Regel mindestens 10 Studien. Interpretieren Sie diese Ergebnisse vorsichtig.'],
'vi':['Nhiều hiệu ứng được xử lý là độc lập theo lựa chọn của người dùng; sai số chuẩn có thể bị đánh giá thấp.','Suy luận CR2 cho biến điều tiết có ít nghiên cứu độc lập hoặc bậc tự do Satterthwaite thấp; hãy diễn giải thận trọng.','CR1 và CR3 là các so sánh độ nhạy; CR2 vẫn là kết quả suy luận vững theo cụm chính.','Trim-and-fill là phân tích độ nhạy cho một cơ chế chọn lọc giả định, không phải phương pháp hiệu chỉnh dứt khoát cho thiên lệch công bố.','Chẩn đoán bất đối xứng biểu đồ phễu thường cần ít nhất 10 nghiên cứu. Hãy diễn giải các kết quả này thận trọng.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'meta.warning.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
