import json,re
from pathlib import Path
rows='''Complete the survival data contract|生存分析のデータ設定を完了してください|完成生存分析数据设置|Complete la definición de los datos de supervivencia|Complétez la définition des données de survie|Vervollständigen Sie die Überlebensdaten-Einstellungen|Hoàn tất thiết lập dữ liệu sống còn
Kaplan-Meier, log-rank test, and RMST|Kaplan–Meier、ログランク検定、RMST|Kaplan–Meier、log-rank检验和RMST|Kaplan–Meier, prueba de log-rank y RMST|Kaplan–Meier, test du log-rank et RMST|Kaplan–Meier, Log-Rank-Test und RMST|Kaplan–Meier, kiểm định log-rank và RMST
Cox proportional hazards regression|Cox比例ハザード回帰|Cox比例风险回归|Regresión de riesgos proporcionales de Cox|Régression à risques proportionnels de Cox|Cox-Regression mit proportionalen Hazards|Hồi quy nguy cơ tỷ lệ Cox
Cumulative incidence function and Gray test|累積発生関数とGray検定|累积发生函数和Gray检验|Función de incidencia acumulada y prueba de Gray|Fonction d’incidence cumulée et test de Gray|Kumulative Inzidenzfunktion und Gray-Test|Hàm tỷ lệ mắc tích lũy và kiểm định Gray
Competing-risk regression|競合リスク回帰|竞争风险回归|Regresión de riesgos competitivos|Régression des risques concurrents|Regression konkurrierender Risiken|Hồi quy nguy cơ cạnh tranh
Cause-specific Cox regression (HR)|原因別Cox回帰（HR）|原因别Cox回归（HR）|Regresión de Cox específica por causa (HR)|Régression de Cox spécifique à la cause (HR)|Ursachenspezifische Cox-Regression (HR)|Hồi quy Cox theo nguyên nhân (HR)
Fine-Gray regression (sHR)|Fine-Gray回帰（sHR）|Fine-Gray回归（sHR）|Regresión de Fine-Gray (sHR)|Régression de Fine-Gray (sHR)|Fine-Gray-Regression (sHR)|Hồi quy Fine-Gray (sHR)
Cause-specific Cox and Fine-Gray regression|原因別Cox回帰とFine-Gray回帰|原因别Cox和Fine-Gray回归|Regresión de Cox específica por causa y de Fine-Gray|Régressions de Cox spécifique à la cause et de Fine-Gray|Ursachenspezifische Cox- und Fine-Gray-Regression|Hồi quy Cox theo nguyên nhân và Fine-Gray
Time-dependent Cox regression|時間依存Cox回帰|时间依赖Cox回归|Regresión de Cox dependiente del tiempo|Régression de Cox dépendante du temps|Zeitabhängige Cox-Regression|Hồi quy Cox phụ thuộc thời gian
Time-dependent Cox model|時間依存Coxモデル|时间依赖Cox模型|Modelo de Cox dependiente del tiempo|Modèle de Cox dépendant du temps|Zeitabhängiges Cox-Modell|Mô hình Cox phụ thuộc thời gian
Interval-censored survival model|区間打ち切り生存モデル|区间删失生存模型|Modelo de supervivencia con censura por intervalos|Modèle de survie avec censure par intervalle|Überlebensmodell mit Intervallzensierung|Mô hình sống còn với kiểm duyệt khoảng
Survival prediction model|生存予測モデル|生存预测模型|Modelo de predicción de supervivencia|Modèle de prédiction de survie|Überlebensvorhersagemodell|Mô hình dự đoán sống còn
Recurrent-event model|反復イベントモデル|重复事件模型|Modelo de eventos recurrentes|Modèle d’événements récurrents|Modell für wiederkehrende Ereignisse|Mô hình biến cố tái diễn
Multi-state model|多状態モデル|多状态模型|Modelo multiestado|Modèle multi-états|Mehrzustandsmodell|Mô hình đa trạng thái
Delayed-entry competing-risk model|遅延エントリー競合リスクモデル|延迟进入竞争风险模型|Modelo de riesgos competitivos con entrada tardía|Modèle de risques concurrents avec entrée retardée|Modell konkurrierender Risiken mit verzögertem Eintritt|Mô hình nguy cơ cạnh tranh với tham gia muộn
Cause-specific summaries|原因別の要約|原因别汇总|Resúmenes por causa|Résumés par cause|Ursachenspezifische Zusammenfassungen|Tóm tắt theo nguyên nhân
Kaplan-Meier descriptive curves|Kaplan–Meier記述曲線|Kaplan–Meier描述曲线|Curvas descriptivas de Kaplan–Meier|Courbes descriptives de Kaplan–Meier|Deskriptive Kaplan–Meier-Kurven|Đường cong mô tả Kaplan–Meier
Cox regression for adjusted association|調整済み関連性のCox回帰|用于调整后关联的Cox回归|Regresión de Cox para la asociación ajustada|Régression de Cox pour l’association ajustée|Cox-Regression für adjustierte Zusammenhänge|Hồi quy Cox cho mối liên hệ đã hiệu chỉnh
Subject-level cluster-robust standard errors will be used.|対象者単位のクラスター頑健標準誤差を使用します。|将使用受试者层面的聚类稳健标准误。|Se utilizarán errores estándar robustos por conglomerado a nivel de sujeto.|Des erreurs-types robustes regroupées par sujet seront utilisées.|Es werden clusterrobuste Standardfehler auf Personenebene verwendet.|Sẽ sử dụng sai số chuẩn vững theo cụm ở cấp đối tượng.
Confirm that the start-stop rows represent time-dependent covariate intervals.|Start–stop行が時間依存共変量の区間を表すことを確認してください。|确认start-stop行表示时间依赖协变量区间。|Confirme que las filas start-stop representan intervalos de covariables dependientes del tiempo.|Confirmez que les lignes start-stop représentent des intervalles de covariables dépendantes du temps.|Bestätigen Sie, dass die Start-Stopp-Zeilen Intervalle zeitabhängiger Kovariaten darstellen.|Xác nhận các hàng start-stop biểu diễn khoảng của hiệp biến phụ thuộc thời gian.
Choose whether the target is cumulative incidence, cause-specific hazard, or both.|目標が累積発生、原因別ハザード、または両方かを選択してください。|选择目标是累积发生率、原因别风险还是两者。|Elija si el objetivo es la incidencia acumulada, el riesgo específico por causa o ambos.|Choisissez si la cible est l’incidence cumulée, le risque spécifique à la cause ou les deux.|Wählen Sie kumulative Inzidenz, ursachenspezifische Hazard oder beides als Ziel.|Chọn mục tiêu là tỷ lệ mắc tích lũy, nguy cơ theo nguyên nhân hoặc cả hai.
Start-stop and time-dependent covariates require a later survival module.|Start–stopデータと時間依存共変量には後続の生存分析モジュールが必要です。|Start-stop和时间依赖协变量需要后续生存分析模块。|Los datos start-stop y las covariables dependientes del tiempo requieren un módulo de supervivencia posterior.|Les données start-stop et les covariables dépendantes du temps nécessitent un module de survie ultérieur.|Start-Stopp-Daten und zeitabhängige Kovariaten erfordern ein späteres Überlebensanalysemodul.|Dữ liệu start-stop và hiệp biến phụ thuộc thời gian cần mô-đun sống còn phiên bản sau.
Interval-censored data are not supported in survival v1.|生存分析v1は区間打ち切りデータに対応していません。|生存分析v1不支持区间删失数据。|La versión 1 de supervivencia no admite datos con censura por intervalos.|La version 1 de survie ne prend pas en charge les données censurées par intervalle.|Überlebensanalyse v1 unterstützt keine intervallzensierten Daten.|Phân tích sống còn v1 không hỗ trợ dữ liệu kiểm duyệt khoảng.
Prediction modelling and validation are not supported in survival v1.|生存分析v1は予測モデルの構築と検証に対応していません。|生存分析v1不支持预测建模和验证。|La versión 1 de supervivencia no admite modelización predictiva ni validación.|La version 1 de survie ne prend pas en charge la modélisation prédictive ni sa validation.|Überlebensanalyse v1 unterstützt keine Vorhersagemodellierung und -validierung.|Phân tích sống còn v1 không hỗ trợ xây dựng và xác thực mô hình dự đoán.
Recurrent-event models are not supported in survival v1.|生存分析v1は反復イベントモデルに対応していません。|生存分析v1不支持重复事件模型。|La versión 1 de supervivencia no admite modelos de eventos recurrentes.|La version 1 de survie ne prend pas en charge les modèles d’événements récurrents.|Überlebensanalyse v1 unterstützt keine Modelle für wiederkehrende Ereignisse.|Phân tích sống còn v1 không hỗ trợ mô hình biến cố tái diễn.
Multi-state models are not supported in survival v1.|生存分析v1は多状態モデルに対応していません。|生存分析v1不支持多状态模型。|La versión 1 de supervivencia no admite modelos multiestado.|La version 1 de survie ne prend pas en charge les modèles multi-états.|Überlebensanalyse v1 unterstützt keine Mehrzustandsmodelle.|Phân tích sống còn v1 không hỗ trợ mô hình đa trạng thái.
The current CIF/Fine-Gray engine does not support delayed entry.|現在のCIF/Fine-Grayエンジンは遅延エントリーに対応していません。|当前CIF/Fine-Gray引擎不支持延迟进入。|El motor actual de CIF/Fine-Gray no admite entrada tardía.|Le moteur actuel CIF/Fine-Gray ne prend pas en charge l’entrée retardée.|Die aktuelle CIF/Fine-Gray-Engine unterstützt keinen verzögerten Eintritt.|Bộ máy CIF/Fine-Gray hiện tại không hỗ trợ tham gia muộn.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
