"""GLIMMPSE/SEM notes with typed, localized categorical slots."""
import json
from pathlib import Path
keys='note_gls_structure_counts note_sem_parameter_counts note_value_exchangeable note_value_ar1 note_value_unstructured note_value_path note_value_loading note_value_correlation note_value_simple note_value_moderate note_value_complex'.split()
rows={
'en':['GLIMMPSE-style mean/covariance simulation using nlme::gls with %s repeated-measures correlation (%s simulations).','Approximate power simulation for a %s of %s using a large-sample standard-error approximation, a %s complexity adjustment, and %s draws per evaluated sample size. This is not a full SEM data-generation and model-refitting Monte Carlo study.','Exchangeable','AR(1)','Unstructured','standardized path','standardized loading','latent correlation','simple','moderate','complex'],
'ko':['반복측정 상관구조 %s에서 nlme::gls를 사용하는 GLIMMPSE 방식 평균·공분산 시뮬레이션(%s회)입니다.','%s 값 %s의 근사 검정력을 시뮬레이션합니다. 대표본 표준오차 근사, 복잡도 %s 보정, 평가 표본수당 %s회 추출을 사용합니다. 전체 SEM 자료를 생성하고 모형을 재적합하는 Monte Carlo 연구는 아닙니다.','교환가능','AR(1)','비구조화','표준화 경로','표준화 적재량','잠재상관','단순','중간','복잡'],
'ja':['反復測定相関%sでnlme::glsを使用するGLIMMPSE方式の平均・共分散シミュレーション（%s回）です。','%sの値%sに対する近似検出力シミュレーションです。大標本標準誤差近似、複雑度%sの調整、評価する標本サイズあたり%s回の抽出を使用します。SEM全体のデータ生成とモデル再適合を行うMonte Carlo研究ではありません。','交換可能','AR(1)','非構造化','標準化パス','標準化負荷量','潜在相関','単純','中程度','複雑'],
'zh':['使用nlme::gls及%s重复测量相关的GLIMMPSE式均值/协方差模拟（%s次模拟）。','对%s值%s进行近似功效模拟，使用大样本标准误近似、%s复杂度调整，以及每个评估样本量%s次抽样。这不是完整SEM数据生成和模型重新拟合的Monte Carlo研究。','可交换','AR(1)','非结构化','标准化路径','标准化载荷','潜变量相关','简单','中等','复杂'],
'es':['Simulación de medias/covarianzas de tipo GLIMMPSE con nlme::gls y correlación de medidas repetidas %s (%s simulaciones).','Simulación de potencia aproximada para %s de %s con una aproximación del error estándar de muestras grandes, ajuste de complejidad %s y %s extracciones por tamaño muestral evaluado. No es un estudio Monte Carlo completo de generación de datos SEM y reajuste del modelo.','intercambiable','AR(1)','no estructurada','ruta estandarizada','carga estandarizada','correlación latente','simple','moderada','compleja'],
'fr':['Simulation des moyennes/covariances de type GLIMMPSE avec nlme::gls et corrélation des mesures répétées %s (%s simulations).','Simulation de puissance approchée pour un paramètre de type %s de valeur %s, avec approximation du grand échantillon de l’erreur standard, ajustement de complexité %s et %s tirages par effectif évalué. Il ne s’agit pas d’une étude Monte Carlo complète générant les données SEM puis réajustant le modèle.','échangeable','AR(1)','non structurée','chemin standardisé','saturation standardisée','corrélation latente','simple','modérée','complexe'],
'de':['Mittelwert-/Kovarianzsimulation nach GLIMMPSE mit nlme::gls und Messwiederholungskorrelation %s (%s Simulationen).','Approximative Teststärkesimulation für den Parametertyp %s mit Wert %s, einer Großstichprobenapproximation des Standardfehlers, Komplexitätsanpassung %s und %s Ziehungen je untersuchter Stichprobengröße. Dies ist keine vollständige Monte-Carlo-Studie mit SEM-Datengenerierung und erneuter Modellschätzung.','austauschbar','AR(1)','unstrukturiert','standardisierter Pfad','standardisierte Ladung','latente Korrelation','einfach','mittel','komplex'],
'vi':['Mô phỏng trung bình/hiệp phương sai kiểu GLIMMPSE bằng nlme::gls với tương quan đo lặp %s (%s lần mô phỏng).','Mô phỏng công suất xấp xỉ cho %s có giá trị %s, dùng xấp xỉ mẫu lớn của sai số chuẩn, điều chỉnh độ phức tạp %s và %s lần lấy mẫu cho mỗi cỡ mẫu đánh giá. Đây không phải nghiên cứu Monte Carlo đầy đủ tạo dữ liệu SEM và khớp lại mô hình.','hoán đổi được','AR(1)','không cấu trúc','đường dẫn chuẩn hóa','hệ số tải chuẩn hóa','tương quan tiềm ẩn','đơn giản','trung bình','phức tạp']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 assert [x.count('%s') for x in values]==[2,4]+[0]*9
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
