import json,re
from pathlib import Path
rows='''Diagonal values are|対角値はsqrt(AVE)、下三角値は潜在相関です。Fornell–Larcker比較が参考値未満でも弁別的妥当性を確立するものではありません。HTMT区間、交差負荷、局所適合、理論、競合する測定モデルも検討してください。|对角值为sqrt(AVE)，下三角值为潜在相关。Fornell–Larcker比较低于参考值并不证明区分效度；还需审查HTMT区间、交叉载荷、局部拟合、理论及竞争测量模型。|La diagonal contiene sqrt(AVE) y el triángulo inferior, correlaciones latentes. Una comparación Fornell–Larcker bajo su referencia no establece validez discriminante; revise intervalos HTMT, cargas cruzadas, ajuste local, teoría y modelos de medida alternativos.|La diagonale contient sqrt(AVE) et le triangle inférieur les corrélations latentes. Une comparaison Fornell–Larcker sous sa référence n’établit pas la validité discriminante ; examinez intervalles HTMT, saturations croisées, ajustement local, théorie et modèles de mesure concurrents.|Diagonalwerte sind sqrt(AVE), Werte im unteren Dreieck latente Korrelationen. Ein Fornell–Larcker-Vergleich unter dem Referenzwert belegt keine diskriminante Validität; prüfen Sie HTMT-Intervalle, Kreuzladungen, lokale Anpassung, Theorie und konkurrierende Messmodelle.|Đường chéo là sqrt(AVE), tam giác dưới là tương quan tiềm ẩn. So sánh Fornell–Larcker dưới mức tham khảo không chứng minh giá trị phân biệt; cần xem khoảng HTMT, tải chéo, độ phù hợp cục bộ, lý thuyết và mô hình đo lường cạnh tranh.
For manuscript reporting|投稿用の本表はAVE、CR、α、ω totalを中心に示します。αはCronbachのalpha、ω totalはMcDonaldのomega totalです。指標数、Fornell–Larcker判定、詳細な解釈案内は本表から省いています。|投稿用本表主要显示AVE、CR、α和ω total。α为Cronbach alpha，ω total为McDonald omega total。本表不含指标数、Fornell–Larcker判断标签及详细解释。|Para publicación, la tabla principal se centra en AVE, CR, α y ω total. α es alfa de Cronbach y ω total, omega total de McDonald. Se omiten el número de indicadores, las etiquetas Fornell–Larcker y la orientación detallada.|Pour publication, le tableau principal présente AVE, CR, α et ω total. α désigne l’alpha de Cronbach et ω total l’oméga total de McDonald. Le nombre d’indicateurs, les critères Fornell–Larcker et les conseils détaillés sont omis.|Für Publikationen konzentriert sich die Haupttabelle auf AVE, CR, α und ω total. α ist Cronbachs Alpha, ω total McDonalds Omega total. Indikatoranzahl, Fornell–Larcker-Bewertungen und detaillierte Hinweise entfallen in der Haupttabelle.|Để báo cáo bài viết, bảng chính tập trung vào AVE, CR, α và ω total. α là alpha Cronbach, ω total là omega total McDonald. Số chỉ báo, nhãn tiêu chí Fornell–Larcker và hướng dẫn chi tiết không nằm trong bảng chính.
Common descriptive guidelines|AVE ≥ .50、CR/α/ω total ≥ .70はよく使われる記述的目安で、普遍的な合否基準ではありません。構成概念の範囲、項目数、モデルの許容性、研究目的と併せて解釈してください。|AVE ≥ .50、CR/α/ω total ≥ .70是常用描述性参考，并非普遍适用的通过规则；应结合构念范围、题项数、模型可接受性及研究目的解释。|AVE ≥ .50 y CR/α/ω total ≥ .70 son guías descriptivas habituales, no reglas universales de aprobación. Interprételas con la amplitud del constructo, número de ítems, admisibilidad y propósito del estudio.|AVE ≥ .50 et CR/α/ω total ≥ .70 sont des repères descriptifs courants, pas des règles universelles d’acceptation. Interprétez-les avec l’étendue du construit, le nombre d’items, l’admissibilité et l’objectif de l’étude.|AVE ≥ .50 und CR/α/ω total ≥ .70 sind übliche deskriptive Richtwerte, keine universellen Bestehensregeln. Berücksichtigen Sie Konstruktbreite, Itemzahl, Modellzulässigkeit und Studienzweck.|AVE ≥ .50 và CR/α/ω total ≥ .70 là hướng dẫn mô tả thường dùng, không phải quy tắc đạt phổ quát. Diễn giải cùng phạm vi cấu trúc, số mục, tính chấp nhận được của mô hình và mục đích nghiên cứu.
CR incorporates|CRは残差共分散行列で推定された測定誤差共分散を反映します。|CR纳入残差协方差矩阵中估计的测量误差协方差。|CR incorpora las covarianzas de error de medida estimadas en la matriz residual.|CR intègre les covariances d’erreur de mesure estimées dans la matrice résiduelle.|CR berücksichtigt die geschätzten Messfehlerkovarianzen in der Residualkovarianzmatrix.|CR tính đến hiệp phương sai sai số đo ước lượng trong ma trận hiệp phương sai phần dư.
† AVE or|† AVEまたは信頼性係数が算出できないか[0, 1]外です。異常な項目共分散、許容できない解、識別されない計算を確認してください。|† AVE或信度系数不可用或超出[0, 1]，提示异常题项协方差、不可接受的解或未识别的计算。|† AVE o un coeficiente de fiabilidad no está disponible o está fuera de [0, 1], por covarianzas inusuales, solución inadmisible o cálculo no identificado.|† AVE ou un coefficient de fiabilité est indisponible ou hors de [0, 1], signalant des covariances inhabituelles, une solution inadmissible ou un calcul non identifié.|† AVE oder ein Reliabilitätskoeffizient ist nicht verfügbar oder liegt außerhalb [0, 1]; prüfen Sie ungewöhnliche Itemkovarianzen, unzulässige Lösungen oder nicht identifizierte Berechnungen.|† AVE hoặc hệ số độ tin cậy không có hoặc ngoài [0, 1], cho thấy hiệp phương sai mục bất thường, nghiệm không chấp nhận được hoặc phép tính không được nhận dạng.
‡ AVE and|‡ 外部根拠のある信頼性制約がない単一指標因子では、AVEとCRを報告しません。|‡ 对于没有外部依据支持信度约束的单指标因子，不报告AVE和CR。|‡ No se informan AVE y CR para un factor de indicador único sin restricciones de fiabilidad justificadas externamente.|‡ AVE et CR ne sont pas rapportés pour un facteur à indicateur unique sans contrainte de fiabilité justifiée extérieurement.|‡ AVE und CR werden für Ein-Indikator-Faktoren ohne extern begründete Reliabilitätsrestriktionen nicht berichtet.|‡ Không báo cáo AVE và CR cho nhân tố một chỉ báo không có ràng buộc độ tin cậy được biện minh từ bên ngoài.
¶ The single-indicator|¶ 単一指標因子には外部根拠のある固定残差分散を使用しています。AVE、CR、ω totalは独立に推定された内的一貫性ではなく、指定した信頼性制約を反映します。αとFornell–Larckerは評価しません。|¶ 单指标因子使用有外部依据的固定残差方差。AVE、CR和ω total反映施加的信度约束，而非独立估计的内部一致性；不评估α和Fornell–Larcker。|¶ El factor de indicador único usa una varianza residual fija justificada externamente. AVE, CR y ω total reflejan esa restricción de fiabilidad, no consistencia interna estimada independientemente; α y Fornell–Larcker no se evalúan.|¶ Le facteur à indicateur unique utilise une variance résiduelle fixe justifiée extérieurement. AVE, CR et ω total reflètent cette contrainte de fiabilité, pas une cohérence interne estimée indépendamment ; α et Fornell–Larcker ne sont pas évalués.|¶ Der Ein-Indikator-Faktor verwendet eine extern begründete feste Residualvarianz. AVE, CR und ω total spiegeln diese Reliabilitätsrestriktion wider, keine unabhängig geschätzte interne Konsistenz; α und Fornell–Larcker werden nicht bewertet.|¶ Nhân tố một chỉ báo dùng phương sai phần dư cố định có căn cứ bên ngoài. AVE, CR và ω total phản ánh ràng buộc độ tin cậy đó, không phải nhất quán nội tại ước lượng độc lập; không đánh giá α và Fornell–Larcker.
§ Fornell-Larcker|§ 外生潜在変数の共分散パスが1つ以上省略され0に固定されたため、Fornell–Larckerを評価していません。|§ 因一个或多个外生潜变量协方差路径被省略并固定为0，未评估Fornell–Larcker。|§ No se evaluó Fornell–Larcker porque una o más covarianzas latentes exógenas se fijaron en cero al omitir sus trayectorias.|§ Fornell–Larcker n’a pas été évalué car au moins une covariance latente exogène a été fixée à zéro par omission du chemin.|§ Fornell–Larcker wurde nicht bewertet, da mindestens eine exogene latente Kovarianz durch ausgelassene Pfade auf null fixiert wurde.|§ Không đánh giá Fornell–Larcker vì một hoặc nhiều hiệp phương sai tiềm ẩn ngoại sinh bị cố định bằng 0 do thiếu đường hiệp phương sai.
For ordered indicators, AVE|順序尺度指標のAVE、CR、ω totalは標準化潜在反応解を使用します。αはlavaanのポリコリック相関行列を使う順序尺度alphaです。|有序指标的AVE、CR和ω total使用标准化潜在反应解；α使用lavaan的多分相关矩阵，即有序alpha。|Con indicadores ordinales, AVE, CR y ω total usan la solución de respuesta latente estandarizada; α usa la matriz policórica de lavaan (alfa ordinal).|Pour les indicateurs ordinaux, AVE, CR et ω total utilisent la solution de réponse latente standardisée ; α utilise la matrice polychorique de lavaan (alpha ordinal).|Bei ordinalen Indikatoren verwenden AVE, CR und ω total die standardisierte latente Antwortlösung; α nutzt lavaans polychorische Korrelationsmatrix (ordinales Alpha).|Với chỉ báo thứ bậc, AVE, CR và ω total dùng nghiệm phản hồi tiềm ẩn chuẩn hóa; α dùng ma trận tương quan polychoric của lavaan (alpha thứ bậc).
α uses|αは分析対象指標の標本共分散行列を使用します。ω totalはモデルに基づき、推定された残差共分散を反映します。|α使用分析指标的样本协方差矩阵。ω total基于模型并纳入估计的残差协方差。|α usa la matriz de covarianzas muestral de los indicadores analizados. ω total se basa en el modelo e incorpora covarianzas residuales estimadas.|α utilise la matrice de covariance d’échantillon des indicateurs analysés. ω total repose sur le modèle et intègre les covariances résiduelles estimées.|α verwendet die Stichprobenkovarianzmatrix der analysierten Indikatoren. ω total ist modellbasiert und berücksichtigt geschätzte Residualkovarianzen.|α dùng ma trận hiệp phương sai mẫu của các chỉ báo được phân tích. ω total dựa trên mô hình và tính đến hiệp phương sai phần dư ước lượng.
In this table, ω total|この表のω totalはCRと同じモデル含意負荷量と残差共分散行列を使用します。現在の同族測定モデルの得点算出仕様では両者は等しくなります。報告を明確にするため両ラベルを残しています。|本表ω total使用与CR相同的模型隐含载荷和残差协方差矩阵，因此在当前同类测量计分设定下等于CR。为清晰报告保留两个标签。|Aquí ω total usa las mismas cargas implícitas y matriz residual que CR; con la especificación congeneric actual es igual a CR. Se conservan ambas etiquetas para claridad del informe.|Ici ω total utilise les mêmes saturations impliquées et la même matrice résiduelle que CR ; il est donc égal à CR avec la spécification congénérique actuelle. Les deux libellés sont conservés pour la clarté du rapport.|ω total verwendet hier dieselben modellimplizierten Ladungen und dieselbe Residualkovarianzmatrix wie CR und entspricht daher unter der aktuellen kongenerischen Scoring-Spezifikation CR. Beide Bezeichnungen bleiben zur Klarheit erhalten.|Trong bảng này, ω total dùng cùng tải hàm ý bởi mô hình và ma trận hiệp phương sai phần dư như CR, nên bằng CR theo đặc tả chấm điểm congeneric hiện tại. Giữ cả hai nhãn để báo cáo rõ ràng.
AVE, CR, Fornell-Larcker and|AVE、CR、Fornell–Larckerと従来のHTMTは観測指標を持つ一次因子に対応します。高次モデルでは上位概念の原項目HTMTと下位尺度平均HTMTを別に示します。両者は同じ完全ケースとPearson相関を使う観測得点の記述量であり、高次潜在相関ではありません。|AVE、CR、Fornell–Larcker和现有HTMT针对具有观测指标的一阶因子。高阶模型另提供顶层原题项HTMT和分量表均值HTMT。两者均基于相同完整个案和Pearson相关，是观测分数的描述性评价，不是高阶潜在相关。|AVE, CR, Fornell–Larcker y el HTMT existente se refieren a factores de primer orden con indicadores observados. Para modelos superiores se ofrecen HTMT de ítems originales y de medias de subescalas de nivel superior. Ambos son evaluaciones descriptivas de puntuaciones observadas con los mismos casos completos y correlaciones Pearson, no correlaciones latentes superiores.|AVE, CR, Fornell–Larcker et HTMT existant concernent les facteurs de premier ordre à indicateurs observés. Les modèles supérieurs présentent séparément HTMT sur items originaux et sur moyennes de sous-échelles au niveau supérieur. Ce sont des évaluations descriptives de scores observés, avec les mêmes cas complets et corrélations Pearson, pas des corrélations latentes supérieures.|AVE, CR, Fornell–Larcker und das bisherige HTMT beziehen sich auf Faktoren erster Ordnung mit beobachteten Indikatoren. Bei höheren Modellen werden HTMT auf Basis ursprünglicher Items und von Subskalenmitteln auf oberster Ebene getrennt berichtet. Beide sind deskriptive Bewertungen beobachteter Scores mit denselben vollständigen Fällen und Pearson-Korrelationen, keine latenten Korrelationen höherer Ordnung.|AVE, CR, Fornell–Larcker và HTMT hiện có áp dụng cho nhân tố bậc một có chỉ báo quan sát. Mô hình bậc cao có riêng HTMT theo mục gốc và trung bình thang con ở cấp trên. Cả hai mô tả điểm quan sát, dùng cùng trường hợp đầy đủ và tương quan Pearson, không phải tương quan tiềm ẩn bậc cao.
Caution: the fitted solution failed|注意：適合した解が1つ以上の許容性検査を通過していません。AVE、CR、弁別的妥当性の結果を最終結果として解釈しないでください。|注意：拟合解未通过一个或多个可接受性检查；AVE、CR和区分效度结果不应作为最终结果解释。|Precaución: la solución ajustada falló una o más comprobaciones de admisibilidad; no interprete AVE, CR y validez discriminante como resultados finales.|Attention : la solution ajustée a échoué à au moins un contrôle d’admissibilité ; AVE, CR et validité discriminante ne doivent pas être interprétés comme définitifs.|Achtung: Die angepasste Lösung bestand mindestens eine Zulässigkeitsprüfung nicht. AVE, CR und diskriminante Validität dürfen nicht als endgültige Ergebnisse interpretiert werden.|Chú ý: nghiệm đã khớp không qua một hoặc nhiều kiểm tra tính chấp nhận được; không diễn giải AVE, CR và giá trị phân biệt như kết quả cuối cùng.'''
p=Path('R/setup_custom_model_canvas_structural_render_validity_notes.R');source=p.read_text(encoding='utf-8')
source=source.replace('ko <- identical(normalize_app_language(statedu_current_language(app_language_fn)), "ko")','tr <- function(en, ko) statedu_localized_text(statedu_current_language(app_language_fn), en, ko)')
source=re.sub(r'if \(ko\) "([^"\n]+)" else "([^"\n]+)"',lambda m:'tr("'+m[2]+'", "'+m[1]+'")',source)
p.write_text(source,encoding='utf-8');sources=re.findall(r'tr\("([^"]+)"',source);data_rows=[]
for row in rows.splitlines():
 f=row.split('|');assert len(f)==7
 matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
