import json
from pathlib import Path
keys = ['or_nonnegative','or_integer','or_ci','or_log','or_b','or_type','or_correction','or_correction_assumption','or_coding']
rows = {
'en':['All 2 x 2 cell counts must be non-negative.','All 2 x 2 cell counts must be integers.','The 95% CI must satisfy 0 < lower < OR < upper.','Enter a finite log(OR) and an SE greater than zero.','Enter a finite logistic coefficient B and an SE greater than zero.','Unsupported odds-ratio input type.','Zero-cell continuity correction applied.','A continuity correction of 0.5 was added to all four cells because at least one cell was zero.','Predictor coding and the event/reference categories must be aligned across studies.'],
'ko':['2 x 2 표의 모든 셀 빈도는 0 이상이어야 합니다.','2 x 2 표의 모든 셀 빈도는 정수여야 합니다.','95% CI는 0 < 하한 < OR < 상한을 만족해야 합니다.','유한한 log(OR)와 0보다 큰 SE를 입력하세요.','유한한 로지스틱 계수 B와 0보다 큰 SE를 입력하세요.','지원하지 않는 오즈비 입력 유형입니다.','0 빈도 셀에 대한 연속성 보정을 적용했습니다.','빈도가 0인 셀이 하나 이상 있어 네 셀 모두에 연속성 보정값 0.5를 더했습니다.','연구 간 예측변수 코딩과 사건/참조 범주를 일치시켜야 합니다.'],
'ja':['2 x 2表のすべてのセル度数は0以上である必要があります。','2 x 2表のすべてのセル度数は整数である必要があります。','95% CIは0 < 下限 < OR < 上限を満たす必要があります。','有限のlog(OR)と0より大きいSEを入力してください。','有限のロジスティック係数Bと0より大きいSEを入力してください。','サポートされていないオッズ比の入力タイプです。','度数0のセルに対する連続性補正を適用しました。','度数0のセルが少なくとも1つあったため、4つのセルすべてに連続性補正値0.5を加えました。','研究間で予測変数のコーディングとイベント/参照カテゴリを統一する必要があります。'],
'zh':['2 x 2 表的所有单元格频数必须非负。','2 x 2 表的所有单元格频数必须为整数。','95% CI 必须满足 0 < 下限 < OR < 上限。','请输入有限的 log(OR) 和大于零的 SE。','请输入有限的逻辑回归系数 B 和大于零的 SE。','不支持的优势比输入类型。','已应用零频数单元格连续性校正。','由于至少一个单元格的频数为零，已向全部四个单元格添加 0.5 的连续性校正值。','各研究的预测变量编码及事件/参照类别必须一致。'],
'es':['Todos los recuentos de las celdas 2 x 2 deben ser no negativos.','Todos los recuentos de las celdas 2 x 2 deben ser enteros.','El IC del 95% debe cumplir 0 < límite inferior < OR < límite superior.','Introduzca un log(OR) finito y un EE mayor que cero.','Introduzca un coeficiente logístico B finito y un EE mayor que cero.','Tipo de entrada de odds ratio no compatible.','Se aplicó una corrección de continuidad por celdas con cero.','Se añadió una corrección de continuidad de 0.5 a las cuatro celdas porque al menos una era cero.','La codificación de los predictores y las categorías de evento/referencia deben coincidir entre los estudios.'],
'fr':['Tous les effectifs des cellules du tableau 2 x 2 doivent être non négatifs.','Tous les effectifs des cellules du tableau 2 x 2 doivent être des entiers.','L’IC à 95% doit satisfaire 0 < borne inférieure < OR < borne supérieure.','Saisissez un log(OR) fini et une erreur-type supérieure à zéro.','Saisissez un coefficient logistique B fini et une erreur-type supérieure à zéro.','Type de saisie d’odds ratio non pris en charge.','Une correction de continuité pour cellule nulle a été appliquée.','Une correction de continuité de 0.5 a été ajoutée aux quatre cellules car au moins une était nulle.','Le codage des prédicteurs et les catégories d’événement/de référence doivent être harmonisés entre les études.'],
'de':['Alle Zellhäufigkeiten der 2 x 2-Tabelle müssen nichtnegativ sein.','Alle Zellhäufigkeiten der 2 x 2-Tabelle müssen ganze Zahlen sein.','Das 95%-KI muss 0 < Untergrenze < OR < Obergrenze erfüllen.','Geben Sie einen endlichen log(OR) und einen SE größer als null ein.','Geben Sie einen endlichen logistischen Koeffizienten B und einen SE größer als null ein.','Nicht unterstützter Eingabetyp für Odds Ratios.','Eine Kontinuitätskorrektur für Nullzellen wurde angewendet.','Da mindestens eine Zelle null war, wurde zu allen vier Zellen eine Kontinuitätskorrektur von 0.5 addiert.','Die Kodierung der Prädiktoren und die Ereignis-/Referenzkategorien müssen über die Studien hinweg übereinstimmen.'],
'vi':['Tất cả tần số ô trong bảng 2 x 2 phải không âm.','Tất cả tần số ô trong bảng 2 x 2 phải là số nguyên.','Khoảng tin cậy 95% phải thỏa mãn 0 < cận dưới < OR < cận trên.','Nhập log(OR) hữu hạn và SE lớn hơn 0.','Nhập hệ số logistic B hữu hạn và SE lớn hơn 0.','Không hỗ trợ kiểu đầu vào tỷ số odds này.','Đã áp dụng hiệu chỉnh liên tục cho ô có tần số bằng 0.','Đã cộng hiệu chỉnh liên tục 0.5 vào cả bốn ô vì có ít nhất một ô bằng 0.','Mã hóa biến dự báo và các nhóm sự kiện/tham chiếu phải thống nhất giữa các nghiên cứu.'],
}
for lang, values in rows.items():
    path = Path('i18n') / (lang + '.json')
    obj = json.loads(path.read_text(encoding='utf-8'))
    obj['translations'].update({'meta.input_error.' + k: v for k, v in zip(keys, values)})
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
