import json,re
from pathlib import Path
phrases={
'Unweighted N':['비가중 N','非加重N','未加权N','N no ponderado','N non pondéré','Ungewichtetes N','N không trọng số'],
'Eligible design N':['분석 가능 설계 N','分析対象の設計N','符合条件的设计N','N elegible del diseño','N admissible du plan','Geeignetes Design-N','N thiết kế đủ điều kiện'],
'Complete-case excluded N':['완전사례 처리 제외 N','完全ケース処理で除外されたN','完整个案处理排除N','N excluido por casos incompletos','N exclu pour cas incomplets','Wegen unvollständiger Fälle ausgeschlossenes N','N bị loại do trường hợp không đầy đủ'],
'Adjusted R-squared':['수정 R 제곱','調整済みR二乗','调整R平方','R cuadrado ajustado','R carré ajusté','Korrigiertes R-Quadrat','R bình phương hiệu chỉnh'],
'Model Wald/F statistic':['모형 Wald/F 통계량','モデルのWald/F統計量','模型Wald/F统计量','Estadístico Wald/F del modelo','Statistique Wald/F du modèle','Wald/F-Statistik des Modells','Thống kê Wald/F của mô hình'],
'Model Wald/F df':['모형 Wald/F 자유도','モデルのWald/F自由度','模型Wald/F自由度','Grados de libertad Wald/F del modelo','Degrés de liberté Wald/F du modèle','Wald/F-Freiheitsgrade des Modells','Bậc tự do Wald/F của mô hình'],
'Model Wald/F p':['모형 Wald/F p','モデルのWald/F p値','模型Wald/F p值','p de Wald/F del modelo','p de Wald/F du modèle','Wald/F-p-Wert des Modells','p Wald/F của mô hình'],
'Complex-sample linear regression':['복합표본 선형 회귀분석','複雑標本の線形回帰分析','复杂抽样线性回归','Regresión lineal de muestras complejas','Régression linéaire pour échantillons complexes','Lineare Regression für komplexe Stichproben','Hồi quy tuyến tính mẫu phức tạp'],
'Complex-sample regression':['복합표본 회귀분석','複雑標本の回帰分析','复杂抽样回归','Regresión de muestras complejas','Régression pour échantillons complexes','Regression für komplexe Stichproben','Hồi quy mẫu phức tạp'],
'Complex-sample logistic regression':['복합표본 로지스틱 회귀분석','複雑標本のロジスティック回帰分析','复杂抽样Logistic回归','Regresión logística de muestras complejas','Régression logistique pour échantillons complexes','Logistische Regression für komplexe Stichproben','Hồi quy logistic mẫu phức tạp'],
'Complex-sample regression overview':['복합표본 회귀분석 개요','複雑標本の回帰分析の概要','复杂抽样回归概览','Resumen de regresión de muestras complejas','Vue d’ensemble de la régression pour échantillons complexes','Regressionsübersicht für komplexe Stichproben','Tổng quan hồi quy mẫu phức tạp'],
'Complex-sample logistic regression overview':['복합표본 로지스틱 회귀분석 개요','複雑標本のロジスティック回帰分析の概要','复杂抽样Logistic回归概览','Resumen de regresión logística de muestras complejas','Vue d’ensemble de la régression logistique pour échantillons complexes','Übersicht der logistischen Regression für komplexe Stichproben','Tổng quan hồi quy logistic mẫu phức tạp'],
'Event category':['사건 범주','イベントカテゴリ','事件类别','Categoría del evento','Catégorie de l’événement','Ereigniskategorie','Danh mục biến cố'],
'McFadden pseudo R-squared':['McFadden 유사 R 제곱','McFaddenの疑似R二乗','McFadden伪R平方','Pseudo R cuadrado de McFadden','Pseudo-R carré de McFadden','McFadden-Pseudo-R-Quadrat','R bình phương giả McFadden'],
'Nagelkerke pseudo R-squared':['Nagelkerke 유사 R 제곱','Nagelkerkeの疑似R二乗','Nagelkerke伪R平方','Pseudo R cuadrado de Nagelkerke','Pseudo-R carré de Nagelkerke','Nagelkerke-Pseudo-R-Quadrat','R bình phương giả Nagelkerke'],
'Error':['오류','エラー','错误','Error','Erreur','Fehler','Lỗi'],
'Complete-case modeling excluded %s row(s) with missing outcome or predictor values after survey design/subpopulation filtering.':['완전사례 모형에서 조사설계 및 부-모집단 필터링 후 결과변수 또는 예측변수 값이 결측인 %s개 행을 제외했습니다.','完全ケースのモデル化では、調査設計・部分母集団の絞り込み後に結果変数または予測変数が欠損している%s行を除外しました。','完整个案建模在应用调查设计及子总体筛选后，排除了结果变量或预测变量缺失的%s行。','El modelado de casos completos excluyó %s filas con valores perdidos en el resultado o los predictores tras aplicar el diseño de encuesta y el filtro de subpoblación.','La modélisation sur cas complets a exclu %s lignes avec des valeurs manquantes dans le résultat ou les prédicteurs après application du plan de sondage et du filtre de sous-population.','Bei der Modellierung vollständiger Fälle wurden nach Anwendung des Erhebungsdesigns und Teilpopulationsfilters %s Zeilen mit fehlenden Ergebnis- oder Prädiktorwerten ausgeschlossen.','Mô hình hóa trường hợp đầy đủ đã loại %s dòng có giá trị thiếu ở biến kết quả hoặc biến dự báo sau khi áp dụng thiết kế khảo sát và bộ lọc tiểu quần thể.'],
'Dependent variable has no usable non-missing values.':['종속변수에 사용할 수 있는 비결측값이 없습니다.','従属変数に利用可能な非欠損値がありません。','因变量没有可用的非缺失值。','La variable dependiente no tiene valores no perdidos utilizables.','La variable dépendante ne contient aucune valeur non manquante utilisable.','Die abhängige Variable hat keine verwendbaren nichtfehlenden Werte.','Biến phụ thuộc không có giá trị không thiếu có thể sử dụng.'],
'Logistic regression requires a binary dependent variable.':['로지스틱 회귀에는 이분형 종속변수가 필요합니다.','ロジスティック回帰には二値の従属変数が必要です。','Logistic回归需要二分类因变量。','La regresión logística requiere una variable dependiente binaria.','La régression logistique nécessite une variable dépendante binaire.','Die logistische Regression erfordert eine binäre abhängige Variable.','Hồi quy logistic yêu cầu biến phụ thuộc nhị phân.']}
for index,lang in enumerate(['ko','ja','zh','es','fr','de','vi']):
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 for source,values in phrases.items():data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',source.lower()).strip('_')]=values[index]
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
