import json,re
from pathlib import Path
rows='''At least one cause-specific Cox omnibus test is non-finite.|少なくとも1つの原因別Cox全体検定が有限値ではありません。|至少一个原因别Cox整体检验为非有限值。|Al menos una prueba global de Cox por causa específica no es finita.|Au moins un test global de Cox par cause n’est pas fini.|Mindestens ein ursachenspezifischer globaler Cox-Test ist nicht endlich.|Ít nhất một kiểm định tổng thể Cox theo nguyên nhân có giá trị không hữu hạn.
Do not report non-finite cause-specific Cox omnibus tests; review sparsity, separation, and model identification.|有限値でない原因別Cox全体検定を報告せず、データの少なさ、分離、モデル識別を確認してください。|不要报告非有限值的原因别Cox整体检验；请检查数据稀疏性、分离及模型识别。|No informe pruebas globales de Cox por causa específica no finitas; revise la escasez de datos, la separación y la identificación del modelo.|Ne présentez pas les tests globaux de Cox par cause non finis ; examinez la rareté des données, la séparation et l’identification du modèle.|Berichten Sie keine nicht endlichen ursachenspezifischen globalen Cox-Tests; prüfen Sie Datenknappheit, Separation und Modellidentifikation.|Không báo cáo kiểm định tổng thể Cox theo nguyên nhân có giá trị không hữu hạn; hãy xem xét dữ liệu thưa thớt, phân tách và khả năng nhận dạng mô hình.
Survival sparse evidence Non-estimable cause-specific categorical joint tests:|推定できない原因別カテゴリ変数の全体検定:|无法估计的原因别分类变量联合检验：|Pruebas conjuntas categóricas por causa específica no estimables:|Tests conjoints catégoriels par cause non estimables :|Nicht schätzbare ursachenspezifische gemeinsame Tests kategorialer Variablen:|Kiểm định đồng thời biến phân loại theo nguyên nhân không thể ước lượng:
Review sparse levels, separation, or a singular covariance matrix and do not report the affected cause-specific categorical joint test.|頻度の少ないカテゴリ、分離、または特異な共分散行列を確認し、該当する原因別カテゴリ変数の全体検定を報告しないでください。|请检查稀疏类别、分离或奇异协方差矩阵，不要报告受影响的原因别分类变量联合检验。|Revise categorías con pocos datos, separación o una matriz de covarianza singular y no informe la prueba conjunta categórica por causa específica afectada.|Examinez les catégories peu représentées, la séparation ou une matrice de covariance singulière et ne présentez pas le test conjoint catégoriel par cause concerné.|Prüfen Sie schwach besetzte Kategorien, Separation oder eine singuläre Kovarianzmatrix und berichten Sie den betroffenen ursachenspezifischen gemeinsamen Test kategorialer Variablen nicht.|Xem xét các mức phân loại thưa thớt, phân tách hoặc ma trận hiệp phương sai suy biến và không báo cáo kiểm định đồng thời biến phân loại theo nguyên nhân bị ảnh hưởng.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
