import json,re
from pathlib import Path
rows='''Time function|時間関数|时间函数|Función del tiempo|Fonction du temps|Zeitfunktion|Hàm thời gian
Interaction B|交互作用B|交互作用B|B de interacción|B d’interaction|Interaktions-B|B tương tác
Time-varying coefficient analysis|時間依存係数分析|时变系数分析|Análisis de coeficientes variables en el tiempo|Analyse des coefficients variant dans le temps|Analyse zeitabhängiger Koeffizienten|Phân tích hệ số thay đổi theo thời gian
Time-specific hazard ratios|時点別ハザード比|各时点风险比|Razones de riesgos por tiempo|Rapports des risques instantanés par temps|Zeitpunktspezifische Hazard Ratios|Tỷ số nguy cơ tại từng thời điểm
For this time-varying-coefficient analysis, the Schoenfeld tests and plots come from the companion proportional-hazards model fitted before adding tt(). They document the diagnostic motivation; they are not post-extension PH tests.|この時間依存係数分析のSchoenfeld検定と図は、tt()を追加する前に適合した対応する比例ハザードモデルに基づきます。これらは診断上の根拠を示し、モデル拡張後のPH検定ではありません。|本时变系数分析的Schoenfeld检验和图形来自添加tt()之前拟合的配套比例风险模型。它们记录诊断依据，并非扩展模型后的PH检验。|En este análisis de coeficientes variables en el tiempo, las pruebas y los gráficos de Schoenfeld proceden del modelo complementario de riesgos proporcionales ajustado antes de añadir tt(). Documentan la motivación diagnóstica; no son pruebas PH posteriores a la extensión.|Pour cette analyse des coefficients variant dans le temps, les tests et graphiques de Schoenfeld proviennent du modèle compagnon à risques proportionnels ajusté avant l’ajout de tt(). Ils documentent la motivation diagnostique ; ce ne sont pas des tests PH après extension.|Bei dieser Analyse zeitabhängiger Koeffizienten stammen die Schoenfeld-Tests und -Diagramme aus dem begleitenden proportionalen Hazards-Modell vor dem Hinzufügen von tt(). Sie dokumentieren die diagnostische Begründung; es sind keine PH-Tests nach der Modellerweiterung.|Trong phân tích hệ số thay đổi theo thời gian này, kiểm định và đồ thị Schoenfeld được lấy từ mô hình nguy cơ tỷ lệ đi kèm được ước lượng trước khi thêm tt(). Chúng ghi nhận cơ sở chẩn đoán, không phải kiểm định PH sau khi mở rộng mô hình.
The model is β(t) = β + γ log(1 + time). The interaction test evaluates γ = 0; report the time-specific HR curve and confidence intervals rather than a single constant HR. The plotted range uses the 5th to 95th percentiles of observed event times, plus requested reporting times.|モデルはβ(t) = β + γ log(1 + time)です。交互作用検定はγ = 0を評価します。単一の一定HRではなく、時点別HR曲線と信頼区間を報告してください。図の範囲には観測イベント時点の第5～第95百分位と指定された報告時点を使用します。|模型为β(t) = β + γ log(1 + time)。交互作用检验评估γ = 0；应报告各时点HR曲线及置信区间，而非单一固定HR。绘图范围采用观测事件时间的第5至第95百分位，并包含指定的报告时点。|El modelo es β(t) = β + γ log(1 + time). La prueba de interacción evalúa γ = 0; informe la curva de HR por tiempo y sus intervalos de confianza, en lugar de un único HR constante. El gráfico abarca los percentiles 5 a 95 de los tiempos de evento observados e incluye los tiempos de informe solicitados.|Le modèle est β(t) = β + γ log(1 + time). Le test d’interaction évalue γ = 0 ; présentez la courbe de HR par temps et les intervalles de confiance plutôt qu’un seul HR constant. Le graphique couvre les 5e à 95e percentiles des temps d’événement observés ainsi que les temps de présentation demandés.|Das Modell lautet β(t) = β + γ log(1 + time). Der Interaktionstest prüft γ = 0; berichten Sie die zeitpunktspezifische HR-Kurve und Konfidenzintervalle statt einer einzelnen konstanten HR. Der dargestellte Bereich umfasst das 5. bis 95. Perzentil der beobachteten Ereigniszeiten sowie die angeforderten Berichtszeitpunkte.|Mô hình là β(t) = β + γ log(1 + time). Kiểm định tương tác đánh giá γ = 0; báo cáo đường HR theo thời điểm và khoảng tin cậy thay vì một HR cố định duy nhất. Phạm vi đồ thị dùng phân vị thứ 5 đến 95 của thời gian biến cố quan sát được, cùng các thời điểm báo cáo được yêu cầu.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
