import json,re
from pathlib import Path
rows='''Every construct passed compositional invariance after the global Holm MICOM adjustment.|すべての構成概念が全体のHolm MICOM補正後に合成不変性を満たしました。|所有构念在整体Holm MICOM校正后均通过组成不变性检验。|Todos los constructos superaron la invariancia composicional tras el ajuste global Holm de MICOM.|Tous les construits ont satisfait l’invariance compositionnelle après l’ajustement global Holm de MICOM.|Alle Konstrukte bestanden die kompositionelle Invarianz nach der globalen Holm-MICOM-Korrektur.|Tất cả cấu trúc đạt tính bất biến thành phần sau hiệu chỉnh Holm MICOM toàn cục.
One or more constructs failed compositional invariance after the global Holm MICOM adjustment.|1つ以上の構成概念が全体のHolm MICOM補正後に合成不変性を満たしませんでした。|一个或多个构念在整体Holm MICOM校正后未通过组成不变性检验。|Uno o más constructos no superaron la invariancia composicional tras el ajuste global Holm de MICOM.|Un ou plusieurs construits n’ont pas satisfait l’invariance compositionnelle après l’ajustement global Holm de MICOM.|Mindestens ein Konstrukt bestand die kompositionelle Invarianz nach der globalen Holm-MICOM-Korrektur nicht.|Một hoặc nhiều cấu trúc không đạt tính bất biến thành phần sau hiệu chỉnh Holm MICOM toàn cục.
Pairwise permutation-validity gate failed.|集団対の置換有効性基準を満たしませんでした。|组对置换有效性未达标。|No se superó el criterio de validez de permutación del par.|Le critère de validité des permutations de la paire n’a pas été satisfait.|Das Kriterium für die Permutationsgültigkeit des Paars wurde nicht erfüllt.|Cặp nhóm không đạt tiêu chí tính hợp lệ của hoán vị.
At least one group has N < 30; review stability|少なくとも1つの集団でN < 30です。安定性を検討してください。|至少一组N < 30；请检查稳定性。|Al menos un grupo tiene N < 30; revise la estabilidad.|Au moins un groupe a N < 30 ; examinez la stabilité.|Mindestens eine Gruppe hat N < 30; prüfen Sie die Stabilität.|Ít nhất một nhóm có N < 30; cần xem xét độ ổn định.
Pair blocked because the MICOM and MGA group sets do not match.|MICOMとMGAの集団構成が一致しないため、集団対の比較を停止しました。|MICOM与MGA的组集合不一致，已阻止该组对比较。|Par bloqueado porque los conjuntos de grupos de MICOM y MGA no coinciden.|Paire bloquée car les ensembles de groupes MICOM et MGA ne correspondent pas.|Paar gesperrt, da die MICOM- und MGA-Gruppenmengen nicht übereinstimmen.|Chặn cặp vì tập nhóm của MICOM và MGA không khớp.
Pair blocked because duplicate MICOM pair-gate records were found.|MICOMの集団対判定記録が重複しているため、比較を停止しました。|发现重复的MICOM组对判定记录，已阻止比较。|Par bloqueado por registros duplicados del criterio MICOM del par.|Paire bloquée en raison de doublons dans les enregistrements de décision MICOM de la paire.|Paar wegen doppelter MICOM-Paarentscheidungen gesperrt.|Chặn cặp vì có bản ghi quyết định MICOM trùng lặp.
Pair blocked because its MICOM pair-gate record is missing.|MICOMの集団対判定記録がないため、比較を停止しました。|缺少该组对的MICOM判定记录，已阻止比较。|Par bloqueado porque falta su registro de decisión MICOM.|Paire bloquée car son enregistrement de décision MICOM est absent.|Paar gesperrt, da sein MICOM-Entscheidungsdatensatz fehlt.|Chặn cặp vì thiếu bản ghi quyết định MICOM của cặp.
Pair blocked because the MICOM pair-gate decision column is missing.|MICOMの集団対判定列がないため、比較を停止しました。|缺少MICOM组对判定列，已阻止比较。|Par bloqueado porque falta la columna de decisión MICOM.|Paire bloquée car la colonne de décision MICOM est absente.|Paar gesperrt, da die MICOM-Paarentscheidungsspalte fehlt.|Chặn cặp vì thiếu cột quyết định MICOM.
Pair admitted by the recorded MICOM composite-invariance gate.|記録されたMICOM合成不変性基準により集団対の比較が許可されました。|根据记录的MICOM复合不变性判定，允许该组对比较。|Par admitido por el criterio registrado de invariancia de compuestos MICOM.|Paire admise selon la décision consignée d’invariance des composites MICOM.|Paar durch die dokumentierte MICOM-Kompositinvarianzentscheidung zugelassen.|Cho phép cặp theo quyết định bất biến biến tổng hợp MICOM đã ghi.
Pair blocked because a passing MICOM composite-invariance gate was not recorded.|MICOM合成不変性基準の通過記録がないため、集団対の比較を停止しました。|未记录MICOM复合不变性达标结果，已阻止该组对比较。|Par bloqueado porque no se registró la superación del criterio de invariancia de compuestos MICOM.|Paire bloquée car aucune réussite au critère d’invariance des composites MICOM n’a été consignée.|Paar gesperrt, da kein bestandenes MICOM-Kompositinvarianzkriterium dokumentiert wurde.|Chặn cặp vì chưa ghi nhận đạt tiêu chí bất biến biến tổng hợp MICOM.
Pairwise inference is blocked because MICOM composite-score invariance was not evaluated.|MICOM合成スコア不変性を評価していないため、集団対の推論を停止しました。|未评估MICOM复合得分不变性，因此阻止组对推断。|La inferencia por pares está bloqueada porque no se evaluó la invariancia de puntuaciones compuestas MICOM.|L’inférence par paires est bloquée car l’invariance des scores composites MICOM n’a pas été évaluée.|Paarweise Inferenz ist gesperrt, da die MICOM-Kompositscore-Invarianz nicht geprüft wurde.|Chặn suy luận theo cặp vì chưa đánh giá bất biến điểm tổng hợp MICOM.
MICOM pair gate was unavailable.|MICOMの集団対判定を利用できませんでした。|MICOM组对判定不可用。|La decisión MICOM del par no estaba disponible.|La décision MICOM de la paire n’était pas disponible.|Die MICOM-Paarentscheidung war nicht verfügbar.|Không có quyết định MICOM cho cặp.
MICOM pair-gate helpers were not loaded; pairwise inference is blocked.|MICOM集団対判定機能が読み込まれていないため、集団対の推論を停止しました。|未加载MICOM组对判定功能，已阻止组对推断。|No se cargaron las funciones de decisión MICOM por pares; la inferencia está bloqueada.|Les fonctions de décision MICOM par paires n’ont pas été chargées ; l’inférence est bloquée.|Die MICOM-Paarprüffunktionen wurden nicht geladen; paarweise Inferenz ist gesperrt.|Chưa tải chức năng quyết định MICOM theo cặp; chặn suy luận theo cặp.
MICOM was not evaluated.|MICOMを評価していません。|未评估MICOM。|No se evaluó MICOM.|MICOM n’a pas été évalué.|MICOM wurde nicht geprüft.|Chưa đánh giá MICOM.
Blocked by MICOM|MICOMにより停止|被MICOM阻止|Bloqueado por MICOM|Bloqué par MICOM|Durch MICOM gesperrt|Bị chặn bởi MICOM
Insufficient|不十分|不足|Insuficiente|Insuffisant|Unzureichend|Không đủ
Small-N warning|小標本の警告|小样本警示|Alerta de muestra pequeña|Alerte de petit effectif|Warnhinweis bei kleinem N|Cảnh báo mẫu nhỏ
Composite-score invariance gate|合成スコア不変性の判定|复合得分不变性判定|Criterio de invariancia de puntuaciones compuestas|Décision d’invariance des scores composites|Kompositscore-Invarianzkriterium|Tiêu chí bất biến điểm tổng hợp
Constructs passed|通過した構成概念数|通过的构念数|Constructos que superaron el criterio|Construits ayant satisfait le critère|Bestandene Konstrukte|Số cấu trúc đạt
Constructs tested|点検した構成概念数|检验的构念数|Constructos evaluados|Construits testés|Geprüfte Konstrukte|Số cấu trúc được kiểm tra
Pair seed|集団対のシード|组对种子|Semilla del par|Graine de la paire|Seed des Paars|Hạt giống của cặp
MICOM admitted|MICOM比較許可|MICOM允许比较|Admitido por MICOM|Admis par MICOM|Durch MICOM zugelassen|MICOM cho phép
MICOM reason|MICOMの理由|MICOM原因|Motivo MICOM|Raison MICOM|MICOM-Begründung|Lý do MICOM
Valid N|有効再標本数|有效重抽样次数|N de remuestreos válidos|N de rééchantillonnages valides|Gültige Resampling-Anzahl|Số lần lấy mẫu lại hợp lệ
Requested N|要求再標本数|请求的重抽样次数|N de remuestreos solicitados|N de rééchantillonnages demandés|Angeforderte Resampling-Anzahl|Số lần lấy mẫu lại yêu cầu
Valid Ratio|有効比率|有效比例|Proporción válida|Proportion valide|Gültiger Anteil|Tỷ lệ hợp lệ
Minimum Valid N|最小有効再標本数|最小有效重抽样次数|N mínimo de remuestreos válidos|N minimal de rééchantillonnages valides|Minimale gültige Resampling-Anzahl|Số lần lấy mẫu lại hợp lệ tối thiểu'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
