"""Remaining basic planning and achieved-power descriptions."""
import json
from pathlib import Path
keys='note_power_t_two note_power_t_paired note_power_t_one note_power_rank note_prop_two_n note_prop_two_power note_prop_one_n note_prop_one_power note_correlation_z note_chisquare_ncp'.split()
rows={
'en':['Exact independent two-sample t-test power calculation.','Exact paired t-test power calculation.','Exact one-sample t-test power calculation.','Approximate nonparametric power using ARE = 0.955 relative to the corresponding t-test under normal data.','Normal approximation for two independent proportions.','Approximate power for two independent proportions.','Approximation for one proportion against null p = 0.50.','Approximate power for one proportion against null p = 0.50.','Fisher z approximation for Pearson correlation.',"Chi-square test using Cohen's w and noncentral chi-square distribution."],
'ko':['독립 두 표본 t 검정의 정확 검정력 계산입니다.','대응표본 t 검정의 정확 검정력 계산입니다.','일표본 t 검정의 정확 검정력 계산입니다.','정규 자료에서 대응하는 t 검정 대비 ARE = 0.955를 적용하여 비모수 검정력을 근사합니다.','독립 두 비율에 대한 정규근사입니다.','독립 두 비율의 검정력을 근사합니다.','영가설 p = 0.50에 대한 단일 비율의 근사입니다.','영가설 p = 0.50에 대한 단일 비율의 검정력을 근사합니다.','Pearson 상관에 대한 Fisher z 근사입니다.','Cohen의 w와 비중심 카이제곱 분포를 사용하는 카이제곱 검정입니다.'],
'ja':['独立2標本t検定の正確な検出力計算です。','対応のあるt検定の正確な検出力計算です。','1標本t検定の正確な検出力計算です。','正規データで対応するt検定に対してARE = 0.955を適用し、ノンパラメトリック検定の検出力を近似します。','独立した二つの比率の正規近似です。','独立した二つの比率の検出力を近似します。','帰無仮説p = 0.50に対する単一比率の近似です。','帰無仮説p = 0.50に対する単一比率の検出力を近似します。','Pearson相関に対するFisher z近似です。','Cohenのwと非心カイ二乗分布を用いたカイ二乗検定です。'],
'zh':['精确计算独立两样本t检验的功效。','精确计算配对t检验的功效。','精确计算单样本t检验的功效。','在正态数据下，相对于对应t检验使用ARE = 0.955近似计算非参数检验功效。','独立两个比例的正态近似。','近似计算独立两个比例的检验功效。','针对零假设p = 0.50的单个比例近似。','针对零假设p = 0.50近似计算单个比例的检验功效。','Pearson相关的Fisher z近似。','使用Cohen w和非中心卡方分布的卡方检验。'],
'es':['Cálculo exacto de potencia de la prueba t de dos muestras independientes.','Cálculo exacto de potencia de la prueba t pareada.','Cálculo exacto de potencia de la prueba t de una muestra.','Potencia no paramétrica aproximada con ARE = 0.955 respecto a la prueba t correspondiente bajo datos normales.','Aproximación normal para dos proporciones independientes.','Potencia aproximada para dos proporciones independientes.','Aproximación para una proporción frente a la hipótesis nula p = 0.50.','Potencia aproximada para una proporción frente a la hipótesis nula p = 0.50.','Aproximación z de Fisher para la correlación de Pearson.','Prueba chi-cuadrado con w de Cohen y la distribución chi-cuadrado no central.'],
'fr':['Calcul exact de la puissance du test t à deux échantillons indépendants.','Calcul exact de la puissance du test t apparié.','Calcul exact de la puissance du test t à un échantillon.','Puissance non paramétrique approchée avec ARE = 0.955 par rapport au test t correspondant pour des données normales.','Approximation normale pour deux proportions indépendantes.','Puissance approchée pour deux proportions indépendantes.','Approximation pour une proportion sous l’hypothèse nulle p = 0.50.','Puissance approchée pour une proportion sous l’hypothèse nulle p = 0.50.','Approximation z de Fisher pour la corrélation de Pearson.','Test du chi carré avec le w de Cohen et la loi du chi carré non centrale.'],
'de':['Exakte Powerberechnung für den unabhängigen Zweistichproben-t-Test.','Exakte Powerberechnung für den gepaarten t-Test.','Exakte Powerberechnung für den Einstichproben-t-Test.','Approximierte nichtparametrische Power mit ARE = 0.955 relativ zum entsprechenden t-Test bei normalverteilten Daten.','Normalapproximation für zwei unabhängige Anteile.','Approximierte Power für zwei unabhängige Anteile.','Approximation für einen Anteil gegen die Nullhypothese p = 0.50.','Approximierte Power für einen Anteil gegen die Nullhypothese p = 0.50.','Fisher-z-Approximation für die Pearson-Korrelation.','Chi-Quadrat-Test mit Cohens w und der nichtzentralen Chi-Quadrat-Verteilung.'],
'vi':['Tính công suất chính xác cho kiểm định t hai mẫu độc lập.','Tính công suất chính xác cho kiểm định t ghép cặp.','Tính công suất chính xác cho kiểm định t một mẫu.','Công suất phi tham số xấp xỉ sử dụng ARE = 0.955 so với kiểm định t tương ứng khi dữ liệu có phân phối chuẩn.','Xấp xỉ chuẩn cho hai tỷ lệ độc lập.','Công suất xấp xỉ cho hai tỷ lệ độc lập.','Xấp xỉ cho một tỷ lệ so với giả thuyết không p = 0.50.','Công suất xấp xỉ cho một tỷ lệ so với giả thuyết không p = 0.50.','Xấp xỉ z của Fisher cho tương quan Pearson.','Kiểm định chi bình phương sử dụng w của Cohen và phân phối chi bình phương phi trung tâm.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
