import json
from pathlib import Path
keys = ['r_range','r_sample','r_controls','r_df','r_z','r_t','r_type','r_assumption']
rows = {
'en':['The correlation must be strictly between -1 and 1.','Sample size must be an integer of at least 4.','The number of controls must be a non-negative integer.','Sample size must exceed the number of controls by more than 3.',"Enter a finite Fisher's z and an SE greater than zero.",'Enter a finite correlation t statistic.','Unsupported correlation input type.','Partial correlations should be pooled only when adjustment sets are substantively comparable.'],
'ko':['상관계수는 -1보다 크고 1보다 작아야 합니다.','표본수는 4 이상의 정수여야 합니다.','통제변수 수는 0 이상의 정수여야 합니다.','표본수는 통제변수 수보다 3을 초과하여 커야 합니다.',"유한한 Fisher's z와 0보다 큰 SE를 입력하세요.",'유한한 상관계수 검정 t 통계량을 입력하세요.','지원하지 않는 상관계수 입력 유형입니다.','부분상관계수는 통제변수 구성이 실질적으로 비교 가능한 경우에만 통합해야 합니다.'],
'ja':['相関係数は-1より大きく1より小さい必要があります。','標本サイズは4以上の整数である必要があります。','統制変数の数は0以上の整数である必要があります。','標本サイズと統制変数の数の差は3より大きい必要があります。',"有限のFisher's zと0より大きいSEを入力してください。",'有限の相関検定のt統計量を入力してください。','サポートされていない相関係数の入力タイプです。','偏相関係数は、調整に用いる変数の構成が実質的に比較可能な場合にのみ統合してください。'],
'zh':['相关系数必须大于 -1 且小于 1。','样本量必须是至少为 4 的整数。','控制变量数必须是非负整数。','样本量与控制变量数之差必须大于 3。',"请输入有限的 Fisher's z 和大于零的 SE。",'请输入有限的相关检验 t 统计量。','不支持的相关系数输入类型。','仅在调整变量集合具有实质可比性时，才应合并偏相关系数。'],
'es':['La correlación debe ser estrictamente mayor que -1 y menor que 1.','El tamaño muestral debe ser un entero de al menos 4.','El número de variables de control debe ser un entero no negativo.','El tamaño muestral debe superar el número de variables de control en más de 3.',"Introduzca una z de Fisher finita y un EE mayor que cero.",'Introduzca un estadístico t de correlación finito.','Tipo de entrada de correlación no compatible.','Las correlaciones parciales solo deben combinarse cuando los conjuntos de variables de ajuste sean sustantivamente comparables.'],
'fr':['La corrélation doit être strictement comprise entre -1 et 1.','La taille de l’échantillon doit être un entier d’au moins 4.','Le nombre de variables de contrôle doit être un entier non négatif.','La taille de l’échantillon doit dépasser le nombre de variables de contrôle de plus de 3.',"Saisissez un z de Fisher fini et une erreur-type supérieure à zéro.",'Saisissez une statistique t de corrélation finie.','Type de saisie de corrélation non pris en charge.','Les corrélations partielles ne doivent être combinées que si les ensembles de variables d’ajustement sont comparables sur le fond.'],
'de':['Die Korrelation muss strikt zwischen -1 und 1 liegen.','Die Stichprobengröße muss eine ganze Zahl von mindestens 4 sein.','Die Anzahl der Kontrollvariablen muss eine nichtnegative ganze Zahl sein.','Die Stichprobengröße muss die Anzahl der Kontrollvariablen um mehr als 3 übersteigen.',"Geben Sie ein endliches Fisher-z und einen SE größer als null ein.",'Geben Sie eine endliche t-Statistik für die Korrelation ein.','Nicht unterstützter Eingabetyp für Korrelationen.','Partielle Korrelationen sollten nur zusammengefasst werden, wenn die zur Adjustierung verwendeten Variablensätze inhaltlich vergleichbar sind.'],
'vi':['Hệ số tương quan phải lớn hơn -1 và nhỏ hơn 1.','Cỡ mẫu phải là số nguyên ít nhất bằng 4.','Số biến kiểm soát phải là số nguyên không âm.','Cỡ mẫu phải lớn hơn số biến kiểm soát trên 3 đơn vị.',"Nhập Fisher's z hữu hạn và SE lớn hơn 0.",'Nhập thống kê t kiểm định tương quan hữu hạn.','Không hỗ trợ kiểu đầu vào tương quan này.','Chỉ nên gộp các hệ số tương quan riêng phần khi các tập biến điều chỉnh có thể so sánh về mặt nội dung.'],
}
for lang, values in rows.items():
    path = Path('i18n') / (lang + '.json')
    obj = json.loads(path.read_text(encoding='utf-8'))
    obj['translations'].update({'meta.input_error.' + k: v for k, v in zip(keys, values)})
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
