import json,re
from pathlib import Path
rows='''No standard candidate|標準候補なし|无标准候选方法|Sin candidato estándar|Aucun candidat standard|Kein Standardkandidat|Không có ứng viên tiêu chuẩn
Specification required|指定が必要|需要指定|Se requiere especificación|Spécification requise|Spezifikation erforderlich|Cần đặc tả
No single current engine|対応する単一エンジンなし|当前无单一适用引擎|Ningún motor único disponible|Aucun moteur unique disponible|Keine einzelne geeignete Engine verfügbar|Hiện không có một bộ máy ước lượng phù hợp
Primary|優先候補|首选|Principal|Principal|Primär|Ưu tiên
Alternative|代替候補|备选|Alternativa|Alternative|Alternative|Thay thế
Review|要確認|需检查|Revisar|À examiner|Prüfung erforderlich|Cần xem xét
Blocked|実行不可|无法执行|Bloqueado|Bloqué|Blockiert|Không thể chạy
Nominal indicators require a different measurement model.|名義尺度の指標には別の測定モデルが必要です。|名义指标需要不同的测量模型。|Los indicadores nominales requieren otro modelo de medida.|Les indicateurs nominaux nécessitent un autre modèle de mesure.|Nominale Indikatoren erfordern ein anderes Messmodell.|Các chỉ báo định danh cần mô hình đo lường khác.
Specify every construct as a common factor or composite before selecting an estimator.|推定法を選ぶ前に各構成概念を共通因子または合成変数として指定してください。|选择估计方法前，请将每个构念指定为公共因子或复合变量。|Especifique cada constructo como factor común o compuesto antes de elegir un estimador.|Spécifiez chaque construit comme facteur commun ou composite avant de choisir un estimateur.|Definieren Sie jedes Konstrukt als gemeinsamen Faktor oder Komposit, bevor Sie ein Schätzverfahren wählen.|Hãy chỉ định từng khái niệm là nhân tố chung hoặc biến tổng hợp trước khi chọn phương pháp ước lượng.
The method is not inferred from sample size, nonnormality, or empirical fit.|標本サイズ、非正規性、経験的適合度だけで手法は決まりません。|不能仅凭样本量、非正态性或经验拟合度确定方法。|El método no se deduce del tamaño muestral, la no normalidad ni el ajuste empírico.|La méthode n’est pas déduite de la taille d’échantillon, de la non-normalité ou de l’ajustement empirique.|Die Methode wird nicht aus Stichprobengröße, Nichtnormalität oder empirischem Fit abgeleitet.|Không suy ra phương pháp từ cỡ mẫu, tính phi chuẩn hoặc độ phù hợp thực nghiệm.
The model combines ordered indicators with composite constructs.|モデルには順序尺度指標と合成変数の構成概念が混在しています。|模型同时包含有序指标和复合构念。|El modelo combina indicadores ordinales y constructos compuestos.|Le modèle combine des indicateurs ordinaux et des construits composites.|Das Modell kombiniert ordinale Indikatoren mit Kompositkonstrukten.|Mô hình kết hợp chỉ báo thứ bậc với khái niệm tổng hợp.
Current WLSMV handles common factors; the current PLS engine does not provide an ordinal composite estimator.|現在のWLSMVは共通因子を扱います。現在のPLSエンジンには順序尺度の合成変数推定法がありません。|当前WLSMV处理公共因子；当前PLS引擎不提供有序复合变量估计方法。|WLSMV trata factores comunes; el motor PLS actual no ofrece un estimador de compuestos ordinales.|WLSMV traite les facteurs communs ; le moteur PLS actuel ne fournit pas d’estimateur de composites ordinaux.|WLSMV verarbeitet gemeinsame Faktoren; die aktuelle PLS-Engine bietet keinen Schätzer für ordinale Komposite.|WLSMV hiện xử lý nhân tố chung; bộ máy PLS hiện không cung cấp ước lượng biến tổng hợp thứ bậc.
Mixed factor-composite model: standard PLS treats the common-factor blocks as composites; do not claim construct-specific consistency correction unless the engine supports it.|因子と合成変数の混合モデルでは、標準PLSは共通因子ブロックも合成変数として扱います。エンジンが対応しない限り、構成概念ごとの一致性補正を主張しないでください。|在因子与复合变量混合模型中，标准PLS将公共因子块视为复合变量；除非引擎支持，否则不能声称进行了构念特定的一致性校正。|En un modelo mixto de factores y compuestos, PLS estándar trata los bloques de factores comunes como compuestos; no afirme una corrección de consistencia específica por constructo si el motor no la admite.|Dans un modèle mixte facteurs-composites, PLS standard traite les blocs de facteurs communs comme des composites ; ne revendiquez pas de correction de consistance propre à chaque construit si le moteur ne la prend pas en charge.|Im gemischten Faktor-Komposit-Modell behandelt Standard-PLS gemeinsame Faktorblöcke als Komposite; behaupten Sie keine konstruktspezifische Konsistenzkorrektur ohne Unterstützung der Engine.|Trong mô hình hỗn hợp nhân tố và biến tổng hợp, PLS chuẩn xem các khối nhân tố chung là biến tổng hợp; không khẳng định có hiệu chỉnh tính nhất quán riêng cho từng khái niệm nếu bộ máy không hỗ trợ.
Evaluate weights, collinearity, and redundancy/convergent validity for formative composites.|形成的合成変数の重み、共線性、冗長性・収束的妥当性を評価してください。|评估形成性复合变量的权重、共线性及冗余/收敛效度。|Evalúe pesos, colinealidad y validez de redundancia/convergente de los compuestos formativos.|Évaluez les poids, la colinéarité et la validité de redondance/convergente des composites formatifs.|Prüfen Sie Gewichte, Kollinearität und Redundanz-/Konvergenzvalidität formativer Komposite.|Đánh giá trọng số, cộng tuyến và tính giá trị dư thừa/hội tụ của biến tổng hợp tạo thành.
All constructs are reflective common factors and the objective is confirmatory or explanatory.|すべての構成概念は反映的共通因子で、目的は確認または説明です。|所有构念均为反映性公共因子，分析目的为验证或解释。|Todos los constructos son factores comunes reflectivos y el objetivo es confirmatorio o explicativo.|Tous les construits sont des facteurs communs réflexifs et l’objectif est confirmatoire ou explicatif.|Alle Konstrukte sind reflektive gemeinsame Faktoren; das Ziel ist konfirmatorisch oder erklärend.|Tất cả khái niệm là nhân tố chung phản ánh và mục tiêu là khẳng định hoặc giải thích.
Choose ML/MLR/WLSMV from indicator scale and estimator assumptions.|指標の尺度と推定法の仮定に基づきML/MLR/WLSMVを選んでください。|根据指标尺度和估计假设选择ML/MLR/WLSMV。|Elija ML/MLR/WLSMV según la escala de los indicadores y los supuestos del estimador.|Choisissez ML/MLR/WLSMV selon l’échelle des indicateurs et les hypothèses de l’estimateur.|Wählen Sie ML/MLR/WLSMV anhand des Skalenniveaus und der Schätzannahmen.|Chọn ML/MLR/WLSMV theo thang đo chỉ báo và giả định của phương pháp ước lượng.
A consistent PLS factor-estimation workflow may be used when substantively required.|実質的な必要がある場合、一致性補正PLSの因子推定手順を利用できます。|有实质需要时，可使用一致性PLS因子估计流程。|Puede utilizarse una estimación factorial PLS consistente cuando exista una necesidad sustantiva.|Une procédure d’estimation factorielle PLS consistante peut être utilisée si elle est justifiée sur le fond.|Bei inhaltlichem Bedarf kann eine konsistente PLS-Faktorschätzung verwendet werden.|Có thể dùng quy trình ước lượng nhân tố PLS nhất quán khi có nhu cầu thực chất.
Do not choose it solely because empirical fit is better.|経験的適合度が良いという理由だけで選ばないでください。|不要仅因经验拟合度更好而选择。|No lo elija solo porque el ajuste empírico sea mejor.|Ne le choisissez pas uniquement pour un meilleur ajustement empirique.|Wählen Sie es nicht allein wegen eines besseren empirischen Fits.|Không chọn chỉ vì độ phù hợp thực nghiệm tốt hơn.
All constructs are reflective common factors and a PLS-based prediction/score workflow was requested.|すべての構成概念は反映的共通因子で、PLSによる予測・得点利用が目的です。|所有构念均为反映性公共因子，并要求使用基于PLS的预测/评分流程。|Todos los constructos son factores comunes reflectivos y se solicitó un procedimiento de predicción/puntuación basado en PLS.|Tous les construits sont des facteurs communs réflexifs et une procédure de prédiction/scores fondée sur PLS a été demandée.|Alle Konstrukte sind reflektive gemeinsame Faktoren; ein PLS-basierter Vorhersage-/Score-Ablauf wurde angefordert.|Tất cả khái niệm là nhân tố chung phản ánh và đã yêu cầu quy trình dự đoán/tính điểm dựa trên PLS.
Verify that the selected PLSc implementation supports every structural feature.|選択したPLSc実装がすべての構造的機能をサポートするか確認してください。|请确认所选PLSc实现支持所有结构特征。|Verifique que la implementación PLSc elegida admita todas las características estructurales.|Vérifiez que l’implémentation PLSc choisie prend en charge toutes les caractéristiques structurelles.|Prüfen Sie, ob die gewählte PLSc-Implementierung alle Strukturmerkmale unterstützt.|Kiểm tra việc triển khai PLSc đã chọn có hỗ trợ mọi đặc điểm cấu trúc.
Retains covariance-based common-factor estimation and confirmatory global-fit assessment.|共分散に基づく共通因子推定と確認的な全体適合度評価を維持します。|保留基于协方差的公共因子估计和验证性整体拟合评估。|Conserva la estimación de factores comunes basada en covarianzas y la evaluación confirmatoria del ajuste global.|Conserve l’estimation des facteurs communs fondée sur les covariances et l’évaluation confirmatoire de l’ajustement global.|Behält kovarianzbasierte Faktorschätzung und konfirmatorische globale Fitbewertung bei.|Duy trì ước lượng nhân tố chung dựa trên hiệp phương sai và đánh giá độ phù hợp tổng thể mang tính khẳng định.
Prediction and score use require separate validation.|予測と得点利用には別途検証が必要です。|预测和评分使用需要单独验证。|La predicción y el uso de puntuaciones requieren validación independiente.|La prédiction et l’utilisation des scores nécessitent une validation distincte.|Vorhersage und Score-Nutzung erfordern eine gesonderte Validierung.|Dự đoán và sử dụng điểm số cần được kiểm định riêng.
Common-factor constructs use ordered indicators.|共通因子の構成概念に順序尺度指標が使われています。|公共因子构念使用有序指标。|Los constructos de factores comunes utilizan indicadores ordinales.|Les construits à facteurs communs utilisent des indicateurs ordinaux.|Gemeinsame Faktorkonstrukte verwenden ordinale Indikatoren.|Các khái niệm nhân tố chung sử dụng chỉ báo thứ bậc.
Use thresholds and an ordinal identification/invariance workflow.|閾値と順序尺度用の識別・不変性手順を使用してください。|使用阈值及有序变量的识别/不变性流程。|Utilice umbrales y un procedimiento de identificación/invariancia ordinal.|Utilisez des seuils et une procédure d’identification/invariance ordinale.|Verwenden Sie Schwellenwerte und einen ordinalen Identifikations-/Invarianzablauf.|Sử dụng ngưỡng và quy trình nhận dạng/bất biến cho dữ liệu thứ bậc.
The model contains both common-factor and composite specifications.|モデルには共通因子と合成変数の両方が指定されています。|模型同时包含公共因子和复合变量设定。|El modelo incluye especificaciones de factores comunes y compuestos.|Le modèle contient des spécifications de facteurs communs et de composites.|Das Modell enthält gemeinsame Faktoren und Kompositspezifikationen.|Mô hình chứa cả đặc tả nhân tố chung và biến tổng hợp.
The model contains composite constructs.|モデルには合成変数の構成概念が含まれます。|模型包含复合构念。|El modelo contiene constructos compuestos.|Le modèle contient des construits composites.|Das Modell enthält Kompositkonstrukte.|Mô hình chứa các khái niệm tổng hợp.
Method guidance: |推定法の案内：|方法指导：|Orientación metodológica: |Conseils méthodologiques : |Methodenhinweise: |Hướng dẫn phương pháp: 
Review construct specification or engine compatibility first.|まず構成概念の指定またはエンジンの互換性を確認してください。|请先检查构念设定或引擎兼容性。|Revise primero la especificación de los constructos o la compatibilidad del motor.|Examinez d’abord la spécification des construits ou la compatibilité du moteur.|Prüfen Sie zuerst Konstruktspezifikation oder Engine-Kompatibilität.|Trước tiên hãy xem xét đặc tả khái niệm hoặc khả năng tương thích của bộ máy.
The current selection matches the primary candidate: %s|現在の選択は優先候補と一致しています：%s|当前选择与首选候选方法一致：%s|La selección actual coincide con el candidato principal: %s|La sélection actuelle correspond au candidat principal : %s|Die aktuelle Auswahl entspricht dem primären Kandidaten: %s|Lựa chọn hiện tại khớp với ứng viên ưu tiên: %s
Primary candidate: %s. Current selection: %s.|優先候補：%s。現在の選択：%s。|首选候选方法：%s。当前选择：%s。|Candidato principal: %s. Selección actual: %s.|Candidat principal : %s. Sélection actuelle : %s.|Primärer Kandidat: %s. Aktuelle Auswahl: %s.|Ứng viên ưu tiên: %s. Lựa chọn hiện tại: %s.
Show rationale and alternatives|根拠と代替案を表示|显示理由与备选方案|Mostrar razones y alternativas|Afficher les raisons et les alternatives|Begründung und Alternativen anzeigen|Hiển thị cơ sở và phương án thay thế
Small samples, nonnormality, or better empirical fit alone do not select PLS/PLSc. The user retains the final choice, which is stored in the analysis record.|小標本、非正規性、経験的適合度の良さだけでPLS/PLScを選びません。最終選択はユーザーが行い、分析記録に保存されます。|不会仅凭小样本、非正态性或更好的经验拟合度选择PLS/PLSc。最终由用户选择，并保存在分析记录中。|Una muestra pequeña, la no normalidad o un mejor ajuste empírico no bastan para elegir PLS/PLSc. El usuario conserva la decisión final, que se guarda en el registro del análisis.|Un petit échantillon, la non-normalité ou un meilleur ajustement empirique ne suffisent pas à choisir PLS/PLSc. Le choix final revient à l’utilisateur et est conservé dans le dossier d’analyse.|Kleine Stichproben, Nichtnormalität oder besserer empirischer Fit allein bestimmen nicht die Wahl von PLS/PLSc. Die endgültige Wahl trifft der Benutzer; sie wird im Analyseprotokoll gespeichert.|Cỡ mẫu nhỏ, tính phi chuẩn hoặc độ phù hợp thực nghiệm tốt hơn không đủ để chọn PLS/PLSc. Người dùng quyết định cuối cùng và lựa chọn được lưu trong hồ sơ phân tích.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('|');assert len(f)==7
  assert f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
