"""Exact and approximate t/rank planning method notes."""
import json
from pathlib import Path
keys = ['note_plan_t_two','note_plan_t_paired','note_plan_t_one','note_plan_t_unequal_n','note_plan_t_unequal_power','note_plan_rank_are']
rows = {
'en': ["Exact independent two-sample t-test power calculation using Cohen's d.", 'Exact paired t-test power calculation using dz, the standardized mean of paired differences.', 'Exact one-sample t-test power calculation using standardized mean difference.', "Normal approximation for unequal-allocation independent means using Cohen's d.", 'Approximate power for unequal-allocation independent means based on the normal distribution.', 'Approximate nonparametric sample size using ARE = 0.955 relative to the corresponding t-test under normal data.'],
'ko': ['Cohen의 d를 사용하는 독립 두 표본 t 검정의 정확 검정력 계산입니다.', '대응 차이의 표준화 평균인 dz를 사용하는 대응표본 t 검정의 정확 검정력 계산입니다.', '표준화 평균차를 사용하는 일표본 t 검정의 정확 검정력 계산입니다.', 'Cohen의 d를 사용하여 불균등 배정 독립집단 평균을 정규근사합니다.', '정규분포에 근거하여 불균등 배정 독립집단 평균의 검정력을 근사합니다.', '정규 자료에서 대응하는 t 검정 대비 ARE = 0.955를 적용하여 비모수 표본수를 근사합니다.'],
'ja': ['Cohenのdを用いた独立2標本t検定の正確な検出力計算です。', '対応差の標準化平均dzを用いた対応のあるt検定の正確な検出力計算です。', '標準化平均差を用いた1標本t検定の正確な検出力計算です。', 'Cohenのdを用いて不均等割付の独立群平均を正規近似します。', '正規分布に基づいて不均等割付の独立群平均の検出力を近似します。', '正規データで対応するt検定に対してARE = 0.955を適用し、ノンパラメトリック検定の標本サイズを近似します。'],
'zh': ['使用Cohen d精确计算独立两样本t检验的功效。', '使用配对差值的标准化均值dz精确计算配对t检验的功效。', '使用标准化均值差精确计算单样本t检验的功效。', '使用Cohen d对不等分配的独立组均值进行正态近似。', '基于正态分布近似计算不等分配的独立组均值检验功效。', '在正态数据下，相对于对应t检验使用ARE = 0.955近似计算非参数样本量。'],
'es': ['Cálculo exacto de potencia de la prueba t de dos muestras independientes con d de Cohen.', 'Cálculo exacto de potencia de la prueba t pareada con dz, la media estandarizada de las diferencias pareadas.', 'Cálculo exacto de potencia de la prueba t de una muestra con la diferencia de medias estandarizada.', 'Aproximación normal para medias independientes con asignación desigual usando d de Cohen.', 'Potencia aproximada para medias independientes con asignación desigual basada en la distribución normal.', 'Tamaño muestral no paramétrico aproximado con ARE = 0.955 respecto a la prueba t correspondiente bajo datos normales.'],
'fr': ['Calcul exact de la puissance du test t à deux échantillons indépendants avec le d de Cohen.', 'Calcul exact de la puissance du test t apparié avec dz, la moyenne standardisée des différences appariées.', 'Calcul exact de la puissance du test t à un échantillon avec la différence moyenne standardisée.', 'Approximation normale pour des moyennes indépendantes à allocation inégale avec le d de Cohen.', 'Puissance approchée pour des moyennes indépendantes à allocation inégale fondée sur la loi normale.', 'Taille d’échantillon non paramétrique approchée avec ARE = 0.955 par rapport au test t correspondant pour des données normales.'],
'de': ['Exakte Powerberechnung für den unabhängigen Zweistichproben-t-Test mit Cohens d.', 'Exakte Powerberechnung für den gepaarten t-Test mit dz, dem standardisierten Mittelwert der gepaarten Differenzen.', 'Exakte Powerberechnung für den Einstichproben-t-Test mit standardisierter Mittelwertdifferenz.', 'Normalapproximation für unabhängige Mittelwerte bei ungleicher Zuteilung mit Cohens d.', 'Approximierte Power für unabhängige Mittelwerte bei ungleicher Zuteilung auf Basis der Normalverteilung.', 'Approximierter nichtparametrischer Stichprobenumfang mit ARE = 0.955 relativ zum entsprechenden t-Test bei normalverteilten Daten.'],
'vi': ['Tính công suất chính xác cho kiểm định t hai mẫu độc lập bằng d của Cohen.', 'Tính công suất chính xác cho kiểm định t ghép cặp bằng dz, trung bình chuẩn hóa của các chênh lệch ghép cặp.', 'Tính công suất chính xác cho kiểm định t một mẫu bằng chênh lệch trung bình chuẩn hóa.', 'Xấp xỉ chuẩn cho các trung bình độc lập với phân bổ không đều bằng d của Cohen.', 'Công suất xấp xỉ cho các trung bình độc lập với phân bổ không đều dựa trên phân phối chuẩn.', 'Cỡ mẫu phi tham số xấp xỉ sử dụng ARE = 0.955 so với kiểm định t tương ứng khi dữ liệu có phân phối chuẩn.']
}
for lang, values in rows.items():
    assert len(values)==len(keys)
    path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
    data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
    path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
