import json,re
from pathlib import Path
rows='''Fine-Gray relative score criterion = %s; tolerance = %s|Fine-Gray相対スコア基準 = %s; 許容値 = %s|Fine-Gray相对得分准则 = %s；容差 = %s|Criterio de puntuación relativa de Fine-Gray = %s; tolerancia = %s|Critère de score relatif de Fine-Gray = %s ; tolérance = %s|Relatives Fine-Gray-Score-Kriterium = %s; Toleranz = %s|Tiêu chí điểm số tương đối Fine-Gray = %s; dung sai = %s
Survival sparse evidence Fine-Gray information rank =|Fine-Gray情報行列のランク =|Fine-Gray信息矩阵秩 =|Rango de la matriz de información de Fine-Gray =|Rang de la matrice d’information de Fine-Gray =|Rang der Fine-Gray-Informationsmatrix =|Hạng ma trận thông tin Fine-Gray =
Survival sparse evidence Standardized Fine-Gray information condition number =|標準化Fine-Gray情報行列の条件数 =|标准化Fine-Gray信息矩阵条件数 =|Número de condición de la información estandarizada de Fine-Gray =|Nombre de condition de l’information standardisée de Fine-Gray =|Konditionszahl der standardisierten Fine-Gray-Informationsmatrix =|Số điều kiện của ma trận thông tin Fine-Gray chuẩn hóa =
The Fine-Gray covariance matrix is non-finite or has a non-positive diagonal.|Fine-Gray共分散行列が有限でないか、対角要素が正ではありません。|Fine-Gray协方差矩阵含非有限值或非正对角元素。|La matriz de covarianza de Fine-Gray no es finita o tiene una diagonal no positiva.|La matrice de covariance de Fine-Gray n’est pas finie ou présente une diagonale non positive.|Die Fine-Gray-Kovarianzmatrix ist nicht endlich oder hat nicht positive Diagonalelemente.|Ma trận hiệp phương sai Fine-Gray không hữu hạn hoặc có phần tử đường chéo không dương.
Do not report the estimates before reviewing the model and data because the optimizer score criterion was not met.|最適化のスコア基準を満たしていないため、モデルとデータを確認するまで推定値を報告しないでください。|由于未满足优化得分准则，请先检查模型和数据，再报告估计值。|No informe las estimaciones antes de revisar el modelo y los datos, ya que no se cumplió el criterio de puntuación del optimizador.|Ne présentez pas les estimations avant d’examiner le modèle et les données, car le critère de score de l’optimiseur n’a pas été atteint.|Berichten Sie die Schätzungen erst nach Prüfung von Modell und Daten, da das Score-Kriterium des Optimierers nicht erfüllt wurde.|Không báo cáo ước lượng trước khi xem xét mô hình và dữ liệu vì tiêu chí điểm số của bộ tối ưu chưa đạt.
Review information-matrix rank deficiency and model-identification problems.|情報行列のランク不足とモデル識別の問題を確認してください。|请检查信息矩阵秩亏和模型识别问题。|Revise la deficiencia de rango de la matriz de información y los problemas de identificación del modelo.|Examinez le défaut de rang de la matrice d’information et les problèmes d’identification du modèle.|Prüfen Sie Rangdefizienz der Informationsmatrix und Probleme der Modellidentifikation.|Kiểm tra thiếu hạng của ma trận thông tin và vấn đề nhận dạng mô hình.
Review standardized information-matrix instability and coefficient sensitivity.|標準化情報行列の不安定性と係数の感度を確認してください。|请检查标准化信息矩阵的不稳定性和系数敏感性。|Revise la inestabilidad de la matriz de información estandarizada y la sensibilidad de los coeficientes.|Examinez l’instabilité de la matrice d’information standardisée et la sensibilité des coefficients.|Prüfen Sie die Instabilität der standardisierten Informationsmatrix und die Empfindlichkeit der Koeffizienten.|Xem xét tính không ổn định của ma trận thông tin chuẩn hóa và độ nhạy của hệ số.
Do not report inferential results with a non-finite covariance matrix or non-positive standard errors.|共分散行列が有限でない場合や標準誤差が正でない場合は、推論結果を報告しないでください。|协方差矩阵含非有限值或标准误非正时，请勿报告推断结果。|No informe resultados inferenciales con una matriz de covarianza no finita o errores estándar no positivos.|Ne présentez pas de résultats inférentiels avec une matrice de covariance non finie ou des erreurs standards non positives.|Berichten Sie keine Inferenzresultate bei nicht endlicher Kovarianzmatrix oder nicht positiven Standardfehlern.|Không báo cáo kết quả suy luận khi ma trận hiệp phương sai không hữu hạn hoặc sai số chuẩn không dương.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
