import json
from pathlib import Path
keys=['reml_derivatives','lmm_inference','lmm_prediction','gee_prediction','model_weights','reml_options','unknown_model']
rows={
'en':['Nonfinite REML derivatives','Repeated LMM returned invalid coefficient inference.','Repeated LMM prediction intervals are not implemented.','Prediction standard errors are not implemented for adjusted GEE.','Model weights must be positive finite values with one value per analyzed row.','Repeated REML LMM supports one subject ID without observation weights, offsets, or additional random effects.','Unknown longitudinal model type.'],
'ko':['REML 도함수가 유한하지 않습니다.','반복측정 LMM의 계수 추론 결과가 유효하지 않습니다.','반복측정 LMM의 예측구간은 구현되지 않았습니다.','보정 GEE의 예측 표준오차는 구현되지 않았습니다.','모형 가중치는 분석 행마다 하나씩 있는 양의 유한값이어야 합니다.','반복측정 REML LMM은 대상자 ID 하나만 지원하며 관측치 가중치·오프셋·추가 랜덤효과는 지원하지 않습니다.','알 수 없는 종단 모형 유형입니다.'],
'ja':['REMLの導関数が有限ではありません。','反復測定LMMの係数推論結果が無効です。','反復測定LMMの予測区間は実装されていません。','補正GEEの予測標準誤差は実装されていません。','モデルの重みは分析行ごとに1つの正の有限値である必要があります。','反復測定REML LMMは1つの対象者IDのみをサポートし、観測重み、オフセット、追加のランダム効果には対応していません。','不明な縦断モデルの種類です。'],
'zh':['REML 导数不是有限值。','重复测量 LMM 返回了无效的系数推断结果。','尚未实现重复测量 LMM 的预测区间。','尚未实现校正 GEE 的预测标准误。','模型权重必须为正的有限值，且每个分析行对应一个权重。','重复测量 REML LMM 仅支持一个受试者 ID，不支持观测权重、偏置项或额外随机效应。','未知的纵向模型类型。'],
'es':['Las derivadas REML no son finitas.','LMM de medidas repetidas devolvió una inferencia de coeficientes no válida.','Los intervalos de predicción de LMM de medidas repetidas no están implementados.','Los errores estándar de predicción no están implementados para GEE ajustado.','Los pesos del modelo deben ser positivos y finitos, con un valor por fila analizada.','LMM REML de medidas repetidas admite un identificador de sujeto, sin pesos por observación, offsets ni efectos aleatorios adicionales.','Tipo de modelo longitudinal desconocido.'],
'fr':['Les dérivées REML ne sont pas finies.','Le LMM à mesures répétées a renvoyé une inférence de coefficients non valide.','Les intervalles de prédiction du LMM à mesures répétées ne sont pas implémentés.','Les erreurs standards de prédiction ne sont pas implémentées pour GEE ajusté.','Les poids du modèle doivent être positifs et finis, avec une valeur par ligne analysée.','Le LMM REML à mesures répétées prend en charge un seul identifiant de sujet, sans poids d’observation, offsets ni effets aléatoires supplémentaires.','Type de modèle longitudinal inconnu.'],
'de':['Die REML-Ableitungen sind nicht endlich.','LMM für Messwiederholungen lieferte ungültige Koeffizienteninferenz.','Vorhersageintervalle für LMM mit Messwiederholungen sind nicht implementiert.','Vorhersagestandardfehler sind für angepasstes GEE nicht implementiert.','Modellgewichte müssen positive, endliche Werte sein, mit einem Wert je analysierter Zeile.','REML-LMM für Messwiederholungen unterstützt eine Personen-ID ohne Beobachtungsgewichte, Offsets oder zusätzliche Zufallseffekte.','Unbekannter Längsschnittmodelltyp.'],
'vi':['Đạo hàm REML không hữu hạn.','LMM đo lặp trả về kết quả suy luận hệ số không hợp lệ.','Khoảng dự đoán cho LMM đo lặp chưa được triển khai.','Sai số chuẩn dự đoán cho GEE hiệu chỉnh chưa được triển khai.','Trọng số mô hình phải dương và hữu hạn, với một giá trị cho mỗi hàng phân tích.','LMM REML đo lặp hỗ trợ một ID đối tượng, không có trọng số quan sát, độ lệch offset hoặc hiệu ứng ngẫu nhiên bổ sung.','Loại mô hình dọc không xác định.']}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.execution_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
