import json
import re
from pathlib import Path
keys=['spline_robust','tv_covariate','tv_spline','tv_robust','tv_start','exact_start','exact_robust','exact_tv']
source=Path('R/analysis_survival.R').read_text(encoding='utf-8')
start=source.index('  if (nzchar(spline_covariate) && (nzchar(cluster) || nzchar(subject_id))) stop(')
end=source.index('  settings <- survival_legacy_settings',start)
english=re.findall(r'stop\("([^"]+)"\)',source[start:end])
assert len(english)==len(keys)
rows={
'en':english,
'ko':['생존분석 v1에서는 군집 강건 Cox 분산을 사용할 때 스플라인 비선형성 검정을 지원하지 않습니다. 부분우도 기반 스플라인 비교에는 군집을 지정하지 않은 모형을 사용하거나 별도의 강건 비선형 효과 분석을 사용하세요.','시간가변 계수 변수를 Cox 공변량에도 포함하세요.','생존분석 v1의 동일한 Cox 모형에 스플라인과 시간가변 계수 옵션을 함께 적용할 수 없습니다.','생존분석 v1에서는 시간가변 계수 Cox 모형에 군집 강건 분산을 사용할 수 없습니다.','생존분석 v1에서는 시작·종료 자료에 시간가변 계수 Cox 모형을 사용할 수 없습니다. 시작·종료 모듈은 시간에 따라 달라지는 공변량 값을 처리하기 위한 기능입니다.','생존분석 v1의 시작·종료 Cox 모형에서는 정확 부분우도를 사용할 수 없습니다.','생존분석 v1에서는 군집 강건 Cox 분산과 정확 부분우도를 함께 사용할 수 없습니다.','생존분석 v1에서는 시간가변 계수와 정확 부분우도를 함께 사용할 수 없습니다.'],
'ja':['生存分析v1では、クラスター頑健Cox分散によるスプライン非線形性検定は使用できません。部分尤度によるスプライン比較にはクラスターを指定しないモデル、または専用の頑健非線形効果分析を使用してください。','時間変動係数の変数をCox共変量にも含めてください。','生存分析v1の同じCoxモデルでスプラインと時間変動係数のオプションを併用することはできません。','生存分析v1では、時間変動係数Coxモデルにクラスター頑健分散を使用できません。','生存分析v1では、開始・終了データに時間変動係数Coxモデルは使用できません。開始・終了モジュールは時間依存の共変量値を扱うためのものです。','生存分析v1の開始・終了Coxモデルでは正確部分尤度を使用できません。','生存分析v1では、クラスター頑健Cox分散と正確部分尤度を併用できません。','生存分析v1では、時間変動係数と正確部分尤度を併用できません。'],
'zh':['生存分析 v1 不支持在使用聚类稳健 Cox 方差时进行样条非线性检验。请使用不指定聚类的模型进行基于偏似然的样条比较，或使用专门的稳健非线性效应分析。','时变系数变量也必须包含在 Cox 协变量中。','生存分析 v1 的同一 Cox 模型不能同时使用样条和时变系数选项。','生存分析 v1 不支持在时变系数 Cox 模型中使用聚类稳健方差。','生存分析 v1 不支持将时变系数 Cox 模型用于起止时间数据；起止时间模块用于处理随时间变化的协变量值。','生存分析 v1 的起止时间 Cox 模型不支持精确偏似然。','生存分析 v1 不支持同时使用精确偏似然和聚类稳健 Cox 方差。','生存分析 v1 不支持同时使用精确偏似然和时变系数。'],
'es':['En supervivencia v1, la prueba de no linealidad spline no admite varianza de Cox robusta por grupos. Use un modelo sin agrupación para comparar splines mediante verosimilitud parcial, o un análisis específico de efectos no lineales robustos.','La variable de coeficiente dependiente del tiempo también debe incluirse entre las covariables de Cox.','En supervivencia v1, un mismo modelo de Cox no puede combinar splines y coeficientes dependientes del tiempo.','En supervivencia v1, el modelo de Cox con coeficientes dependientes del tiempo no admite varianza robusta por grupos.','En supervivencia v1, el modelo de Cox con coeficientes dependientes del tiempo no admite datos de inicio y fin; ese módulo está reservado para valores de covariables dependientes del tiempo.','En supervivencia v1, los modelos de Cox con inicio y fin no admiten verosimilitud parcial exacta.','En supervivencia v1, la verosimilitud parcial exacta no admite varianza de Cox robusta por grupos.','En supervivencia v1, la verosimilitud parcial exacta no admite coeficientes dependientes del tiempo.'],
'fr':['Dans survie v1, le test de non-linéarité des splines ne permet pas une variance de Cox robuste par groupes. Utilisez un modèle sans regroupement pour comparer les splines par vraisemblance partielle, ou une analyse dédiée des effets non linéaires robustes.','La variable à coefficient variant dans le temps doit également figurer parmi les covariables de Cox.','Dans survie v1, un même modèle de Cox ne peut pas combiner splines et coefficients variant dans le temps.','Dans survie v1, le modèle de Cox à coefficients variant dans le temps ne permet pas une variance robuste par groupes.','Dans survie v1, le modèle de Cox à coefficients variant dans le temps ne permet pas les données début-fin ; ce module est réservé aux valeurs de covariables dépendantes du temps.','Dans survie v1, les modèles de Cox début-fin ne permettent pas la vraisemblance partielle exacte.','Dans survie v1, la vraisemblance partielle exacte ne permet pas une variance de Cox robuste par groupes.','Dans survie v1, la vraisemblance partielle exacte ne permet pas de coefficient variant dans le temps.'],
'de':['In Überlebensanalyse v1 ist der Spline-Nichtlinearitätstest mit clusterrobuster Cox-Varianz nicht verfügbar. Verwenden Sie für den Spline-Vergleich anhand der partiellen Likelihood ein Modell ohne Cluster oder eine spezielle robuste Analyse nichtlinearer Effekte.','Die Variable mit zeitvariablem Koeffizienten muss auch zu den Cox-Kovariaten gehören.','Im selben Cox-Modell von Überlebensanalyse v1 können Spline-Optionen und zeitvariable Koeffizienten nicht kombiniert werden.','In Überlebensanalyse v1 sind zeitvariable Cox-Koeffizienten mit clusterrobuster Varianz nicht verfügbar.','In Überlebensanalyse v1 sind zeitvariable Cox-Koeffizienten für Start-Stopp-Daten nicht verfügbar; das Start-Stopp-Modul ist für zeitabhängige Kovariatenwerte vorgesehen.','In Überlebensanalyse v1 ist die exakte partielle Likelihood für Start-Stopp-Cox-Modelle nicht verfügbar.','In Überlebensanalyse v1 ist die exakte partielle Likelihood mit clusterrobuster Cox-Varianz nicht verfügbar.','In Überlebensanalyse v1 ist die exakte partielle Likelihood mit zeitvariablem Koeffizienten nicht verfügbar.'],
'vi':['Trong phân tích sống còn v1, kiểm định tính phi tuyến spline không hỗ trợ phương sai Cox vững theo cụm. Hãy dùng mô hình không phân cụm để so sánh spline theo hợp lý riêng phần, hoặc phân tích chuyên biệt về hiệu ứng phi tuyến vững.','Biến có hệ số thay đổi theo thời gian cũng phải nằm trong các hiệp biến Cox.','Trong phân tích sống còn v1, không thể kết hợp spline và hệ số thay đổi theo thời gian trong cùng mô hình Cox.','Trong phân tích sống còn v1, mô hình Cox có hệ số thay đổi theo thời gian không hỗ trợ phương sai vững theo cụm.','Trong phân tích sống còn v1, mô hình Cox có hệ số thay đổi theo thời gian không hỗ trợ dữ liệu bắt đầu–kết thúc; mô-đun này dành cho giá trị hiệp biến phụ thuộc thời gian.','Trong phân tích sống còn v1, mô hình Cox bắt đầu–kết thúc không hỗ trợ hợp lý riêng phần chính xác.','Trong phân tích sống còn v1, hợp lý riêng phần chính xác không hỗ trợ phương sai Cox vững theo cụm.','Trong phân tích sống còn v1, hợp lý riêng phần chính xác không hỗ trợ hệ số thay đổi theo thời gian.'],
}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
