import json, re
from pathlib import Path

rows = '''Missing data and multivariate outliers|欠測データと多変量外れ値|缺失数据与多元异常值|Datos faltantes y valores atípicos multivariantes|Données manquantes et valeurs aberrantes multivariées|Fehlende Daten und multivariate Ausreißer|Dữ liệu thiếu và ngoại lệ đa biến
Variable-level missingness|変数別の欠測|各变量缺失情况|Datos faltantes por variable|Données manquantes par variable|Fehlende Werte je Variable|Dữ liệu thiếu theo biến
No missing indicator values were detected.|指標に欠測値はありません。|未发现指标缺失值。|No se detectaron valores faltantes en los indicadores.|Aucune valeur manquante dans les indicateurs.|Keine fehlenden Indikatorwerte gefunden.|Không phát hiện giá trị thiếu ở các chỉ báo.
Complete cases: {complete} of {n}; incomplete cases: {incomplete}; distinct missingness patterns: {patterns}.|完全ケース：{n}件中{complete}件、不完全ケース：{incomplete}件、欠測パターン数：{patterns}。|完整个案：{complete}/{n}；不完整个案：{incomplete}；不同缺失模式数：{patterns}。|Casos completos: {complete} de {n}; incompletos: {incomplete}; patrones de datos faltantes: {patterns}.|Cas complets : {complete} sur {n} ; incomplets : {incomplete} ; profils de données manquantes : {patterns}.|Vollständige Fälle: {complete} von {n}; unvollständige Fälle: {incomplete}; unterschiedliche Fehlwertmuster: {patterns}.|Trường hợp đầy đủ: {complete}/{n}; không đầy đủ: {incomplete}; số mẫu thiếu khác nhau: {patterns}.
Listwise deletion excludes {n} cases ({percent}%) with any missing indicator from model estimation. Examine differences between retained and excluded cases and the potential for selection bias.|リストワイズ削除により、指標に欠測のある{n}件（{percent}%）をモデル推定から除外します。採用・除外ケースの差と選択バイアスの可能性を検討してください。|整行删除将有任一指标缺失的{n}个个案（{percent}%）排除于模型估计之外。请检查保留与排除个案的差异及选择偏差的可能性。|La eliminación por lista excluye de la estimación {n} casos ({percent}%) con algún indicador faltante. Examine las diferencias entre casos retenidos y excluidos y el posible sesgo de selección.|La suppression par liste exclut de l’estimation {n} cas ({percent} %) ayant au moins un indicateur manquant. Examinez les différences entre cas conservés et exclus et le risque de biais de sélection.|Listenweiser Ausschluss entfernt {n} Fälle ({percent}%) mit mindestens einem fehlenden Indikator aus der Modellschätzung. Prüfen Sie Unterschiede zwischen einbezogenen und ausgeschlossenen Fällen sowie mögliche Selektionsverzerrungen.|Loại theo danh sách bỏ {n} trường hợp ({percent}%) có ít nhất một chỉ báo thiếu khỏi ước lượng mô hình. Xem xét khác biệt giữa trường hợp giữ lại và bị loại cùng nguy cơ sai lệch chọn mẫu.
Minimum indicator-pair available N = {n}. Because covariances can use different case sets, inspect imbalance in pairwise N and positive definiteness.|指標ペアの最小利用可能N = {n}。共分散ごとに異なるケースを使用するため、ペア別Nの不均衡と正定値性を確認してください。|指标对最小可用N = {n}。不同协方差可能使用不同个案集，请检查成对N的不均衡及正定性。|N mínimo disponible por par de indicadores = {n}. Las covarianzas pueden usar distintos conjuntos de casos; revise el desequilibrio de N por pares y la definitud positiva.|N minimal disponible par paire d’indicateurs = {n}. Les covariances peuvent reposer sur des cas différents ; vérifiez le déséquilibre des N par paire et le caractère défini positif.|Kleinstes verfügbares N je Indikatorpaar = {n}. Kovarianzen können auf unterschiedlichen Fällen beruhen; prüfen Sie ungleiche paarweise N und positive Definitheit.|N khả dụng nhỏ nhất theo cặp chỉ báo = {n}. Các hiệp phương sai có thể dùng tập trường hợp khác nhau; kiểm tra chênh lệch N theo cặp và tính xác định dương.
Missing-assumption sensitivity record|欠測仮定の感度分析記録|缺失假设敏感性记录|Registro de sensibilidad a supuestos de datos faltantes|Registre de sensibilité aux hypothèses de données manquantes|Sensitivitätsprotokoll zu Fehlwertannahmen|Ghi nhận độ nhạy với giả định dữ liệu thiếu
The MAR assumption underlying FIML is not verified by observed data alone. Assess and document whether key conclusions persist under plausible MNAR departures or alternative missing-data handling.|FIMLのMAR仮定は観測データだけでは検証できません。妥当なMNARへの逸脱や別の欠測処理でも主要な結論が維持されるかを評価し、記録してください。|仅凭观测数据无法验证FIML所依赖的MAR假设。请评估并记录在合理的MNAR偏离或其他缺失处理下主要结论是否保持。|El supuesto MAR de FIML no se verifica solo con los datos observados. Evalúe y documente si las conclusiones se mantienen ante desviaciones MNAR plausibles u otros tratamientos de datos faltantes.|L’hypothèse MAR de FIML ne se vérifie pas avec les seules données observées. Évaluez et documentez la stabilité des conclusions sous des écarts MNAR plausibles ou d’autres traitements des données manquantes.|Die MAR-Annahme von FIML lässt sich nicht allein anhand beobachteter Daten prüfen. Bewerten und dokumentieren Sie, ob Kernaussagen bei plausiblen MNAR-Abweichungen oder alternativer Fehlwertbehandlung bestehen bleiben.|Không thể xác minh giả định MAR của FIML chỉ từ dữ liệu quan sát. Đánh giá và ghi nhận kết luận chính có giữ vững khi có lệch MNAR hợp lý hoặc cách xử lý thiếu khác hay không.
Missingness patterns|欠測パターン|缺失模式|Patrones de datos faltantes|Profils de données manquantes|Fehlwertmuster|Mẫu dữ liệu thiếu
Ordered-indicator estimation uses {method} missing-data handling. Review sparse pairwise coverage alongside category frequencies.|順序指標の推定は欠測処理{method}を使用します。カテゴリ度数と併せてペアごとのデータ不足を確認してください。|有序指标估计使用{method}缺失处理。请结合类别频数检查成对覆盖的稀疏性。|La estimación de indicadores ordinales usa el tratamiento {method}. Revise la cobertura escasa por pares junto con las frecuencias de las categorías.|L’estimation des indicateurs ordinaux utilise le traitement {method}. Examinez la faible couverture par paire avec les fréquences des catégories.|Die Schätzung ordinaler Indikatoren nutzt die Fehlwertbehandlung {method}. Prüfen Sie geringe paarweise Abdeckung zusammen mit den Kategoriehäufigkeiten.|Ước lượng chỉ báo thứ bậc dùng cách xử lý thiếu {method}. Xem xét độ bao phủ thưa theo cặp cùng tần số các nhóm.
FIML uses all available observations under a missing-at-random (MAR) assumption conditional on variables in the model. MAR cannot be established from the observed data alone; report likely causes of missingness, use of auxiliary variables, and sensitivity analyses. The complete-case count above applies only to diagnostics such as Mardia and Mahalanobis distance.|FIMLはモデル内の変数を条件とするMAR（ランダムな欠測）仮定のもとで、利用可能な全観測を使用します。MARは観測データだけでは確定できないため、欠測原因、補助変数の使用、感度分析を報告してください。上記の完全ケース数はMardiaやMahalanobis距離などの診断のみに適用されます。|FIML在给定模型变量的随机缺失（MAR）假设下使用所有可用观测。仅凭观测数据无法确立MAR；请报告可能的缺失原因、辅助变量使用情况及敏感性分析。上述完整个案数仅适用于Mardia和Mahalanobis距离等诊断。|FIML utiliza todas las observaciones disponibles bajo el supuesto MAR condicionado a las variables del modelo. MAR no puede establecerse solo con los datos observados; informe las posibles causas de ausencia, las variables auxiliares y los análisis de sensibilidad. El número de casos completos anterior solo se aplica a diagnósticos como Mardia y la distancia de Mahalanobis.|FIML utilise toutes les observations disponibles sous l’hypothèse MAR conditionnelle aux variables du modèle. MAR ne peut être établi avec les seules données observées ; rapportez les causes probables des données manquantes, les variables auxiliaires et les analyses de sensibilité. Le nombre de cas complets ci-dessus concerne uniquement les diagnostics comme Mardia et la distance de Mahalanobis.|FIML nutzt alle verfügbaren Beobachtungen unter der MAR-Annahme, bedingt auf die Modellvariablen. MAR lässt sich nicht allein aus beobachteten Daten ableiten; berichten Sie wahrscheinliche Fehlwertursachen, Hilfsvariablen und Sensitivitätsanalysen. Die obige Zahl vollständiger Fälle gilt nur für Diagnosen wie Mardia und Mahalanobis-Distanz.|FIML dùng mọi quan sát khả dụng dưới giả định thiếu ngẫu nhiên MAR có điều kiện theo biến trong mô hình. Không thể xác lập MAR chỉ từ dữ liệu quan sát; cần báo cáo nguyên nhân thiếu, biến bổ trợ và phân tích độ nhạy. Số trường hợp đầy đủ ở trên chỉ áp dụng cho chẩn đoán như Mardia và khoảng cách Mahalanobis.
The fitted model used missing-data option: {method}.|適合モデルの欠測処理：{method}。|拟合模型使用的缺失处理：{method}。|Tratamiento de datos faltantes del modelo: {method}.|Traitement des données manquantes du modèle : {method}.|Fehlwertoption des angepassten Modells: {method}.|Tùy chọn xử lý thiếu của mô hình đã ước lượng: {method}.
Mahalanobis outlier candidates|Mahalanobis外れ値候補|Mahalanobis异常值候选|Candidatos a valores atípicos de Mahalanobis|Valeurs aberrantes potentielles selon Mahalanobis|Mahalanobis-Ausreißerkandidaten|Trường hợp nghi ngoại lệ Mahalanobis
Mahalanobis diagnostics are not reported for ordered indicators.|順序指標にはMahalanobis診断を報告しません。|不对有序指标报告Mahalanobis诊断。|No se presentan diagnósticos de Mahalanobis para indicadores ordinales.|Les diagnostics de Mahalanobis ne sont pas présentés pour les indicateurs ordinaux.|Für ordinale Indikatoren wird keine Mahalanobis-Diagnostik berichtet.|Không báo cáo chẩn đoán Mahalanobis cho chỉ báo thứ bậc.
No complete cases were flagged at p < {alpha}.|p < {alpha}で該当する完全ケースはありません。|在p < {alpha}下未标记完整个案。|No se marcaron casos completos con p < {alpha}.|Aucun cas complet signalé à p < {alpha}.|Keine vollständigen Fälle bei p < {alpha} markiert.|Không có trường hợp đầy đủ bị đánh dấu ở p < {alpha}.
{flagged} of {n} complete cases flagged at p < {alpha}.|完全ケース{n}件中{flagged}件をp < {alpha}で表示しました。|{n}个完整个案中有{flagged}个在p < {alpha}下被标记。|{flagged} de {n} casos completos marcados con p < {alpha}.|{flagged} cas complets sur {n} signalés à p < {alpha}.|{flagged} von {n} vollständigen Fällen bei p < {alpha} markiert.|{flagged}/{n} trường hợp đầy đủ bị đánh dấu ở p < {alpha}.
Mahalanobis candidates should be investigated for data errors, unusual but valid cases, and influence. They are not removed automatically; use robust estimation or a documented sensitivity analysis when appropriate.|Mahalanobis候補はデータ誤り、珍しくても有効なケース、影響力を調べてください。自動削除はしません。必要に応じてロバスト推定や記録を伴う感度分析を使用してください。|对Mahalanobis候选应检查数据错误、异常但有效的个案及影响力。不会自动删除；必要时使用稳健估计或有记录的敏感性分析。|Investigue los candidatos de Mahalanobis por errores de datos, casos inusuales pero válidos e influencia. No se eliminan automáticamente; use estimación robusta o un análisis de sensibilidad documentado cuando proceda.|Examinez les candidats de Mahalanobis pour détecter les erreurs, les cas inhabituels mais valides et leur influence. Ils ne sont pas supprimés automatiquement ; utilisez si nécessaire une estimation robuste ou une analyse de sensibilité documentée.|Prüfen Sie Mahalanobis-Kandidaten auf Datenfehler, ungewöhnliche, aber gültige Fälle und Einfluss. Sie werden nicht automatisch entfernt; nutzen Sie gegebenenfalls robuste Schätzung oder dokumentierte Sensitivitätsanalysen.|Cần kiểm tra lỗi dữ liệu, trường hợp khác thường nhưng hợp lệ và mức ảnh hưởng của các ứng viên Mahalanobis. Không tự động loại bỏ; dùng ước lượng vững hoặc phân tích độ nhạy có ghi nhận khi phù hợp.
At least two numeric continuous indicators are required.|数値の連続指標が2個以上必要です。|至少需要两个数值型连续指标。|Se requieren al menos dos indicadores numéricos continuos.|Au moins deux indicateurs numériques continus sont requis.|Mindestens zwei numerische kontinuierliche Indikatoren sind erforderlich.|Cần ít nhất hai chỉ báo số liên tục.
Too few complete cases for multivariate outlier diagnostics.|多変量外れ値診断には完全ケースが不足しています。|用于多元异常值诊断的完整个案过少。|Muy pocos casos completos para diagnosticar valores atípicos multivariantes.|Trop peu de cas complets pour le diagnostic des valeurs aberrantes multivariées.|Zu wenige vollständige Fälle für die multivariate Ausreißerdiagnostik.|Quá ít trường hợp đầy đủ để chẩn đoán ngoại lệ đa biến.
The complete-case covariance matrix is singular.|完全ケースの共分散行列が特異です。|完整个案协方差矩阵为奇异矩阵。|La matriz de covarianzas de casos completos es singular.|La matrice de covariance des cas complets est singulière.|Die Kovarianzmatrix der vollständigen Fälle ist singulär.|Ma trận hiệp phương sai của các trường hợp đầy đủ là ma trận suy biến.'''

rows += '''
Primary missing-data method|主な欠測処理|主要缺失处理方法|Método principal para datos faltantes|Méthode principale de traitement des données manquantes|Primäre Fehlwertmethode|Phương pháp xử lý thiếu chính
Sensitivity assessment|感度評価|敏感性评估|Evaluación de sensibilidad|Évaluation de sensibilité|Sensitivitätsbewertung|Đánh giá độ nhạy
Assumptions, results, and conclusion|仮定・結果・結論|假设、结果与结论|Supuestos, resultados y conclusión|Hypothèses, résultats et conclusion|Annahmen, Ergebnisse und Schlussfolgerung|Giả định, kết quả và kết luận
Not required - no incomplete indicator cases|不要：指標の不完全ケースなし|无需：无指标不完整个案|No requerida: no hay casos con indicadores incompletos|Non requise : aucun cas avec indicateurs incomplets|Nicht erforderlich: keine unvollständigen Indikatorfälle|Không cần: không có trường hợp thiếu chỉ báo
Documented|記録済み|已记录|Documentada|Documentée|Dokumentiert|Đã ghi nhận
Pattern|パターン|模式|Patrón|Profil|Muster|Mẫu
Description|説明|说明|Descripción|Description|Beschreibung|Mô tả
Missing|欠測|缺失|Faltantes|Manquantes|Fehlend|Thiếu
Complete|完全ケース|完整|Completo|Complet|Vollständig|Đầy đủ
Row|行|行|Fila|Ligne|Zeile|Dòng
Pairwise deletion|ペアワイズ除外|成对删除|Eliminación por pares|Suppression par paire|Paarweiser Ausschluss|Loại theo cặp
Not recorded|未記録|未记录|No registrado|Non consigné|Nicht dokumentiert|Chưa ghi nhận
FIML relies on MAR conditional on modeled variables. Document a sensitivity assessment and whether key conclusions change under plausible departures.|FIMLはモデル変数を条件とするMARに依存します。感度評価と、妥当な仮定の逸脱で主要な結論が変わるかを記録してください。|FIML依赖于给定模型变量的MAR假设。请记录敏感性评估，以及合理偏离下主要结论是否改变。|FIML depende de MAR condicionado a las variables modeladas. Documente una evaluación de sensibilidad y si las conclusiones cambian ante desviaciones plausibles.|FIML repose sur MAR conditionnel aux variables modélisées. Documentez une évaluation de sensibilité et les changements éventuels des conclusions sous des écarts plausibles.|FIML setzt MAR bedingt auf die Modellvariablen voraus. Dokumentieren Sie eine Sensitivitätsbewertung und ob sich Kernaussagen bei plausiblen Abweichungen ändern.|FIML dựa vào MAR có điều kiện theo biến mô hình. Ghi nhận đánh giá độ nhạy và kết luận chính có thay đổi khi có lệch hợp lý hay không.
Sensitivity records are user-supplied evidence and do not cause this engine to perform or validate the stated external analysis.|感度分析記録はユーザー提供の根拠です。このエンジンは記載された外部分析を実行・検証しません。|敏感性记录是用户提供的证据，本引擎不会执行或验证所述外部分析。|Los registros de sensibilidad son evidencia aportada por el usuario; el motor no ejecuta ni valida el análisis externo indicado.|Les registres de sensibilité sont fournis par l’utilisateur ; le moteur n’exécute ni ne valide l’analyse externe décrite.|Sensitivitätsprotokolle sind vom Benutzer bereitgestellte Nachweise; die Engine führt die angegebene externe Analyse weder aus noch validiert sie diese.|Ghi nhận độ nhạy là bằng chứng do người dùng cung cấp; bộ máy không thực hiện hoặc xác minh phân tích bên ngoài đã nêu.'''

rows += '''
PLS missing-data handling|PLSの欠測処理|PLS缺失数据处理|Tratamiento de datos faltantes en PLS|Traitement des données manquantes en PLS|PLS-Fehlwertbehandlung|Xử lý dữ liệu thiếu trong PLS
Missing-data diagnostics could not be computed for the model indicators.|モデル指標の欠測診断を計算できません。|无法计算模型指标的缺失诊断。|No se pudieron calcular los diagnósticos de datos faltantes para los indicadores del modelo.|Impossible de calculer les diagnostics des données manquantes pour les indicateurs du modèle.|Die Fehlwertdiagnostik für die Modellindikatoren konnte nicht berechnet werden.|Không thể tính chẩn đoán dữ liệu thiếu cho chỉ báo mô hình.
Indicator missingness and replacement values|指標別の欠測と代入値|指标缺失与替代值|Datos faltantes y valores de reemplazo por indicador|Données manquantes et valeurs de remplacement par indicateur|Fehlende Indikatorwerte und Ersatzwerte|Dữ liệu thiếu và giá trị thay thế theo chỉ báo
Replacement mean|代入平均値|替代均值|Media de reemplazo|Moyenne de remplacement|Ersatzmittelwert|Trung bình thay thế
Analysis N: {n}; complete cases: {complete}; rows receiving mean replacement: {rows}; replaced cells: {cells}/{total} ({percent}%).|分析N：{n}、完全ケース：{complete}件、平均代入した行：{rows}行、代入セル：{cells}/{total}（{percent}%）。|分析N：{n}；完整个案：{complete}；接受均值替代的行：{rows}；替代单元格：{cells}/{total}（{percent}%）。|N de análisis: {n}; casos completos: {complete}; filas con reemplazo por la media: {rows}; celdas reemplazadas: {cells}/{total} ({percent}%).|N analysé : {n} ; cas complets : {complete} ; lignes avec remplacement par la moyenne : {rows} ; cellules remplacées : {cells}/{total} ({percent} %).|Analyse-N: {n}; vollständige Fälle: {complete}; Zeilen mit Mittelwertersetzung: {rows}; ersetzte Zellen: {cells}/{total} ({percent}%).|N phân tích: {n}; trường hợp đầy đủ: {complete}; dòng được thay thế bằng trung bình: {rows}; ô được thay thế: {cells}/{total} ({percent}%).
Before each PLS/PLSc fit, every missing model-indicator cell is replaced by that indicator's arithmetic mean over the observed analysis cases.|各PLS/PLSc推定の前に、モデル指標の欠測セルを、その指標の観測された分析ケースの算術平均で代入します。|每次PLS/PLSc拟合前，将模型指标的每个缺失单元格替换为该指标在已观测分析个案中的算术平均值。|Antes de cada ajuste PLS/PLSc, cada celda faltante de un indicador se reemplaza por su media aritmética entre los casos observados del análisis.|Avant chaque ajustement PLS/PLSc, toute cellule manquante d’un indicateur est remplacée par sa moyenne arithmétique sur les cas observés de l’analyse.|Vor jeder PLS/PLSc-Schätzung wird jede fehlende Indikatorzelle durch den arithmetischen Mittelwert dieses Indikators über die beobachteten Analysefälle ersetzt.|Trước mỗi lần ước lượng PLS/PLSc, mỗi ô chỉ báo thiếu được thay bằng trung bình số học của chỉ báo đó trên các trường hợp phân tích đã quan sát.
Every case-resampled bootstrap data set recomputes the indicator means inside that resample before fitting the PLS/PLSc model.|ケース再標本化による各ブートストラップ標本内で指標平均を再計算してから、PLS/PLScモデルを推定します。|每个按个案重抽样的bootstrap数据集，均在该重抽样样本内重新计算指标均值，然后拟合PLS/PLSc模型。|Cada muestra bootstrap de casos recalcula las medias de los indicadores dentro de esa muestra antes de ajustar el modelo PLS/PLSc.|Chaque échantillon bootstrap de cas recalcule les moyennes des indicateurs dans cet échantillon avant d’ajuster le modèle PLS/PLSc.|In jedem Bootstrap-Datensatz mit fallweiser Wiederholungsziehung werden die Indikatormittelwerte innerhalb dieser Stichprobe vor der PLS/PLSc-Schätzung neu berechnet.|Mỗi bộ dữ liệu bootstrap lấy mẫu lại theo trường hợp tính lại trung bình chỉ báo trong chính mẫu đó trước khi ước lượng mô hình PLS/PLSc.
Mean replacement can distort variances and associations. Report the amount and likely mechanism of missingness and consider a complete-case or otherwise justified sensitivity analysis when missingness is material.|平均代入は分散や関連を歪める可能性があります。欠測の量と想定される仕組みを報告し、欠測が実質的な場合は完全ケース分析や根拠のある別の感度分析を検討してください。|均值替代可能扭曲方差与关联。请报告缺失量及可能机制；缺失较多时，考虑完整个案分析或其他有依据的敏感性分析。|El reemplazo por la media puede distorsionar varianzas y asociaciones. Informe la cantidad y el posible mecanismo de ausencia; si es relevante, considere un análisis de casos completos u otro análisis de sensibilidad justificado.|Le remplacement par la moyenne peut déformer les variances et associations. Rapportez la quantité et le mécanisme probable des données manquantes ; si elles sont importantes, envisagez une analyse des cas complets ou une autre analyse de sensibilité justifiée.|Mittelwertersetzung kann Varianzen und Zusammenhänge verzerren. Berichten Sie Umfang und wahrscheinlichen Fehlwertmechanismus; erwägen Sie bei wesentlichen Fehlwerten eine vollständige-Fälle-Analyse oder eine andere begründete Sensitivitätsanalyse.|Thay thế bằng trung bình có thể làm sai lệch phương sai và quan hệ. Báo cáo lượng thiếu và cơ chế có thể xảy ra; khi thiếu đáng kể, cân nhắc phân tích trường hợp đầy đủ hoặc phân tích độ nhạy có căn cứ khác.'''

rows += '\nNot specified|未指定|未指定|No especificado|Non spécifié|Nicht angegeben|Chưa chỉ định'

for i, lang in enumerate(['ja','zh','es','fr','de','vi'], 1):
    p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
    for line in rows.splitlines():
        row=line.split('|');assert len(row)==7
        key='analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')
        data['translations'][key]=row[i]
    p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
