import json
from pathlib import Path
keys=['gee','random','panel','covariance','selected','fitted','computed','intercept','slope','hausman','re_note','dk_note']
rows={
'en':['GEE correlation sensitivity','Random-effects sensitivity','Panel model sensitivity','Panel covariance sensitivity','Fitted (selected)','Fitted','Computed','Random intercept only','Random intercept + random slope for time','Hausman FE vs RE','Random effects not rejected; still justify the RE independence assumption.','Use as sensitivity inference when cross-sectional dependence or common shocks are plausible; report the chosen covariance estimator explicitly.'],
'ko':['GEE 상관구조 민감도','확률효과 민감도','패널 모형 민감도','패널 공분산 민감도','적합됨(선택)','적합됨','계산됨','확률절편만 포함','확률절편 + 시점 확률기울기','Hausman 고정효과 대 확률효과','확률효과가 기각되지 않았지만 확률효과의 독립 가정에 대한 근거는 여전히 필요합니다.','횡단면 의존성이나 공통 충격이 타당한 경우 민감도 추론으로 사용하고 선택한 공분산 추정량을 명시하십시오.'],
'ja':['GEE相関構造の感度分析','ランダム効果の感度分析','パネルモデルの感度分析','パネル共分散の感度分析','適合済み（選択）','適合済み','計算済み','ランダム切片のみ','ランダム切片＋時間のランダム傾き','Hausman固定効果対ランダム効果','ランダム効果は棄却されませんでしたが、独立性の仮定を正当化する必要があります。','横断面依存や共通ショックが考えられる場合の感度推論として使用し、選択した共分散推定量を明記してください。'],
'zh':['GEE相关结构敏感性分析','随机效应敏感性分析','面板模型敏感性分析','面板协方差敏感性分析','已拟合（所选）','已拟合','已计算','仅随机截距','随机截距＋时间随机斜率','Hausman固定效应与随机效应比较','未拒绝随机效应，但仍需论证随机效应独立性假设。','可能存在横截面依赖或共同冲击时，用于敏感性推断，并明确报告所选协方差估计量。'],
'es':['Sensibilidad de la correlación GEE','Sensibilidad de efectos aleatorios','Sensibilidad del modelo de panel','Sensibilidad de la covarianza de panel','Ajustado (seleccionado)','Ajustado','Calculado','Solo intercepto aleatorio','Intercepto aleatorio + pendiente aleatoria del tiempo','Hausman: efectos fijos frente a aleatorios','No se rechazaron los efectos aleatorios; aun así, justifique su supuesto de independencia.','Úselo como inferencia de sensibilidad cuando sea plausible la dependencia transversal o los choques comunes; informe explícitamente el estimador de covarianza elegido.'],
'fr':['Sensibilité de la corrélation GEE','Sensibilité des effets aléatoires','Sensibilité du modèle de panel','Sensibilité de la covariance de panel','Ajusté (sélectionné)','Ajusté','Calculé','Intercept aléatoire seul','Intercept aléatoire + pente aléatoire du temps','Hausman : effets fixes contre effets aléatoires','Les effets aléatoires ne sont pas rejetés ; justifiez néanmoins leur hypothèse d’indépendance.','À utiliser comme inférence de sensibilité si une dépendance transversale ou des chocs communs sont plausibles ; indiquez explicitement l’estimateur de covariance choisi.'],
'de':['Sensitivität der GEE-Korrelation','Sensitivität der zufälligen Effekte','Sensitivität des Panelmodells','Sensitivität der Panelkovarianz','Angepasst (ausgewählt)','Angepasst','Berechnet','Nur zufälliger Interzept','Zufälliger Interzept + zufällige Zeitsteigung','Hausman: feste versus zufällige Effekte','Zufällige Effekte wurden nicht verworfen; begründen Sie dennoch deren Unabhängigkeitsannahme.','Bei plausibler Querschnittsabhängigkeit oder gemeinsamen Schocks als Sensitivitätsinferenz verwenden; den gewählten Kovarianzschätzer ausdrücklich angeben.'],
'vi':['Phân tích độ nhạy tương quan GEE','Phân tích độ nhạy hiệu ứng ngẫu nhiên','Phân tích độ nhạy mô hình bảng','Phân tích độ nhạy hiệp phương sai bảng','Đã khớp (được chọn)','Đã khớp','Đã tính','Chỉ hệ số chặn ngẫu nhiên','Hệ số chặn ngẫu nhiên + hệ số góc thời gian ngẫu nhiên','Hausman: hiệu ứng cố định so với ngẫu nhiên','Không bác bỏ hiệu ứng ngẫu nhiên; vẫn cần giải trình giả định độc lập của hiệu ứng ngẫu nhiên.','Dùng để suy luận độ nhạy khi có thể có phụ thuộc chéo hoặc cú sốc chung; nêu rõ bộ ước lượng hiệp phương sai đã chọn.'],
}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.sensitivity_table.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
