import json,re
from pathlib import Path
phrases={
'Survey design was constructed from %s rows; final design N after exclusions/subpopulation was %s.': ['조사설계는 %s개 행으로 구성되었으며, 제외 및 부-모집단 적용 후 최종 설계 N은 %s입니다.','調査設計は%s行から構成され、除外・部分母集団の適用後の最終設計Nは%sです。','调查设计由%s行构建；排除及子总体筛选后的最终设计N为%s。','El diseño de encuesta se construyó con %s filas; el N final tras las exclusiones y la subpoblación fue %s.','Le plan de sondage a été construit à partir de %s lignes ; le N final après exclusions et sélection de la sous-population est de %s.','Das Erhebungsdesign wurde aus %s Zeilen erstellt; das endgültige Design-N nach Ausschlüssen und Teilpopulationsauswahl beträgt %s.','Thiết kế khảo sát được xây dựng từ %s dòng; N cuối cùng sau khi loại trừ và chọn tiểu quần thể là %s.'],
'Variance estimation used Taylor linearization.': ['분산 추정에는 Taylor 선형화 방법을 사용했습니다.','分散推定にはTaylor線形化を使用しました。','方差估计采用Taylor线性化。','La varianza se estimó mediante linealización de Taylor.','La variance a été estimée par linéarisation de Taylor.','Die Varianz wurde mittels Taylor-Linearisierung geschätzt.','Phương sai được ước lượng bằng tuyến tính hóa Taylor.'],
"Single-PSU strata were handled using survey.lonely.psu = '%s'.": ["단일 PSU 층은 survey.lonely.psu = '%s' 방식으로 처리했습니다.","単一PSUの層はsurvey.lonely.psu = '%s'で処理しました。","仅含一个PSU的层采用survey.lonely.psu = '%s'处理。","Los estratos con una sola UPM se trataron con survey.lonely.psu = '%s'.","Les strates à une seule unité primaire ont été traitées avec survey.lonely.psu = '%s'.","Schichten mit nur einer PSU wurden mit survey.lonely.psu = '%s' behandelt.","Các tầng chỉ có một PSU được xử lý bằng survey.lonely.psu = '%s'."],
'Missing N is the unweighted number of rows with missing values for the displayed variable after survey design and subpopulation filtering.': ['결측 N은 조사설계 및 부-모집단 필터링 후 표시 변수에 결측값이 있는 행의 비가중 사례 수입니다.','欠損Nは、調査設計と部分母集団の絞り込み後に、表示変数に欠損値がある行の非加重件数です。','缺失N是应用调查设计和子总体筛选后，所显示变量含缺失值的未加权行数。','N perdido es el número no ponderado de filas con valores perdidos en la variable mostrada tras aplicar el diseño de encuesta y el filtro de subpoblación.','N manquant est le nombre non pondéré de lignes présentant une valeur manquante pour la variable affichée après application du plan de sondage et du filtre de sous-population.','Fehlendes N ist die ungewichtete Anzahl der Zeilen mit fehlenden Werten der angezeigten Variable nach Anwendung des Erhebungsdesigns und des Teilpopulationsfilters.','N thiếu là số dòng không trọng số có giá trị thiếu ở biến được hiển thị sau khi áp dụng thiết kế khảo sát và bộ lọc tiểu quần thể.'],
'Variables with no usable non-missing values after survey design/subpopulation filtering were not displayed: %s.': ['조사설계 및 부-모집단 필터링 후 사용할 수 있는 비결측값이 없는 변수는 표시하지 않았습니다: %s.','調査設計・部分母集団の絞り込み後に利用可能な非欠損値がない変数は表示していません：%s。','应用调查设计及子总体筛选后，无可用非缺失值的变量未显示：%s。','No se mostraron las variables sin valores no perdidos utilizables tras aplicar el diseño de encuesta y el filtro de subpoblación: %s.','Les variables sans valeurs non manquantes utilisables après application du plan de sondage et du filtre de sous-population ne sont pas affichées : %s.','Variablen ohne verwendbare nichtfehlende Werte nach Anwendung des Erhebungsdesigns und Teilpopulationsfilters wurden nicht angezeigt: %s.','Các biến không có giá trị không thiếu có thể sử dụng sau khi áp dụng thiết kế khảo sát và bộ lọc tiểu quần thể không được hiển thị: %s.'],
'Survey design':['조사설계','調査設計','调查设计','Diseño de encuesta','Plan de sondage','Erhebungsdesign','Thiết kế khảo sát'],
'Skipped analyses':['제외된 분석','除外された分析','跳过的分析','Análisis omitidos','Analyses ignorées','Ausgelassene Analysen','Phân tích bị bỏ qua'],
'Details':['상세 내용','詳細','详细信息','Detalles','Détails','Details','Chi tiết']}
for index,lang in enumerate(['ko','ja','zh','es','fr','de','vi']):
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 for source,values in phrases.items():
  key='analysis.ui.'+re.sub(r'[^a-z0-9]+','_',source.lower()).strip('_');data['translations'][key]=values[index]
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
