"""ANCOVA and regression planning method descriptions."""
import json
from pathlib import Path
keys='note_plan_manova note_plan_rank_ancova note_plan_ancova note_plan_logistic note_plan_multiple note_plan_hierarchical note_plan_moderation'.split()
rows={
'en':["Approximate MANOVA power using Pillai's trace transformed to an F-style noncentrality parameter.",'Rank-transform ANCOVA approximation using covariate R-squared adjustment and a Wilcoxon-style asymptotic relative efficiency factor.',"ANCOVA approximation using Cohen's f, covariate R-squared residual-variance adjustment, and noncentral F distribution.",'Approximate logistic regression sample size using a Hsieh-style Wald test approximation for an odds ratio.',"Overall multiple regression R-squared test using Cohen's f2 and noncentral F distribution.","Incremental R-squared test using Cohen's f2 and noncentral F distribution.","Interaction-term incremental R-squared test using Cohen's f2 and noncentral F distribution."],
'ko':['Pillai의 트레이스를 F 방식 비중심성 모수로 변환하여 MANOVA 검정력을 근사합니다.','공변량 R-squared 보정과 Wilcoxon 방식의 점근 상대효율 계수를 사용하는 순위변환 ANCOVA 근사입니다.','Cohen의 f, 공변량 R-squared에 따른 잔차분산 보정, 비중심 F 분포를 사용하는 ANCOVA 근사입니다.','오즈비에 대한 Hsieh 방식 Wald 검정 근사로 로지스틱 회귀 표본수를 근사합니다.','Cohen의 f2와 비중심 F 분포를 사용하는 다중회귀 전체 R-squared 검정입니다.','Cohen의 f2와 비중심 F 분포를 사용하는 R-squared 증가량 검정입니다.','Cohen의 f2와 비중심 F 분포를 사용하는 상호작용항의 R-squared 증가량 검정입니다.'],
'ja':['PillaiのトレースをF型の非心度パラメータに変換してMANOVAの検出力を近似します。','共変量R-squaredの調整とWilcoxon型の漸近相対効率係数を用いた順位変換ANCOVAの近似です。','Cohenのf、共変量R-squaredによる残差分散調整、非心F分布を用いたANCOVAの近似です。','オッズ比に対するHsieh型Wald検定近似でロジスティック回帰の標本サイズを近似します。','Cohenのf2と非心F分布を用いた重回帰全体のR-squared検定です。','Cohenのf2と非心F分布を用いたR-squared増分検定です。','Cohenのf2と非心F分布を用いた交互作用項のR-squared増分検定です。'],
'zh':['将Pillai迹转换为F型非中心参数，近似计算MANOVA功效。','使用协变量R-squared调整和Wilcoxon型渐近相对效率系数的秩转换ANCOVA近似。','使用Cohen f、协变量R-squared残差方差调整及非中心F分布的ANCOVA近似。','使用针对优势比的Hsieh型Wald检验近似，计算逻辑回归近似样本量。','使用Cohen f2和非中心F分布的多元回归整体R-squared检验。','使用Cohen f2和非中心F分布的R-squared增量检验。','使用Cohen f2和非中心F分布的交互项R-squared增量检验。'],
'es':['Potencia MANOVA aproximada transformando la traza de Pillai en un parámetro de no centralidad de tipo F.','Aproximación ANCOVA con transformación de rangos, ajuste por R-squared de covariables y eficiencia relativa asintótica de tipo Wilcoxon.','Aproximación ANCOVA con f de Cohen, ajuste de varianza residual por R-squared de covariables y distribución F no central.','Tamaño muestral aproximado de regresión logística mediante una aproximación Wald de tipo Hsieh para una razón de momios.','Prueba global de R-squared de regresión múltiple con f2 de Cohen y distribución F no central.','Prueba incremental de R-squared con f2 de Cohen y distribución F no central.','Prueba incremental de R-squared del término de interacción con f2 de Cohen y distribución F no central.'],
'fr':['Puissance MANOVA approchée en transformant la trace de Pillai en paramètre de non-centralité de type F.','Approximation ANCOVA par transformation en rangs avec ajustement du R-squared des covariables et facteur d’efficacité relative asymptotique de type Wilcoxon.','Approximation ANCOVA avec le f de Cohen, ajustement de variance résiduelle par le R-squared des covariables et loi F non centrale.','Taille d’échantillon de régression logistique approchée par un test de Wald de type Hsieh pour un odds ratio.','Test global du R-squared de régression multiple avec le f2 de Cohen et la loi F non centrale.','Test de l’accroissement du R-squared avec le f2 de Cohen et la loi F non centrale.','Test de l’accroissement du R-squared du terme d’interaction avec le f2 de Cohen et la loi F non centrale.'],
'de':['Approximierte MANOVA-Power durch Transformation von Pillais Spur in einen F-artigen Nichtzentralitätsparameter.','Rangtransformierte ANCOVA-Approximation mit Kovariaten-R-squared-Anpassung und asymptotischem relativem Effizienzfaktor nach Wilcoxon.','ANCOVA-Approximation mit Cohens f, Residualvarianzanpassung über das Kovariaten-R-squared und nichtzentraler F-Verteilung.','Approximierter logistischer Regressionsstichprobenumfang mit einer Wald-Test-Approximation nach Hsieh für ein Odds Ratio.','Gesamter R-squared-Test der multiplen Regression mit Cohens f2 und nichtzentraler F-Verteilung.','Inkrementeller R-squared-Test mit Cohens f2 und nichtzentraler F-Verteilung.','Inkrementeller R-squared-Test des Interaktionsterms mit Cohens f2 und nichtzentraler F-Verteilung.'],
'vi':['Công suất MANOVA xấp xỉ bằng cách chuyển vết Pillai thành tham số phi trung tâm kiểu F.','Xấp xỉ ANCOVA biến đổi hạng với điều chỉnh R-squared của hiệp biến và hệ số hiệu quả tương đối tiệm cận kiểu Wilcoxon.','Xấp xỉ ANCOVA sử dụng f của Cohen, điều chỉnh phương sai phần dư theo R-squared của hiệp biến và phân phối F phi trung tâm.','Cỡ mẫu hồi quy logistic xấp xỉ bằng kiểm định Wald kiểu Hsieh cho tỷ số odds.','Kiểm định R-squared tổng thể của hồi quy bội sử dụng f2 của Cohen và phân phối F phi trung tâm.','Kiểm định mức tăng R-squared sử dụng f2 của Cohen và phân phối F phi trung tâm.','Kiểm định mức tăng R-squared của số hạng tương tác sử dụng f2 của Cohen và phân phối F phi trung tâm.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
