"""t-test effect-size prose with unchanged mathematical expressions."""
import json
from pathlib import Path
keys='note_t_independent note_t_equal note_t_one note_t_paired note_t_r note_t_pooled'.split()
rows={
'en':["For an independent two-sample t-test, Cohen's d = t * sqrt(1/n1 + 1/n2). Hedges' g applies the small-sample correction.","For equal-sized independent groups, Cohen's d = 2t / sqrt(df + 2). Use the group-n option when n1 and n2 differ.","For a one-sample t-test, Cohen's d = t / sqrt(n).","For a paired t-test, Cohen's dz = t / sqrt(number of pairs).","For a two-group contrast, Cohen's d can be converted from point-biserial r as d = 2r / sqrt(1 - r^2).","Cohen's d uses the pooled SD; Hedges' g applies the small-sample correction J = 1 - 3 / (4df - 1)."],
'ko':["독립 두 표본 t 검정에서 Cohen's d = t * sqrt(1/n1 + 1/n2)입니다. Hedges의 g는 소표본 보정을 적용합니다.","크기가 같은 독립 집단에서 Cohen's d = 2t / sqrt(df + 2)입니다. n1과 n2가 다르면 집단별 표본수 입력 옵션을 사용하세요.","일표본 t 검정에서 Cohen's d = t / sqrt(n)입니다.","대응표본 t 검정에서 Cohen's dz = t / sqrt(number of pairs)입니다.","두 집단 대비에서 점이연 상관 r을 Cohen의 d로 변환할 수 있습니다: d = 2r / sqrt(1 - r^2).","Cohen의 d는 통합 SD를 사용합니다; Hedges의 g는 소표본 보정 J = 1 - 3 / (4df - 1)을 적용합니다."],
'ja':["独立2標本t検定ではCohen's d = t * sqrt(1/n1 + 1/n2)です。Hedgesのgは小標本補正を適用します。","同じ大きさの独立群ではCohen's d = 2t / sqrt(df + 2)です。n1とn2が異なる場合は群別標本サイズの入力を使用してください。","1標本t検定ではCohen's d = t / sqrt(n)です。","対応のあるt検定ではCohen's dz = t / sqrt(number of pairs)です。","2群の対比では点双列相関rからCohenのdに変換できます：d = 2r / sqrt(1 - r^2)。","CohenのdはプールしたSDを使用します; Hedgesのgは小標本補正J = 1 - 3 / (4df - 1)を適用します。"],
'zh':["独立双样本t检验中，Cohen's d = t * sqrt(1/n1 + 1/n2)。Hedges g应用小样本校正。","等样本量独立组中，Cohen's d = 2t / sqrt(df + 2)。n1和n2不同时，请使用按组输入样本量的选项。","单样本t检验中，Cohen's d = t / sqrt(n)。","配对t检验中，Cohen's dz = t / sqrt(number of pairs)。","两组对比中，可将点二列相关r转换为Cohen d：d = 2r / sqrt(1 - r^2)。","Cohen d使用合并SD; Hedges g应用小样本校正J = 1 - 3 / (4df - 1)。"],
'es':["Para una prueba t de dos muestras independientes, Cohen's d = t * sqrt(1/n1 + 1/n2). La g de Hedges aplica la corrección para muestras pequeñas.","Para grupos independientes de igual tamaño, Cohen's d = 2t / sqrt(df + 2). Use la opción de tamaños por grupo cuando n1 y n2 difieran.","Para una prueba t de una muestra, Cohen's d = t / sqrt(n).","Para una prueba t pareada, Cohen's dz = t / sqrt(number of pairs).","En un contraste de dos grupos, r biserial puntual puede convertirse a d de Cohen: d = 2r / sqrt(1 - r^2).","La d de Cohen usa la SD combinada; la g de Hedges aplica la corrección para muestras pequeñas J = 1 - 3 / (4df - 1)."],
'fr':["Pour un test t à deux échantillons indépendants, Cohen's d = t * sqrt(1/n1 + 1/n2). Le g de Hedges applique la correction pour petits échantillons.","Pour des groupes indépendants de même taille, Cohen's d = 2t / sqrt(df + 2). Utiliser les tailles par groupe lorsque n1 et n2 diffèrent.","Pour un test t à un échantillon, Cohen's d = t / sqrt(n).","Pour un test t apparié, Cohen's dz = t / sqrt(number of pairs).","Pour un contraste à deux groupes, le r point-bisérial se convertit en d de Cohen : d = 2r / sqrt(1 - r^2).","Le d de Cohen utilise la SD combinée; le g de Hedges applique la correction pour petits échantillons J = 1 - 3 / (4df - 1)."],
'de':["Für einen t-Test mit zwei unabhängigen Stichproben gilt Cohen's d = t * sqrt(1/n1 + 1/n2). Hedges’ g verwendet die Kleinstichprobenkorrektur.","Für gleich große unabhängige Gruppen gilt Cohen's d = 2t / sqrt(df + 2). Bei unterschiedlichen n1 und n2 die gruppenspezifischen Stichprobengrößen verwenden.","Für einen Einstichproben-t-Test gilt Cohen's d = t / sqrt(n).","Für einen gepaarten t-Test gilt Cohen's dz = t / sqrt(number of pairs).","Bei einem Zweigruppenkontrast lässt sich das punktbiseriale r in Cohens d umrechnen: d = 2r / sqrt(1 - r^2).","Cohens d verwendet die gepoolte SD; Hedges’ g verwendet die Kleinstichprobenkorrektur J = 1 - 3 / (4df - 1)."],
'vi':["Với kiểm định t hai mẫu độc lập, Cohen's d = t * sqrt(1/n1 + 1/n2). g của Hedges áp dụng hiệu chỉnh mẫu nhỏ.","Với hai nhóm độc lập có cỡ mẫu bằng nhau, Cohen's d = 2t / sqrt(df + 2). Dùng tùy chọn cỡ mẫu từng nhóm khi n1 và n2 khác nhau.","Với kiểm định t một mẫu, Cohen's d = t / sqrt(n).","Với kiểm định t ghép cặp, Cohen's dz = t / sqrt(number of pairs).","Trong tương phản hai nhóm, có thể đổi tương quan điểm nhị phân r thành d của Cohen: d = 2r / sqrt(1 - r^2).","d của Cohen dùng SD gộp; g của Hedges áp dụng hiệu chỉnh mẫu nhỏ J = 1 - 3 / (4df - 1)."]}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
