import json,re
from pathlib import Path
rows='''Spline df|スプライン自由度|样条自由度|Grados de libertad del spline|Degrés de liberté de la spline|Spline-Freiheitsgrade|Bậc tự do của spline
Reference value|基準値|参考值|Valor de referencia|Valeur de référence|Referenzwert|Giá trị tham chiếu
Nonlinearity LR chi-square|非線形性の尤度比カイ二乗|非线性似然比卡方|Chi-cuadrado de razón de verosimilitudes para no linealidad|Khi-deux du rapport de vraisemblance pour la non-linéarité|Likelihood-Ratio-Chi-Quadrat für Nichtlinearität|Chi bình phương tỷ số hợp lý cho tính phi tuyến
Linear-model AIC|線形モデルAIC|线性模型AIC|AIC del modelo lineal|AIC du modèle linéaire|AIC des linearen Modells|AIC của mô hình tuyến tính
Spline-model AIC|スプラインモデルAIC|样条模型AIC|AIC del modelo spline|AIC du modèle spline|AIC des Spline-Modells|AIC của mô hình spline
Natural cubic spline functional-form analysis|自然三次スプラインによる関数形分析|自然三次样条函数形式分析|Análisis de la forma funcional con spline cúbico natural|Analyse de la forme fonctionnelle par spline cubique naturelle|Funktionsformanalyse mit natürlichem kubischem Spline|Phân tích dạng hàm bằng spline bậc ba tự nhiên
The likelihood-ratio test compares the prespecified natural-cubic-spline model with the corresponding linear-term model. The HR curve is relative to the sample median and spans the 5th to 95th percentiles. Spline basis coefficients are intentionally omitted because their individual HRs are not substantively interpretable; evaluate the joint test and curve together.|尤度比検定は事前指定の自然三次スプラインモデルと対応する線形項モデルを比較します。HR曲線は標本中央値を基準とし、第5～第95百分位を示します。スプライン基底係数の個別HRには実質的な解釈ができないため省略しています。全体検定と曲線を併せて評価してください。|似然比检验比较预先指定的自然三次样条模型与相应的线性项模型。HR曲线以样本中位数为参考，范围为第5至第95百分位。样条基函数系数的单独HR缺乏实质性解释，因此有意省略；应结合联合检验与曲线进行评估。|La prueba de razón de verosimilitudes compara el modelo de spline cúbico natural preespecificado con el modelo correspondiente de término lineal. La curva de HR toma como referencia la mediana muestral y abarca los percentiles 5 a 95. Se omiten los coeficientes de la base spline porque sus HR individuales no tienen una interpretación sustantiva; evalúe conjuntamente la prueba global y la curva.|Le test du rapport de vraisemblance compare le modèle de spline cubique naturelle préspécifié au modèle correspondant avec terme linéaire. La courbe de HR prend la médiane de l’échantillon comme référence et couvre les 5e à 95e percentiles. Les coefficients de base de la spline sont omis car leurs HR individuels n’ont pas d’interprétation substantielle ; évaluez ensemble le test conjoint et la courbe.|Der Likelihood-Ratio-Test vergleicht das vorab festgelegte natürliche kubische Spline-Modell mit dem entsprechenden Modell mit linearem Term. Die HR-Kurve bezieht sich auf den Stichprobenmedian und umfasst das 5. bis 95. Perzentil. Spline-Basiskoeffizienten werden ausgelassen, da ihre einzelnen HRs inhaltlich nicht interpretierbar sind; beurteilen Sie den gemeinsamen Test und die Kurve zusammen.|Kiểm định tỷ số hợp lý so sánh mô hình spline bậc ba tự nhiên được chỉ định trước với mô hình có số hạng tuyến tính tương ứng. Đường HR lấy trung vị mẫu làm tham chiếu và trải từ phân vị thứ 5 đến 95. Các hệ số cơ sở spline được lược bỏ vì HR riêng lẻ của chúng không có diễn giải thực chất; hãy đánh giá kiểm định chung và đường cong cùng nhau.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
