import json,re
from pathlib import Path
rows='''Modification indices cannot be computed because the information matrix is singular. Identification may be borderline or estimation unstable; MI candidates are not displayed.	情報行列が特異なため修正指標を計算できません。識別が境界的または推定が不安定な可能性があり、MI候補は表示しません。	信息矩阵奇异，无法计算修正指数。模型可能处于识别边界或估计不稳定；不显示MI候选项。	No se pueden calcular los índices de modificación porque la matriz de información es singular. La identificación puede ser limítrofe o la estimación inestable; no se muestran candidatos MI.	Les indices de modification ne peuvent pas être calculés car la matrice d’information est singulière. L’identification peut être limite ou l’estimation instable ; les candidats MI ne sont pas affichés.	Modifikationsindizes können wegen einer singulären Informationsmatrix nicht berechnet werden. Die Identifikation kann grenzwertig oder die Schätzung instabil sein; MI-Kandidaten werden nicht angezeigt.	Không thể tính chỉ số sửa đổi vì ma trận thông tin suy biến. Tính định danh có thể ở ranh giới hoặc ước lượng không ổn định; không hiển thị ứng viên MI.
Modification indices cannot be computed for the current fitted model; no MI candidates are available.	現在の適合モデルでは修正指標を計算できず、MI候補はありません。	无法为当前拟合模型计算修正指数；没有可用的MI候选项。	No se pueden calcular los índices de modificación del modelo ajustado actual; no hay candidatos MI disponibles.	Les indices de modification du modèle ajusté actuel ne peuvent pas être calculés ; aucun candidat MI n’est disponible.	Für das aktuell angepasste Modell können keine Modifikationsindizes berechnet werden; es sind keine MI-Kandidaten verfügbar.	Không thể tính chỉ số sửa đổi cho mô hình đã khớp hiện tại; không có ứng viên MI.
The information matrix is singular, so standard errors or modification indices cannot be computed reliably. Check model identification, covariances, and higher-order factor structure.	情報行列が特異なため、標準誤差や修正指標を安定して計算できません。モデルの識別性、共分散、高次因子構造を確認してください。	信息矩阵奇异，无法可靠计算标准误或修正指数。请检查模型识别、协方差和高阶因子结构。	La matriz de información es singular, por lo que no se pueden calcular con fiabilidad los errores estándar o índices de modificación. Revise la identificación, las covarianzas y la estructura factorial de orden superior.	La matrice d’information est singulière ; les erreurs-types ou indices de modification ne peuvent pas être calculés de façon fiable. Vérifiez l’identification, les covariances et la structure factorielle d’ordre supérieur.	Die Informationsmatrix ist singulär; Standardfehler oder Modifikationsindizes können nicht zuverlässig berechnet werden. Prüfen Sie Identifikation, Kovarianzen und die Faktorenstruktur höherer Ordnung.	Ma trận thông tin suy biến nên không thể tính đáng tin cậy sai số chuẩn hoặc chỉ số sửa đổi. Hãy kiểm tra tính định danh, hiệp phương sai và cấu trúc nhân tố bậc cao.
The matrix is nearly singular and cannot be inverted reliably. Check zero within-group variances, nearly duplicate variables, extreme multicollinearity, model identification, and excessive equality constraints.	行列がほぼ特異なため、安定した逆行列を求められません。群内分散が0の変数、ほぼ重複した変数、極端な多重共線性、モデル識別性、過度な等値制約を確認してください。	矩阵接近奇异，无法可靠求逆。请检查组内零方差、近乎重复的变量、极端多重共线性、模型识别及过多相等约束。	La matriz es casi singular y no se puede invertir con fiabilidad. Revise varianzas intragrupo nulas, variables casi duplicadas, multicolinealidad extrema, identificación y restricciones de igualdad excesivas.	La matrice est presque singulière et ne peut pas être inversée de façon fiable. Vérifiez les variances intragroupes nulles, variables quasi identiques, multicolinéarité extrême, identification et contraintes d’égalité excessives.	Die Matrix ist nahezu singulär und lässt sich nicht zuverlässig invertieren. Prüfen Sie Nullvarianzen innerhalb von Gruppen, fast identische Variablen, extreme Multikollinearität, Identifikation und übermäßige Gleichheitsrestriktionen.	Ma trận gần suy biến nên không thể nghịch đảo đáng tin cậy. Hãy kiểm tra phương sai trong nhóm bằng không, biến gần trùng lặp, đa cộng tuyến cực đoan, tính định danh và ràng buộc bằng nhau quá mức.
Reciprocal condition number: %s	逆条件数：%s	倒条件数：%s	Número de condición recíproco: %s	Inverse du nombre de condition : %s	Reziproke Konditionszahl: %s	Nghịch đảo số điều kiện: %s'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
