"""GEE, GLMM and LMM method descriptions; preserve model-scale expressions."""
import json
from pathlib import Path
keys = ['note_gee_supplied', 'note_glmm_logit', 'note_glmm_probs', 'note_glmm_log', 'note_glmm_rates', 'note_glmm_identity', 'note_lmm_vectors']
expressions = ['log(OR)', 'd = log(OR) * sqrt(3) / pi', 'log(IRR)', 'IRR = exp(B)', 'd = fixed-effect coefficient B / residual SD']
rows = {
'en': ['Uses the supplied standardized mean difference d.', 'For a binary logit GLMM, the model-scale fixed effect is {0}. Approximate latent-scale {1}.', "For binary outcomes, probabilities are converted to odds ratio; Cohen's h is also reported for the marginal proportion contrast.", 'For a Poisson or negative-binomial GLMM with log link, the model-scale fixed effect is {2}, and {3}.', 'For count outcomes with a log link, the marginal rate ratio is equivalent to IRR when offsets/exposure are handled consistently.', 'For a Gaussian identity-link mixed model, standardized effect {4}.', 'GLIMMPSE-style effect uses the last-minus-first mean contrast divided by residual SD, with repeated-measures planning adjustment.'],
'ko': ['입력한 표준화 평균차 d를 사용합니다.', '이분형 로짓 GLMM에서 모형 척도의 고정효과는 {0}입니다. 잠재 척도의 근사 효과크기는 {1}입니다.', '이분형 결과의 확률을 오즈비로 변환하며, 주변 비율 대비에 대한 Cohen의 h도 제시합니다.', '로그 연결을 사용하는 포아송 또는 음이항 GLMM에서 모형 척도의 고정효과는 {2}이며, {3}입니다.', '로그 연결을 사용하는 계수형 결과에서 오프셋과 노출량을 일관되게 처리하면 주변 발생률비는 IRR과 같습니다.', '항등 연결을 사용하는 가우시안 혼합모형에서 표준화 효과크기는 {4}입니다.', 'GLIMMPSE 방식의 효과크기는 마지막 평균에서 첫 평균을 뺀 대비를 잔차 표준편차로 나누고 반복측정 계획 보정을 적용합니다.'],
'ja': ['入力された標準化平均差dを使用します。', '二値ロジットGLMMでは、モデル尺度の固定効果は{0}です。潜在尺度の近似効果量は{1}です。', '二値アウトカムの確率をオッズ比に変換し、周辺比率の対比に対するCohenのhも示します。', '対数リンクのポアソンまたは負の二項GLMMでは、モデル尺度の固定効果は{2}で、{3}です。', '対数リンクの計数アウトカムでは、オフセットと曝露量を一貫して扱う場合、周辺率比はIRRと等しくなります。', '恒等リンクのガウス混合モデルでは、標準化効果量は{4}です。', 'GLIMMPSE方式の効果量は、最後の平均から最初の平均を引いた対比を残差標準偏差で割り、反復測定計画の調整を適用します。'],
'zh': ['使用输入的标准化均值差d。', '二元logit GLMM的模型尺度固定效应为{0}。潜变量尺度的近似效应量为{1}。', '将二元结局的概率转换为优势比，并报告边际比例对比的Cohen h。', '采用对数链接的泊松或负二项GLMM中，模型尺度固定效应为{2}，且{3}。', '对于采用对数链接的计数结局，若偏置项和暴露量处理一致，边际率比等于IRR。', '采用恒等链接的高斯混合模型中，标准化效应量为{4}。', 'GLIMMPSE方式的效应量使用末次均值减去首次均值的对比除以残差标准差，并进行重复测量规划调整。'],
'es': ['Se utiliza la diferencia de medias estandarizada d proporcionada.', 'En un GLMM logit binario, el efecto fijo en la escala del modelo es {0}. En la escala latente, aproximadamente {1}.', 'Para resultados binarios, las probabilidades se convierten en una razón de momios; también se presenta h de Cohen para el contraste de proporciones marginales.', 'En un GLMM de Poisson o binomial negativo con enlace logarítmico, el efecto fijo en la escala del modelo es {2}, y {3}.', 'Para resultados de recuento con enlace logarítmico, la razón de tasas marginales equivale a IRR si los offsets y la exposición se tratan de forma coherente.', 'En un modelo mixto gaussiano con enlace identidad, el efecto estandarizado es {4}.', 'El efecto de tipo GLIMMPSE utiliza el contraste de la última media menos la primera dividido por la desviación estándar residual, con ajuste para planificar medidas repetidas.'],
'fr': ['La différence moyenne standardisée d fournie est utilisée.', 'Pour un GLMM logit binaire, l’effet fixe sur l’échelle du modèle est {0}. Sur l’échelle latente, approximativement {1}.', 'Pour les résultats binaires, les probabilités sont converties en odds ratio; le h de Cohen est aussi présenté pour le contraste des proportions marginales.', 'Pour un GLMM de Poisson ou binomial négatif à lien logarithmique, l’effet fixe sur l’échelle du modèle est {2}, et {3}.', 'Pour les résultats de comptage à lien logarithmique, le rapport des taux marginaux équivaut à IRR lorsque les offsets et l’exposition sont traités de manière cohérente.', 'Pour un modèle mixte gaussien à lien identité, l’effet standardisé est {4}.', 'L’effet de type GLIMMPSE utilise le contraste entre la dernière et la première moyenne divisé par l’écart-type résiduel, avec un ajustement pour la planification des mesures répétées.'],
'de': ['Die angegebene standardisierte Mittelwertdifferenz d wird verwendet.', 'Bei einem binären Logit-GLMM ist der feste Effekt auf der Modellskala {0}. Auf der latenten Skala gilt näherungsweise {1}.', 'Bei binären Ergebnissen werden Wahrscheinlichkeiten in ein Odds Ratio umgerechnet; Cohens h wird zusätzlich für den marginalen Anteilsvergleich angegeben.', 'Bei einem Poisson- oder negativ-binomialen GLMM mit Log-Link ist der feste Effekt auf der Modellskala {2}, und {3}.', 'Bei Zählergebnissen mit Log-Link entspricht das marginale Ratenverhältnis dem IRR, wenn Offsets und Exposition konsistent behandelt werden.', 'Bei einem gaußschen gemischten Modell mit Identitätslink ist der standardisierte Effekt {4}.', 'Der GLIMMPSE-artige Effekt verwendet den Kontrast letzter minus erster Mittelwert geteilt durch die Residualstandardabweichung, mit einer Anpassung für die Messwiederholungsplanung.'],
'vi': ['Sử dụng chênh lệch trung bình chuẩn hóa d đã nhập.', 'Với GLMM logit nhị phân, hiệu ứng cố định trên thang mô hình là {0}. Trên thang tiềm ẩn, xấp xỉ {1}.', 'Với kết quả nhị phân, xác suất được chuyển thành tỷ số odds; h của Cohen cũng được báo cáo cho tương phản tỷ lệ biên.', 'Với GLMM Poisson hoặc nhị thức âm có liên kết log, hiệu ứng cố định trên thang mô hình là {2}, và {3}.', 'Với kết quả đếm có liên kết log, tỷ số suất biên tương đương IRR khi offset và mức phơi nhiễm được xử lý nhất quán.', 'Với mô hình hỗn hợp Gaussian có liên kết đồng nhất, hiệu ứng chuẩn hóa là {4}.', 'Hiệu ứng kiểu GLIMMPSE lấy tương phản trung bình cuối trừ trung bình đầu chia cho độ lệch chuẩn phần dư, có điều chỉnh lập kế hoạch đo lặp.']
}
for lang, templates in rows.items():
    assert len(templates) == len(keys)
    path = Path('i18n') / (lang + '.json')
    data = json.loads(path.read_text(encoding='utf-8'))
    data['translations'].update({'sample_size.result.' + key: value.format(*expressions) for key, value in zip(keys, templates)})
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
