import json, re
from pathlib import Path

# UI-only diagnostic prose. Model estimates and user labels are not translated.
rows = '''Multivariate normality|다변량 정규성|多変量正規性|多元正态性|Normalidad multivariante|Normalité multivariée|Multivariate Normalität|Tính chuẩn đa biến
Multivariate normality and estimator guidance|다변량 정규성 및 추정량 안내|多変量正規性と推定法の案内|多元正态性与估计方法建议|Normalidad multivariante y orientación del estimador|Normalité multivariée et choix de l’estimateur|Multivariate Normalität und Hinweise zum Schätzer|Tính chuẩn đa biến và hướng dẫn chọn phương pháp ước lượng
MLR recommended|MLR 권장|MLRを推奨|建议使用MLR|Se recomienda MLR|MLR recommandé|MLR empfohlen|Khuyến nghị MLR
No Mardia test flag; normality not established|Mardia 검정 표시는 없으나 정규성이 입증된 것은 아님|Mardia検定の警告なし。ただし正規性が証明されたわけではありません|Mardia检验未提示异常；但不能据此确立正态性|Sin alerta de Mardia; no se ha establecido la normalidad|Aucune alerte de Mardia ; la normalité n’est pas établie|Kein Mardia-Testhinweis; Normalität ist nicht nachgewiesen|Kiểm định Mardia không cảnh báo; chưa xác lập tính chuẩn
Guidance: {recommendation}. This recommendation is diagnostic and does not automatically change the estimator.|안내: {recommendation}. 이 권고는 진단용이며 추정량을 자동으로 변경하지 않습니다.|案内：{recommendation}。これは診断上の推奨であり、推定法は自動変更されません。|建议：{recommendation}。此建议仅用于诊断，不会自动更改估计方法。|Orientación: {recommendation}. Esta recomendación es diagnóstica y no cambia automáticamente el estimador.|Orientation : {recommendation}. Cette recommandation est diagnostique et ne change pas automatiquement l’estimateur.|Hinweis: {recommendation}. Diese diagnostische Empfehlung ändert den Schätzer nicht automatisch.|Hướng dẫn: {recommendation}. Khuyến nghị này phục vụ chẩn đoán và không tự động thay đổi phương pháp ước lượng.
Complete cases used: {n} of {total}; indicators: {p}.|사용된 완전 사례: {n} / {total}; 지표 수: {p}.|使用した完全ケース：{total}件中{n}件、指標数：{p}。|使用的完整个案：{n}/{total}；指标数：{p}。|Casos completos utilizados: {n} de {total}; indicadores: {p}.|Cas complets utilisés : {n} sur {total} ; indicateurs : {p}.|Verwendete vollständige Fälle: {n} von {total}; Indikatoren: {p}.|Số trường hợp đầy đủ đã dùng: {n}/{total}; số chỉ báo: {p}.
For computational stability, Mardia statistics used a reproducible random subsample of complete cases.|계산 안정성을 위해 Mardia 통계량은 완전 사례 중 재현 가능한 무작위 부분표본으로 계산했습니다.|計算の安定性のため、Mardia統計量は完全ケースから再現可能な無作為部分標本を抽出して計算しました。|为保证计算稳定，Mardia统计量使用完整个案的可复现随机子样本计算。|Para estabilizar el cálculo, los estadísticos de Mardia utilizaron una submuestra aleatoria reproducible de casos completos.|Pour stabiliser le calcul, les statistiques de Mardia utilisent un sous-échantillon aléatoire reproductible des cas complets.|Für rechnerische Stabilität wurden Mardia-Statistiken anhand einer reproduzierbaren zufälligen Teilstichprobe vollständiger Fälle berechnet.|Để ổn định tính toán, thống kê Mardia sử dụng mẫu con ngẫu nhiên có thể tái lập từ các trường hợp đầy đủ.
Mardia tests are sample-size-sensitive omnibus screens. Nonsignificance does not establish multivariate normality, while significance alone does not quantify the substantive size of skew/kurtosis or its impact on estimates. Consider distribution shape, outliers, measurement assumptions, and sensitivity analyses.|Mardia 검정은 표본 수에 민감한 전체분포 선별검사입니다. 유의하지 않은 결과는 다변량 정규성을 입증하지 않으며, 유의한 결과도 왜도·첨도의 실질적 크기나 추정치에 대한 영향 정도를 단독으로 보여주지 않습니다. 분포 형태, 이상치, 측정 가정과 민감도 분석을 함께 검토하십시오.|Mardia検定は標本サイズに敏感な全体的スクリーニングです。非有意でも多変量正規性は証明されず、有意性だけでは歪度・尖度の実質的な大きさや推定値への影響は分かりません。分布形状、外れ値、測定の仮定、感度分析を併せて検討してください。|Mardia检验是对样本量敏感的总体筛查。不显著并不能确立多元正态性，而仅凭显著性也无法量化偏度或峰度的实际大小及其对估计的影响。请结合分布形态、异常值、测量假设和敏感性分析判断。|Los tests de Mardia son pruebas globales sensibles al tamaño muestral. Un resultado no significativo no establece normalidad multivariante; la significación por sí sola tampoco cuantifica la magnitud de la asimetría o curtosis ni su efecto sobre las estimaciones. Considere la forma de la distribución, los valores atípicos, los supuestos de medición y los análisis de sensibilidad.|Les tests de Mardia sont des examens globaux sensibles à la taille de l’échantillon. La non-significativité n’établit pas la normalité multivariée ; la significativité seule ne quantifie ni l’ampleur de l’asymétrie ou de l’aplatissement ni leur impact sur les estimations. Examinez aussi la forme des distributions, les valeurs aberrantes, les hypothèses de mesure et les analyses de sensibilité.|Mardia-Tests sind globale Prüfungen, die auf den Stichprobenumfang reagieren. Ein nicht signifikantes Ergebnis belegt keine multivariate Normalität. Signifikanz allein quantifiziert weder das Ausmaß von Schiefe oder Kurtosis noch deren Einfluss auf Schätzwerte. Berücksichtigen Sie Verteilungsform, Ausreißer, Messannahmen und Sensitivitätsanalysen.|Kiểm định Mardia là phép sàng lọc tổng thể nhạy với cỡ mẫu. Kết quả không có ý nghĩa thống kê không xác lập tính chuẩn đa biến; riêng tính có ý nghĩa cũng không định lượng mức độ lệch, độ nhọn hay ảnh hưởng đến ước lượng. Cần xem xét hình dạng phân phối, ngoại lệ, giả định đo lường và phân tích độ nhạy.
At least two continuous indicators are required.|연속형 지표가 2개 이상 필요합니다.|連続指標が2個以上必要です。|至少需要两个连续指标。|Se requieren al menos dos indicadores continuos.|Au moins deux indicateurs continus sont requis.|Mindestens zwei kontinuierliche Indikatoren sind erforderlich.|Cần ít nhất hai chỉ báo liên tục.
All indicators must be numeric and continuous.|모든 지표는 숫자형 연속변수여야 합니다.|すべての指標は数値の連続変数である必要があります。|所有指标必须为数值型连续变量。|Todos los indicadores deben ser numéricos y continuos.|Tous les indicateurs doivent être numériques et continus.|Alle Indikatoren müssen numerisch und kontinuierlich sein.|Tất cả chỉ báo phải là biến số liên tục.
Too few complete cases for the number of indicators.|지표 수에 비해 완전 사례가 너무 적습니다.|指標数に対して完全ケースが不足しています。|相对于指标数量，完整个案过少。|Hay muy pocos casos completos para el número de indicadores.|Trop peu de cas complets pour le nombre d’indicateurs.|Zu wenige vollständige Fälle für die Anzahl der Indikatoren.|Quá ít trường hợp đầy đủ so với số chỉ báo.'''

rows += '\nThe indicator covariance matrix is singular.|지표 공분산 행렬이 특이행렬입니다.|指標の共分散行列が特異です。|指标协方差矩阵为奇异矩阵。|La matriz de covarianzas de los indicadores es singular.|La matrice de covariance des indicateurs est singulière.|Die Kovarianzmatrix der Indikatoren ist singulär.|Ma trận hiệp phương sai của các chỉ báo là ma trận suy biến.'
translations = [line.split('|') for line in rows.splitlines()]
for row in translations:
    assert len(row) == 8, row
for i, lang in enumerate(['ko', 'ja', 'zh', 'es', 'fr', 'de', 'vi'], 1):
    p = Path('i18n') / (lang + '.json')
    data = json.loads(p.read_text(encoding='utf-8'))
    for row in translations:
        key = 'analysis.ui.' + re.sub(r'[^a-z0-9]+', '_', row[0].lower()).strip('_')
        data['translations'][key] = row[i]
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
