import json
from pathlib import Path
keys=['gee_parameter','gee_matrix','gee_weights','gee_pairs','gee_convergence','gee_variance','lmm_design','lmm_pairs','lmm_variation','lmm_occasions']
rows={
'en':['GEE returned an invalid working correlation parameter; estimates were not accepted.','GEE returned an invalid working correlation matrix; estimates were not accepted.','Adjusted unstructured GEE does not yet support observation weights.','Unstructured GEE requires a unique, nonmissing time for each subject observation.','GEE did not converge; estimates were not accepted. Review the model and working correlation.','GEE returned invalid coefficient variances; estimates were not accepted.','Repeated LMM requires a finite numeric outcome and full-rank design.','Repeated LMM requires unique, nonmissing subject/time pairs.','Repeated LMM requires outcome variation.','Repeated LMM requires at least two occasions.'],
'ko':['GEE의 작업상관 모수가 유효하지 않아 추정값을 채택하지 않았습니다.','GEE의 작업상관행렬이 유효하지 않아 추정값을 채택하지 않았습니다.','보정 비구조적 GEE는 아직 관측치 가중치를 지원하지 않습니다.','비구조적 GEE는 대상자별 관측 시점이 중복되지 않고 결측이 없어야 합니다.','GEE가 수렴하지 않아 추정값을 채택하지 않았습니다. 모형과 작업상관 구조를 확인하세요.','GEE 계수의 분산이 유효하지 않아 추정값을 채택하지 않았습니다.','반복측정 LMM에는 유한한 숫자형 결과와 완전계수 설계행렬이 필요합니다.','반복측정 LMM은 대상자·시점 조합이 중복되지 않고 결측이 없어야 합니다.','반복측정 LMM에는 결과변수의 변동이 필요합니다.','반복측정 LMM에는 두 개 이상의 시점이 필요합니다.'],
'ja':['GEEの作業相関パラメータが無効なため、推定値を採用しませんでした。','GEEの作業相関行列が無効なため、推定値を採用しませんでした。','補正非構造化GEEは観測重みにまだ対応していません。','非構造化GEEでは、対象者ごとの観測時点に重複や欠測がない必要があります。','GEEが収束しなかったため、推定値を採用しませんでした。モデルと作業相関構造を確認してください。','GEEの係数分散が無効なため、推定値を採用しませんでした。','反復測定LMMには有限の数値アウトカムとフルランクの計画行列が必要です。','反復測定LMMでは対象者と時点の組合せに重複や欠測がない必要があります。','反復測定LMMにはアウトカムの変動が必要です。','反復測定LMMには少なくとも2時点が必要です。'],
'zh':['GEE 返回的工作相关参数无效，未接受估计值。','GEE 返回的工作相关矩阵无效，未接受估计值。','校正的非结构化 GEE 尚不支持观测权重。','非结构化 GEE 要求每个受试者的观测时间唯一且无缺失。','GEE 未收敛，未接受估计值。请检查模型和工作相关结构。','GEE 返回的系数方差无效，未接受估计值。','重复测量 LMM 需要有限的数值型结局和满秩设计矩阵。','重复测量 LMM 要求受试者与时间组合唯一且无缺失。','重复测量 LMM 要求结局变量存在变异。','重复测量 LMM 至少需要两个时间点。'],
'es':['GEE devolvió un parámetro de correlación de trabajo no válido; no se aceptaron las estimaciones.','GEE devolvió una matriz de correlación de trabajo no válida; no se aceptaron las estimaciones.','GEE no estructurado ajustado aún no admite pesos por observación.','GEE no estructurado requiere tiempos únicos y no faltantes para las observaciones de cada sujeto.','GEE no convergió; no se aceptaron las estimaciones. Revise el modelo y la correlación de trabajo.','GEE devolvió varianzas de coeficientes no válidas; no se aceptaron las estimaciones.','LMM de medidas repetidas requiere un resultado numérico finito y una matriz de diseño de rango completo.','LMM de medidas repetidas requiere pares sujeto/tiempo únicos y sin valores faltantes.','LMM de medidas repetidas requiere variación en el resultado.','LMM de medidas repetidas requiere al menos dos momentos.'],
'fr':['GEE a renvoyé un paramètre de corrélation de travail non valide ; les estimations ont été rejetées.','GEE a renvoyé une matrice de corrélation de travail non valide ; les estimations ont été rejetées.','GEE non structuré ajusté ne prend pas encore en charge les poids des observations.','GEE non structuré nécessite des temps uniques et non manquants pour les observations de chaque sujet.','GEE n’a pas convergé ; les estimations ont été rejetées. Vérifiez le modèle et la corrélation de travail.','GEE a renvoyé des variances de coefficients non valides ; les estimations ont été rejetées.','Le LMM à mesures répétées nécessite un résultat numérique fini et une matrice de conception de rang complet.','Le LMM à mesures répétées nécessite des paires sujet/temps uniques et non manquantes.','Le LMM à mesures répétées nécessite une variation du résultat.','Le LMM à mesures répétées nécessite au moins deux temps de mesure.'],
'de':['GEE lieferte einen ungültigen Arbeitskorrelationsparameter; die Schätzwerte wurden verworfen.','GEE lieferte eine ungültige Arbeitskorrelationsmatrix; die Schätzwerte wurden verworfen.','Das angepasste unstrukturierte GEE unterstützt noch keine Beobachtungsgewichte.','Unstrukturiertes GEE erfordert eindeutige, nicht fehlende Zeitpunkte für die Beobachtungen jeder Person.','GEE konvergierte nicht; die Schätzwerte wurden verworfen. Prüfen Sie Modell und Arbeitskorrelation.','GEE lieferte ungültige Koeffizientenvarianzen; die Schätzwerte wurden verworfen.','LMM für Messwiederholungen erfordert eine endliche numerische Zielvariable und eine Designmatrix mit vollem Rang.','LMM für Messwiederholungen erfordert eindeutige, nicht fehlende Personen-Zeit-Paare.','LMM für Messwiederholungen erfordert Variation der Zielvariable.','LMM für Messwiederholungen erfordert mindestens zwei Zeitpunkte.'],
'vi':['GEE trả về tham số tương quan làm việc không hợp lệ; các ước lượng không được chấp nhận.','GEE trả về ma trận tương quan làm việc không hợp lệ; các ước lượng không được chấp nhận.','GEE phi cấu trúc hiệu chỉnh chưa hỗ trợ trọng số quan sát.','GEE phi cấu trúc yêu cầu thời điểm quan sát của mỗi đối tượng không trùng lặp và không bị thiếu.','GEE không hội tụ; các ước lượng không được chấp nhận. Kiểm tra mô hình và tương quan làm việc.','GEE trả về phương sai hệ số không hợp lệ; các ước lượng không được chấp nhận.','LMM đo lặp yêu cầu kết quả dạng số hữu hạn và ma trận thiết kế đủ hạng.','LMM đo lặp yêu cầu cặp đối tượng/thời điểm không trùng lặp và không bị thiếu.','LMM đo lặp yêu cầu biến kết quả có biến thiên.','LMM đo lặp yêu cầu ít nhất hai thời điểm.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
