import json,re
from pathlib import Path
rows='''SEM quality checklist|SEM品質チェックリスト|SEM质量检查清单|Lista de calidad SEM|Liste de contrôle de qualité SEM|SEM-Qualitätscheckliste|Danh sách kiểm tra chất lượng SEM
PLS-SEM quality checklist|PLS-SEM品質チェックリスト|PLS-SEM质量检查清单|Lista de calidad PLS-SEM|Liste de contrôle de qualité PLS-SEM|PLS-SEM-Qualitätscheckliste|Danh sách kiểm tra chất lượng PLS-SEM
Quality status|品質状態|质量状态|Estado de calidad|État de qualité|Qualitätsstatus|Trạng thái chất lượng
Quality status: not assessed.|品質状態：未評価。|质量状态：未评估。|Estado de calidad: no evaluado.|État de qualité : non évalué.|Qualitätsstatus: nicht bewertet.|Trạng thái chất lượng: chưa đánh giá.
Reference only|基準として参照|仅供基准参考|Solo como referencia|Référence uniquement|Nur als Referenz|Chỉ tham khảo chuẩn
Descriptive only|記述的参考のみ|仅供描述参考|Solo descriptivo|Descriptif uniquement|Nur deskriptiv|Chỉ mô tả
Screen only|予備的点検のみ|仅作初筛|Solo exploratorio|Dépistage uniquement|Nur Vorprüfung|Chỉ sàng lọc
Reporting readiness: no quality-review blockers detected.|報告準備：品質検討を妨げる項目はありません。|报告准备度：未发现质量审查阻碍项。|Preparación para informar: sin impedimentos en la revisión de calidad.|Préparation au rapport : aucun obstacle détecté lors de la revue de qualité.|Berichtsbereitschaft: keine blockierenden Qualitätsprüfpunkte erkannt.|Sẵn sàng báo cáo: không phát hiện mục cản trở trong rà soát chất lượng.
Reporting readiness: blocked until {n} critical review item(s) are resolved.|報告準備：重大な検討項目{n}件の解決が必要です。|报告准备度：须先解决{n}项关键审查问题。|Preparación para informar: bloqueada hasta resolver {n} puntos críticos.|Préparation au rapport : bloquée jusqu’à résolution de {n} points critiques.|Berichtsbereitschaft: blockiert, bis {n} kritische Prüfpunkte behoben sind.|Sẵn sàng báo cáo: bị chặn cho đến khi giải quyết {n} mục nghiêm trọng.
Reporting readiness: requires resolution or explicit justification for {n} major review item(s).|報告準備：主要な検討項目{n}件の解決または明確な根拠が必要です。|报告准备度：{n}项主要审查问题需要解决或明确说明依据。|Preparación para informar: requiere resolver o justificar explícitamente {n} puntos importantes.|Préparation au rapport : {n} points majeurs doivent être résolus ou explicitement justifiés.|Berichtsbereitschaft: {n} wesentliche Prüfpunkte müssen behoben oder ausdrücklich begründet werden.|Sẵn sàng báo cáo: cần giải quyết hoặc nêu rõ căn cứ cho {n} mục quan trọng.
Reporting readiness: advisory review item(s) should be documented.|報告準備：参考検討項目は限界として記録してください。|报告准备度：应记录建议性审查事项。|Preparación para informar: documente los puntos orientativos.|Préparation au rapport : les points consultatifs doivent être documentés.|Berichtsbereitschaft: beratende Prüfpunkte sollten dokumentiert werden.|Sẵn sàng báo cáo: cần ghi nhận các mục rà soát mang tính khuyến nghị.
Review focus|検討が必要な項目|重点审查事项|Aspectos a revisar|Points à examiner|Prüfschwerpunkte|Nội dung cần xem xét
No Review rows in the quality checklist.|品質チェックリストに要検討項目はありません。|质量检查清单中无待审查项。|No hay filas que requieran revisión en la lista de calidad.|Aucune ligne à examiner dans la liste de contrôle de qualité.|Keine zu prüfenden Zeilen in der Qualitätscheckliste.|Không có dòng cần xem xét trong danh sách kiểm tra chất lượng.
Rows marked Review should be resolved or explicitly justified before confirmatory reporting.|「要検討」の行は確認的な報告の前に解決するか、明確な根拠を示してください。|标记为审查的行应在验证性报告前解决或明确说明依据。|Las filas marcadas para revisión deben resolverse o justificarse explícitamente antes de informar resultados confirmatorios.|Les lignes à examiner doivent être résolues ou explicitement justifiées avant un rapport confirmatoire.|Als prüfbedürftig markierte Zeilen sollten vor konfirmatorischen Berichten geklärt oder ausdrücklich begründet werden.|Các dòng cần xem xét phải được giải quyết hoặc giải trình rõ trước khi báo cáo kết quả khẳng định.
Critical|重大|关键|Crítica|Critique|Kritisch|Nghiêm trọng
Major|主要|主要|Importante|Majeure|Wesentlich|Quan trọng
Advisory|参考|建议性|Orientativa|Consultative|Beratend|Khuyến nghị
Priority|優先度|优先级|Prioridad|Priorité|Priorität|Mức ưu tiên
Action|対応|措施|Acción|Action|Maßnahme|Hành động
Resolve before reporting|報告前に解決|报告前解决|Resolver antes de informar|Résoudre avant le rapport|Vor Berichterstattung beheben|Giải quyết trước khi báo cáo
Resolve or justify|解決または根拠を提示|解决或说明依据|Resolver o justificar|Résoudre ou justifier|Beheben oder begründen|Giải quyết hoặc giải trình
Document limitation|限界として記録|记录局限性|Documentar la limitación|Documenter la limite|Einschränkung dokumentieren|Ghi nhận hạn chế
This checklist summarizes lavaan SEM/CFA convergence, admissibility, sample adequacy, common-method-bias screens, chi-square/df, robust/scaled fit source, global fit, measurement quality, discriminant-validity risk, and structural explanatory-power conditions for reporting and review.|このチェックリストは、lavaan SEM/CFAの収束、解の許容性、標本の適切性、共通方法バイアスの点検、χ²/df、ロバスト・補正済み適合度の出典、全体適合度、測定品質、弁別妥当性のリスク、構造モデルの説明力について、報告・検討の条件を要約します。|本清单汇总lavaan SEM/CFA的收敛、解的可接受性、样本适当性、共同方法偏差筛查、χ²/df、稳健或校正拟合指标来源、总体拟合、测量质量、区分效度风险及结构解释力的报告和审查条件。|Esta lista resume las condiciones de reporte y revisión de lavaan SEM/CFA: convergencia, admisibilidad, adecuación muestral, sesgo de método común, χ²/df, origen de índices robustos o escalados, ajuste global, calidad de medición, riesgo para la validez discriminante y poder explicativo estructural.|Cette liste résume les conditions de rapport et de revue de lavaan SEM/CFA : convergence, admissibilité, adéquation de l’échantillon, biais de méthode commune, χ²/df, source des indices robustes ou corrigés, ajustement global, qualité de mesure, risque de validité discriminante et pouvoir explicatif structurel.|Diese Checkliste fasst Berichts- und Prüfbedingungen für lavaan SEM/CFA zusammen: Konvergenz, Zulässigkeit, Stichprobenangemessenheit, Methodenverzerrung, χ²/df, Quelle robuster oder skalierter Fit-Indizes, globale Anpassung, Messqualität, Risiken der Diskriminanzvalidität und strukturelle Erklärungskraft.|Danh sách này tóm tắt điều kiện báo cáo và rà soát lavaan SEM/CFA: hội tụ, tính chấp nhận của nghiệm, độ phù hợp mẫu, sai lệch phương pháp chung, χ²/df, nguồn chỉ số phù hợp vững/hiệu chỉnh, độ phù hợp tổng thể, chất lượng đo lường, rủi ro giá trị phân biệt và sức giải thích cấu trúc.
This checklist summarizes PLS-SEM sample adequacy, approximate reflective-model fit diagnostics, measurement, collinearity, common-method-bias screens, explanatory power, and repeated PLSpredict boundary conditions for reporting and review.|このチェックリストは、PLS-SEMの標本の適切性、反映型モデルの近似適合度、測定、多重共線性、共通方法バイアス、説明力、反復PLSpredictの適用条件を報告・検討のために要約します。|本清单汇总PLS-SEM的样本适当性、反映式模型近似拟合诊断、测量、共线性、共同方法偏差筛查、解释力及重复PLSpredict的报告和审查适用条件。|Esta lista resume las condiciones de reporte y revisión de PLS-SEM: adecuación muestral, ajuste aproximado de modelos reflectivos, medición, colinealidad, sesgo de método común, poder explicativo y límites de PLSpredict repetido.|Cette liste résume les conditions de rapport et de revue de PLS-SEM : adéquation de l’échantillon, ajustement approché des modèles réflexifs, mesure, colinéarité, biais de méthode commune, pouvoir explicatif et conditions d’application de PLSpredict répété.|Diese Checkliste fasst Berichts- und Prüfbedingungen für PLS-SEM zusammen: Stichprobenangemessenheit, approximativer Fit reflektiver Modelle, Messung, Kollinearität, Methodenverzerrung, Erklärungskraft und Anwendungsgrenzen wiederholter PLSpredict-Auswertungen.|Danh sách này tóm tắt điều kiện báo cáo và rà soát PLS-SEM: độ phù hợp mẫu, chẩn đoán phù hợp xấp xỉ mô hình phản ánh, đo lường, đa cộng tuyến, sai lệch phương pháp chung, sức giải thích và điều kiện áp dụng PLSpredict lặp lại.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');d=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  row=line.split('|');assert len(row)==7
  d['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
