import json,re
from pathlib import Path
# Tabs delimit fields so mathematical absolute-value bars remain intact.
rows='''Admissible solution	許容可能な解	可接受的解	Solución admisible	Solution admissible	Zulässige Lösung	Nghiệm chấp nhận được
Model df	モデル自由度	模型自由度	Grados de libertad del modelo	Degrés de liberté du modèle	Modellfreiheitsgrade	Bậc tự do mô hình
Chi-square/df	カイ二乗/自由度	卡方/自由度	Chi-cuadrado/gl	Khi-deux/dl	Chi-Quadrat/df	Chi bình phương/bậc tự do
Fit statistic source	適合度統計量の出典	拟合统计量来源	Origen del estadístico de ajuste	Source des statistiques d’ajustement	Quelle der Fit-Statistiken	Nguồn thống kê độ phù hợp
N/free parameter ratio	N/自由パラメータ比	N/自由参数比	Razón N/parámetros libres	Rapport N/paramètres libres	N/freie-Parameter-Verhältnis	Tỷ số N/tham số tự do
Harman first-factor %	Harman第1因子の割合（%）	Harman第一因子占比（%）	Porcentaje del primer factor de Harman	Pourcentage du premier facteur de Harman	Harman-Erstfaktoranteil (%)	Tỷ lệ nhân tố thứ nhất Harman (%)
Max full collinearity VIF	最大完全共線性VIF	最大全共线性VIF	VIF máximo de colinealidad completa	VIF maximal de colinéarité complète	Maximaler Vollkollinearitäts-VIF	VIF đa cộng tuyến toàn phần lớn nhất
Min standardized loading	最小標準化負荷量	最小标准化载荷	Carga estandarizada mínima	Saturation standardisée minimale	Kleinste standardisierte Ladung	Hệ số tải chuẩn hóa nhỏ nhất
Min CR	最小CR	最小CR	CR mínimo	CR minimal	Kleinster CR-Wert	CR nhỏ nhất
Min AVE	最小AVE	最小AVE	AVE mínimo	AVE minimale	Kleinster AVE-Wert	AVE nhỏ nhất
Max latent correlation	最大潜在相関	最大潜变量相关	Correlación latente máxima	Corrélation latente maximale	Größte latente Korrelation	Tương quan tiềm ẩn lớn nhất
Structural path count	構造パス数	结构路径数	Número de rutas estructurales	Nombre de chemins structurels	Anzahl struktureller Pfade	Số đường dẫn cấu trúc
Max structural beta	最大構造β	最大结构β	Beta estructural máximo	Bêta structurel maximal	Größtes strukturelles Beta	Beta cấu trúc lớn nhất
Min endogenous R2	最小内生R²	最小内生R²	R² endógeno mínimo	R² endogène minimal	Kleinstes endogenes R²	R² nội sinh nhỏ nhất
Model status	モデルの状態	模型状态	Estado del modelo	Statut du modèle	Modellstatus	Trạng thái mô hình
Original/prespecified model	元の事前指定モデル	原始/预先指定模型	Modelo original/preespecificado	Modèle initial/préspécifié	Ursprüngliches/vorab spezifiziertes Modell	Mô hình gốc/định trước
Exploratory modified model	探索的修正モデル	探索性修改模型	Modelo modificado exploratorio	Modèle modifié exploratoire	Explorativ modifiziertes Modell	Mô hình sửa đổi mang tính khám phá
Must be TRUE before interpreting estimates.	推定値を解釈する前に「はい」である必要があります。	解释估计值前必须为“是”。	Debe ser afirmativo antes de interpretar las estimaciones.	Doit être affirmatif avant d’interpréter les estimations.	Muss vor der Interpretation der Schätzwerte bejaht sein.	Phải là có trước khi diễn giải ước lượng.
Must be TRUE before reporting fit, reliability, validity, or structural paths as final.	適合度・信頼性・妥当性・構造パスを最終結果として報告する前に「はい」である必要があります。	将拟合、信度、效度或结构路径作为最终结果报告前必须为“是”。	Debe ser afirmativo antes de informar el ajuste, la fiabilidad, la validez o las rutas estructurales como definitivos.	Doit être affirmatif avant de présenter l’ajustement, la fiabilité, la validité ou les chemins structurels comme définitifs.	Muss bejaht sein, bevor Fit, Reliabilität, Validität oder strukturelle Pfade als endgültig berichtet werden.	Phải là có trước khi báo cáo độ phù hợp, độ tin cậy, giá trị hoặc đường dẫn cấu trúc như kết quả cuối cùng.
df = 0 indicates a saturated model; approximate fit is not substantively diagnostic.	df = 0は飽和モデルを示し、近似適合度には実質的な診断力がありません。	df = 0表示饱和模型；近似拟合不具有实质诊断意义。	df = 0 indica un modelo saturado; el ajuste aproximado no aporta un diagnóstico sustantivo.	df = 0 indique un modèle saturé ; l’ajustement approché n’a pas de portée diagnostique substantielle.	df = 0 kennzeichnet ein saturiertes Modell; approximativer Fit ist inhaltlich nicht diagnostisch.	df = 0 biểu thị mô hình bão hòa; độ phù hợp xấp xỉ không có ý nghĩa chẩn đoán thực chất.
Descriptive ratio only; conventional ranges are not a model-acceptance test. Large values flag possible misfit for investigation.	記述的な比率です。慣用的な範囲はモデル採択の検定ではありません。大きな値は不適合の可能性を検討する目安です。	仅为描述性比值；惯用范围不是模型接受检验。较大值提示需检查可能的拟合不良。	Es una razón descriptiva; los rangos convencionales no prueban la aceptación del modelo. Los valores altos señalan posible desajuste que debe investigarse.	Il s’agit d’un rapport descriptif ; les plages usuelles ne constituent pas un test d’acceptation du modèle. Des valeurs élevées signalent un défaut d’ajustement possible à examiner.	Nur ein deskriptives Verhältnis; übliche Bereiche sind kein Modellakzeptanztest. Große Werte weisen auf möglichen Fehlfit hin, der zu prüfen ist.	Chỉ là tỷ số mô tả; khoảng thường dùng không phải kiểm định chấp nhận mô hình. Giá trị lớn gợi ý cần xem xét độ phù hợp kém.
Records whether lavaan robust/scaled or conventional fit statistics were selected.	lavaanのロバスト・補正済み統計量と通常の適合度統計量のどちらを選んだかを記録します。	记录所选为lavaan稳健/校正统计量还是常规拟合统计量。	Registra si se seleccionaron estadísticas de ajuste robustas/escaladas o convencionales de lavaan.	Indique si les statistiques d’ajustement lavaan retenues sont robustes/corrigées ou conventionnelles.	Dokumentiert, ob robuste/skalierte oder konventionelle lavaan-Fit-Statistiken gewählt wurden.	Ghi nhận đã chọn thống kê độ phù hợp vững/hiệu chỉnh hay thông thường của lavaan.
Descriptive sample-size ratio only; no universal N-to-parameter cutoff establishes adequate power or stable estimation.	標本サイズの記述的な比率です。検定力や安定した推定を保証する普遍的なN/パラメータ基準はありません。	仅为描述性样本量比；不存在可确立充分检验力或稳定估计的通用N/参数阈值。	Es una razón descriptiva del tamaño muestral; ningún umbral universal N/parámetros establece potencia adecuada o estimación estable.	Ce rapport décrit la taille de l’échantillon ; aucun seuil universel N/paramètres ne garantit une puissance suffisante ou une estimation stable.	Nur ein deskriptives Stichprobenverhältnis; kein universeller N/Parameter-Grenzwert belegt ausreichende Teststärke oder stabile Schätzung.	Chỉ là tỷ số cỡ mẫu mô tả; không có ngưỡng N/tham số phổ quát xác lập lực kiểm định đủ hoặc ước lượng ổn định.
Exploratory Harman screen only; values above 50% may flag concentration, while lower values do not rule out common-method bias.	探索的なHarman点検です。50%超は集中を示す可能性がありますが、それ未満でも共通方法バイアスを否定できません。	仅作探索性Harman筛查；超过50%可能提示集中，但较低值也不能排除共同方法偏差。	Es una exploración de Harman; valores superiores al 50% pueden indicar concentración, pero valores menores no descartan sesgo de método común.	Dépistage exploratoire de Harman uniquement ; au-delà de 50 %, une concentration est possible, mais des valeurs inférieures n’excluent pas le biais de méthode commune.	Nur explorative Harman-Prüfung; Werte über 50% können Konzentration anzeigen, niedrigere Werte schließen Methodenverzerrung jedoch nicht aus.	Chỉ sàng lọc Harman mang tính khám phá; giá trị trên 50% có thể gợi ý tập trung, nhưng giá trị thấp hơn không loại trừ sai lệch phương pháp chung.
Exploratory full-collinearity screen only; values above 3.3 are nonspecific and lower values do not rule out common-method bias.	探索的な完全共線性点検です。3.3超は非特異的な兆候であり、それ未満でも共通方法バイアスを否定できません。	仅作探索性全共线性筛查；超过3.3不具特异性，较低值也不能排除共同方法偏差。	Es una exploración de colinealidad completa; valores superiores a 3.3 son inespecíficos y valores menores no descartan sesgo de método común.	Dépistage exploratoire de colinéarité complète uniquement ; les valeurs supérieures à 3.3 sont non spécifiques et les valeurs inférieures n’excluent pas le biais de méthode commune.	Nur explorative Vollkollinearitätsprüfung; Werte über 3.3 sind unspezifisch, niedrigere Werte schließen Methodenverzerrung nicht aus.	Chỉ sàng lọc đa cộng tuyến toàn phần mang tính khám phá; giá trị trên 3.3 không đặc hiệu, còn giá trị thấp hơn không loại trừ sai lệch phương pháp chung.
Common .90/.95 values are descriptive references, not universal acceptance rules; interpret with residuals, model complexity, and theory.	慣用的な.90/.95は記述的な参考値であり、普遍的な採択規則ではありません。残差・モデルの複雑さ・理論と併せて解釈します。	常用的.90/.95是描述性参考值，并非通用接受规则；需结合残差、模型复杂度和理论解释。	Los valores usuales .90/.95 son referencias descriptivas, no reglas universales de aceptación; interprételos con los residuos, la complejidad y la teoría.	Les valeurs usuelles .90/.95 sont des repères descriptifs, non des règles universelles d’acceptation ; interprétez-les avec les résidus, la complexité et la théorie.	Übliche Werte von .90/.95 sind deskriptive Referenzen, keine universellen Akzeptanzregeln; berücksichtigen Sie Residuen, Modellkomplexität und Theorie.	Các giá trị thường dùng .90/.95 là mốc mô tả, không phải quy tắc chấp nhận phổ quát; diễn giải cùng phần dư, độ phức tạp mô hình và lý thuyết.
Common .08/.06 values are descriptive references; interpret the estimate and CI with df, sample size, residuals, and theory.	慣用的な.08/.06は記述的な参考値です。推定値とCIを自由度・標本サイズ・残差・理論と併せて解釈します。	常用的.08/.06是描述性参考值；需结合自由度、样本量、残差和理论解释估计值与CI。	Los valores usuales .08/.06 son referencias descriptivas; interprete la estimación y el IC con los gl, el tamaño muestral, los residuos y la teoría.	Les valeurs usuelles .08/.06 sont des repères descriptifs ; interprétez l’estimation et l’IC avec les degrés de liberté, la taille d’échantillon, les résidus et la théorie.	Übliche Werte von .08/.06 sind deskriptive Referenzen; interpretieren Sie Schätzwert und KI zusammen mit df, Stichprobenumfang, Residuen und Theorie.	Các giá trị thường dùng .08/.06 là mốc mô tả; diễn giải ước lượng và khoảng tin cậy cùng df, cỡ mẫu, phần dư và lý thuyết.
Common .10/.08 values are descriptive references, not universal acceptance rules; inspect the residual pattern and substantive size.	慣用的な.10/.08は記述的な参考値であり、普遍的な採択規則ではありません。残差のパターンと実質的な大きさを確認します。	常用的.10/.08是描述性参考值，并非通用接受规则；请检查残差模式及实际大小。	Los valores usuales .10/.08 son referencias descriptivas, no reglas universales; examine el patrón y la magnitud sustantiva de los residuos.	Les valeurs usuelles .10/.08 sont des repères descriptifs, non des règles universelles ; examinez la structure et l’ampleur substantielle des résidus.	Übliche Werte von .10/.08 sind deskriptive Referenzen, keine universellen Akzeptanzregeln; prüfen Sie Muster und inhaltliches Ausmaß der Residuen.	Các giá trị thường dùng .10/.08 là mốc mô tả, không phải quy tắc phổ quát; xem xét mẫu phần dư và mức độ thực chất.
Loading values are descriptive evidence, not automatic item-retention rules. Review low values with content validity, residuals, cross-loadings, uncertainty, and prespecified theory.	負荷量は記述的な根拠であり、項目を自動的に採用する規則ではありません。低い値は内容妥当性・残差・交差負荷・不確実性・事前の理論と併せて検討します。	载荷是描述性证据，并非自动保留题项的规则。低值需结合内容效度、残差、交叉载荷、不确定性和预先指定理论审查。	Las cargas son evidencia descriptiva, no reglas automáticas de retención. Revise los valores bajos con la validez de contenido, residuos, cargas cruzadas, incertidumbre y teoría preespecificada.	Les saturations sont des éléments descriptifs, non des règles automatiques de conservation des items. Examinez les faibles valeurs avec la validité de contenu, les résidus, les saturations croisées, l’incertitude et la théorie préspécifiée.	Ladungen sind deskriptive Evidenz, keine automatischen Regeln zum Behalten von Items. Prüfen Sie niedrige Werte anhand von Inhaltsvalidität, Residuen, Kreuzladungen, Unsicherheit und vorab festgelegter Theorie.	Hệ số tải là bằng chứng mô tả, không phải quy tắc tự động giữ mục đo. Xem xét giá trị thấp cùng giá trị nội dung, phần dư, tải chéo, độ bất định và lý thuyết định trước.
The .70 value is a descriptive reliability reference, not a universal scale-acceptance rule; report the estimate, formula, and uncertainty.	.70は信頼性の記述的参考値であり、尺度採択の普遍的規則ではありません。推定値・計算式・不確実性を報告します。	.70是描述性信度参考值，并非通用量表接受规则；请报告估计值、公式和不确定性。	.70 es una referencia descriptiva de fiabilidad, no una regla universal de aceptación; informe la estimación, la fórmula y la incertidumbre.	.70 est un repère descriptif de fiabilité, non une règle universelle d’acceptation ; rapportez l’estimation, la formule et l’incertitude.	.70 ist ein deskriptiver Reliabilitätsreferenzwert, keine universelle Skalenakzeptanzregel; berichten Sie Schätzwert, Formel und Unsicherheit.	.70 là mốc độ tin cậy mô tả, không phải quy tắc chấp nhận thang đo phổ quát; báo cáo ước lượng, công thức và độ bất định.
The .50 value is a descriptive convergent-validity reference, not an automatic construct-acceptance or item-deletion rule.	.50は収束妥当性の記述的参考値であり、構成概念の採択や項目削除の自動規則ではありません。	.50是描述性聚合效度参考值，并非自动接受构念或删除题项的规则。	.50 es una referencia descriptiva de validez convergente, no una regla automática para aceptar constructos o eliminar ítems.	.50 est un repère descriptif de validité convergente, non une règle automatique d’acceptation des construits ou de suppression des items.	.50 ist ein deskriptiver Referenzwert der konvergenten Validität, keine automatische Regel zur Konstruktakzeptanz oder Itemlöschung.	.50 là mốc giá trị hội tụ mô tả, không phải quy tắc tự động chấp nhận cấu trúc hoặc xóa mục đo.
Latent-correlation references do not establish discriminant validity; interpret with HTMT intervals, cross-loadings, local fit, theory, and competing measurement models.	潜在相関の参考値だけでは弁別妥当性を確定できません。HTMT区間・交差負荷・局所適合度・理論・競合する測定モデルと併せて解釈します。	潜变量相关参考值不能确立区分效度；需结合HTMT区间、交叉载荷、局部拟合、理论及竞争测量模型解释。	Las referencias de correlación latente no establecen validez discriminante; interprete con intervalos HTMT, cargas cruzadas, ajuste local, teoría y modelos de medición alternativos.	Les repères de corrélation latente n’établissent pas la validité discriminante ; interprétez-les avec les intervalles HTMT, les saturations croisées, l’ajustement local, la théorie et les modèles de mesure concurrents.	Referenzen für latente Korrelationen belegen keine Diskriminanzvalidität; berücksichtigen Sie HTMT-Intervalle, Kreuzladungen, lokalen Fit, Theorie und konkurrierende Messmodelle.	Mốc tương quan tiềm ẩn không xác lập giá trị phân biệt; diễn giải cùng khoảng HTMT, tải chéo, độ phù hợp cục bộ, lý thuyết và mô hình đo lường cạnh tranh.
Report whether the model includes structural regressions.	モデルに構造回帰を含むか報告してください。	请报告模型是否包含结构回归。	Informe si el modelo incluye regresiones estructurales.	Indiquez si le modèle comprend des régressions structurelles.	Berichten Sie, ob das Modell strukturelle Regressionen enthält.	Báo cáo mô hình có bao gồm hồi quy cấu trúc hay không.
Inspect coefficients near or above |1| for inadmissibility or suppression.	絶対値が1に近い、または1を超える係数は、不適解や抑制効果を確認してください。	对绝对值接近或超过1的系数检查不可接受解或抑制效应。	Examine los coeficientes cercanos o superiores a |1| por inadmisibilidad o supresión.	Examinez les coefficients proches ou supérieurs à |1| pour détecter une inadmissibilité ou une suppression.	Prüfen Sie Koeffizienten nahe oder über |1| auf unzulässige Lösungen oder Suppression.	Kiểm tra hệ số gần hoặc vượt |1| về nghiệm không chấp nhận được hoặc hiệu ứng ức chế.
Report R2 descriptively for each endogenous construct; no universal value establishes adequate explanation or causal importance.	各内生構成概念のR²を記述的に報告します。十分な説明力や因果的重要性を示す普遍的な値はありません。	请描述性报告每个内生构念的R²；不存在可确立充分解释力或因果重要性的通用值。	Informe R² descriptivamente para cada constructo endógeno; ningún valor universal establece explicación adecuada o importancia causal.	Rapportez R² de façon descriptive pour chaque construit endogène ; aucune valeur universelle n’établit une explication suffisante ou une importance causale.	Berichten Sie R² deskriptiv für jedes endogene Konstrukt; kein universeller Wert belegt ausreichende Erklärungskraft oder kausale Bedeutung.	Báo cáo R² theo mô tả cho từng cấu trúc nội sinh; không có giá trị phổ quát xác lập sức giải thích đủ hoặc tầm quan trọng nhân quả.
MI-based modifications are exploratory unless validated in independent data.	MIに基づく修正は独立データで検証されない限り探索的です。	基于MI的修改除非在独立数据中验证，否则属于探索性。	Las modificaciones basadas en MI son exploratorias salvo validación con datos independientes.	Les modifications fondées sur les MI restent exploratoires sans validation sur des données indépendantes.	MI-basierte Änderungen sind explorativ, solange sie nicht mit unabhängigen Daten validiert wurden.	Sửa đổi dựa trên MI mang tính khám phá trừ khi được xác minh bằng dữ liệu độc lập.'''
rows += '\nYes\tはい\t是\tSí\tOui\tJa\tCó\nNo\tいいえ\t否\tNo\tNon\tNein\tKhông'
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');d=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  row=line.split('\t');assert len(row)==7,row
  d['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
