import json,re
from pathlib import Path
rows='''Identification and power preflight|식별성 및 검정력 사전점검|識別性と検出力の事前確認|识别性与检验效能预检|Comprobación previa de identificación y potencia|Vérification préalable de l’identification et de la puissance|Vorabprüfung von Identifikation und Teststärke|Kiểm tra trước tính nhận dạng và lực kiểm định
Latent constructs|잠재 구성개념|潜在構成概念|潜在构念|Constructos latentes|Construits latents|Latente Konstrukte|Cấu trúc tiềm ẩn
Observed indicators|관측 지표|観測指標|观测指标|Indicadores observados|Indicateurs observés|Beobachtete Indikatoren|Chỉ báo quan sát
Structural paths|구조경로|構造パス|结构路径|Rutas estructurales|Chemins structurels|Strukturelle Pfade|Đường dẫn cấu trúc
Latent scaling|잠재변수 척도|潜在変数の尺度設定|潜变量定标|Escalamiento de variables latentes|Mise à l’échelle des variables latentes|Skalierung latenter Variablen|Định thang biến tiềm ẩn
Model df|모형 자유도|モデル自由度|模型自由度|Grados de libertad del modelo|Degrés de liberté du modèle|Modellfreiheitsgrade|Bậc tự do mô hình
Free parameters|자유모수|自由パラメータ|自由参数|Parámetros libres|Paramètres libres|Freie Parameter|Tham số tự do
A-priori power basis|사전 검정력 근거|事前検出力の根拠|事前检验效能依据|Fundamento de potencia a priori|Fondement de puissance a priori|Grundlage der A-priori-Teststärke|Căn cứ lực kiểm định tiên nghiệm
Latent variance = 1|잠재분산 = 1|潜在分散 = 1|潜变量方差 = 1|Varianza latente = 1|Variance latente = 1|Latente Varianz = 1|Phương sai tiềm ẩn = 1
Marker loading = 1|표지 지표 적재량 = 1|マーカー負荷量 = 1|标记指标载荷 = 1|Carga del indicador marcador = 1|Saturation de l’indicateur marqueur = 1|Markerladung = 1|Tải chỉ báo đánh dấu = 1
Not recorded; not inferred from fitted data|기록되지 않음; 적합된 자료에서 역산하지 않음|未記録；適合データから逆算しない|未记录；不从拟合数据反推|No registrado; no inferido de los datos ajustados|Non consigné ; non inféré des données ajustées|Nicht dokumentiert; nicht aus angepassten Daten abgeleitet|Chưa ghi nhận; không suy ngược từ dữ liệu đã khớp
%s: details not recorded|%s: 상세 기록 없음|%s：詳細未記録|%s：未记录详情|%s: detalles no registrados|%s : détails non consignés|%s: Details nicht dokumentiert|%s: chưa ghi nhận chi tiết
No rule-based pre-fit identification issues were detected.|규칙 기반 사전 식별성 문제는 발견되지 않았습니다.|規則に基づく推定前の識別性の問題は検出されませんでした。|未检测到基于规则的拟合前识别性问题。|No se detectaron problemas de identificación previos al ajuste basados en reglas.|Aucun problème d’identification fondé sur les règles n’a été détecté avant ajustement.|Keine regelbasierten Identifikationsprobleme vor der Schätzung erkannt.|Không phát hiện vấn đề nhận dạng trước khớp mô hình theo quy tắc.
This rule-based screen does not prove mathematical identification; lavaan estimation, degrees of freedom, information-matrix checks, and solution admissibility remain decisive.|이 규칙 기반 점검만으로 수학적 식별성이 증명되지는 않습니다. lavaan 추정, 자유도, 정보행렬 점검, 해의 허용성이 최종 판단 기준입니다.|この規則に基づく確認は数学的識別性を証明しません。lavaan推定、自由度、情報行列の確認、解の適切性が最終判断の基準です。|此规则检查不能证明数学识别性；lavaan估计、自由度、信息矩阵检查及解的可接受性仍是决定依据。|Esta revisión basada en reglas no demuestra identificación matemática; siguen siendo decisivos la estimación lavaan, los grados de libertad, la matriz de información y la admisibilidad de la solución.|Ce contrôle fondé sur des règles ne prouve pas l’identification mathématique ; l’estimation lavaan, les degrés de liberté, la matrice d’information et l’admissibilité de la solution restent déterminants.|Diese regelbasierte Prüfung beweist keine mathematische Identifikation; lavaan-Schätzung, Freiheitsgrade, Informationsmatrix und Zulässigkeit der Lösung bleiben entscheidend.|Kiểm tra theo quy tắc này không chứng minh tính nhận dạng toán học; ước lượng lavaan, bậc tự do, ma trận thông tin và tính chấp nhận của nghiệm vẫn quyết định.
Power is not back-calculated from fitted-sample p values. Record an a-priori RMSEA-power analysis or a simulation based on explicitly specified parameters and model structure.|검정력은 적합된 표본의 유의확률에서 역산하지 않습니다. 연구 전 RMSEA 검정력 또는 명시한 모수·모형을 이용한 시뮬레이션 근거를 별도로 기록하십시오.|検出力は適合標本のp値から逆算しません。事前のRMSEA検出力分析、または明示したパラメータとモデル構造に基づくシミュレーションを記録してください。|不从拟合样本的p值反推检验效能。请记录事前RMSEA效能分析，或基于明确参数及模型结构的模拟依据。|La potencia no se calcula retrospectivamente a partir de valores p de la muestra ajustada. Registre un análisis a priori de potencia RMSEA o una simulación con parámetros y estructura del modelo explícitos.|La puissance n’est pas calculée rétrospectivement à partir des valeurs p de l’échantillon ajusté. Consignez une analyse a priori de puissance RMSEA ou une simulation avec paramètres et structure de modèle explicites.|Teststärke wird nicht aus p-Werten der angepassten Stichprobe zurückgerechnet. Dokumentieren Sie eine A-priori-RMSEA-Teststärkeanalyse oder eine Simulation mit expliziten Parametern und Modellstruktur.|Không tính ngược lực kiểm định từ giá trị p của mẫu đã khớp. Ghi nhận phân tích lực kiểm định RMSEA tiên nghiệm hoặc mô phỏng dựa trên tham số và cấu trúc mô hình được chỉ rõ.'''
rows += '\nElement|요소|要素|元素|Elemento|Élément|Element|Phần tử'
data_rows=[r.split('|') for r in rows.splitlines()]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],2):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in data_rows:
  assert len(row)==8 and row[0].count('%s')==row[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
