import json,re
from pathlib import Path
rows='''Research model vs exploratory modified model|연구모형 vs 탐색적 수정모형|研究モデルと探索的修正モデル|研究模型与探索性修正模型|Modelo de investigación frente a modelo modificado exploratorio|Modèle de recherche et modèle modifié exploratoire|Forschungsmodell und explorativ modifiziertes Modell|Mô hình nghiên cứu và mô hình điều chỉnh khám phá
A formal model-difference test was suppressed: %s|공식 모형 차이 검정을 표시하지 않았습니다: %s|正式なモデル差検定を表示しませんでした：%s|未显示正式模型差异检验：%s|No se mostró una prueba formal de diferencia entre modelos: %s|Le test formel de différence entre modèles n’a pas été affiché : %s|Ein formaler Modelldifferenztest wurde nicht angezeigt: %s|Không hiển thị kiểm định chênh lệch mô hình chính thức: %s
Because the modification was selected using MI from the same data, this difference test is exploratory and should not be treated as confirmatory evidence.|이 수정은 동일 자료의 MI를 보고 선택했으므로, 이 차이 검정은 탐색적 결과이며 확인적 근거로 해석하면 안 됩니다.|同じデータのMIに基づいて修正を選択したため、この差検定は探索的であり確認的証拠として扱えません。|此修正根据同一数据的MI选择，因此该差异检验是探索性的，不应作为验证性证据。|La modificación se seleccionó con MI de los mismos datos; esta prueba es exploratoria y no debe tratarse como evidencia confirmatoria.|La modification a été choisie avec les MI des mêmes données ; ce test est exploratoire et ne constitue pas une preuve confirmatoire.|Die Modifikation wurde anhand der MI derselben Daten ausgewählt; dieser Test ist explorativ und darf nicht als konfirmatorische Evidenz gelten.|Điều chỉnh được chọn theo MI từ cùng dữ liệu, nên kiểm định này mang tính khám phá và không được xem là bằng chứng khẳng định.
eligibility was not established|비교 가능 조건이 확인되지 않았습니다|比較条件を確認できませんでした|未确认比较条件|no se verificaron las condiciones de comparación|les conditions de comparaison n’ont pas été établies|Vergleichsvoraussetzungen wurden nicht bestätigt|chưa xác lập điều kiện so sánh
Models use different sample sizes.|모형의 표본 크기가 다릅니다.|モデルの標本サイズが異なります。|模型使用不同样本量。|Los modelos usan tamaños muestrales diferentes.|Les modèles utilisent des tailles d’échantillon différentes.|Die Modelle verwenden unterschiedliche Stichprobengrößen.|Các mô hình dùng cỡ mẫu khác nhau.
Models use different observed variables.|모형의 관측변수가 다릅니다.|モデルの観測変数が異なります。|模型使用不同观测变量。|Los modelos usan variables observadas diferentes.|Les modèles utilisent des variables observées différentes.|Die Modelle verwenden unterschiedliche beobachtete Variablen.|Các mô hình dùng biến quan sát khác nhau.
Models do not use the same analyzed observations and values.|모형이 동일한 분석 관측치와 값을 사용하지 않습니다.|モデルは同じ分析対象の観測値と値を使用していません。|模型未使用相同的分析观测及数值。|Los modelos no usan las mismas observaciones y valores analizados.|Les modèles n’utilisent pas les mêmes observations et valeurs analysées.|Die Modelle verwenden nicht dieselben analysierten Beobachtungen und Werte.|Các mô hình không dùng cùng quan sát và giá trị được phân tích.
Models use different group structures.|모형의 집단 구조가 다릅니다.|モデルの群構造が異なります。|模型使用不同组结构。|Los modelos usan estructuras de grupos diferentes.|Les modèles utilisent des structures de groupes différentes.|Die Modelle verwenden unterschiedliche Gruppenstrukturen.|Các mô hình dùng cấu trúc nhóm khác nhau.
Models use incompatible estimator families.|모형의 추정량 계열이 호환되지 않습니다.|モデルの推定量系列が互換ではありません。|模型的估计量类别不兼容。|Las familias de estimadores de los modelos son incompatibles.|Les familles d’estimateurs des modèles sont incompatibles.|Die Schätzerfamilien der Modelle sind nicht kompatibel.|Các họ phương pháp ước lượng không tương thích.
Models use different ML likelihood conventions.|모형의 ML 우도 규약이 다릅니다.|モデルのML尤度規約が異なります。|模型使用不同ML似然约定。|Los modelos usan convenciones de verosimilitud ML diferentes.|Les modèles utilisent des conventions de vraisemblance ML différentes.|Die Modelle verwenden unterschiedliche ML-Likelihood-Konventionen.|Các mô hình dùng quy ước hợp lý ML khác nhau.
Models do not have different finite degrees of freedom.|모형의 자유도가 유한하면서 서로 다른 조건을 충족하지 않습니다.|モデルの自由度が有限かつ異なるという条件を満たしません。|模型未满足自由度有限且不同的条件。|Los modelos no tienen grados de libertad finitos diferentes.|Les modèles n’ont pas de degrés de liberté finis différents.|Die Modelle haben keine unterschiedlichen endlichen Freiheitsgrade.|Các mô hình không có bậc tự do hữu hạn khác nhau.
A strict free-parameter nesting relation was not verified.|자유모수의 엄격한 내포 관계가 확인되지 않았습니다.|自由パラメータの厳密な入れ子関係を確認できませんでした。|未确认自由参数的严格嵌套关系。|No se verificó una relación estricta de anidamiento de parámetros libres.|Une relation stricte d’emboîtement des paramètres libres n’a pas été vérifiée.|Eine strikte Schachtelung der freien Parameter wurde nicht bestätigt.|Chưa xác minh quan hệ lồng nhau nghiêm ngặt của tham số tự do.
Nesting was verified, but lavaan did not return a usable difference test.|내포 관계는 확인했지만 lavaan이 사용 가능한 차이검정을 반환하지 않았습니다.|入れ子関係は確認できましたが、lavaanは利用可能な差検定を返しませんでした。|已确认嵌套关系，但lavaan未返回可用差异检验。|Se verificó el anidamiento, pero lavaan no devolvió una prueba de diferencia utilizable.|L’emboîtement a été vérifié, mais lavaan n’a pas renvoyé de test de différence utilisable.|Die Schachtelung wurde bestätigt, aber lavaan lieferte keinen verwendbaren Differenztest.|Đã xác minh tính lồng nhau nhưng lavaan không trả về kiểm định chênh lệch khả dụng.
One or both models are inadmissible.|하나 이상의 모형이 허용 불가능한 해를 산출했습니다.|一方または両方のモデルが不適解です。|一个或两个模型的解不可接受。|Uno o ambos modelos tienen soluciones inadmisibles.|Un ou les deux modèles présentent des solutions inadmissibles.|Ein oder beide Modelle haben unzulässige Lösungen.|Một hoặc cả hai mô hình có nghiệm không chấp nhận được.
Chi-Squared Difference Test|카이제곱 차이검정|カイ二乗差検定|卡方差异检验|Prueba de diferencia chi-cuadrado|Test de différence du khi-deux|Chi-Quadrat-Differenztest|Kiểm định chênh lệch chi bình phương
Likelihood-ratio difference test|우도비 차이검정|尤度比差検定|似然比差异检验|Prueba de diferencia de razón de verosimilitudes|Test de différence du rapport de vraisemblance|Likelihood-Quotienten-Differenztest|Kiểm định chênh lệch tỷ số hợp lý
Scaled chi-square difference test (method: %s). The Chisq column contains standard test statistics, not the robust statistics to report for each model. The robust difference test is a function of two standard statistics.|척도 보정 카이제곱 차이검정(방법: %s). Chisq 열에는 각 모형에 보고할 강건 통계량이 아닌 일반 검정통계량이 들어 있습니다. 강건 차이검정은 두 일반 통계량의 함수입니다.|尺度補正カイ二乗差検定（方法：%s）。Chisq列は各モデルで報告すべき頑健統計量ではなく通常の検定統計量です。頑健差検定は二つの通常統計量の関数です。|缩放卡方差异检验（方法：%s）。Chisq列为普通检验统计量，并非各模型应报告的稳健统计量。稳健差异检验是两个普通统计量的函数。|Prueba de diferencia chi-cuadrado escalada (método: %s). Chisq contiene estadísticas estándar, no las robustas que se deben informar para cada modelo. La prueba robusta es función de dos estadísticas estándar.|Test de différence du khi-deux corrigé (méthode : %s). Chisq contient les statistiques standard, pas les statistiques robustes à rapporter pour chaque modèle. Le test robuste est fonction de deux statistiques standard.|Skalierter Chi-Quadrat-Differenztest (Methode: %s). Chisq enthält Standardteststatistiken, nicht die je Modell zu berichtenden robusten Statistiken. Der robuste Differenztest ist eine Funktion zweier Standardstatistiken.|Kiểm định chênh lệch chi bình phương hiệu chỉnh thang đo (phương pháp: %s). Cột Chisq chứa thống kê chuẩn, không phải thống kê vững cần báo cáo cho từng mô hình. Kiểm định chênh lệch vững là hàm của hai thống kê chuẩn.'''
data_rows=[r.split('|') for r in rows.splitlines()]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],2):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in data_rows:
  assert len(row)==8 and row[0].count('%s')==row[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
