import json,re
from pathlib import Path
rows='''Parcel-plan safety review|項目パーセル計画の安全性点検|题项打包计划安全检查|Revisión de seguridad del plan de parcelas|Vérification de sécurité du plan de parcelles|Sicherheitsprüfung des Parcel-Plans|Kiểm tra an toàn kế hoạch gộp mục
Preview unavailable: %s|プレビューを利用できません：%s|无法预览：%s|Vista previa no disponible: %s|Aperçu indisponible : %s|Vorschau nicht verfügbar: %s|Không thể xem trước: %s
Recorded purpose: |記録された目的：|已记录的目的：|Propósito registrado: |Objectif consigné : |Dokumentierter Zweck: |Mục đích đã ghi: 
Status: %s. %s|状態：%s。%s|状态：%s。%s|Estado: %s. %s|Statut : %s. %s|Status: %s. %s|Trạng thái: %s. %s
The result model fitted %s as a higher-order factor with lower-order item-level factors: %s.|結果モデルでは%sを高次因子とし、項目レベルの低次因子%sを適合しました。|结果模型将%s拟合为高阶因子，题项层面的低阶因子为：%s。|El modelo resultante ajustó %s como factor de orden superior con factores de orden inferior a nivel de ítem: %s.|Le modèle obtenu a ajusté %s comme facteur d’ordre supérieur avec les facteurs d’ordre inférieur au niveau des items : %s.|Das Ergebnismodell passte %s als übergeordneten Faktor mit folgenden untergeordneten Faktoren auf Itemebene an: %s.|Mô hình kết quả ước lượng %s là nhân tố bậc cao với các nhân tố bậc thấp ở cấp mục: %s.
Item-level lower-order model fit failed: %s|項目レベルの低次因子モデルの適合に失敗しました：%s|题项层面低阶模型拟合失败：%s|Falló el ajuste del modelo de orden inferior a nivel de ítem: %s|Échec de l’ajustement du modèle d’ordre inférieur au niveau des items : %s|Anpassung des untergeordneten Modells auf Itemebene fehlgeschlagen: %s|Ước lượng mô hình bậc thấp ở cấp mục thất bại: %s
Item-level minimum |loading| = %s; maximum absolute residual correlation = %s.|項目レベルの最小絶対負荷量 = %s；最大絶対残差相関 = %s。|题项层面最小绝对载荷 = %s；最大绝对残差相关 = %s。|Carga absoluta mínima a nivel de ítem = %s; correlación residual absoluta máxima = %s.|Saturation absolue minimale au niveau des items = %s ; corrélation résiduelle absolue maximale = %s.|Minimale absolute Ladung auf Itemebene = %s; maximale absolute Residualkorrelation = %s.|Tải tuyệt đối nhỏ nhất ở cấp mục = %s; tương quan phần dư tuyệt đối lớn nhất = %s.
Allocation preview|割り当てプレビュー|分配预览|Vista previa de la asignación|Aperçu de l’affectation|Zuteilungsvorschau|Xem trước phân bổ
Parcel balance summary|パーセルのバランス要約|题项包平衡摘要|Resumen del equilibrio de parcelas|Résumé de l’équilibre des parcelles|Zusammenfassung der Parcel-Balance|Tóm tắt độ cân bằng các nhóm mục
Mean absolute loading|絶対負荷量の平均|平均绝对载荷|Carga absoluta media|Saturation absolue moyenne|Mittlere absolute Ladung|Tải tuyệt đối trung bình
No parcel variables were created. The lower-order factors remain item-level representations using the original indicators. Review substantive item homogeneity, local dependence, and sensitivity to alternative allocations before interpretation.|パーセル変数は作成されていません。低次因子は元の指標を用いた項目レベルの表現です。解釈前に、項目内容の均質性、局所依存、別の割り当てに対する感度を検討してください。|未创建题项包变量。低阶因子仍使用原始指标进行题项层面的表示。解释前应检查题项内容同质性、局部依赖以及对其他分配方式的敏感性。|No se crearon variables de parcela. Los factores de orden inferior siguen siendo representaciones a nivel de ítem con los indicadores originales. Antes de interpretar, revise la homogeneidad sustantiva de los ítems, la dependencia local y la sensibilidad a otras asignaciones.|Aucune variable de parcelle n’a été créée. Les facteurs d’ordre inférieur restent des représentations au niveau des items utilisant les indicateurs originaux. Avant l’interprétation, examinez l’homogénéité substantielle des items, la dépendance locale et la sensibilité à d’autres affectations.|Es wurden keine Parcel-Variablen erstellt. Die untergeordneten Faktoren bleiben Darstellungen auf Itemebene mit den ursprünglichen Indikatoren. Prüfen Sie vor der Interpretation die inhaltliche Homogenität der Items, lokale Abhängigkeiten und die Sensitivität gegenüber alternativen Zuteilungen.|Không tạo biến gộp mục. Các nhân tố bậc thấp vẫn biểu diễn ở cấp mục bằng các chỉ báo gốc. Trước khi diễn giải, cần xem xét tính đồng nhất nội dung, phụ thuộc cục bộ và độ nhạy với các cách phân bổ khác.
Parcel planning was not requested.|パーセル計画は要求されていません。|未请求题项打包计划。|No se solicitó la planificación de parcelas.|La planification de parcelles n’a pas été demandée.|Die Parcel-Planung wurde nicht angefordert.|Chưa yêu cầu lập kế hoạch gộp mục.
Parcel preview currently supports three or four parcels.|現在のプレビューは3個または4個のパーセルをサポートします。|当前预览支持三个或四个题项包。|La vista previa admite actualmente tres o cuatro parcelas.|L’aperçu prend actuellement en charge trois ou quatre parcelles.|Die Vorschau unterstützt derzeit drei oder vier Parcels.|Xem trước hiện hỗ trợ ba hoặc bốn nhóm mục.
The selected construct is not present in the model.|選択された構成概念がモデルにありません。|模型中不存在所选构念。|El constructo seleccionado no está presente en el modelo.|Le construit sélectionné est absent du modèle.|Das ausgewählte Konstrukt ist im Modell nicht vorhanden.|Cấu trúc đã chọn không có trong mô hình.
Parceling preview is restricted to reflective common-factor constructs.|パーセル化のプレビューは反映型共通因子の構成概念に限定されます。|题项打包预览仅适用于反映性共同因子构念。|La vista previa del agrupamiento en parcelas se limita a constructos de factor común reflectivos.|L’aperçu du regroupement en parcelles est limité aux construits à facteur commun réflexifs.|Die Parcel-Vorschau ist auf reflektive gemeinsame Faktoren beschränkt.|Xem trước gộp mục chỉ áp dụng cho cấu trúc nhân tố chung phản ánh.
An admissible item-level CFA must be fitted before parcel planning.|パーセル計画の前に、項目レベルのCFAで許容可能な解を得る必要があります。|制定题项打包计划前，必须拟合出具有可接受解的题项层面CFA。|Antes de planificar parcelas, debe ajustarse una AFC a nivel de ítem con una solución admisible.|Une AFC au niveau des items avec une solution admissible doit être ajustée avant la planification des parcelles.|Vor der Parcel-Planung muss eine CFA auf Itemebene mit zulässiger Lösung angepasst werden.|Trước khi lập kế hoạch gộp mục, phải ước lượng CFA ở cấp mục với nghiệm chấp nhận được.
Parcel preview currently requires a single-group item-level CFA.|現在のパーセルプレビューには単一集団の項目レベルCFAが必要です。|当前题项包预览需要单组题项层面CFA。|La vista previa requiere actualmente una AFC a nivel de ítem de un solo grupo.|L’aperçu nécessite actuellement une AFC au niveau des items pour un seul groupe.|Die Vorschau erfordert derzeit eine CFA auf Itemebene für eine einzelne Gruppe.|Xem trước hiện yêu cầu CFA ở cấp mục cho một nhóm.
Parcel preview currently requires continuous indicators; ordinal items need an ordinal-specific scoring and sensitivity plan.|現在のパーセルプレビューには連続指標が必要です。順序項目には専用の得点化と感度検討の計画が必要です。|当前题项包预览需要连续指标；有序题项需要专门的计分与敏感性分析计划。|La vista previa requiere indicadores continuos; los ítems ordinales necesitan un plan específico de puntuación y sensibilidad.|L’aperçu nécessite des indicateurs continus ; les items ordinaux exigent un plan spécifique de calcul des scores et de sensibilité.|Die Vorschau erfordert kontinuierliche Indikatoren; ordinale Items benötigen einen eigenen Bewertungs- und Sensitivitätsplan.|Xem trước hiện yêu cầu chỉ báo liên tục; mục thứ bậc cần kế hoạch chấm điểm và đánh giá độ nhạy riêng.
At least %s indicators are required to preview %s parcels with at least two items each.|各パーセルに少なくとも2項目を含むプレビューには、指標%s個以上が必要です（パーセル%s個）。|预览每包至少两个题项的分配需要至少%s个指标（共%s个题项包）。|Se requieren al menos %s indicadores para previsualizar %s parcelas con al menos dos ítems cada una.|Il faut au moins %s indicateurs pour prévisualiser %s parcelles contenant chacune au moins deux items.|Mindestens %s Indikatoren sind erforderlich, um %s Parcels mit jeweils mindestens zwei Items anzuzeigen.|Cần ít nhất %s chỉ báo để xem trước %s nhóm, mỗi nhóm ít nhất hai mục.
Item-level parcel-factor model requested|項目レベルのパーセル因子モデルを要求済み|已请求题项层面题项包因子模型|Modelo de factores de parcela a nivel de ítem solicitado|Modèle de facteurs de parcelle au niveau des items demandé|Parcel-Faktormodell auf Itemebene angefordert|Đã yêu cầu mô hình nhân tố nhóm mục ở cấp mục
Item-level parcel-factor model could not be fitted|項目レベルのパーセル因子モデルを適合できませんでした|无法拟合题项层面题项包因子模型|No se pudo ajustar el modelo de factores de parcela a nivel de ítem|Le modèle de facteurs de parcelle au niveau des items n’a pas pu être ajusté|Parcel-Faktormodell auf Itemebene konnte nicht angepasst werden|Không thể ước lượng mô hình nhân tố nhóm mục ở cấp mục
Item-level parcel-factor CFA fitted|項目レベルのパーセル因子CFAの適合完了|已拟合题项层面题项包因子CFA|AFC de factores de parcela a nivel de ítem ajustada|AFC de facteurs de parcelle au niveau des items ajustée|Parcel-Faktor-CFA auf Itemebene angepasst|Đã ước lượng CFA nhân tố nhóm mục ở cấp mục
Loading-balanced allocation is sample-dependent and can conceal multidimensionality or local dependence.|負荷量を均衡させる割り当ては標本に依存し、多次元性や局所依存を隠す可能性があります。|按载荷平衡的分配依赖于样本，可能掩盖多维性或局部依赖。|La asignación equilibrada por cargas depende de la muestra y puede ocultar multidimensionalidad o dependencia local.|L’affectation équilibrée selon les saturations dépend de l’échantillon et peut masquer la multidimensionnalité ou la dépendance locale.|Eine ladungsbalancierte Zuteilung ist stichprobenabhängig und kann Mehrdimensionalität oder lokale Abhängigkeiten verdecken.|Phân bổ cân bằng theo tải phụ thuộc vào mẫu và có thể che giấu tính đa chiều hoặc phụ thuộc cục bộ.
No parcel variables were created; the requested parcels are represented as lower-order item-level factors.|パーセル変数は作成されていません。要求されたパーセルは項目レベルの低次因子として表現されています。|未创建题项包变量；所请求的题项包以题项层面低阶因子表示。|No se crearon variables de parcela; las parcelas solicitadas se representan como factores de orden inferior a nivel de ítem.|Aucune variable de parcelle n’a été créée ; les parcelles demandées sont représentées par des facteurs d’ordre inférieur au niveau des items.|Es wurden keine Parcel-Variablen erstellt; die angeforderten Parcels werden als untergeordnete Faktoren auf Itemebene dargestellt.|Không tạo biến gộp mục; các nhóm mục yêu cầu được biểu diễn bằng nhân tố bậc thấp ở cấp mục.
A substantive parceling purpose was not recorded.|内容面でのパーセル化の目的が記録されていません。|未记录题项打包的实质性目的。|No se registró un propósito sustantivo para el agrupamiento en parcelas.|Aucun objectif substantiel de regroupement en parcelles n’a été consigné.|Es wurde kein inhaltlicher Zweck für die Parcel-Bildung dokumentiert.|Chưa ghi mục đích về nội dung của việc gộp mục.'''
# The absolute-value bars belong to the English text, not to column delimiters.
rows=rows.replace('Item-level minimum |loading|', 'Item-level minimum ABSLOADING')
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');f[0]=f[0].replace('ABSLOADING','|loading|');assert len(f)==7 and f[0].count('%s')==f[i].count('%s'),f[0]
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
