import json
from pathlib import Path
keys=['adjusted_start','adjusted_strata','adjusted_cluster','adjusted_tv']
rows={
'en':['Marginal adjusted survival is not available for start-stop Cox models in survival v1.','Marginal adjusted survival is not available with stratified Cox regression in survival v1. Report the stratified hazard-ratio model separately or remove stratification before requesting standardized curves.','Marginal adjusted survival is not available with user-specified clustered Cox regression in survival v1 because valid uncertainty estimation requires cluster-level resampling.','Marginal adjusted survival is not available with a time-varying coefficient Cox model in survival v1.'],
'ko':['생존분석 v1의 시작·종료 Cox 모형에서는 주변 조정 생존곡선을 사용할 수 없습니다.','생존분석 v1의 층화 Cox 회귀에서는 주변 조정 생존곡선을 사용할 수 없습니다. 층화 위험비 모형을 별도로 보고하거나, 표준화 곡선을 요청하기 전에 층화를 해제하세요.','생존분석 v1에서는 사용자가 군집을 지정한 Cox 회귀에 주변 조정 생존곡선을 사용할 수 없습니다. 타당한 불확실성 추정에는 군집 단위 재표집이 필요합니다.','생존분석 v1의 시간가변 계수 Cox 모형에서는 주변 조정 생존곡선을 사용할 수 없습니다.'],
'ja':['生存分析v1の開始・終了Coxモデルでは周辺調整生存曲線を使用できません。','生存分析v1の層別Cox回帰では周辺調整生存曲線を使用できません。層別ハザード比モデルを別途報告するか、標準化曲線を要求する前に層別化を解除してください。','生存分析v1では、ユーザーがクラスターを指定したCox回帰で周辺調整生存曲線を使用できません。妥当な不確実性推定にはクラスター単位の再標本化が必要です。','生存分析v1の時間変動係数Coxモデルでは周辺調整生存曲線を使用できません。'],
'zh':['生存分析 v1 的起止时间 Cox 模型不支持边际调整生存曲线。','生存分析 v1 的分层 Cox 回归不支持边际调整生存曲线。请单独报告分层风险比模型，或在请求标准化曲线前取消分层。','生存分析 v1 不支持为用户指定聚类的 Cox 回归计算边际调整生存曲线，因为有效的不确定性估计需要按聚类重抽样。','生存分析 v1 的时变系数 Cox 模型不支持边际调整生存曲线。'],
'es':['La supervivencia marginal ajustada no está disponible para modelos de Cox con inicio y fin en supervivencia v1.','La supervivencia marginal ajustada no está disponible con regresión de Cox estratificada en supervivencia v1. Informe por separado el modelo de razones de riesgos estratificado o quite la estratificación antes de solicitar curvas estandarizadas.','La supervivencia marginal ajustada no está disponible con regresión de Cox agrupada por el usuario en supervivencia v1, porque una estimación válida de la incertidumbre requiere remuestreo a nivel de grupo.','La supervivencia marginal ajustada no está disponible con un modelo de Cox de coeficientes dependientes del tiempo en supervivencia v1.'],
'fr':['La survie marginale ajustée n’est pas disponible pour les modèles de Cox début-fin dans survie v1.','La survie marginale ajustée n’est pas disponible avec la régression de Cox stratifiée dans survie v1. Présentez séparément le modèle de rapports de risques stratifié ou retirez la stratification avant de demander des courbes standardisées.','La survie marginale ajustée n’est pas disponible avec une régression de Cox regroupée selon le choix de l’utilisateur dans survie v1, car une estimation valide de l’incertitude nécessite un rééchantillonnage au niveau des groupes.','La survie marginale ajustée n’est pas disponible avec un modèle de Cox à coefficient variant dans le temps dans survie v1.'],
'de':['Marginal adjustiertes Überleben ist für Start-Stopp-Cox-Modelle in Überlebensanalyse v1 nicht verfügbar.','Marginal adjustiertes Überleben ist mit stratifizierter Cox-Regression in Überlebensanalyse v1 nicht verfügbar. Berichten Sie das stratifizierte Hazard-Ratio-Modell separat oder entfernen Sie die Stratifizierung, bevor Sie standardisierte Kurven anfordern.','Marginal adjustiertes Überleben ist mit benutzerdefinierter clusterbasierter Cox-Regression in Überlebensanalyse v1 nicht verfügbar, da eine gültige Unsicherheitsschätzung Resampling auf Clusterebene erfordert.','Marginal adjustiertes Überleben ist mit einem Cox-Modell mit zeitvariablem Koeffizienten in Überlebensanalyse v1 nicht verfügbar.'],
'vi':['Đường cong sống còn điều chỉnh biên không khả dụng cho mô hình Cox bắt đầu–kết thúc trong phân tích sống còn v1.','Đường cong sống còn điều chỉnh biên không khả dụng với hồi quy Cox phân tầng trong phân tích sống còn v1. Hãy báo cáo riêng mô hình tỷ số nguy cơ phân tầng hoặc bỏ phân tầng trước khi yêu cầu đường cong chuẩn hóa.','Đường cong sống còn điều chỉnh biên không khả dụng với hồi quy Cox phân cụm do người dùng chỉ định trong phân tích sống còn v1 vì ước lượng độ bất định hợp lệ cần tái lấy mẫu ở cấp cụm.','Đường cong sống còn điều chỉnh biên không khả dụng với mô hình Cox có hệ số thay đổi theo thời gian trong phân tích sống còn v1.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
