import json, re
from pathlib import Path

rows = '''Harman single-factor screen|Harman単一因子スクリーニング|Harman单因子筛查|Cribado unifactorial de Harman|Dépistage unifactoriel de Harman|Harman-Einfaktor-Screening|Sàng lọc một nhân tố Harman
Single-factor CFA comparison|単一因子CFAの比較|单因子CFA比较|Comparación de AFC unifactorial|Comparaison d’AFC unifactorielle|Vergleich der Einfaktor-CFA|So sánh CFA một nhân tố
Common latent factor screen|共通潜在因子スクリーニング|共同潜在因子筛查|Cribado con factor latente común|Dépistage par facteur latent commun|Screening mit gemeinsamem latentem Faktor|Sàng lọc nhân tố tiềm ẩn chung
Common method diagnostics|共通方法診断|共同方法诊断|Diagnóstico de método común|Diagnostic de méthode commune|Diagnostik der gemeinsamen Methode|Chẩn đoán phương pháp chung
First factor percent|第1因子の説明分散（%）|第一因子解释方差（%）|Varianza del primer factor (%)|Variance du premier facteur (%)|Varianzanteil des ersten Faktors (%)|Phương sai giải thích của nhân tố đầu tiên (%)
One-factor model fit|単一因子モデルの適合度|单因子模型拟合|Ajuste del modelo unifactorial|Ajustement du modèle unifactoriel|Anpassung des Einfaktormodells|Độ phù hợp mô hình một nhân tố
Max loading change|負荷量変化の最大値|最大载荷变化|Cambio máximo en las cargas|Variation maximale des saturations|Maximale Ladungsänderung|Thay đổi tải lớn nhất
Mean absolute method loading|方法因子負荷量の絶対値の平均|方法因子载荷绝对值均值|Media de las cargas absolutas del método|Moyenne des saturations absolues du facteur de méthode|Mittlere absolute Methodenladung|Trung bình trị tuyệt đối tải nhân tố phương pháp
Requested diagnostics|要求された診断|请求的诊断|Diagnósticos solicitados|Diagnostics demandés|Angeforderte Diagnostik|Chẩn đoán được yêu cầu
OK|良好|良好|Aceptable|Satisfaisant|Unauffällig|Đạt
Review|要検討|需复核|Revisar|À examiner|Prüfung erforderlich|Cần xem xét
Screen only|探索的点検のみ|仅探索性筛查|Solo cribado exploratorio|Dépistage exploratoire uniquement|Nur exploratives Screening|Chỉ sàng lọc thăm dò
Screen flag|探索的点検での警告|探索性筛查警示|Alerta de cribado|Signal de dépistage|Screening-Hinweis|Cảnh báo sàng lọc
Not available|算出不可|无法计算|No disponible|Non disponible|Nicht verfügbar|Không có kết quả
Harman PCA requires at least two numeric indicators.|Harman PCAには少なくとも2つの数値指標が必要です。|Harman PCA至少需要两个数值型指标。|El ACP de Harman requiere al menos dos indicadores numéricos.|L’ACP de Harman nécessite au moins deux indicateurs numériques.|Die Harman-PCA erfordert mindestens zwei numerische Indikatoren.|PCA Harman cần ít nhất hai chỉ báo dạng số.
Harman PCA requires more complete rows than indicators.|Harman PCAには指標数より多い完全データ行が必要です。|Harman PCA要求完整数据行数多于指标数。|El ACP de Harman requiere más filas completas que indicadores.|L’ACP de Harman nécessite plus de lignes complètes que d’indicateurs.|Die Harman-PCA erfordert mehr vollständige Zeilen als Indikatoren.|PCA Harman cần số dòng đầy đủ lớn hơn số chỉ báo.
Harman PCA failed for the selected indicators.|選択された指標でHarman PCAを計算できませんでした。|无法对所选指标计算Harman PCA。|No se pudo calcular el ACP de Harman para los indicadores seleccionados.|L’ACP de Harman a échoué pour les indicateurs sélectionnés.|Die Harman-PCA ist für die ausgewählten Indikatoren fehlgeschlagen.|Không thể tính PCA Harman cho các chỉ báo đã chọn.
Exploratory first-component screen only; values above 50% may flag concentration, but no value establishes presence or absence of common-method bias.|第1成分による探索的点検のみです。50%超は集中を示唆する場合がありますが、どの値も共通方法バイアスの有無を確定しません。|仅为第一成分的探索性筛查；超过50%可能提示集中，但任何数值都不能确定共同方法偏差存在或不存在。|Es solo un cribado exploratorio del primer componente; superar el 50% puede indicar concentración, pero ningún valor confirma la presencia o ausencia de sesgo de método común.|Il s’agit uniquement d’un dépistage exploratoire du premier composant ; dépasser 50% peut signaler une concentration, mais aucune valeur n’établit la présence ou l’absence d’un biais de méthode commune.|Nur exploratives Screening der ersten Komponente; Werte über 50% können auf Konzentration hinweisen, aber kein Wert belegt das Vorliegen oder Fehlen gemeinsamer Methodenverzerrung.|Đây chỉ là sàng lọc thăm dò thành phần đầu tiên; giá trị trên 50% có thể báo hiệu sự tập trung, nhưng không giá trị nào xác định có hay không có sai lệch phương pháp chung.
First unrotated principal component percent; values above 50% suggest possible common-method concentration.|回転前の第1主成分の説明分散比率です。50%超は共通方法への集中の可能性を示唆します。|未旋转第一主成分的解释方差比例；超过50%提示可能存在共同方法集中。|Porcentaje del primer componente principal sin rotar; superar el 50% sugiere una posible concentración por método común.|Pourcentage du premier composant principal non tourné ; dépasser 50% suggère une possible concentration liée à la méthode commune.|Varianzanteil der ersten unrotierten Hauptkomponente; Werte über 50% deuten auf mögliche Konzentration durch die gemeinsame Methode hin.|Tỷ lệ phương sai của thành phần chính đầu tiên chưa xoay; giá trị trên 50% gợi ý khả năng tập trung do phương pháp chung.
A single-factor CFA fit the indicators reasonably well; review common-method concentration.|単一因子CFAは指標に比較的よく適合しました。共通方法への集中を検討してください。|单因子CFA对指标的拟合较好；请复核共同方法集中情况。|La AFC unifactorial se ajustó razonablemente bien a los indicadores; revise la concentración por método común.|L’AFC unifactorielle s’ajuste assez bien aux indicateurs ; examinez la concentration liée à la méthode commune.|Die Einfaktor-CFA passte recht gut zu den Indikatoren; prüfen Sie die Konzentration durch die gemeinsame Methode.|CFA một nhân tố phù hợp khá tốt với các chỉ báo; cần xem xét sự tập trung do phương pháp chung.
The single-factor CFA did not show a strong one-factor fit pattern.|単一因子CFAでは強い単一因子適合パターンは見られませんでした。|单因子CFA未显示强单因子拟合模式。|La AFC unifactorial no mostró un patrón sólido de ajuste a un solo factor.|L’AFC unifactorielle n’a pas montré de forte adéquation à un facteur unique.|Die Einfaktor-CFA zeigte kein starkes Einfaktor-Anpassungsmuster.|CFA một nhân tố không cho thấy mô hình phù hợp một nhân tố rõ rệt.
Single-factor CFA requires at least three indicators.|単一因子CFAには少なくとも3つの指標が必要です。|单因子CFA至少需要三个指标。|La AFC unifactorial requiere al menos tres indicadores.|L’AFC unifactorielle nécessite au moins trois indicateurs.|Die Einfaktor-CFA erfordert mindestens drei Indikatoren.|CFA một nhân tố cần ít nhất ba chỉ báo.
Common latent factor screening requires at least three indicators.|共通潜在因子の点検には少なくとも3つの指標が必要です。|共同潜在因子筛查至少需要三个指标。|El cribado con factor latente común requiere al menos tres indicadores.|Le dépistage par facteur latent commun nécessite au moins trois indicateurs.|Das Screening mit gemeinsamem latentem Faktor erfordert mindestens drei Indikatoren.|Sàng lọc nhân tố tiềm ẩn chung cần ít nhất ba chỉ báo.
Equal-loading common latent factor screen; loading changes above .20 suggest possible method effects.|等負荷の共通潜在因子による点検です。負荷量の変化が.20を超える場合、方法効果の可能性を示唆します。|等载荷共同潜在因子筛查；载荷变化超过.20提示可能存在方法效应。|Cribado con factor latente común de cargas iguales; los cambios de cargas superiores a .20 sugieren posibles efectos de método.|Dépistage par facteur latent commun à saturations égales ; des variations supérieures à .20 suggèrent de possibles effets de méthode.|Screening mit gleich geladenem gemeinsamem latentem Faktor; Ladungsänderungen über .20 deuten auf mögliche Methodeneffekte hin.|Sàng lọc nhân tố tiềm ẩn chung có tải bằng nhau; thay đổi tải trên .20 gợi ý hiệu ứng phương pháp có thể có.
Descriptive size of the common method factor loadings.|共通方法因子負荷量の記述的な大きさです。|共同方法因子载荷大小的描述。|Magnitud descriptiva de las cargas del factor de método común.|Amplitude descriptive des saturations du facteur de méthode commune.|Deskriptive Größe der Ladungen des gemeinsamen Methodenfaktors.|Độ lớn mô tả của tải nhân tố phương pháp chung.
Mean absolute method factor loading above .50 suggests substantial method-factor concentration.|方法因子負荷量の絶対値の平均が.50を超える場合、方法因子への大きな集中を示唆します。|方法因子载荷绝对值均值超过.50提示明显的方法因子集中。|Una carga absoluta media del factor de método superior a .50 sugiere una concentración considerable en dicho factor.|Une saturation absolue moyenne du facteur de méthode supérieure à .50 suggère une concentration importante sur ce facteur.|Eine mittlere absolute Methodenfaktorladung über .50 deutet auf erhebliche Konzentration auf den Methodenfaktor hin.|Trung bình trị tuyệt đối tải nhân tố phương pháp trên .50 gợi ý sự tập trung đáng kể vào nhân tố phương pháp.
No common method diagnostics could be computed for the current model.|現在のモデルでは共通方法診断を計算できませんでした。|无法为当前模型计算共同方法诊断。|No se pudo calcular ningún diagnóstico de método común para el modelo actual.|Aucun diagnostic de méthode commune n’a pu être calculé pour le modèle actuel.|Für das aktuelle Modell konnte keine Diagnostik der gemeinsamen Methode berechnet werden.|Không thể tính chẩn đoán phương pháp chung cho mô hình hiện tại.
Common latent factor loading changes exceed the .20 screening threshold.|共通潜在因子による負荷量の変化が点検基準.20を超えています。|共同潜在因子载荷变化超过.20筛查阈值。|Los cambios en las cargas con factor latente común superan el umbral de cribado de .20.|Les variations des saturations avec un facteur latent commun dépassent le seuil de dépistage de .20.|Die Ladungsänderungen durch den gemeinsamen latenten Faktor überschreiten den Screening-Schwellenwert von .20.|Thay đổi tải khi thêm nhân tố tiềm ẩn chung vượt ngưỡng sàng lọc .20.
Mean common method factor loading exceeds the .50 screening threshold.|共通方法因子の平均負荷量が点検基準.50を超えています。|共同方法因子平均载荷超过.50筛查阈值。|La carga media del factor de método común supera el umbral de cribado de .50.|La saturation moyenne du facteur de méthode commune dépasse le seuil de dépistage de .50.|Die mittlere Ladung des gemeinsamen Methodenfaktors überschreitet den Screening-Schwellenwert von .50.|Tải trung bình của nhân tố phương pháp chung vượt ngưỡng sàng lọc .50.
The single-factor CFA is comparatively close to conventional fit references and requires review.|単一因子CFAが慣用的な適合度参考値に比較的近いため、検討が必要です。|单因子CFA较接近常用拟合参考值，需要复核。|La AFC unifactorial está relativamente cerca de las referencias convencionales de ajuste y requiere revisión.|L’AFC unifactorielle est relativement proche des références usuelles d’ajustement et nécessite un examen.|Die Einfaktor-CFA liegt vergleichsweise nahe an üblichen Anpassungsreferenzen und erfordert eine Prüfung.|CFA một nhân tố tương đối gần các giá trị tham chiếu độ phù hợp thông thường và cần xem xét.
Harman's first factor exceeds 50%.|Harmanの第1因子が50%を超えています。|Harman第一因子超过50%。|El primer factor de Harman supera el 50%.|Le premier facteur de Harman dépasse 50%.|Der erste Harman-Faktor überschreitet 50%.|Nhân tố đầu tiên của Harman vượt 50%.
At least one common method diagnostic crossed its review threshold.|少なくとも1つの共通方法診断が検討基準を超えました。|至少一项共同方法诊断超过复核阈值。|Al menos un diagnóstico de método común superó su umbral de revisión.|Au moins un diagnostic de méthode commune a dépassé son seuil d’examen.|Mindestens eine Diagnostik der gemeinsamen Methode überschritt ihren Prüfschwellenwert.|Ít nhất một chẩn đoán phương pháp chung vượt ngưỡng cần xem xét.
Some common method diagnostics could not be computed; interpret the available checks only.|一部の共通方法診断を計算できませんでした。得られた点検結果のみを解釈してください。|部分共同方法诊断无法计算；请仅解释可用的检查结果。|No se pudieron calcular algunos diagnósticos de método común; interprete solo las comprobaciones disponibles.|Certains diagnostics de méthode commune n’ont pas pu être calculés ; interprétez uniquement les vérifications disponibles.|Einige Diagnosen der gemeinsamen Methode konnten nicht berechnet werden; interpretieren Sie nur die verfügbaren Prüfungen.|Không thể tính một số chẩn đoán phương pháp chung; chỉ diễn giải các kiểm tra hiện có.
No selected common method diagnostic crossed its screening threshold.|選択した共通方法診断で点検基準を超えたものはありません。|所选共同方法诊断均未超过筛查阈值。|Ningún diagnóstico de método común seleccionado superó su umbral de cribado.|Aucun diagnostic de méthode commune sélectionné n’a dépassé son seuil de dépistage.|Keine ausgewählte Diagnostik der gemeinsamen Methode überschritt ihren Screening-Schwellenwert.|Không chẩn đoán phương pháp chung nào đã chọn vượt ngưỡng sàng lọc.
An exploratory screen crossed its heuristic threshold; this is neither a diagnosis nor evidence that common-method bias caused the results.|探索的点検が経験則による基準を超えましたが、これは診断でも、共通方法バイアスが結果を生じさせた証拠でもありません。|探索性筛查超过经验阈值；这既不是诊断，也不是共同方法偏差导致结果的证据。|Un cribado exploratorio superó su umbral heurístico; esto no constituye un diagnóstico ni evidencia de que el sesgo de método común causara los resultados.|Un dépistage exploratoire a dépassé son seuil heuristique ; cela ne constitue ni un diagnostic ni une preuve que le biais de méthode commune a causé les résultats.|Ein exploratives Screening überschritt seinen heuristischen Schwellenwert; dies ist weder eine Diagnose noch ein Beleg dafür, dass gemeinsame Methodenverzerrung die Ergebnisse verursacht hat.|Một phép sàng lọc thăm dò vượt ngưỡng kinh nghiệm; đây không phải chẩn đoán hay bằng chứng cho thấy sai lệch phương pháp chung gây ra kết quả.
No selected screen crossed its heuristic threshold; this does not establish the absence of common-method bias.|選択した点検は経験則による基準を超えませんでしたが、共通方法バイアスが存在しないことを示すものではありません。|所选筛查均未超过经验阈值；这不能证明共同方法偏差不存在。|Ningún cribado seleccionado superó su umbral heurístico; esto no demuestra la ausencia de sesgo de método común.|Aucun dépistage sélectionné n’a dépassé son seuil heuristique ; cela n’établit pas l’absence de biais de méthode commune.|Kein ausgewähltes Screening überschritt seinen heuristischen Schwellenwert; dies belegt nicht das Fehlen gemeinsamer Methodenverzerrung.|Không phép sàng lọc nào đã chọn vượt ngưỡng kinh nghiệm; điều này không chứng minh không có sai lệch phương pháp chung.
Single-factor CFA failed:|単一因子CFAの計算に失敗しました：|单因子CFA计算失败：|Falló la AFC unifactorial:|Échec de l’AFC unifactorielle :|Einfaktor-CFA fehlgeschlagen:|CFA một nhân tố thất bại:
Common latent factor model failed:|共通潜在因子モデルの計算に失敗しました：|共同潜在因子模型计算失败：|Falló el modelo de factor latente común:|Échec du modèle à facteur latent commun :|Modell mit gemeinsamem latentem Faktor fehlgeschlagen:|Mô hình nhân tố tiềm ẩn chung thất bại:'''

if __name__ == '__main__':
    for i, language in enumerate(['ja', 'zh', 'es', 'fr', 'de', 'vi'], 1):
        path = Path('i18n') / (language + '.json')
        data = json.loads(path.read_text(encoding='utf-8'))
        for row in rows.splitlines():
            fields = row.split('|')
            assert len(fields) == 7, fields[0]
            key = 'analysis.ui.' + re.sub(r'[^a-z0-9]+', '_', fields[0].lower()).strip('_')
            data['translations'][key] = fields[i]
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
