import json,re
from pathlib import Path
rows='''Survival sparse evidence Unique target-failure times available for residual review =|残差検討に使用できる異なる関心イベント時点数 =|可用于残差审查的不同目标事件时点数 =|Tiempos distintos del evento de interés disponibles para revisar residuos =|Temps distincts de l’événement d’intérêt disponibles pour examiner les résidus =|Für die Residuenprüfung verfügbare unterschiedliche Zielereigniszeiten =|Số thời điểm biến cố quan tâm khác nhau có thể dùng để xem xét phần dư =
Survival sparse evidence Schoenfeld-like residual time-pattern signals:|Schoenfeld型残差の時間パターンのシグナル:|Schoenfeld型残差时间模式信号：|Señales de patrones temporales en residuos tipo Schoenfeld:|Signaux de tendances temporelles des résidus de type Schoenfeld :|Zeitmustersignale in Schoenfeld-ähnlichen Residuen:|Dấu hiệu mẫu hình theo thời gian của phần dư kiểu Schoenfeld:
Survival sparse evidence Sparse censoring-distribution strata:|データが少ない検閲分布の層:|数据稀疏的删失分布层：|Estratos de distribución de censura con pocos datos:|Strates de distribution de censure avec peu de données :|Datenarme Strata der Zensierungsverteilung:|Các tầng phân phối kiểm duyệt có dữ liệu thưa thớt:
With few target-failure times, time-pattern diagnostics have limited power; do not claim that proportional subdistribution hazards has been established.|関心イベント時点が少ないと時間パターン診断の検出力が限られるため、比例部分分布ハザードが確認されたとは結論しないでください。|目标事件时点较少时，时间模式诊断的效能有限；不要宣称比例亚分布风险假设已得到确认。|Con pocos tiempos del evento de interés, los diagnósticos temporales tienen potencia limitada; no afirme que se ha establecido la proporcionalidad de los riesgos de subdistribución.|Avec peu de temps d’événement d’intérêt, les diagnostics temporels ont une puissance limitée ; n’affirmez pas que la proportionnalité des risques de sous-distribution est établie.|Bei wenigen Zielereigniszeiten ist die Teststärke der Zeitmusterdiagnostik begrenzt; behaupten Sie nicht, dass proportionale Subdistributionshazards nachgewiesen wurden.|Khi có ít thời điểm biến cố quan tâm, chẩn đoán mẫu hình thời gian có lực kiểm định hạn chế; không khẳng định giả định nguy cơ phân phối phụ tỷ lệ đã được xác lập.
Review the residual plots and a prespecified time-interaction model. Do not reject the assumption automatically from the exploratory correlation p-value alone.|残差図と事前指定の時間交互作用モデルを検討してください。探索的な相関のp値だけで仮定を自動的に棄却しないでください。|请检查残差图和预先指定的时间交互作用模型。不要仅凭探索性相关检验的p值自动否定假设。|Revise los gráficos de residuos y un modelo de interacción temporal preespecificado. No rechace automáticamente el supuesto solo por el valor p de una correlación exploratoria.|Examinez les graphiques des résidus et un modèle d’interaction temporelle préspécifié. Ne rejetez pas automatiquement l’hypothèse sur la seule base de la valeur p d’une corrélation exploratoire.|Prüfen Sie die Residuenplots und ein vorab festgelegtes Zeitinteraktionsmodell. Verwerfen Sie die Annahme nicht automatisch allein aufgrund des p-Werts einer explorativen Korrelation.|Xem xét đồ thị phần dư và mô hình tương tác thời gian được chỉ định trước. Không tự động bác bỏ giả định chỉ dựa vào giá trị p của tương quan thăm dò.
Review instability in stratum-specific censoring-distribution estimation and report stratum sizes, censoring counts, and the design rationale.|層別検閲分布推定の不安定性を確認し、層の大きさ、検閲数、研究デザイン上の根拠を併せて報告してください。|请检查各层删失分布估计的不稳定性，并报告各层样本量、删失数和设计依据。|Revise la inestabilidad de la estimación de la distribución de censura por estrato e informe los tamaños de estrato, los recuentos de censura y la justificación del diseño.|Examinez l’instabilité de l’estimation de la distribution de censure par strate et présentez les tailles des strates, les nombres de censures et la justification du plan d’étude.|Prüfen Sie die Instabilität stratumsspezifischer Zensierungsverteilungsschätzungen und berichten Sie Stratengrößen, Zensierungszahlen und die Begründung des Studiendesigns.|Xem xét tính không ổn định của ước lượng phân phối kiểm duyệt theo tầng và báo cáo cỡ từng tầng, số trường hợp kiểm duyệt và cơ sở thiết kế.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
