import json,re
from pathlib import Path
# Source sentences are read from the actual note calls; translations retain all qualifications.
source=Path('R/setup_custom_model_canvas_structural_render_mi.R').read_text(encoding='utf-8').split('output[[paste0(prefix, "_result_mi_history")]]')[0]
sentences=re.findall(r'result_note_paragraph\(class = "structural-result-note", tr\("([^"]+)"',source)
assert len(sentences)==6
rows='''MI pは各修正指数を、補正されていない漸近的な自由度1のカイ二乗検定として扱います。BH-adjusted pは、画面のMIフィルタや理論フィルタを適用する前の、有限値を持つすべてのlavaan修正候補について偽発見率を制御します。|MI p将每个修正指数视为未经缩放的渐近1自由度卡方检验。BH-adjusted p控制应用显示的MI筛选和理论筛选之前，所有有限值lavaan修正候选项的错误发现率。|MI p trata cada índice de modificación como una prueba chi-cuadrado asintótica no escalada de 1 grado de libertad. BH-adjusted p controla la tasa de falsos descubrimientos entre todas las modificaciones candidatas de lavaan con valores finitos, antes de aplicar los filtros de MI y teóricos de la pantalla.|MI p traite chaque indice de modification comme un test du khi-deux asymptotique non corrigé à 1 degré de liberté. BH-adjusted p contrôle le taux de fausses découvertes parmi toutes les modifications candidates de lavaan à valeurs finies, avant les filtres MI et théoriques affichés.|MI p behandelt jeden Modifikationsindex als unskalierten asymptotischen Chi-Quadrat-Test mit 1 Freiheitsgrad. BH-adjusted p kontrolliert die Falschentdeckungsrate über alle endlichen lavaan-Modifikationskandidaten vor Anwendung der angezeigten MI- und Theoriefilter.|MI p xem mỗi chỉ số điều chỉnh là kiểm định chi bình phương tiệm cận chưa hiệu chỉnh với 1 bậc tự do. BH-adjusted p kiểm soát tỷ lệ phát hiện sai trên mọi điều chỉnh ứng viên lavaan có giá trị hữu hạn, trước khi áp dụng bộ lọc MI và lý thuyết trên màn hình.
MLRまたはWLSMVでは、これらの算出されたp値は別途の頑健・補正スコア検定ではなく、探索的な参考値として扱ってください。|对于MLR或WLSMV，这些推导的p值并非单独的稳健/缩放得分检验校正，应视为探索性参考值。|En MLR o WLSMV, estos valores p derivados no constituyen una corrección independiente de prueba de puntuación robusta/escalada y deben tratarse como referencias exploratorias.|Pour MLR ou WLSMV, ces valeurs p dérivées ne constituent pas une correction distincte de test de score robuste/corrigé et doivent être considérées comme des références exploratoires.|Bei MLR oder WLSMV sind diese abgeleiteten p-Werte keine gesonderte robuste/skalierte Score-Test-Korrektur und sollten als explorative Referenzwerte behandelt werden.|Với MLR hoặc WLSMV, các giá trị p suy ra này không phải hiệu chỉnh kiểm định điểm số vững/hiệu chỉnh riêng biệt và nên được xem là giá trị tham khảo khám phá.
EPCは固定パラメータを自由化した場合に予想される非標準化パラメータの変化です。Std. EPCはlavaanの完全標準化された期待変化（sepc.all）です。MI順位だけでなく、方向と大きさも検討してください。|EPC是释放固定参数时预期的非标准化参数变化。Std. EPC是lavaan的完全标准化预期变化（sepc.all）。请结合方向和大小判断，而非仅看MI排序。|EPC es el cambio esperado del parámetro no estandarizado al liberar un parámetro fijo. Std. EPC es el cambio esperado completamente estandarizado de lavaan (sepc.all). Considere la dirección y magnitud, no solo el orden de MI.|EPC est le changement attendu du paramètre non standardisé lorsqu’un paramètre fixé est libéré. Std. EPC est le changement attendu entièrement standardisé de lavaan (sepc.all). Examinez le sens et l’ampleur, pas seulement le classement MI.|EPC ist die erwartete unstandardisierte Parameteränderung bei Freigabe eines fixierten Parameters. Std. EPC ist die vollständig standardisierte erwartete Änderung von lavaan (sepc.all). Berücksichtigen Sie Richtung und Größe statt nur den MI-Rang.|EPC là thay đổi tham số chưa chuẩn hóa dự kiến khi cho phép ước lượng tự do một tham số cố định. Std. EPC là thay đổi dự kiến được chuẩn hóa hoàn toàn của lavaan (sepc.all). Hãy xét hướng và độ lớn, không chỉ thứ hạng MI.
各ステップは逐次的です。表示された経路を追加してモデルを再推定し、次の行のMI、多重検定の集合、EPC、累積適合度を更新後のモデルから再計算します。各行は同じ未変更モデルから得た同時候補ではありません。|各步骤依次进行：添加所示路径并重新拟合模型，再从更新后的模型重新计算下一行的MI、多重检验族、EPC及累积拟合度。各行不是来自同一未修改模型的同时候选项。|Cada paso es secuencial: se añade la trayectoria mostrada, se reajusta el modelo y se recalculan MI, la familia de pruebas múltiples, EPC y el ajuste acumulado de la siguiente fila desde el modelo actualizado. Las filas no son candidatos simultáneos de un único modelo sin modificar.|Chaque étape est séquentielle : le chemin affiché est ajouté, le modèle est réestimé, puis MI, la famille de tests multiples, EPC et l’ajustement cumulé de la ligne suivante sont recalculés à partir du modèle actualisé. Les lignes ne sont pas des candidats simultanés issus d’un même modèle inchangé.|Jeder Schritt ist sequenziell: Der angezeigte Pfad wird hinzugefügt und das Modell neu geschätzt. MI, die Familie multipler Tests, EPC und kumulierter Fit der nächsten Zeile werden aus dem aktualisierten Modell neu berechnet. Die Zeilen sind keine gleichzeitigen Kandidaten eines unveränderten Modells.|Mỗi bước diễn ra tuần tự: thêm đường dẫn hiển thị, khớp lại mô hình rồi tính lại MI, nhóm kiểm định bội, EPC và độ phù hợp tích lũy của hàng tiếp theo từ mô hình đã cập nhật. Các hàng không phải ứng viên đồng thời từ cùng một mô hình chưa thay đổi.
安全性による除外数は、より上位でも未収束、post.check失敗、負の分散、残差・潜在・パラメータ共分散行列の非正定値または境界、無効な自由度、または潜在相関の絶対値が1以上のため却下された候補の数です。除外詳細には各経路と診断理由を記録し、除外候補は自動適用の対象にしません。|安全性排除计数指排名更高但因不收敛、post.check失败、负方差、残差/潜变量/参数协方差矩阵非正定或处于边界、自由度无效或潜变量相关绝对值至少为1而被拒绝的候选项数。排除详情记录各路径及诊断原因；被排除的候选项不会提供自动应用。|El recuento de candidatos inseguros omitidos incluye los de mayor rango rechazados por no convergencia, fallo de post.check, varianza negativa, matriz de covarianzas residual/latente/de parámetros no definida positiva o en el límite, grados de libertad no válidos o correlación latente absoluta ≥ 1. Los detalles registran cada trayectoria rechazada y el motivo; no se ofrece su aplicación automática.|Le nombre de candidats non sûrs ignorés compte les candidats mieux classés rejetés pour non-convergence, échec de post.check, variance négative, matrice de covariance résiduelle/latente/des paramètres non définie positive ou à la frontière, degrés de liberté non valides ou corrélation latente absolue ≥ 1. Les détails consignent chaque chemin et son diagnostic ; les candidats ignorés ne sont pas proposés pour application automatique.|Die Anzahl übersprungener unsicherer Kandidaten umfasst höher platzierte Kandidaten, die wegen Nichtkonvergenz, post.check-Fehlern, negativer Varianz, nicht positiv definiter oder auf der Grenze liegender Residual-/latenter/Parameterkovarianzmatrix, ungültiger Freiheitsgrade oder absoluter latenter Korrelation ≥ 1 abgelehnt wurden. Die Details nennen jeden Pfad und Diagnosegrund; übersprungene Kandidaten werden nicht zur automatischen Anwendung angeboten.|Số ứng viên không an toàn bị bỏ qua gồm các ứng viên xếp hạng cao hơn nhưng bị từ chối do không hội tụ, lỗi post.check, phương sai âm, ma trận hiệp phương sai phần dư/tiềm ẩn/tham số không xác định dương hoặc ở biên, bậc tự do không hợp lệ, hoặc tương quan tiềm ẩn có giá trị tuyệt đối ≥ 1. Chi tiết ghi từng đường dẫn và lý do; ứng viên bị bỏ qua không được đề xuất áp dụng tự động.
未補正または補正済みのp値だけでは修正を正当化できません。効果量（EPC・標準化EPC）、残差診断、解の許容性、理論、可能なら独立した検証を併用してください。|未校正或校正后的p值均不能单独证明修改合理。请结合效应量（EPC/标准化EPC）、残差诊断、解的可接受性、理论，并尽可能进行独立验证。|Ni un valor p sin ajustar ni uno ajustado justifican una modificación. Utilice tamaño del efecto (EPC/EPC estandarizado), diagnóstico de residuos, admisibilidad, teoría y, preferiblemente, validación independiente.|Une valeur p non ajustée ou ajustée ne justifie pas une modification. Utilisez la taille d’effet (EPC/EPC standardisé), les diagnostics résiduels, l’admissibilité, la théorie et, de préférence, une validation indépendante.|Weder ein unadjustierter noch ein adjustierter p-Wert rechtfertigt eine Modifikation. Verwenden Sie Effektgröße (EPC/standardisiertes EPC), Residualdiagnostik, Zulässigkeit, Theorie und möglichst unabhängige Validierung.|Giá trị p chưa hiệu chỉnh hay đã hiệu chỉnh đều không đủ để biện minh cho điều chỉnh. Hãy kết hợp cỡ hiệu ứng (EPC/EPC chuẩn hóa), chẩn đoán phần dư, tính chấp nhận được, lý thuyết và ưu tiên kiểm định độc lập.'''
translations=[row.split('|') for row in rows.splitlines()]
assert len(translations)==len(sentences) and all(len(row)==6 for row in translations)
for i,lang in enumerate(['ja','zh','es','fr','de','vi']):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 data['translations']['analysis.ui.select']=['選択','选择','Seleccionar','Sélectionner','Auswählen','Chọn'][i]
 for sentence,row in zip(sentences,translations):
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',sentence.lower()).strip('_')]=row[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
