import json, re
from pathlib import Path
rows = '''Proportional hazards|比例ハザード|比例风险|Riesgos proporcionales|Risques proportionnels|Proportionale Hazards|Nguy cơ tỷ lệ
Causal interpretation|因果解釈|因果解释|Interpretación causal|Interprétation causale|Kausale Interpretation|Diễn giải nhân quả
Cause-specific HR|原因別HR|原因别HR|HR específico por causa|HR spécifique à la cause|Ursachenspezifische HR|HR theo nguyên nhân
An HR is a relative instantaneous hazard, not a cumulative risk or probability ratio.|HRは瞬間的なハザードの相対比であり、累積リスクや確率の比ではありません。|HR是瞬时风险率的相对比值，而不是累积风险或概率之比。|Un HR es una razón de riesgos instantáneos, no una razón de riesgos acumulados ni de probabilidades.|Un HR est un rapport de risques instantanés, et non un rapport de risques cumulés ou de probabilités.|Eine HR ist ein Verhältnis momentaner Ereignisraten, kein Verhältnis kumulativer Risiken oder Wahrscheinlichkeiten.|HR là tỷ số nguy cơ tức thời, không phải tỷ số nguy cơ tích lũy hay tỷ số xác suất.
Schoenfeld tests are review signals, not automatic pass/fail rules.|Schoenfeld検定は検討の目安であり、合否を自動的に判定する基準ではありません。|Schoenfeld检验是审查信号，不是自动判定通过或不通过的规则。|Las pruebas de Schoenfeld son señales para revisión, no reglas automáticas de aprobación o rechazo.|Les tests de Schoenfeld sont des éléments à examiner, et non des règles automatiques de validation ou de rejet.|Schoenfeld-Tests liefern Prüfsignale, keine automatischen Regeln für Bestehen oder Nichtbestehen.|Kiểm định Schoenfeld cung cấp dấu hiệu cần xem xét, không phải quy tắc tự động kết luận đạt hay không đạt.
An adjusted HR from observational data is not automatically a causal treatment effect.|観察データの調整済みHRを、そのまま治療の因果効果と解釈することはできません。|观察数据中的调整后HR不能自动解释为治疗的因果效应。|Un HR ajustado a partir de datos observacionales no constituye automáticamente un efecto causal del tratamiento.|Un HR ajusté issu de données observationnelles ne constitue pas automatiquement un effet causal du traitement.|Eine adjustierte HR aus Beobachtungsdaten ist nicht automatisch ein kausaler Behandlungseffekt.|HR đã hiệu chỉnh từ dữ liệu quan sát không tự động là hiệu ứng nhân quả của điều trị.
The CIF estimates actual cumulative incidence in the presence of competing events.|CIFは競合イベントが存在する場合の実際の累積発生率を推定します。|CIF估计存在竞争事件时的实际累积发生率。|La CIF estima la incidencia acumulada real en presencia de eventos competitivos.|La CIF estime l’incidence cumulée réelle en présence d’événements concurrents.|Die CIF schätzt die tatsächliche kumulative Inzidenz bei konkurrierenden Ereignissen.|CIF ước tính tỷ lệ mắc tích lũy thực tế khi có các biến cố cạnh tranh.
A cause-specific HR compares instantaneous hazards among those still event-free.|原因別HRは、まだイベントを経験していない対象者の瞬間的なハザードを比較します。|原因别HR比较尚未发生任何事件者的瞬时风险率。|Un HR específico por causa compara los riesgos instantáneos entre quienes aún no han presentado ningún evento.|Un HR spécifique à la cause compare les risques instantanés parmi les personnes encore sans événement.|Eine ursachenspezifische HR vergleicht momentane Ereignisraten bei Personen, die noch ereignisfrei sind.|HR theo nguyên nhân so sánh nguy cơ tức thời ở những người chưa gặp bất kỳ biến cố nào.
An sHR is a subdistribution hazard ratio linked to the CIF, not an individual risk ratio.|sHRはCIFに関連する部分分布ハザード比であり、個人のリスク比ではありません。|sHR是与CIF相关的亚分布风险比，而不是个体风险比。|Un sHR es una razón de riesgos de subdistribución vinculada a la CIF, no una razón de riesgos individuales.|Un sHR est un rapport de risques de sous-distribution lié à la CIF, et non un risque relatif individuel.|Eine sHR ist eine mit der CIF verbundene Subdistributions-Hazard-Ratio, kein individuelles Risikoverhältnis.|sHR là tỷ số nguy cơ phân phối phụ liên quan đến CIF, không phải tỷ số nguy cơ cá nhân.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
    p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
    for row in rows.splitlines():
        f=row.split('|');assert len(f)==7
        data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
    p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
