import json,re
from pathlib import Path
phrases={
'%s by %s was not computed because no complete cases were available after survey design/subpopulation filtering.':['%s × %s 분석은 조사설계 및 부-모집단 필터링 후 완전사례가 없어 계산하지 못했습니다.','%s × %sは、調査設計・部分母集団の絞り込み後に完全なケースがないため計算されませんでした。','%s × %s在应用调查设计及子总体筛选后没有完整个案，因此未计算。','No se calculó %s por %s porque no había casos completos tras aplicar el diseño de encuesta y el filtro de subpoblación.','%s par %s n’a pas été calculé, car aucun cas complet n’était disponible après application du plan de sondage et du filtre de sous-population.','%s nach %s wurde nicht berechnet, da nach Anwendung des Erhebungsdesigns und Teilpopulationsfilters keine vollständigen Fälle verfügbar waren.','Không tính được %s theo %s vì không có trường hợp đầy đủ sau khi áp dụng thiết kế khảo sát và bộ lọc tiểu quần thể.'],
'%s by %s excluded %s row(s) with missing dependent or group values after survey design/subpopulation filtering.':['%s × %s 분석에서 조사설계 및 부-모집단 필터링 후 종속변수 또는 집단변수 값이 결측인 %s개 행을 제외했습니다.','%s × %sでは、調査設計・部分母集団の絞り込み後に従属変数または群変数が欠損している%s行を除外しました。','%s × %s在应用调查设计及子总体筛选后，排除了因变量或分组变量缺失的%s行。','En %s por %s se excluyeron %s filas con valores perdidos en la variable dependiente o de grupo tras aplicar el diseño de encuesta y el filtro de subpoblación.','Pour %s par %s, %s lignes avec une valeur manquante dans la variable dépendante ou de groupe ont été exclues après application du plan de sondage et du filtre de sous-population.','Für %s nach %s wurden nach Anwendung des Erhebungsdesigns und Teilpopulationsfilters %s Zeilen mit fehlenden Werten der abhängigen oder der Gruppenvariable ausgeschlossen.','Với %s theo %s, đã loại %s dòng có giá trị thiếu ở biến phụ thuộc hoặc biến nhóm sau khi áp dụng thiết kế khảo sát và bộ lọc tiểu quần thể.'],
'%s by %s was not computed because the group variable had fewer than two usable groups after complete-case filtering.':['%s × %s 분석은 완전사례 필터링 후 사용할 수 있는 집단이 2개 미만이어서 계산하지 못했습니다.','%s × %sは、完全ケースへの絞り込み後に利用可能な群が2つ未満のため計算されませんでした。','%s × %s在完整个案筛选后可用组数少于两组，因此未计算。','No se calculó %s por %s porque la variable de grupo tenía menos de dos grupos utilizables tras filtrar los casos completos.','%s par %s n’a pas été calculé, car la variable de groupe comportait moins de deux groupes utilisables après sélection des cas complets.','%s nach %s wurde nicht berechnet, da die Gruppenvariable nach Auswahl vollständiger Fälle weniger als zwei verwendbare Gruppen hatte.','Không tính được %s theo %s vì biến nhóm có ít hơn hai nhóm sử dụng được sau khi lọc các trường hợp đầy đủ.']}
for index,lang in enumerate(['ko','ja','zh','es','fr','de','vi']):
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 for source,values in phrases.items():
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',source.lower()).strip('_')]=values[index]
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
