import json,re
from pathlib import Path
rows='''No higher-order loading paths are specified.|高次因子の負荷パスが指定されていません。|未指定高阶因子载荷路径。|No se han especificado trayectorias de carga de orden superior.|Aucun chemin de saturation d’ordre supérieur n’est spécifié.|Es sind keine Ladungspfade höherer Ordnung angegeben.|Chưa chỉ định đường tải nhân tố bậc cao.
Omega-h requires exactly one higher-order general factor.|omega-hには高次の一般因子がちょうど1つ必要です。|omega-h要求恰好一个高阶一般因子。|Omega-h requiere exactamente un factor general de orden superior.|Omega-h nécessite exactement un facteur général d’ordre supérieur.|Omega-h erfordert genau einen allgemeinen Faktor höherer Ordnung.|Omega-h yêu cầu đúng một nhân tố chung bậc cao.
Omega-h is not reported when a lower-order factor has multiple higher-order loadings.|低次因子が複数の高次因子に負荷する場合、omega-hは報告しません。|低阶因子具有多个高阶载荷时，不报告omega-h。|No se informa omega-h cuando un factor de orden inferior tiene varias cargas de orden superior.|Omega-h n’est pas rapporté lorsqu’un facteur d’ordre inférieur présente plusieurs saturations d’ordre supérieur.|Omega-h wird nicht berichtet, wenn ein Faktor niedrigerer Ordnung mehrere Ladungen höherer Ordnung aufweist.|Không báo cáo omega-h khi một nhân tố bậc thấp có nhiều tải từ các nhân tố bậc cao.
No observed indicators were found under the lower-order factors.|低次因子の下に観測指標が見つかりません。|未在低阶因子下找到观测指标。|No se encontraron indicadores observados bajo los factores de orden inferior.|Aucun indicateur observé n’a été trouvé sous les facteurs d’ordre inférieur.|Unter den Faktoren niedrigerer Ordnung wurden keine beobachteten Indikatoren gefunden.|Không tìm thấy chỉ báo quan sát thuộc các nhân tố bậc thấp.
Omega-h is not reported with cross-loaded observed indicators.|観測指標に交差負荷がある場合、omega-hは報告しません。|观测指标存在交叉载荷时，不报告omega-h。|No se informa omega-h con indicadores observados con cargas cruzadas.|Omega-h n’est pas rapporté en présence d’indicateurs observés à saturations croisées.|Bei beobachteten Indikatoren mit Kreuzladungen wird Omega-h nicht berichtet.|Không báo cáo omega-h khi chỉ báo quan sát có tải chéo.
The model-implied indicator covariance matrix is unavailable.|モデルが含意する指標共分散行列を利用できません。|模型隐含的指标协方差矩阵不可用。|La matriz de covarianzas de indicadores implícita en el modelo no está disponible.|La matrice de covariance des indicateurs impliquée par le modèle n’est pas disponible.|Die modellimplizierte Kovarianzmatrix der Indikatoren ist nicht verfügbar.|Không có ma trận hiệp phương sai chỉ báo hàm ý bởi mô hình.
Omega-h denominator is not positive and finite.|omega-hの分母が正の有限値ではありません。|omega-h的分母不是正的有限值。|El denominador de omega-h no es positivo y finito.|Le dénominateur d’omega-h n’est pas positif et fini.|Der Nenner von Omega-h ist nicht positiv und endlich.|Mẫu số omega-h không phải là giá trị hữu hạn dương.
Hierarchical omega was not reported: %s|階層的omegaは報告されませんでした：%s|未报告层级omega：%s|No se informó omega jerárquico: %s|L’oméga hiérarchique n’a pas été rapporté : %s|Hierarchisches Omega wurde nicht berichtet: %s|Không báo cáo omega phân cấp: %s'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
