import json, re
from pathlib import Path

# Fixed, generated checklist text only; user construct names are not dictionary keys.
rows = '''PLS algorithm iterations	PLSアルゴリズム反復回数	PLS算法迭代次数	Iteraciones del algoritmo PLS	Itérations de l’algorithme PLS	PLS-Algorithmus: Iterationen	Số lần lặp thuật toán PLS
Final weight difference	最終重み差	最终权重差	Diferencia final de pesos	Différence finale des poids	Abschließende Gewichtsdifferenz	Chênh lệch trọng số cuối cùng
Missing-data method	欠測データ処理法	缺失数据处理方法	Método para datos faltantes	Méthode de traitement des données manquantes	Verfahren für fehlende Daten	Phương pháp xử lý dữ liệu thiếu
Approx PLS SRMR	近似PLS SRMR	近似PLS SRMR	SRMR de PLS aproximado	SRMR PLS approximatif	Approximativer PLS-SRMR	SRMR PLS xấp xỉ
Approx d_G	近似d_G	近似d_G	d_G aproximado	d_G approximatif	Approximatives d_G	d_G xấp xỉ
Approx d_ULS	近似d_ULS	近似d_ULS	d_ULS aproximado	d_ULS approximatif	Approximatives d_ULS	d_ULS xấp xỉ
Approx NFI	近似NFI	近似NFI	NFI aproximado	NFI approximatif	Approximativer NFI	NFI xấp xỉ
10-times rule margin	10倍則の余裕比	10倍规则余量比	Margen de la regla de 10 veces	Marge de la règle des 10 fois	Spielraum der 10-fach-Regel	Tỷ lệ dư theo quy tắc 10 lần
Min outer loading	最小外部負荷量	最小外部载荷	Carga externa mínima	Charge externe minimale	Minimale äußere Ladung	Hệ số tải ngoài nhỏ nhất
Min rhoC	最小rhoC	最小rhoC	rhoC mínimo	rhoC minimal	Minimales rhoC	rhoC nhỏ nhất
Max HTMT	最大HTMT	最大HTMT	HTMT máximo	HTMT maximal	Maximales HTMT	HTMT lớn nhất
Max item VIF	最大指標VIF	最大指标VIF	VIF máximo de indicadores	VIF maximal des indicateurs	Maximaler Indikator-VIF	VIF chỉ báo lớn nhất
Max inner VIF	最大内部VIF	最大内部VIF	VIF interno máximo	VIF interne maximal	Maximaler innerer VIF	VIF bên trong lớn nhất
Max f2	最大f²	最大f²	f² máximo	f² maximal	Maximales f²	f² lớn nhất
PLSpredict summary	PLSpredictの要約	PLSpredict摘要	Resumen de PLSpredict	Résumé de PLSpredict	PLSpredict-Zusammenfassung	Tóm tắt PLSpredict
Not executed	未実行	未执行	No ejecutado	Non exécuté	Nicht ausgeführt	Chưa thực hiện
Algorithm diagnostic; inspect unusually high iteration counts.	アルゴリズム診断です。反復回数が異常に多い場合は確認してください。	算法诊断；请检查异常偏高的迭代次数。	Diagnóstico del algoritmo; examine los recuentos de iteraciones inusualmente altos.	Diagnostic de l’algorithme ; examinez les nombres d’itérations anormalement élevés.	Algorithmusdiagnostik; prüfen Sie ungewöhnlich hohe Iterationszahlen.	Chẩn đoán thuật toán; kiểm tra số lần lặp cao bất thường.
Smaller values indicate stable outer-weight convergence.	値が小さいほど外部重みの収束が安定しています。	值越小表示外部权重收敛越稳定。	Los valores menores indican una convergencia estable de los pesos externos.	Les valeurs faibles indiquent une convergence stable des poids externes.	Kleinere Werte zeigen eine stabile Konvergenz der äußeren Gewichte an.	Giá trị nhỏ hơn cho thấy trọng số ngoài hội tụ ổn định.
Indicator-mean replacement is fixed for PLS/PLSc. Report the replaced rows/cells; bootstrap recomputes indicator means within each resample.	PLS/PLScでは指標平均による置換を固定的に使用します。置換した行・セル数を報告してください。ブートストラップでは各再標本内で指標平均を再計算します。	PLS/PLSc固定采用指标均值替代。请报告替代的行和单元格；Bootstrap在每次重采样内重新计算指标均值。	PLS/PLSc utiliza siempre sustitución por la media del indicador. Informe las filas/celdas sustituidas; el bootstrap recalcula las medias en cada remuestra.	PLS/PLSc utilise systématiquement le remplacement par la moyenne de l’indicateur. Rapportez les lignes/cellules remplacées ; le bootstrap recalcule les moyennes dans chaque rééchantillon.	PLS/PLSc verwendet fest den Ersatz durch Indikatormittelwerte. Berichten Sie ersetzte Zeilen/Zellen; der Bootstrap berechnet die Mittelwerte in jeder Stichprobenwiederholung neu.	PLS/PLSc cố định thay thế bằng trung bình chỉ báo. Báo cáo các hàng/ô được thay thế; bootstrap tính lại trung bình chỉ báo trong từng mẫu lấy lại.
Locally reconstructed reflective-measurement SRMR; report descriptively without an accept/reject cutoff.	ローカルに再構成した反映型測定のSRMRです。採択・棄却の閾値を設けず記述的に報告します。	本地重构的反映性测量SRMR；应描述性报告，不采用接受/拒绝阈值。	SRMR de medición reflectiva reconstruido localmente; infórmelo descriptivamente sin umbral de aceptación/rechazo.	SRMR de mesure réflexive reconstruit localement ; rapportez-le descriptivement sans seuil d’acceptation/rejet.	Lokal rekonstruierter SRMR der reflektiven Messung; deskriptiv ohne Annahme-/Ablehnungsgrenzwert berichten.	SRMR đo lường phản xạ được tái dựng cục bộ; báo cáo theo mô tả, không dùng ngưỡng chấp nhận/bác bỏ.
Locally reconstructed geodesic discrepancy; report descriptively because no universal cutoff applies.	ローカルに再構成した測地距離に基づく不一致です。普遍的な閾値がないため記述的に報告します。	本地重构的测地距离差异；不存在通用阈值，应描述性报告。	Discrepancia geodésica reconstruida localmente; infórmela descriptivamente, pues no existe un umbral universal.	Écart géodésique reconstruit localement ; rapportez-le descriptivement, sans seuil universel applicable.	Lokal rekonstruierte geodätische Diskrepanz; deskriptiv berichten, da kein universeller Grenzwert gilt.	Độ sai khác trắc địa được tái dựng cục bộ; báo cáo theo mô tả vì không có ngưỡng phổ quát.
Locally reconstructed squared Euclidean discrepancy; report descriptively because no universal cutoff applies.	ローカルに再構成したユークリッド距離の二乗に基づく不一致です。普遍的な閾値がないため記述的に報告します。	本地重构的平方欧氏距离差异；不存在通用阈值，应描述性报告。	Discrepancia euclídea cuadrática reconstruida localmente; infórmela descriptivamente, pues no existe un umbral universal.	Écart euclidien au carré reconstruit localement ; rapportez-le descriptivement, sans seuil universel applicable.	Lokal rekonstruierte quadrierte euklidische Diskrepanz; deskriptiv berichten, da kein universeller Grenzwert gilt.	Độ sai khác Euclid bình phương được tái dựng cục bộ; báo cáo theo mô tả vì không có ngưỡng phổ quát.
Locally reconstructed NFI against an independence baseline; report descriptively without an accept/reject cutoff.	独立モデルを基準にローカルで再構成したNFIです。採択・棄却の閾値を設けず記述的に報告します。	以独立模型为基准本地重构的NFI；应描述性报告，不采用接受/拒绝阈值。	NFI reconstruido localmente frente a un modelo de independencia; infórmelo descriptivamente sin umbral de aceptación/rechazo.	NFI reconstruit localement par rapport au modèle d’indépendance ; rapportez-le descriptivement sans seuil d’acceptation/rejet.	Lokal rekonstruierter NFI gegenüber einem Unabhängigkeitsmodell; deskriptiv ohne Annahme-/Ablehnungsgrenzwert berichten.	NFI được tái dựng cục bộ so với mô hình độc lập; báo cáo theo mô tả, không dùng ngưỡng chấp nhận/bác bỏ.
Historically imprecise 10-times heuristic; do not use it to justify sample size. Prefer a priori power or model-specific simulation.	従来の10倍則は不正確な経験則であり、標本サイズの根拠には使用しないでください。事前の検出力分析やモデル固有のシミュレーションを優先します。	传统10倍经验规则不精确，不应用于论证样本量。应优先采用事前功效分析或针对模型的模拟。	La regla histórica de 10 veces es imprecisa; no la use para justificar el tamaño muestral. Prefiera potencia a priori o simulación específica del modelo.	La règle historique des 10 fois est imprécise ; ne l’utilisez pas pour justifier la taille d’échantillon. Préférez une analyse de puissance a priori ou une simulation propre au modèle.	Die historische 10-fach-Faustregel ist ungenau; begründen Sie damit nicht den Stichprobenumfang. Bevorzugen Sie eine A-priori-Poweranalyse oder modellspezifische Simulation.	Quy tắc kinh nghiệm 10 lần vốn không chính xác; không dùng để biện minh cỡ mẫu. Ưu tiên phân tích lực kiểm định tiên nghiệm hoặc mô phỏng riêng cho mô hình.
Outer loadings are descriptive evidence, not automatic deletion rules; review low values with content validity, cross-loadings, uncertainty, and prespecified theory.	外部負荷量は記述的な証拠であり、自動削除の規則ではありません。低い値は内容妥当性・交差負荷量・不確実性・事前に定めた理論と併せて検討します。	外部载荷是描述性证据，而非自动删除规则；低值应结合内容效度、交叉载荷、不确定性和预先设定的理论审查。	Las cargas externas son evidencia descriptiva, no reglas de eliminación automática; revise valores bajos con validez de contenido, cargas cruzadas, incertidumbre y teoría preespecificada.	Les charges externes sont des éléments descriptifs, pas des règles de suppression automatique ; examinez les valeurs faibles avec la validité de contenu, les charges croisées, l’incertitude et la théorie préspécifiée.	Äußere Ladungen sind deskriptive Evidenz, keine automatischen Löschregeln; prüfen Sie niedrige Werte mit Inhaltsvalidität, Kreuzladungen, Unsicherheit und vorab festgelegter Theorie.	Hệ số tải ngoài là bằng chứng mô tả, không phải quy tắc tự động loại bỏ; xem xét giá trị thấp cùng giá trị nội dung, tải chéo, độ bất định và lý thuyết định trước.
The .70 rhoC value is a descriptive reliability reference, not a universal scale-acceptance rule.	rhoCの.70は信頼性の記述的な参考値であり、尺度採択の普遍的な規則ではありません。	rhoC的.70是描述性信度参考值，并非通用的量表接受规则。	El valor .70 de rhoC es una referencia descriptiva de fiabilidad, no una regla universal de aceptación de escalas.	La valeur .70 de rhoC est un repère descriptif de fiabilité, pas une règle universelle d’acceptation des échelles.	Der rhoC-Wert .70 ist eine deskriptive Reliabilitätsreferenz, keine universelle Regel zur Annahme einer Skala.	Giá trị rhoC .70 là mốc mô tả độ tin cậy, không phải quy tắc phổ quát để chấp nhận thang đo.
The .50 AVE value is a descriptive convergent-validity reference, not an automatic construct-acceptance or indicator-deletion rule.	AVEの.50は収束的妥当性の記述的な参考値であり、構成概念の自動採択や指標削除の規則ではありません。	AVE的.50是描述性聚合效度参考值，并非自动接受构念或删除指标的规则。	El valor .50 de AVE es una referencia descriptiva de validez convergente, no una regla automática de aceptación de constructos o eliminación de indicadores.	La valeur .50 d’AVE est un repère descriptif de validité convergente, pas une règle automatique d’acceptation des construits ou de suppression des indicateurs.	Der AVE-Wert .50 ist eine deskriptive Referenz für konvergente Validität, keine automatische Regel zur Annahme von Konstrukten oder Löschung von Indikatoren.	Giá trị AVE .50 là mốc mô tả giá trị hội tụ, không phải quy tắc tự động chấp nhận cấu trúc hoặc loại bỏ chỉ báo.
HTMT references do not establish discriminant validity; interpret with intervals, cross-loadings, construct correlations, theory, and competing measurement models.	HTMTの参考値だけでは弁別的妥当性は確立できません。区間・交差負荷量・構成概念間相関・理論・競合測定モデルと併せて解釈します。	HTMT参考值不能确立区分效度；应结合区间、交叉载荷、构念相关、理论和竞争测量模型解释。	Las referencias HTMT no establecen validez discriminante; interprete con intervalos, cargas cruzadas, correlaciones entre constructos, teoría y modelos de medición alternativos.	Les repères HTMT n’établissent pas la validité discriminante ; interprétez-les avec les intervalles, charges croisées, corrélations entre construits, théorie et modèles de mesure concurrents.	HTMT-Referenzwerte belegen keine diskriminante Validität; interpretieren Sie sie mit Intervallen, Kreuzladungen, Konstruktkorrelationen, Theorie und konkurrierenden Messmodellen.	Các mốc HTMT không xác lập giá trị phân biệt; diễn giải cùng khoảng ước lượng, tải chéo, tương quan cấu trúc, lý thuyết và mô hình đo lường cạnh tranh.
Item VIF cutoffs are descriptive references. High values flag redundant indicators or unstable formative weights; low values do not establish measurement quality.	指標VIFの閾値は記述的な参考値です。高い値は指標の冗長性や形成型重みの不安定さを示唆しますが、低い値だけでは測定品質は確立できません。	指标VIF阈值是描述性参考。高值提示指标冗余或形成性权重不稳定；低值不能确立测量质量。	Los umbrales VIF de indicadores son referencias descriptivas. Valores altos señalan indicadores redundantes o pesos formativos inestables; los bajos no establecen calidad de medición.	Les seuils VIF des indicateurs sont descriptifs. Les valeurs élevées signalent des indicateurs redondants ou des poids formatifs instables ; les faibles n’établissent pas la qualité de mesure.	Indikator-VIF-Grenzwerte sind deskriptive Referenzen. Hohe Werte weisen auf redundante Indikatoren oder instabile formative Gewichte hin; niedrige belegen keine Messqualität.	Ngưỡng VIF chỉ báo là mốc mô tả. Giá trị cao cảnh báo chỉ báo dư thừa hoặc trọng số tạo thành không ổn định; giá trị thấp không xác lập chất lượng đo lường.
Inner VIF cutoffs are descriptive references. Review coefficient sign/magnitude changes, suppression, bootstrap instability, and theoretical overlap across predictors.	内部VIFの閾値は記述的な参考値です。係数の符号・大きさの変化、抑制効果、ブートストラップの不安定さ、予測変数間の理論的重複を確認します。	内部VIF阈值是描述性参考。请检查系数符号/大小变化、抑制效应、Bootstrap不稳定性及预测变量的理论重叠。	Los umbrales VIF internos son referencias descriptivas. Revise cambios de signo/magnitud, supresión, inestabilidad del bootstrap y solapamiento teórico entre predictores.	Les seuils VIF internes sont descriptifs. Examinez les changements de signe/amplitude des coefficients, la suppression, l’instabilité du bootstrap et le chevauchement théorique des prédicteurs.	Innere VIF-Grenzwerte sind deskriptive Referenzen. Prüfen Sie Änderungen von Vorzeichen/Größe der Koeffizienten, Suppression, Bootstrap-Instabilität und theoretische Überlappung der Prädiktoren.	Ngưỡng VIF bên trong là mốc mô tả. Xem xét thay đổi dấu/độ lớn hệ số, hiệu ứng ức chế, bootstrap không ổn định và sự chồng lấp lý thuyết giữa các biến dự báo.
The .02/.15/.35 f2 ranges are descriptive anchors, not universal importance thresholds.	f²の.02/.15/.35は記述的な目安であり、重要性の普遍的な閾値ではありません。	f²的.02/.15/.35是描述性参照，并非通用的重要性阈值。	Los rangos .02/.15/.35 de f² son referencias descriptivas, no umbrales universales de importancia.	Les plages .02/.15/.35 de f² sont des repères descriptifs, pas des seuils universels d’importance.	Die f²-Bereiche .02/.15/.35 sind deskriptive Anhaltspunkte, keine universellen Wichtigkeitsgrenzen.	Các mức f² .02/.15/.35 là mốc mô tả, không phải ngưỡng phổ quát về tầm quan trọng.
Out-of-sample prediction is strongest when PLS error is lower than LM.	PLSの誤差がLMより小さい場合に、標本外予測が最も良好です。	当PLS误差低于LM时，样本外预测表现最佳。	La predicción fuera de muestra es más sólida cuando el error PLS es menor que el de LM.	La prédiction hors échantillon est la meilleure lorsque l’erreur PLS est inférieure à celle de LM.	Die Vorhersage außerhalb der Stichprobe ist am stärksten, wenn der PLS-Fehler unter dem LM-Fehler liegt.	Dự báo ngoài mẫu tốt nhất khi sai số PLS thấp hơn LM.'''

rows += '''
mean_replacement	平均代入	均值替代	Sustitución por la media	Remplacement par la moyenne	Mittelwertersetzung	Thay thế bằng trung bình
not recorded	記録なし	未记录	No registrado	Non renseigné	Nicht dokumentiert	Chưa ghi nhận
Executed; no comparable indicator metrics	実行済み：比較可能な指標の評価値なし	已执行；无可比较的指标度量	Ejecutado; sin métricas de indicadores comparables	Exécuté ; aucune métrique d’indicateur comparable	Ausgeführt; keine vergleichbaren Indikatormetriken	Đã thực hiện; không có thước đo chỉ báo có thể so sánh
{count}/{total} indicator metrics favor PLS over LM	{total}件中{count}件の指標評価でPLSの誤差がLMより小さい	{total}项指标度量中有{count}项的PLS误差低于LM	{count}/{total} métricas de indicadores favorecen PLS frente a LM	{count}/{total} métriques d’indicateurs favorisent PLS par rapport à LM	{count}/{total} Indikatormetriken sprechen für PLS gegenüber LM	{count}/{total} thước đo chỉ báo cho thấy PLS tốt hơn LM'''

for i, lang in enumerate(['ja', 'zh', 'es', 'fr', 'de', 'vi'], 1):
    path = Path('i18n') / (lang + '.json')
    data = json.loads(path.read_text(encoding='utf-8'))
    for line in rows.splitlines():
        fields = line.split('\t')
        assert len(fields) == 7, fields
        key = 'analysis.ui.' + re.sub(r'[^a-z0-9]+', '_', fields[0].lower()).strip('_')
        data['translations'][key] = fields[i]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
