import json,re
from pathlib import Path
rows='''All selected MI paths have already been applied.|選択したMI経路はすべて適用済みです。|所有选定MI路径均已应用。|Todas las trayectorias MI seleccionadas ya se han aplicado.|Tous les chemins MI sélectionnés ont déjà été appliqués.|Alle ausgewählten MI-Pfade wurden bereits angewendet.|Tất cả đường dẫn MI đã chọn đã được áp dụng.
Document MI modification|MI修正の記録|记录MI修改|Documentar modificación MI|Documenter la modification MI|MI-Modifikation dokumentieren|Ghi lại điều chỉnh MI
Paths to add: |追加する経路：|要添加的路径：|Trayectorias que se añadirán: |Chemins à ajouter : |Hinzuzufügende Pfade: |Đường dẫn cần thêm: 
Skipped candidates and reasons|除外した候補と理由|跳过的候选项及原因|Candidatos omitidos y motivos|Candidats ignorés et raisons|Übersprungene Kandidaten und Gründe|Các ứng viên bị bỏ qua và lý do
These candidates were excluded from application because they failed safety diagnostics.|これらの候補は安全性診断を通過しなかったため適用対象から除外されました。|这些候选项未通过安全性诊断，因此未予应用。|Estos candidatos se excluyeron de la aplicación porque no superaron los diagnósticos de seguridad.|Ces candidats ont été exclus de l’application car ils n’ont pas satisfait aux diagnostics de sécurité.|Diese Kandidaten wurden nicht angewendet, da sie die Sicherheitsdiagnostik nicht bestanden haben.|Các ứng viên này bị loại khỏi việc áp dụng vì không vượt qua kiểm tra an toàn.
Substantive justification|実質的な根拠|实质性依据|Justificación sustantiva|Justification substantielle|Inhaltliche Begründung|Cơ sở lý luận thực chất
Explain why freeing these parameters is theoretically defensible.|これらのパラメータを自由化することが理論的に妥当な理由を記述してください。|请说明为何释放这些参数在理论上是合理的。|Explique por qué es teóricamente defendible liberar estos parámetros.|Expliquez pourquoi la libération de ces paramètres est théoriquement justifiable.|Erläutern Sie, warum die freie Schätzung dieser Parameter theoretisch vertretbar ist.|Giải thích vì sao việc cho phép ước lượng tự do các tham số này có cơ sở lý thuyết.
Apply and reanalyze|適用して再分析|应用并重新分析|Aplicar y volver a analizar|Appliquer et réanalyser|Anwenden und erneut analysieren|Áp dụng và phân tích lại
The selected MI paths were added, documented, and reanalyzed.|選択したMI経路を追加・記録し、再分析しました。|已添加并记录选定MI路径，然后重新进行了分析。|Se añadieron y documentaron las trayectorias MI seleccionadas y se repitió el análisis.|Les chemins MI sélectionnés ont été ajoutés et documentés, puis l’analyse a été relancée.|Die ausgewählten MI-Pfade wurden hinzugefügt und dokumentiert; die Analyse wurde erneut durchgeführt.|Đã thêm và ghi lại các đường dẫn MI đã chọn, sau đó phân tích lại.
Estimator recommendation|推定量の推奨|估计量建议|Recomendación de estimador|Recommandation d’estimateur|Empfehlung des Schätzverfahrens|Khuyến nghị phương pháp ước lượng
The sample-size-sensitive Mardia screen flagged departure from multivariate normality in the continuous indicators. Consider MLR for robust standard errors and a scaled test. This screen alone does not establish the substantive magnitude of departure or its impact on estimates.|標本サイズに敏感なMardiaスクリーニングで、連続指標の多変量正規性からの逸脱が示されました。頑健標準誤差と補正検定を提供するMLRを検討してください。この検査だけでは逸脱の実質的な大きさや推定値への影響は判断できません。|对样本量敏感的Mardia筛查提示连续指标偏离多元正态分布。可考虑使用MLR获得稳健标准误和缩放检验。仅凭此筛查无法确定偏离的实际程度或其对估计值的影响。|El cribado de Mardia, sensible al tamaño muestral, detectó una desviación de la normalidad multivariante en los indicadores continuos. Considere MLR para obtener errores estándar robustos y una prueba escalada. Este cribado por sí solo no determina la magnitud sustantiva de la desviación ni su impacto en las estimaciones.|Le dépistage de Mardia, sensible à la taille de l’échantillon, a signalé un écart à la normalité multivariée des indicateurs continus. Envisagez MLR pour des erreurs types robustes et un test corrigé. Ce dépistage seul ne permet pas de déterminer l’ampleur substantielle de l’écart ni son impact sur les estimations.|Das stichprobengrößenabhängige Mardia-Screening zeigt eine Abweichung der kontinuierlichen Indikatoren von der multivariaten Normalverteilung. Erwägen Sie MLR für robuste Standardfehler und einen skalierten Test. Dieses Screening allein bestimmt weder das inhaltliche Ausmaß der Abweichung noch deren Einfluss auf die Schätzungen.|Sàng lọc Mardia, vốn nhạy với cỡ mẫu, phát hiện các chỉ báo liên tục lệch khỏi phân phối chuẩn đa biến. Hãy cân nhắc MLR để có sai số chuẩn vững và kiểm định hiệu chỉnh. Chỉ riêng sàng lọc này không xác định được mức độ sai lệch thực chất hay ảnh hưởng đến các ước lượng.
Mardia skewness p = %s; kurtosis p = %s; complete cases = %s of %s.|Mardia歪度 p = %s；尖度 p = %s；完全ケース = %s / %s。|Mardia偏度 p = %s；峰度 p = %s；完整个案 = %s / %s。|Asimetría de Mardia p = %s; curtosis p = %s; casos completos = %s de %s.|Asymétrie de Mardia p = %s ; aplatissement p = %s ; cas complets = %s sur %s.|Mardia-Schiefe p = %s; Kurtosis p = %s; vollständige Fälle = %s von %s.|Độ lệch Mardia p = %s; độ nhọn p = %s; trường hợp đầy đủ = %s trên %s.
Bollen-Stine bootstrap is available only for ML; choosing MLR will run the model without Bollen-Stine bootstrap.|Bollen-StineブートストラップはMLでのみ利用できます。MLRを選ぶとBollen-Stineブートストラップなしでモデルを実行します。|Bollen-Stine自助法仅适用于ML；选择MLR将运行不含Bollen-Stine自助法的模型。|El bootstrap de Bollen-Stine solo está disponible para ML; al elegir MLR se ejecutará el modelo sin este bootstrap.|Le bootstrap de Bollen-Stine est disponible uniquement avec ML ; choisir MLR exécutera le modèle sans ce bootstrap.|Der Bollen-Stine-Bootstrap ist nur für ML verfügbar; bei Auswahl von MLR wird das Modell ohne Bollen-Stine-Bootstrap ausgeführt.|Bootstrap Bollen-Stine chỉ khả dụng với ML; chọn MLR sẽ chạy mô hình không có bootstrap Bollen-Stine.
Run with ML|MLで実行|使用ML运行|Ejecutar con ML|Exécuter avec ML|Mit ML ausführen|Chạy với ML
Run with MLR|MLRで実行|使用MLR运行|Ejecutar con MLR|Exécuter avec MLR|Mit MLR ausführen|Chạy với MLR'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('|');assert len(f)==7
  assert f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
