"""Reliability precision planning notes with preserved count tokens."""
import json
from pathlib import Path
keys='note_reliability_ba note_reliability_alpha_items note_reliability_icc_items note_reliability_kappa'.split()
rows={
'en':['Approximate sample size for precision of Bland-Altman limits of agreement using SD of paired differences and desired LoA confidence interval half-width.','Bonett-style log(1 - alpha) normal approximation for coefficient alpha precision with %s items; final n is not allowed below items + 1.','Approximate Fisher z precision method for intraclass correlation with %s raters/measurements.',"Large-sample normal approximation for Cohen's kappa precision assuming equal category prevalence."],
'ko':['대응 차이의 표준편차와 원하는 일치한계 신뢰구간 반폭을 사용하여 Bland–Altman 일치한계의 정밀도 표본수를 근사합니다.','%s개 문항의 알파 계수 정밀도를 위한 Bonett 방식 log(1 - alpha) 정규근사입니다. 최종 n은 items + 1보다 작을 수 없습니다.','평가자/측정 %s개에 대한 급내상관 정밀도를 Fisher z 방식으로 근사합니다.','범주 비율이 같다고 가정하는 Cohen의 카파 정밀도에 대한 대표본 정규근사입니다.'],
'ja':['対応差の標準偏差と希望する一致限界の信頼区間半幅を用いてBland–Altman一致限界の精度の標本サイズを近似します。','%s項目のアルファ係数の精度に対するBonett型log(1 - alpha)正規近似です。最終nはitems + 1未満にはしません。','%s人の評価者/回の測定による級内相関の精度をFisher z法で近似します。','各カテゴリーの割合が等しいと仮定したCohenのカッパの精度に対する大標本正規近似です。'],
'zh':['使用配对差值标准差及期望的一致性界限置信区间半宽，近似计算Bland–Altman一致性界限精度所需样本量。','含%s个条目的alpha系数精度采用Bonett型log(1 - alpha)正态近似；最终n不得小于items + 1。','对%s名评定者/次测量的组内相关精度采用近似Fisher z方法。','假设各类别比例相等，对Cohen kappa精度采用大样本正态近似。'],
'es':['Tamaño muestral aproximado para la precisión de los límites de acuerdo de Bland–Altman usando la desviación estándar de las diferencias pareadas y la semiamplitud deseada del intervalo de confianza de los límites.','Aproximación normal de tipo Bonett log(1 - alpha) para la precisión del coeficiente alfa con %s ítems; n final no puede ser inferior a items + 1.','Método aproximado de precisión z de Fisher para la correlación intraclase con %s evaluadores/mediciones.','Aproximación normal de muestra grande para la precisión de kappa de Cohen suponiendo proporciones iguales de categorías.'],
'fr':['Taille d’échantillon approchée pour la précision des limites d’accord de Bland–Altman avec l’écart-type des différences appariées et la demi-largeur souhaitée de leur intervalle de confiance.','Approximation normale de type Bonett log(1 - alpha) pour la précision du coefficient alpha avec %s items; n final ne peut être inférieur à items + 1.','Méthode approchée de précision z de Fisher pour la corrélation intraclasse avec %s évaluateurs/mesures.','Approximation normale de grand échantillon pour la précision du kappa de Cohen en supposant des proportions de catégories égales.'],
'de':['Approximierter Stichprobenumfang für die Präzision der Bland–Altman-Übereinstimmungsgrenzen mit der Standardabweichung gepaarter Differenzen und gewünschter Konfidenzintervall-Halbbreite der Grenzen.','Bonett-artige log(1 - alpha)-Normalapproximation für die Präzision von Koeffizient Alpha mit %s Items; das endgültige n darf nicht unter items + 1 liegen.','Approximative Fisher-z-Präzisionsmethode für die Intraklassenkorrelation mit %s Beurteilern/Messungen.','Großstichproben-Normalapproximation für Cohens Kappa-Präzision unter Annahme gleicher Kategorieanteile.'],
'vi':['Cỡ mẫu xấp xỉ cho độ chính xác của giới hạn đồng thuận Bland–Altman sử dụng độ lệch chuẩn của chênh lệch ghép cặp và nửa độ rộng khoảng tin cậy mong muốn của giới hạn.','Xấp xỉ chuẩn log(1 - alpha) kiểu Bonett cho độ chính xác hệ số alpha với %s mục; n cuối cùng không được nhỏ hơn items + 1.','Phương pháp độ chính xác Fisher z xấp xỉ cho tương quan nội lớp với %s người đánh giá/lần đo.','Xấp xỉ chuẩn mẫu lớn cho độ chính xác kappa của Cohen, giả định các loại có tỷ lệ bằng nhau.']}
for lang,values in rows.items():
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
