import json,re
from pathlib import Path
# English, Korean, Japanese, Chinese, Spanish, French, German, Vietnamese.
rows='''Structural-effect capability plan|구조효과 지원 범위|構造効果の対応範囲|结构效应支持范围|Compatibilidad de efectos estructurales|Prise en charge des effets structurels|Unterstützte strukturelle Effekte|Phạm vi hỗ trợ tác động cấu trúc
This preflight record confirms whether requested effects are actually estimated by the selected engine.|요청한 효과가 선택한 엔진에서 실제로 추정되는지 확인하는 사전 기록입니다.|要求した効果を選択したエンジンで実際に推定できるか確認する事前記録です。|此预检记录确认所选引擎是否实际估计请求的效应。|Este registro previo confirma si el motor seleccionado estima realmente los efectos solicitados.|Ce relevé préalable confirme si le moteur sélectionné estime effectivement les effets demandés.|Diese Vorabprüfung dokumentiert, ob die angeforderten Effekte mit der gewählten Engine tatsächlich geschätzt werden.|Bản ghi kiểm tra trước xác nhận công cụ đã chọn có thực sự ước lượng các tác động được yêu cầu hay không.
Effect|효과|効果|效应|Efecto|Effet|Effekt|Tác động
Limitation|제한 사항|制約|限制|Limitación|Limite|Einschränkung|Giới hạn
Direct effects|직접효과|直接効果|直接效应|Efectos directos|Effets directs|Direkte Effekte|Tác động trực tiếp
Mediation|매개효과|媒介効果|中介效应|Mediación|Médiation|Mediation|Trung gian
Moderation|조절효과|調整効果|调节效应|Moderación|Modération|Moderation|Điều tiết
Moderated mediation|조절된 매개효과|調整された媒介効果|有调节的中介效应|Mediación moderada|Médiation modérée|Moderierte Mediation|Trung gian có điều tiết
Supported|지원됨|対応|支持|Compatible|Pris en charge|Unterstützt|Được hỗ trợ
Available when an indirect chain contains the moderated path|간접효과 경로에 조절된 경로가 포함되면 사용 가능|間接経路に調整されたパスが含まれる場合に利用可能|间接路径包含被调节路径时可用|Disponible si la cadena indirecta contiene la ruta moderada|Disponible si la chaîne indirecte contient le chemin modéré|Verfügbar, wenn die indirekte Kette den moderierten Pfad enthält|Khả dụng khi chuỗi gián tiếp chứa đường dẫn có điều tiết
lavaan structural regression|lavaan 구조회귀|lavaan構造回帰|lavaan结构回归|Regresión estructural lavaan|Régression structurelle lavaan|Strukturelle Regression mit lavaan|Hồi quy cấu trúc lavaan
Defined indirect and total effects|정의된 간접효과와 총효과|定義された間接効果と総効果|定义的间接效应和总效应|Efectos indirectos y totales definidos|Effets indirects et totaux définis|Definierte indirekte und Gesamteffekte|Tác động gián tiếp và tổng tác động đã định nghĩa
Unconstrained all-pairs product indicators with double-mean-centering|이중 평균중심화를 적용한 비제약 전체 쌍 곱지표|二重平均中心化による非制約の全ペア積指標|双重均值中心化的无约束全配对乘积指标|Indicadores producto de todos los pares sin restricciones con doble centrado en la media|Indicateurs produits de toutes les paires sans contraintes avec double centrage sur la moyenne|Unbeschränkte Produktindikatoren aller Paare mit doppelter Mittelwertzentrierung|Chỉ báo tích mọi cặp không ràng buộc với định tâm trung bình kép
Unconstrained matched-pair product indicators with double-mean-centering|이중 평균중심화를 적용한 비제약 대응 쌍 곱지표|二重平均中心化による非制約の対応ペア積指標|双重均值中心化的无约束匹配配对乘积指标|Indicadores producto de pares emparejados sin restricciones con doble centrado en la media|Indicateurs produits de paires appariées sans contraintes avec double centrage sur la moyenne|Unbeschränkte Produktindikatoren zugeordneter Paare mit doppelter Mittelwertzentrierung|Chỉ báo tích cặp tương ứng không ràng buộc với định tâm trung bình kép
Unconstrained all-pairs product indicators with indicator mean-centering (legacy)|지표 평균중심화를 적용한 비제약 전체 쌍 곱지표(기존 방식)|指標平均中心化による非制約の全ペア積指標（旧方式）|指标均值中心化的无约束全配对乘积指标（旧版）|Indicadores producto de todos los pares sin restricciones con centrado de indicadores en la media (heredado)|Indicateurs produits de toutes les paires sans contraintes avec centrage des indicateurs sur la moyenne (ancien)|Unbeschränkte Produktindikatoren aller Paare mit Mittelwertzentrierung der Indikatoren (alt)|Chỉ báo tích mọi cặp không ràng buộc với định tâm trung bình chỉ báo (cũ)
Conditional indirect effect and index of moderated mediation|조건부 간접효과와 조절된 매개효과 지수|条件付き間接効果と調整された媒介効果の指数|条件间接效应和有调节的中介效应指数|Efecto indirecto condicional e índice de mediación moderada|Effet indirect conditionnel et indice de médiation modérée|Bedingter indirekter Effekt und Index der moderierten Mediation|Tác động gián tiếp có điều kiện và chỉ số trung gian có điều tiết
Interpret only theory-specified directed paths.|이론으로 명시한 방향성 경로만 해석하세요.|理論で指定した有向パスのみを解釈してください。|仅解释理论指定的有向路径。|Interprete solo las rutas dirigidas especificadas por la teoría.|Interprétez uniquement les chemins orientés spécifiés par la théorie.|Interpretieren Sie nur theoretisch spezifizierte gerichtete Pfade.|Chỉ diễn giải các đường dẫn có hướng được lý thuyết xác định.
Use bootstrap confidence intervals when requested; significance of component paths alone is not a mediation test.|요청한 경우 부트스트랩 신뢰구간을 사용하세요. 구성 경로의 유의성만으로 매개효과를 검정할 수 없습니다.|要求時はブートストラップ信頼区間を使用します。構成パスの有意性だけでは媒介効果の検定になりません。|请求时使用自助法置信区间；组成路径的显著性本身不是中介效应检验。|Use intervalos de confianza bootstrap cuando se soliciten; la significación de las rutas componentes por sí sola no prueba mediación.|Utilisez les intervalles de confiance bootstrap demandés ; la significativité des chemins composants seule ne teste pas la médiation.|Verwenden Sie angeforderte Bootstrap-Konfidenzintervalle; die Signifikanz einzelner Teilpfade allein ist kein Mediationstest.|Dùng khoảng tin cậy bootstrap khi được yêu cầu; ý nghĩa thống kê của các đường thành phần riêng lẻ không phải kiểm định trung gian.
Johnson-Neyman regions require a continuous observed moderator or a latent moderator represented on its factor-score scale.|Johnson-Neyman 영역에는 연속형 관측 조절변수 또는 요인점수 척도로 표현된 잠재 조절변수가 필요합니다.|Johnson-Neyman領域には連続観測調整変数、または因子得点尺度で表した潜在調整変数が必要です。|Johnson-Neyman区域要求连续观测调节变量，或以因子得分尺度表示的潜在调节变量。|Las regiones Johnson-Neyman requieren un moderador observado continuo o un moderador latente representado en su escala de puntuaciones factoriales.|Les régions Johnson-Neyman nécessitent un modérateur observé continu ou un modérateur latent représenté sur son échelle de scores factoriels.|Johnson-Neyman-Bereiche erfordern einen kontinuierlichen beobachteten Moderator oder einen latenten Moderator auf seiner Faktorwertskala.|Vùng Johnson-Neyman yêu cầu biến điều tiết quan sát liên tục hoặc biến điều tiết tiềm ẩn biểu diễn trên thang điểm nhân tố.
Inference uses the fitted product-indicator parameterization and the observed moderator range.|추론에는 적합된 곱지표 모수화와 관측된 조절변수 범위를 사용합니다.|推論には適合した積指標のパラメータ化と観測された調整変数の範囲を用います。|推断使用拟合的乘积指标参数化及观测到的调节变量范围。|La inferencia usa la parametrización ajustada de indicadores producto y el rango observado del moderador.|L’inférence utilise la paramétrisation ajustée des indicateurs produits et l’étendue observée du modérateur.|Die Inferenz verwendet die angepasste Produktindikator-Parametrisierung und den beobachteten Moderatorbereich.|Suy luận dùng tham số hóa chỉ báo tích đã khớp và phạm vi quan sát của biến điều tiết.
PLS path coefficients|PLS 경로계수|PLSパス係数|PLS路径系数|Coeficientes de ruta PLS|Coefficients de chemin PLS|PLS-Pfadkoeffizienten|Hệ số đường dẫn PLS
Bootstrap indirect and total effects|부트스트랩 간접효과와 총효과|ブートストラップ間接効果と総効果|自助法间接效应和总效应|Efectos indirectos y totales bootstrap|Effets indirects et totaux bootstrap|Bootstrap-Schätzung indirekter und Gesamteffekte|Tác động gián tiếp và tổng tác động bootstrap
seminr two-stage interaction|seminr 2단계 상호작용|seminr二段階交互作用|seminr两阶段交互作用|Interacción en dos etapas de seminr|Interaction en deux étapes de seminr|Zweistufige Interaktion mit seminr|Tương tác hai giai đoạn seminr
seminr product-indicator interaction|seminr 곱지표 상호작용|seminr積指標交互作用|seminr乘积指标交互作用|Interacción de indicadores producto de seminr|Interaction par indicateurs produits de seminr|Produktindikator-Interaktion mit seminr|Tương tác chỉ báo tích seminr
seminr orthogonalized interaction|seminr 직교화 상호작용|seminr直交化交互作用|seminr正交化交互作用|Interacción ortogonalizada de seminr|Interaction orthogonalisée de seminr|Orthogonalisierte Interaktion mit seminr|Tương tác trực giao hóa seminr
PLS conditional path components; moderated-mediation inference is compiled separately|PLS 조건부 경로 구성요소; 조절된 매개효과 추론은 별도로 구성|PLS条件付きパス成分；調整された媒介効果の推論は別途構成|PLS条件路径分量；有调节的中介效应推断另行构建|Componentes condicionales de ruta PLS; la inferencia de mediación moderada se construye por separado|Composantes conditionnelles de chemin PLS ; l’inférence de médiation modérée est construite séparément|Bedingte PLS-Pfadkomponenten; Inferenz zur moderierten Mediation wird separat erstellt|Thành phần đường dẫn PLS có điều kiện; suy luận trung gian có điều tiết được xây dựng riêng
Requires PLS bootstrap inference; no covariance-model global fit claim.|PLS 부트스트랩 추론이 필요하며, 공분산 모형의 전역 적합도를 주장하지 않습니다.|PLSブートストラップ推論が必要です。共分散モデルの全体適合度は主張しません。|需要PLS自助法推断；不宣称协方差模型的整体拟合。|Requiere inferencia bootstrap PLS; no permite afirmar ajuste global de un modelo de covarianzas.|Nécessite une inférence bootstrap PLS ; ne permet pas d’affirmer l’ajustement global d’un modèle de covariance.|Erfordert PLS-Bootstrap-Inferenz; keine Aussage zur globalen Anpassung eines Kovarianzmodells.|Cần suy luận bootstrap PLS; không khẳng định độ phù hợp tổng thể của mô hình hiệp phương sai.
Simple slopes are reported on the standardized construct-score scale.|단순기울기는 표준화된 구성개념 점수 척도로 보고합니다.|単純傾斜は標準化した構成概念得点尺度で報告します。|简单斜率以标准化构念得分尺度报告。|Las pendientes simples se informan en la escala estandarizada de puntuaciones del constructo.|Les pentes simples sont rapportées sur l’échelle standardisée des scores de construit.|Einfache Steigungen werden auf der standardisierten Konstruktwertskala berichtet.|Độ dốc đơn được báo cáo trên thang điểm cấu trúc chuẩn hóa.
The interaction is re-estimated in every accepted whole-draw bootstrap sample; PLSpredict remains unavailable for interaction models.|허용된 전체 통계량 부트스트랩 표본마다 상호작용을 재추정합니다. 상호작용 모형에서는 PLSpredict를 사용할 수 없습니다.|採用された各ブートストラップ標本で交互作用を再推定します。交互作用モデルではPLSpredictを利用できません。|在每个通过整组统计量要求的自助样本中重新估计交互作用；交互模型仍不可使用PLSpredict。|La interacción se reestima en cada muestra bootstrap aceptada con el conjunto completo de estadísticas; PLSpredict no está disponible para modelos con interacciones.|L’interaction est réestimée dans chaque échantillon bootstrap accepté pour l’ensemble des statistiques ; PLSpredict reste indisponible pour les modèles d’interaction.|Die Interaktion wird in jeder vollständig akzeptierten Bootstrap-Stichprobe neu geschätzt; PLSpredict bleibt für Interaktionsmodelle nicht verfügbar.|Tương tác được ước lượng lại trong mỗi mẫu bootstrap được chấp nhận cho toàn bộ thống kê; PLSpredict chưa khả dụng cho mô hình tương tác.
The interaction is an uncorrected composite; PLSc consistency correction remains selective for declared common-factor constructs.|상호작용은 보정하지 않은 합성변수이며, PLSc 일치성 보정은 공통요인으로 선언한 구성개념에만 선택적으로 적용됩니다.|交互作用は未補正の合成変数です。PLSc一致性補正は共通因子として宣言した構成概念に選択的に適用します。|交互作用是未经校正的复合变量；PLSc一致性校正仍仅选择性用于声明为共同因子的构念。|La interacción es un compuesto sin corregir; la corrección de consistencia PLSc sigue siendo selectiva para los constructos declarados como factores comunes.|L’interaction est un composite non corrigé ; la correction de cohérence PLSc reste sélective pour les construits déclarés comme facteurs communs.|Die Interaktion ist ein unkorrigiertes Komposit; die PLSc-Konsistenzkorrektur gilt selektiv für als gemeinsame Faktoren deklarierte Konstrukte.|Tương tác là biến tổng hợp chưa hiệu chỉnh; hiệu chỉnh tính nhất quán PLSc chỉ áp dụng có chọn lọc cho cấu trúc được khai báo là nhân tố chung.'''
data_rows=[r.split('|') for r in rows.splitlines()]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],2):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in data_rows:
  assert len(row)==8
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
