import json,re
from pathlib import Path
rows='''Detailed proportional-hazards diagnostics|比例ハザードの詳細診断|比例风险详细诊断|Diagnósticos detallados de riesgos proporcionales|Diagnostics détaillés des risques proportionnels|Detaillierte Diagnostik proportionaler Hazards|Chẩn đoán chi tiết giả định nguy cơ tỷ lệ
Review status|検討状況|审查状态|Estado de revisión|Statut de l’examen|Prüfstatus|Trạng thái xem xét
Review possible time-varying effect|時間依存効果の可能性を検討|审查可能的时变效应|Revisar posible efecto variable en el tiempo|Examiner un éventuel effet variant dans le temps|Möglichen zeitabhängigen Effekt prüfen|Xem xét khả năng hiệu ứng thay đổi theo thời gian
No strong signal in this test|この検定で強いシグナルなし|此检验中无明显信号|Sin señal clara en esta prueba|Aucun signal marqué dans ce test|Kein deutliches Signal in diesem Test|Không có dấu hiệu rõ rệt trong kiểm định này
Covariate-specific Schoenfeld-residual tests are supplementary diagnostics for possible time-varying effects. The main table reports only the overall likelihood-ratio test and the PH GLOBAL test.|共変量ごとのSchoenfeld残差検定は、時間依存効果の可能性に関する補助診断です。主表にはモデル全体の尤度比検定とPH GLOBAL検定のみを示します。|各协变量的Schoenfeld残差检验是诊断可能时变效应的辅助工具。主表仅报告整体似然比检验和PH GLOBAL检验。|Las pruebas de residuos de Schoenfeld por covariable son diagnósticos complementarios de posibles efectos variables en el tiempo. La tabla principal solo presenta la prueba global de razón de verosimilitudes y la prueba PH GLOBAL.|Les tests des résidus de Schoenfeld par covariable sont des diagnostics complémentaires d’éventuels effets variant dans le temps. Le tableau principal ne présente que le test global du rapport de vraisemblance et le test PH GLOBAL.|Kovariatenspezifische Schoenfeld-Residualtests ergänzen die Diagnostik möglicher zeitabhängiger Effekte. Die Haupttabelle enthält nur den globalen Likelihood-Ratio-Test und den PH-GLOBAL-Test.|Kiểm định phần dư Schoenfeld theo từng hiệp biến là chẩn đoán bổ sung cho khả năng hiệu ứng thay đổi theo thời gian. Bảng chính chỉ báo cáo kiểm định tỷ số hợp lý tổng thể và kiểm định PH GLOBAL.
Smoothed scaled Schoenfeld-residual plots support assessment of time-varying coefficients. Formal p-values and plots should be interpreted together; neither is an automatic pass/fail rule.|平滑化した尺度化Schoenfeld残差図は時間依存係数の評価を補助します。正式なp値と図を併せて解釈し、どちらも自動的な合否基準とはしません。|平滑后的缩放Schoenfeld残差图辅助评估时变系数。正式p值和图形应结合解释；两者都不是自动判定通过或不通过的规则。|Los gráficos suavizados de residuos de Schoenfeld escalados ayudan a evaluar coeficientes variables en el tiempo. Los valores p y los gráficos deben interpretarse conjuntamente; ninguno es una regla automática de aprobación o rechazo.|Les graphiques lissés des résidus de Schoenfeld mis à l’échelle aident à évaluer les coefficients variant dans le temps. Les valeurs p et les graphiques doivent être interprétés ensemble ; aucun ne constitue une règle automatique de validation ou de rejet.|Geglättete skalierte Schoenfeld-Residuenplots unterstützen die Beurteilung zeitabhängiger Koeffizienten. Formale p-Werte und Diagramme sind gemeinsam zu interpretieren; keines ist eine automatische Bestehensregel.|Đồ thị làm trơn phần dư Schoenfeld đã chuẩn hóa hỗ trợ đánh giá hệ số thay đổi theo thời gian. Cần diễn giải giá trị p và đồ thị cùng nhau; không yếu tố nào là quy tắc tự động đạt hay không đạt.
The loess smooth of Martingale residuals against each continuous covariate is a functional-form screening plot. Systematic curvature suggests considering a prespecified transformation or spline and comparing substantive conclusions.|各連続共変量に対するマルチンゲール残差のloess平滑線は関数形のスクリーニング図です。系統的な曲率があれば、事前指定の変換やスプラインを検討し、実質的な結論を比較します。|针对各连续协变量的鞅残差loess平滑曲线用于筛查函数形式。系统性弯曲提示应考虑预先指定的变换或样条，并比较实质性结论。|El suavizado loess de los residuos de martingala frente a cada covariable continua permite revisar la forma funcional. Una curvatura sistemática sugiere considerar una transformación o spline preespecificado y comparar las conclusiones sustantivas.|Le lissage loess des résidus de martingale selon chaque covariable continue sert à examiner la forme fonctionnelle. Une courbure systématique invite à envisager une transformation ou une spline préspécifiée et à comparer les conclusions de fond.|Die Loess-Glättung der Martingalresiduen gegen jede stetige Kovariate dient zur Prüfung der Funktionsform. Systematische Krümmung legt nahe, eine vorab festgelegte Transformation oder einen Spline zu erwägen und die inhaltlichen Schlussfolgerungen zu vergleichen.|Đường làm trơn loess của phần dư martingale theo từng hiệp biến liên tục là đồ thị sàng lọc dạng hàm. Độ cong có hệ thống gợi ý xem xét phép biến đổi hoặc spline được chỉ định trước và so sánh các kết luận thực chất.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
