import json
from pathlib import Path
keys=['gamma_rows','correlation','iterations','adjusted_correlation','not_positive','singular']
rows={
'en':['Gamma GEE requires strictly positive outcomes; %s analyzed rows contain zero or negative values. Review the outcome and family; values were not replaced.','GEE %s working correlation is singular or numerically non-positive-definite (minimum eigenvalue %s); estimates were not accepted.','Adjusted GEE did not converge after %s iterations (maximum scaled coefficient step %s; required < 1e-10). Estimates were not accepted. Review the model and working correlation.','Adjusted GEE working correlation is %s (minimum eigenvalue %s). Estimates were not accepted. Review within-subject variation and the working correlation structure.','not positive definite','singular or numerically near-singular'],
'ko':['Gamma GEE의 결과값은 모두 양수여야 합니다. 분석 행 %s개에 0 또는 음수가 있습니다. 결과변수와 분포 계열을 확인하세요. 값은 대체하지 않았습니다.','GEE %s 작업상관행렬이 특이행렬이거나 수치적으로 양의 정부호가 아닙니다(최소 고유값 %s). 추정값을 채택하지 않았습니다.','보정 GEE가 %s회 반복 후에도 수렴하지 않았습니다(최대 척도화 계수 변화 %s; 요구값 < 1e-10). 추정값을 채택하지 않았습니다. 모형과 작업상관 구조를 확인하세요.','보정 GEE 작업상관행렬의 상태: %s(최소 고유값 %s). 추정값을 채택하지 않았습니다. 대상자 내 변동과 작업상관 구조를 확인하세요.','양의 정부호 아님','특이행렬 또는 수치적으로 거의 특이행렬'],
'ja':['Gamma GEEではアウトカムがすべて正である必要があります。分析対象の%s行に0または負の値があります。アウトカムと分布族を確認してください。値は置換していません。','GEEの%s作業相関行列は特異または数値的に正定値ではありません（最小固有値%s）。推定値を採用しませんでした。','補正GEEは%s回の反復後も収束しませんでした（尺度調整後の係数変化の最大値%s、必要条件 < 1e-10）。推定値を採用しませんでした。モデルと作業相関を確認してください。','補正GEEの作業相関行列の状態：%s（最小固有値%s）。推定値を採用しませんでした。対象者内の変動と作業相関構造を確認してください。','正定値ではない','特異または数値的にほぼ特異'],
'zh':['Gamma GEE 要求结局值严格为正；%s 个分析行含有零或负值。请检查结局和分布族；未替换这些值。','GEE %s 工作相关矩阵奇异或数值上非正定（最小特征值 %s）；未接受估计值。','校正 GEE 在 %s 次迭代后仍未收敛（最大尺度化系数步长 %s；要求 < 1e-10）。未接受估计值。请检查模型和工作相关结构。','校正 GEE 工作相关矩阵状态：%s（最小特征值 %s）。未接受估计值。请检查受试者内变异和工作相关结构。','非正定','奇异或数值上近似奇异'],
'es':['Gamma GEE requiere resultados estrictamente positivos; %s filas analizadas contienen ceros o valores negativos. Revise el resultado y la familia; no se sustituyeron los valores.','La correlación de trabajo GEE %s es singular o numéricamente no definida positiva (valor propio mínimo %s); no se aceptaron las estimaciones.','GEE ajustado no convergió tras %s iteraciones (paso máximo del coeficiente escalado %s; requerido < 1e-10). No se aceptaron las estimaciones. Revise el modelo y la correlación de trabajo.','Estado de la correlación de trabajo GEE ajustada: %s (valor propio mínimo %s). No se aceptaron las estimaciones. Revise la variación intrasujeto y la estructura de correlación de trabajo.','no definida positiva','singular o numéricamente casi singular'],
'fr':['Gamma GEE nécessite des résultats strictement positifs ; %s lignes analysées contiennent des valeurs nulles ou négatives. Vérifiez le résultat et la famille ; les valeurs n’ont pas été remplacées.','La corrélation de travail GEE %s est singulière ou numériquement non définie positive (valeur propre minimale %s) ; les estimations ont été rejetées.','GEE ajusté n’a pas convergé après %s itérations (pas maximal du coefficient mis à l’échelle %s ; requis < 1e-10). Les estimations ont été rejetées. Vérifiez le modèle et la corrélation de travail.','État de la corrélation de travail GEE ajustée : %s (valeur propre minimale %s). Les estimations ont été rejetées. Vérifiez la variation intra-sujet et la structure de corrélation de travail.','non définie positive','singulière ou numériquement quasi singulière'],
'de':['Gamma GEE erfordert strikt positive Zielwerte; %s analysierte Zeilen enthalten null oder negative Werte. Prüfen Sie Zielvariable und Verteilungsfamilie; Werte wurden nicht ersetzt.','Die GEE-Arbeitskorrelation %s ist singulär oder numerisch nicht positiv definit (kleinster Eigenwert %s); die Schätzwerte wurden verworfen.','Das angepasste GEE konvergierte nach %s Iterationen nicht (maximaler skalierter Koeffizientenschritt %s; erforderlich < 1e-10). Die Schätzwerte wurden verworfen. Prüfen Sie Modell und Arbeitskorrelation.','Zustand der angepassten GEE-Arbeitskorrelation: %s (kleinster Eigenwert %s). Die Schätzwerte wurden verworfen. Prüfen Sie die Variation innerhalb der Personen und die Arbeitskorrelationsstruktur.','nicht positiv definit','singulär oder numerisch nahezu singulär'],
'vi':['Gamma GEE yêu cầu kết quả dương hoàn toàn; %s hàng phân tích chứa giá trị bằng không hoặc âm. Kiểm tra kết quả và họ phân phối; các giá trị không được thay thế.','Tương quan làm việc GEE %s suy biến hoặc không xác định dương về mặt số học (trị riêng nhỏ nhất %s); các ước lượng không được chấp nhận.','GEE hiệu chỉnh không hội tụ sau %s lần lặp (bước hệ số đã chuẩn hóa lớn nhất %s; yêu cầu < 1e-10). Các ước lượng không được chấp nhận. Kiểm tra mô hình và tương quan làm việc.','Trạng thái tương quan làm việc GEE hiệu chỉnh: %s (trị riêng nhỏ nhất %s). Các ước lượng không được chấp nhận. Kiểm tra biến thiên trong đối tượng và cấu trúc tương quan làm việc.','không xác định dương','suy biến hoặc gần suy biến về mặt số học']}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.dynamic_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
