import json,re
from pathlib import Path
rows='''Advanced Options|詳細オプション|高级选项|Opciones avanzadas|Options avancées|Erweiterte Optionen|Tùy chọn nâng cao
Reporting, sensitivity, and supplementary-model settings. These are not required to fit the base model.|報告・感度分析・補助モデルの設定です。基本モデルの推定には必須ではありません。|报告、敏感性及补充模型设置。拟合基础模型不要求设置这些项目。|Configuración de informes, sensibilidad y modelos complementarios. No es necesaria para ajustar el modelo base.|Paramètres de rapport, de sensibilité et de modèles complémentaires. Ils ne sont pas requis pour ajuster le modèle de base.|Einstellungen für Berichte, Sensitivität und ergänzende Modelle. Für die Schätzung des Basismodells nicht erforderlich.|Thiết lập báo cáo, độ nhạy và mô hình bổ sung. Không bắt buộc để ước lượng mô hình cơ sở.
A-priori sample-size/power basis|事前の標本数・検出力の根拠|事先样本量/检验效能依据|Base previa del tamaño muestral/potencia|Justification préalable de la taille d’échantillon/puissance|A-priori-Begründung für Stichprobengröße/Teststärke|Cơ sở cỡ mẫu/lực kiểm định xác định trước
RMSEA fit-test power|RMSEA適合度検定の検出力|RMSEA拟合检验效能|Potencia de la prueba de ajuste RMSEA|Puissance du test d’ajustement RMSEA|Teststärke des RMSEA-Anpassungstests|Lực kiểm định độ phù hợp RMSEA
Model-specific Monte Carlo|モデル別Monte Carlo|模型特定Monte Carlo|Monte Carlo específico del modelo|Monte Carlo propre au modèle|Modellspezifische Monte-Carlo-Analyse|Monte Carlo theo mô hình
Target effect/precision|目標効果・精度|目标效应/精度|Efecto/precisión objetivo|Effet/précision cible|Zieleffekt/Präzision|Hiệu ứng/độ chính xác mục tiêu
Prior evidence|先行研究の根拠|既有研究依据|Evidencia previa|Données probantes antérieures|Vorliegende Evidenz|Bằng chứng trước đó
Other documented basis|その他の文書化された根拠|其他书面依据|Otra base documentada|Autre justification documentée|Andere dokumentierte Grundlage|Cơ sở khác đã ghi nhận
Power-basis details|検出力の根拠の詳細|检验效能依据详情|Detalles de la base de potencia|Détails de la justification de puissance|Details zur Teststärkebegründung|Chi tiết cơ sở lực kiểm định
Record assumed effects/parameters, target power, alpha, attrition/missingness allowance, and software or source.|仮定した効果・パラメータ、目標検出力、α、脱落・欠測の想定、使用ソフトまたは文献を記録してください。|记录假定效应/参数、目标效能、alpha、脱落/缺失预留以及软件或文献来源。|Registre los efectos/parámetros supuestos, la potencia objetivo, alfa, el margen por pérdidas/datos faltantes y el software o fuente.|Consignez les effets/paramètres supposés, la puissance cible, alpha, la marge pour attrition/données manquantes et le logiciel ou la source.|Angenommene Effekte/Parameter, Zielteststärke, Alpha, Zuschlag für Ausfälle/fehlende Daten sowie Software oder Quelle dokumentieren.|Ghi hiệu ứng/tham số giả định, lực kiểm định mục tiêu, alpha, dự phòng bỏ cuộc/thiếu dữ liệu và phần mềm hoặc nguồn.
N-to-parameter ratios and the PLS 10-times rule are not a-priori power evidence.|Nとパラメータ数の比やPLSの10倍ルールは、事前の検出力の根拠にはなりません。|样本量与参数数之比及PLS十倍规则不是事先检验效能依据。|La razón N/parámetros y la regla de diez veces de PLS no justifican la potencia a priori.|Le rapport N/paramètres et la règle des dix fois de PLS ne justifient pas la puissance a priori.|N-Parameter-Verhältnisse und die PLS-Zehnfachregel sind keine A-priori-Teststärkebelege.|Tỷ lệ N/số tham số và quy tắc 10 lần của PLS không phải bằng chứng lực kiểm định xác định trước.
ML likelihood convention|ML尤度の規約|ML似然约定|Convención de verosimilitud ML|Convention de vraisemblance ML|ML-Likelihood-Konvention|Quy ước hợp lý ML
Normal ML (lavaan default; N multiplier)|Normal ML（lavaan既定、N倍）|Normal ML（lavaan默认；N倍数）|ML normal (predeterminado en lavaan; multiplicador N)|ML normal (défaut lavaan ; multiplicateur N)|Normal-ML (lavaan-Standard; Multiplikator N)|ML chuẩn (mặc định lavaan; hệ số N)
Wishart ML (AMOS/LISREL/EQS compatible; N-1 multiplier)|Wishart ML（AMOS/LISREL/EQS互換、N−1倍）|Wishart ML（兼容AMOS/LISREL/EQS；N-1倍数）|ML Wishart (compatible con AMOS/LISREL/EQS; multiplicador N−1)|ML Wishart (compatible AMOS/LISREL/EQS ; multiplicateur N−1)|Wishart-ML (AMOS/LISREL/EQS-kompatibel; Multiplikator N−1)|ML Wishart (tương thích AMOS/LISREL/EQS; hệ số N−1)
Normal ML is the lavaan default. Select Wishart ML only for a matched numerical comparison with AMOS or similar software, while also matching the model, data, and missing-data handling. The full model is refitted under that convention; chi-square is not adjusted post hoc.|lavaanの既定はNormal MLです。AMOSなどと数値を比較する場合のみ、モデル・データ・欠測処理も揃えてWishart MLを選択してください。モデル全体をその規約で再推定し、カイ二乗だけを事後補正するものではありません。|lavaan默认采用Normal ML。仅在与AMOS等软件进行匹配数值比较时选择Wishart ML，并保持模型、数据和缺失处理一致。整个模型按该约定重新拟合，而非事后仅校正卡方值。|Normal ML es el valor predeterminado de lavaan. Use Wishart ML solo al comparar resultados numéricos con AMOS o similar, manteniendo iguales modelo, datos y tratamiento de faltantes. Se reajusta todo el modelo; no se corrige solo chi-cuadrado a posteriori.|Normal ML est le défaut de lavaan. Choisissez Wishart ML uniquement pour comparer les valeurs avec AMOS ou équivalent, à modèle, données et traitement des valeurs manquantes identiques. Le modèle entier est réajusté ; le khi-deux n’est pas corrigé a posteriori.|Normal-ML ist der lavaan-Standard. Wishart-ML nur für numerische Vergleiche mit AMOS oder ähnlicher Software bei gleichem Modell, gleichen Daten und gleicher Behandlung fehlender Werte wählen. Das gesamte Modell wird neu geschätzt; Chi-Quadrat wird nicht nachträglich korrigiert.|Normal ML là mặc định của lavaan. Chỉ chọn Wishart ML khi đối chiếu số liệu với AMOS hoặc phần mềm tương tự, với cùng mô hình, dữ liệu và cách xử lý thiếu. Toàn bộ mô hình được ước lượng lại; không chỉ hiệu chỉnh chi-bình phương sau đó.
Missing-data sensitivity assessment|欠測データの感度評価|缺失数据敏感性评估|Evaluación de sensibilidad a datos faltantes|Évaluation de sensibilité aux données manquantes|Sensitivitätsprüfung für fehlende Daten|Đánh giá độ nhạy với dữ liệu thiếu
Not assessed|未評価|未评估|No evaluado|Non évalué|Nicht geprüft|Chưa đánh giá
Complete-case comparison|完全ケースとの比較|完整案例比较|Comparación de casos completos|Comparaison des cas complets|Vergleich vollständiger Fälle|So sánh trường hợp đầy đủ
Multiple-imputation comparison|多重代入との比較|多重插补比较|Comparación con imputación múltiple|Comparaison avec imputation multiple|Vergleich mit multipler Imputation|So sánh với đa nội suy
External sensitivity analysis|外部での感度分析|外部敏感性分析|Análisis de sensibilidad externo|Analyse de sensibilité externe|Externe Sensitivitätsanalyse|Phân tích độ nhạy bên ngoài
Other documented assessment|その他の文書化された評価|其他书面评估|Otra evaluación documentada|Autre évaluation documentée|Andere dokumentierte Prüfung|Đánh giá khác đã ghi nhận
Sensitivity assumptions, results, and conclusion|感度分析の仮定・結果・結論|敏感性假设、结果及结论|Supuestos, resultados y conclusión de sensibilidad|Hypothèses, résultats et conclusion de sensibilité|Sensitivitätsannahmen, Ergebnisse und Schlussfolgerung|Giả định, kết quả và kết luận độ nhạy
Record the comparison method, MNAR-departure assumptions, changes in key parameters, and robustness of conclusions.|比較方法、MNARからの逸脱に関する仮定、主要パラメータの変化、結論の頑健性を記録してください。|记录比较方法、MNAR偏离假设、关键参数变化及结论稳健性。|Registre el método de comparación, los supuestos de desviación MNAR, los cambios en parámetros clave y la robustez de las conclusiones.|Consignez la méthode de comparaison, les hypothèses d’écart MNAR, les changements des paramètres clés et la robustesse des conclusions.|Vergleichsmethode, MNAR-Abweichungsannahmen, Änderungen wichtiger Parameter und Robustheit der Schlussfolgerungen dokumentieren.|Ghi phương pháp so sánh, giả định sai lệch MNAR, thay đổi tham số chính và tính vững của kết luận.
Latent scale|潜在変数の尺度|潜变量尺度|Escala latente|Échelle latente|Skalierung latenter Variablen|Thang đo biến tiềm ẩn
Marker loading = 1|基準指標の負荷量 = 1|标记指标载荷 = 1|Carga del indicador marcador = 1|Saturation de l’indicateur marqueur = 1|Markerladung = 1|Tải chỉ báo mốc = 1
Latent variance = 1|潜在変数の分散 = 1|潜变量方差 = 1|Varianza latente = 1|Variance latente = 1|Latente Varianz = 1|Phương sai biến tiềm ẩn = 1
RMSEA confidence level|RMSEA信頼水準|RMSEA置信水平|Nivel de confianza RMSEA|Niveau de confiance RMSEA|RMSEA-Konfidenzniveau|Mức tin cậy RMSEA
Latent-moderation product-indicator method|潜在調整効果の積指標法|潜调节乘积指标方法|Método de indicadores producto para moderación latente|Méthode des indicateurs produits pour modération latente|Produktindikator-Methode für latente Moderation|Phương pháp chỉ báo tích cho điều tiết tiềm ẩn
PLS latent-interaction method|PLS潜在交互作用の方法|PLS潜交互作用方法|Método de interacción latente PLS|Méthode d’interaction latente PLS|Methode für latente PLS-Interaktion|Phương pháp tương tác tiềm ẩn PLS
Two-stage (default)|2段階法（既定）|两阶段法（默认）|Dos etapas (predeterminado)|Deux étapes (défaut)|Zweistufig (Standard)|Hai giai đoạn (mặc định)
Product indicator|積指標法|乘积指标法|Indicador producto|Indicateur produit|Produktindikator|Chỉ báo tích
Orthogonalizing|直交化法|正交化法|Ortogonalización|Orthogonalisation|Orthogonalisierung|Trực giao hóa
Used only when a latent moderator is linked to a structural path. The two-stage method is the default; every bootstrap draw re-estimates both the measurement model and interaction.|潜在調整変数を構造パスに接続した場合のみ適用します。既定は2段階法です。各ブートストラップ標本で測定モデルと交互作用をともに再推定します。|仅在潜调节变量连接到结构路径时使用。默认两阶段法；每次自助抽样均重新估计测量模型和交互作用。|Se usa solo al vincular un moderador latente a una ruta estructural. El método predeterminado es de dos etapas; cada muestra bootstrap reestima el modelo de medida y la interacción.|Utilisé uniquement lorsqu’un modérateur latent est lié à un chemin structurel. La méthode par défaut est à deux étapes ; chaque tirage bootstrap réestime le modèle de mesure et l’interaction.|Nur bei einem mit einem Strukturpfad verknüpften latenten Moderator. Standard ist die zweistufige Methode; jede Bootstrap-Stichprobe schätzt Messmodell und Interaktion neu.|Chỉ dùng khi biến điều tiết tiềm ẩn được nối với đường cấu trúc. Mặc định dùng hai giai đoạn; mỗi mẫu bootstrap ước lượng lại cả mô hình đo lường và tương tác.
Delta/pattern-mixture|デルタ／パターン混合|Delta/模式混合|Delta/mezcla de patrones|Delta/mélange de profils|Delta/Pattern-Mixture|Delta/hỗn hợp mẫu hình
All-pairs + double-mean-centering|全ペア＋二重平均中心化|所有配对＋双重均值中心化|Todos los pares + doble centrado en la media|Toutes les paires + double centrage sur la moyenne|Alle Paare + doppelte Mittelwertzentrierung|Mọi cặp + định tâm trung bình kép
Matched-pair + double-mean-centering|対応ペア＋二重平均中心化|匹配配对＋双重均值中心化|Pares emparejados + doble centrado en la media|Paires appariées + double centrage sur la moyenne|Zugeordnete Paare + doppelte Mittelwertzentrierung|Cặp ghép + định tâm trung bình kép
All-pairs mean-centering (legacy)|全ペア平均中心化（従来）|所有配对均值中心化（旧版）|Centrado de todos los pares (heredado)|Centrage de toutes les paires (ancien)|Mittelwertzentrierung aller Paare (bisherig)|Định tâm trung bình mọi cặp (cũ)'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi']):
 p=Path('i18n')/(lang+'.json');d=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  row=line.split('|');assert len(row)==7
  d['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i+1]
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
