import json
from pathlib import Path
keys='rho studies lower upper tau omitted change estimator side observed missing original adjusted adjusted_lower adjusted_upper left right id study year outcome predictor weight dependency_title leave_title trim_title study_title'.split()
rows={
'en':['Assumed rho','Studies','CI lower','CI upper','Tau squared','Omitted study','Change','Estimator','Side','Observed studies','Estimated missing','Observed estimate','Adjusted estimate','Adjusted CI lower','Adjusted CI upper','left','right','ID','Study','Year','Outcome','Predictor','Weight (%)','Within-study correlation sensitivity','Leave-one-study-out sensitivity','Trim-and-fill sensitivity analysis','Study effects'],
'ko':['가정한 연구 내 ρ','논문 수','신뢰구간 하한','신뢰구간 상한','τ²','제외 논문','통합효과 변화','추정법','추정 누락 방향','관측 논문 수','추정 누락 논문 수','관측 통합효과','보정 통합효과','보정 신뢰구간 하한','보정 신뢰구간 상한','왼쪽','오른쪽','연구 ID','연구명','출판연도','종속변수','독립변수','가중치 (%)','연구 내 상관 가정 민감도','논문 단위 순차 제외 민감도','Trim-and-fill 민감도 분석','연구별 효과크기'],
'ja':['仮定した研究内ρ','研究数','信頼区間下限','信頼区間上限','τ²','除外研究','統合効果の変化','推定法','欠落推定方向','観測研究数','推定欠落研究数','観測統合効果','補正統合効果','補正信頼区間下限','補正信頼区間上限','左','右','研究ID','研究名','出版年','従属変数','独立変数','重み (%)','研究内相関の感度分析','研究の逐次除外による感度分析','Trim-and-fill感度分析','研究別効果量'],
'zh':['假定的研究内ρ','研究数','置信区间下限','置信区间上限','τ²','排除的研究','合并效应变化','估计方法','估计缺失方向','观测研究数','估计缺失研究数','观测合并效应','校正合并效应','校正置信区间下限','校正置信区间上限','左侧','右侧','研究ID','研究名称','发表年份','因变量','自变量','权重 (%)','研究内相关敏感性分析','逐一排除研究敏感性分析','剪补法敏感性分析','各研究效应量'],
'es':['ρ intrastudio supuesto','Estudios','Límite inferior del IC','Límite superior del IC','τ²','Estudio excluido','Cambio del efecto combinado','Estimador','Lado de los estudios faltantes','Estudios observados','Estudios faltantes estimados','Efecto combinado observado','Efecto combinado ajustado','Límite inferior del IC ajustado','Límite superior del IC ajustado','izquierda','derecha','ID del estudio','Estudio','Año de publicación','Variable dependiente','Variable independiente','Peso (%)','Sensibilidad a la correlación intrastudio','Sensibilidad al excluir un estudio cada vez','Análisis de sensibilidad de recorte y relleno','Efectos por estudio'],
'fr':['ρ intra-étude supposé','Études','Borne inférieure de l’IC','Borne supérieure de l’IC','τ²','Étude exclue','Variation de l’effet combiné','Estimateur','Côté des études manquantes','Études observées','Études manquantes estimées','Effet combiné observé','Effet combiné ajusté','Borne inférieure de l’IC ajusté','Borne supérieure de l’IC ajusté','gauche','droite','ID de l’étude','Étude','Année de publication','Variable dépendante','Variable indépendante','Poids (%)','Sensibilité à la corrélation intra-étude','Sensibilité au retrait successif de chaque étude','Analyse de sensibilité par trim-and-fill','Effets par étude'],
'de':['Angenommenes studieninternes ρ','Studien','Untere KI-Grenze','Obere KI-Grenze','τ²','Ausgeschlossene Studie','Änderung des gepoolten Effekts','Schätzer','Seite fehlender Studien','Beobachtete Studien','Geschätzte fehlende Studien','Beobachteter gepoolter Effekt','Korrigierter gepoolter Effekt','Untere korrigierte KI-Grenze','Obere korrigierte KI-Grenze','links','rechts','Studien-ID','Studie','Publikationsjahr','Abhängige Variable','Unabhängige Variable','Gewicht (%)','Sensitivität gegenüber studieninterner Korrelation','Sensitivität beim sukzessiven Ausschluss einzelner Studien','Trim-and-Fill-Sensitivitätsanalyse','Studieneffekte'],
'vi':['ρ trong nghiên cứu giả định','Số nghiên cứu','Cận dưới KTC','Cận trên KTC','τ²','Nghiên cứu bị loại','Thay đổi hiệu ứng gộp','Phương pháp ước lượng','Phía thiếu ước tính','Số nghiên cứu quan sát','Số nghiên cứu thiếu ước tính','Hiệu ứng gộp quan sát','Hiệu ứng gộp hiệu chỉnh','Cận dưới KTC hiệu chỉnh','Cận trên KTC hiệu chỉnh','trái','phải','ID nghiên cứu','Tên nghiên cứu','Năm công bố','Biến phụ thuộc','Biến độc lập','Trọng số (%)','Độ nhạy với tương quan trong nghiên cứu','Độ nhạy khi lần lượt loại từng nghiên cứu','Phân tích độ nhạy bằng phương pháp trim-and-fill','Hiệu ứng từng nghiên cứu']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'meta.sensitivity.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
