import json,re
from pathlib import Path
rows='''Estimating Bollen-Stine global-fit p value	Bollen-Stine 전반적 적합도 p값 추정 중	Bollen–Stine全体適合度p値を推定中	正在估计Bollen–Stine整体拟合p值	Estimando p de ajuste global Bollen–Stine	Estimation du p d’ajustement global Bollen–Stine	Bollen–Stine-p für globale Anpassung wird geschätzt	Đang ước lượng p độ phù hợp tổng thể Bollen–Stine
%s transformed-data bootstrap replicates	변환 자료 부트스트랩 %s회	変換データのブートストラップ%s回	变换数据自助法重复%s次	%s réplicas bootstrap de datos transformados	%s réplications bootstrap sur données transformées	%s Bootstrap-Wiederholungen mit transformierten Daten	%s lần lặp bootstrap dữ liệu biến đổi
Bollen-Stine bootstrap %s/%s; valid replicates %s	Bollen-Stine 부트스트랩 %s/%s; 유효 반복 %s회	Bollen–Stineブートストラップ%s/%s；有効反復%s回	Bollen–Stine自助法%s/%s；有效重复%s次	Bootstrap Bollen–Stine %s/%s; réplicas válidas %s	Bootstrap Bollen–Stine %s/%s ; réplications valides %s	Bollen–Stine-Bootstrap %s/%s; gültige Wiederholungen %s	Bootstrap Bollen–Stine %s/%s; số lần lặp hợp lệ %s
Preparing bootstrap goodness-of-fit result	부트스트랩 적합도 결과 준비 중	ブートストラップ適合度結果を準備中	正在准备自助法拟合优度结果	Preparando el resultado bootstrap de bondad de ajuste	Préparation du résultat bootstrap d’ajustement	Bootstrap-Anpassungsergebnis wird vorbereitet	Đang chuẩn bị kết quả độ phù hợp bootstrap
Bollen-Stine bootstrap is available only for ML estimation.	Bollen-Stine 부트스트랩은 ML 추정에서만 사용할 수 있습니다.	Bollen–StineブートストラップはML推定でのみ利用できます。	Bollen–Stine自助法仅适用于ML估计。	El bootstrap Bollen–Stine solo está disponible para estimación ML.	Le bootstrap Bollen–Stine est disponible uniquement pour l’estimation ML.	Der Bollen–Stine-Bootstrap ist nur für ML-Schätzung verfügbar.	Bootstrap Bollen–Stine chỉ dùng cho ước lượng ML.
Bollen-Stine bootstrap is not available for ordered indicators.	Bollen-Stine 부트스트랩은 순서형 지표에서 사용할 수 없습니다.	Bollen–Stineブートストラップは順序指標では利用できません。	Bollen–Stine自助法不适用于有序指标。	El bootstrap Bollen–Stine no está disponible para indicadores ordinales.	Le bootstrap Bollen–Stine n’est pas disponible pour les indicateurs ordinaux.	Der Bollen–Stine-Bootstrap ist für ordinale Indikatoren nicht verfügbar.	Bootstrap Bollen–Stine không dùng cho chỉ báo thứ bậc.
Bollen-Stine bootstrap is currently available only for single-group CFA.	Bollen-Stine 부트스트랩은 현재 단일집단 CFA에서만 사용할 수 있습니다.	Bollen–Stineブートストラップは現在、単一群CFAでのみ利用できます。	Bollen–Stine自助法目前仅适用于单组CFA。	El bootstrap Bollen–Stine solo está disponible actualmente para CFA de un grupo.	Le bootstrap Bollen–Stine est actuellement disponible uniquement pour une CFA à un groupe.	Der Bollen–Stine-Bootstrap ist derzeit nur für Ein-Gruppen-CFA verfügbar.	Bootstrap Bollen–Stine hiện chỉ dùng cho CFA một nhóm.
Bollen-Stine bootstrap is not informative for a saturated model with df = 0.	Bollen-Stine 부트스트랩은 df = 0인 포화모형에서 유용한 정보를 제공하지 않습니다.	Bollen–Stineブートストラップはdf = 0の飽和モデルでは有益な情報を提供しません。	Bollen–Stine自助法对df = 0的饱和模型不能提供有用信息。	El bootstrap Bollen–Stine no aporta información para un modelo saturado con gl = 0.	Le bootstrap Bollen–Stine n’est pas informatif pour un modèle saturé avec ddl = 0.	Der Bollen–Stine-Bootstrap ist bei einem saturierten Modell mit df = 0 nicht aussagekräftig.	Bootstrap Bollen–Stine không cung cấp thông tin hữu ích cho mô hình bão hòa có df = 0.
Bollen-Stine bootstrap requires complete analyzed data in this implementation.	현재 구현에서 Bollen-Stine 부트스트랩은 결측이 없는 분석 자료가 필요합니다.	この実装ではBollen–Stineブートストラップに欠測のない分析データが必要です。	此实现中的Bollen–Stine自助法要求分析数据无缺失。	Esta implementación del bootstrap Bollen–Stine requiere datos analizados completos.	Cette implémentation du bootstrap Bollen–Stine exige des données analysées complètes.	Diese Implementierung des Bollen–Stine-Bootstraps erfordert vollständige Analysedaten.	Trong triển khai này, bootstrap Bollen–Stine yêu cầu dữ liệu phân tích đầy đủ.'''
for i,lang in enumerate(['ko','ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==8
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
