import json
from pathlib import Path
keys=['review','structure','structure_note','missing_note','weights','engine','alternatives','coefficient_note','sensitivity','comparison','footnotes','manuscript']
rows={
'en':['Needs review','Data structure summarized','Subject count, time points, balanced/unbalanced status, and cluster size are summarized.','Missing-data method, exclusions, and variable-level missingness are summarized.','Analysis weights described','Missing-data sensitivity engine run','Recommended alternatives provided','Coefficient table includes B, SE, p-value, and 95% CI; exp(B) is added for logit/log models.','Sensitivity analysis suggested','Automated sensitivity comparison reported','Footnotes for estimand, standard errors, confidence intervals, missing data, and sensitivity interpretation are provided.','Suggested Methods, Results, Assumptions, Sensitivity, and Software text is provided for manuscript drafting.'],
'ko':['검토 필요','자료 구조 요약','대상자 수, 시점, 균형/불균형 여부 및 군집 크기를 요약했습니다.','결측자료 처리 방법, 제외 사례 및 변수별 결측을 요약했습니다.','분석 가중치 설명','결측자료 민감도 분석 실행','권고 대안 제시','계수 표에는 B, SE, p값 및 95% CI가 포함되며 logit/log 모형에는 exp(B)가 추가됩니다.','민감도 분석 제안','자동 민감도 비교 보고','추정대상, 표준오차, 신뢰구간, 결측자료 및 민감도 해석에 관한 주석을 제공합니다.','원고 작성을 위한 방법, 결과, 가정, 민감도 및 소프트웨어 문구를 제공합니다.'],
'ja':['要確認','データ構造の要約','対象者数、時点、均衡／不均衡の状態、クラスターサイズを要約しています。','欠測データの処理方法、除外、変数別の欠測状況を要約しています。','分析重みの説明','欠測データ感度分析の実行','推奨される代替方法の提示','係数表にはB、SE、p値、95% CIが含まれ、logit/logモデルにはexp(B)が追加されます。','感度分析の提案','自動感度比較の報告','推定対象、標準誤差、信頼区間、欠測データ、感度分析の解釈に関する注記を提供しています。','原稿作成用に方法、結果、仮定、感度分析、ソフトウェアの文章案を提供しています。'],
'zh':['需要审查','数据结构摘要','已汇总受试者数量、时间点、平衡／非平衡状态及聚类大小。','已汇总缺失数据处理方法、排除情况及各变量的缺失情况。','分析权重说明','缺失数据敏感性分析执行','推荐替代方法','系数表包含 B、SE、p 值及 95% CI；logit/log 模型还包含 exp(B)。','敏感性分析建议','自动敏感性比较报告','提供关于估计目标、标准误、置信区间、缺失数据和敏感性分析解释的注释。','提供用于撰写论文的方法、结果、假设、敏感性分析及软件说明文本。'],
'es':['Requiere revisión','Estructura de datos resumida','Se resumen el número de sujetos, los puntos temporales, el equilibrio/desequilibrio y el tamaño de los conglomerados.','Se resumen el método para datos faltantes, las exclusiones y los datos faltantes por variable.','Pesos de análisis descritos','Análisis de sensibilidad a datos faltantes ejecutado','Alternativas recomendadas proporcionadas','La tabla de coeficientes incluye B, SE, valor p e IC del 95%; se añade exp(B) en los modelos logit/log.','Análisis de sensibilidad sugerido','Comparación automática de sensibilidad informada','Se proporcionan notas sobre el estimando, los errores estándar, los intervalos de confianza, los datos faltantes y la interpretación de sensibilidad.','Se proporcionan textos sugeridos de métodos, resultados, supuestos, sensibilidad y software para redactar el manuscrito.'],
'fr':['À vérifier','Structure des données résumée','Le nombre de sujets, les temps de mesure, le caractère équilibré ou non et la taille des grappes sont résumés.','La méthode de traitement des données manquantes, les exclusions et les données manquantes par variable sont résumées.','Poids d’analyse décrits','Analyse de sensibilité aux données manquantes exécutée','Autres méthodes recommandées proposées','Le tableau des coefficients comprend B, SE, la valeur p et l’IC à 95 % ; exp(B) est ajouté pour les modèles logit/log.','Analyse de sensibilité suggérée','Comparaison automatique de sensibilité rapportée','Des notes sur l’estimand, les erreurs standard, les intervalles de confiance, les données manquantes et l’interprétation de la sensibilité sont fournies.','Des propositions de texte pour les méthodes, résultats, hypothèses, analyses de sensibilité et logiciels sont fournies pour la rédaction du manuscrit.'],
'de':['Überprüfung erforderlich','Datenstruktur zusammengefasst','Personenzahl, Messzeitpunkte, balancierte/unbalancierte Struktur und Clustergröße sind zusammengefasst.','Verfahren für fehlende Daten, Ausschlüsse und fehlende Werte je Variable sind zusammengefasst.','Analysegewichte beschrieben','Sensitivitätsanalyse für fehlende Daten ausgeführt','Empfohlene Alternativen angegeben','Die Koeffiziententabelle enthält B, SE, p-Wert und 95%-KI; bei Logit-/Log-Modellen wird exp(B) ergänzt.','Sensitivitätsanalyse vorgeschlagen','Automatischer Sensitivitätsvergleich berichtet','Anmerkungen zu Zielgröße, Standardfehlern, Konfidenzintervallen, fehlenden Daten und Sensitivitätsinterpretation werden bereitgestellt.','Textvorschläge zu Methoden, Ergebnissen, Annahmen, Sensitivität und Software für das Manuskript werden bereitgestellt.'],
'vi':['Cần xem xét','Đã tóm tắt cấu trúc dữ liệu','Đã tóm tắt số đối tượng, thời điểm, trạng thái cân bằng/không cân bằng và kích thước cụm.','Đã tóm tắt phương pháp xử lý dữ liệu thiếu, các trường hợp bị loại và dữ liệu thiếu theo biến.','Đã mô tả trọng số phân tích','Đã chạy phân tích độ nhạy với dữ liệu thiếu','Đã cung cấp phương pháp thay thế được khuyến nghị','Bảng hệ số gồm B, SE, giá trị p và KTC 95%; exp(B) được thêm cho mô hình logit/log.','Đã đề xuất phân tích độ nhạy','Đã báo cáo so sánh độ nhạy tự động','Cung cấp chú thích về đại lượng đích, sai số chuẩn, khoảng tin cậy, dữ liệu thiếu và diễn giải độ nhạy.','Cung cấp văn bản gợi ý về phương pháp, kết quả, giả định, độ nhạy và phần mềm để soạn bản thảo.'],
}
for lang,values in rows.items():
 assert len(values)==len(keys)
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.checklist.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
