import json
from pathlib import Path
keys=['binary_levels','binary_values','weights','weight_alignment','weight_select','weight_missing','glmm_gaussian']
rows={
'en':['Binary longitudinal models require exactly two observed dependent-variable levels.','Binary longitudinal models require exactly two observed dependent-variable values.','Weights must be positive finite values.','Could not align analyzed rows with raw rows for weight construction.','Select one positive numeric weight variable for the selected weight type.','Selected weight variable must be positive and non-missing in analyzed rows.','GLMM requires a non-Gaussian family. Use LMM for Gaussian continuous outcomes.'],
'ko':['이분형 종단 모형의 종속변수에는 관측된 범주가 정확히 두 개 있어야 합니다.','이분형 종단 모형의 종속변수에는 관측된 값이 정확히 두 개 있어야 합니다.','가중치는 양의 유한값이어야 합니다.','가중치를 구성하기 위해 분석 행과 원본 행을 대응시킬 수 없습니다.','선택한 가중치 유형에 사용할 양의 숫자형 가중치 변수 하나를 선택하세요.','선택한 가중치 변수는 분석 행에서 양수이고 결측이 없어야 합니다.','GLMM에는 비정규분포 계열이 필요합니다. 정규분포 연속형 결과에는 LMM을 사용하세요.'],
'ja':['二値の縦断モデルでは、従属変数の観測カテゴリーがちょうど2つ必要です。','二値の縦断モデルでは、従属変数の観測値がちょうど2種類必要です。','重みは正の有限値である必要があります。','重みの作成に必要な分析行と元の行の対応付けができませんでした。','選択した重みの種類に使用する正の数値型重み変数を1つ選択してください。','選択した重み変数は分析行で正の値を持ち、欠測がない必要があります。','GLMMには非ガウス分布族が必要です。ガウス分布の連続アウトカムにはLMMを使用してください。'],
'zh':['二分类纵向模型的因变量必须恰好有两个观测类别。','二分类纵向模型的因变量必须恰好有两个不同的观测值。','权重必须为正的有限值。','无法将分析行与原始行对应以构造权重。','请为所选权重类型选择一个正数值型权重变量。','所选权重变量在分析行中必须为正且无缺失值。','GLMM 需要非高斯分布族。对于高斯连续结局，请使用 LMM。'],
'es':['Los modelos longitudinales binarios requieren exactamente dos niveles observados de la variable dependiente.','Los modelos longitudinales binarios requieren exactamente dos valores observados de la variable dependiente.','Los pesos deben ser valores positivos y finitos.','No se pudieron alinear las filas analizadas con las originales para construir los pesos.','Seleccione una variable numérica de pesos positivos para el tipo de ponderación seleccionado.','La variable de ponderación seleccionada debe ser positiva y no tener valores faltantes en las filas analizadas.','GLMM requiere una familia no gaussiana. Utilice LMM para resultados continuos gaussianos.'],
'fr':['Les modèles longitudinaux binaires nécessitent exactement deux modalités observées de la variable dépendante.','Les modèles longitudinaux binaires nécessitent exactement deux valeurs observées de la variable dépendante.','Les poids doivent être positifs et finis.','Impossible de faire correspondre les lignes analysées aux lignes originales pour construire les poids.','Sélectionnez une variable numérique de poids positifs pour le type de pondération choisi.','La variable de pondération sélectionnée doit être positive et sans valeurs manquantes dans les lignes analysées.','Le GLMM nécessite une famille non gaussienne. Utilisez le LMM pour les résultats continus gaussiens.'],
'de':['Binäre Längsschnittmodelle erfordern genau zwei beobachtete Kategorien der abhängigen Variable.','Binäre Längsschnittmodelle erfordern genau zwei beobachtete Werte der abhängigen Variable.','Gewichte müssen positive, endliche Werte sein.','Die analysierten Zeilen konnten zur Gewichtserstellung nicht den ursprünglichen Zeilen zugeordnet werden.','Wählen Sie eine numerische Gewichtsvariable mit positiven Werten für den gewählten Gewichtstyp.','Die gewählte Gewichtsvariable muss in den analysierten Zeilen positiv sein und darf keine fehlenden Werte enthalten.','GLMM erfordert eine nicht gaußsche Verteilungsfamilie. Verwenden Sie LMM für gaußsche kontinuierliche Zielvariablen.'],
'vi':['Mô hình dọc nhị phân yêu cầu đúng hai mức quan sát của biến phụ thuộc.','Mô hình dọc nhị phân yêu cầu đúng hai giá trị quan sát của biến phụ thuộc.','Trọng số phải là giá trị dương và hữu hạn.','Không thể khớp các hàng phân tích với các hàng gốc để tạo trọng số.','Chọn một biến trọng số dạng số dương cho loại trọng số đã chọn.','Biến trọng số đã chọn phải dương và không bị thiếu trong các hàng phân tích.','GLMM yêu cầu họ phân phối không phải Gaussian. Sử dụng LMM cho kết quả liên tục có phân phối Gaussian.']}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'longitudinal.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
