import json,re
from pathlib import Path
rows='''Survival sparse evidence Maximum cause-specific Cox VIF =|原因別Coxの最大VIF =|原因别Cox最大VIF =|VIF máximo de Cox por causa =|VIF maximal de Cox par cause =|Maximaler ursachenspezifischer Cox-VIF =|VIF Cox theo nguyên nhân lớn nhất =
Survival sparse evidence Cause-specific Cox design condition number =|原因別Cox計画行列の条件数 =|原因别Cox设计矩阵条件数 =|Número de condición del diseño de Cox por causa =|Nombre de condition de la matrice de Cox par cause =|Konditionszahl der ursachenspezifischen Cox-Designmatrix =|Số điều kiện của ma trận thiết kế Cox theo nguyên nhân =
At least one cause-specific Cox design-column VIF is not finite.|少なくとも1つの原因別Cox計画行列の列のVIFが有限ではありません。|至少一个原因别Cox设计矩阵列的VIF不是有限值。|Al menos un VIF de una columna del diseño de Cox por causa no es finito.|Au moins un VIF d’une colonne de la matrice de Cox par cause n’est pas fini.|Mindestens ein VIF einer ursachenspezifischen Cox-Designspalte ist nicht endlich.|Ít nhất một VIF của cột thiết kế Cox theo nguyên nhân không hữu hạn.
Review exact collinearity or non-estimable columns in the cause-specific Cox design matrix.|原因別Cox計画行列の完全共線性や推定できない列を確認してください。|请检查原因别Cox设计矩阵中的完全共线性或无法估计的列。|Revise la colinealidad exacta o las columnas no estimables de la matriz de diseño de Cox por causa.|Examinez la colinéarité exacte ou les colonnes non estimables de la matrice de Cox par cause.|Prüfen Sie exakte Kollinearität oder nicht schätzbare Spalten in der ursachenspezifischen Cox-Designmatrix.|Kiểm tra cộng tuyến hoàn toàn hoặc các cột không thể ước lượng trong ma trận thiết kế Cox theo nguyên nhân.
Review instability in cause-specific Cox coefficients and standard errors.|原因別Cox係数と標準誤差の不安定性を確認してください。|请检查原因别Cox系数和标准误的不稳定性。|Revise la inestabilidad de los coeficientes y errores estándar de Cox por causa.|Examinez l’instabilité des coefficients et erreurs standards de Cox par cause.|Prüfen Sie die Instabilität ursachenspezifischer Cox-Koeffizienten und Standardfehler.|Xem xét tính không ổn định của hệ số và sai số chuẩn Cox theo nguyên nhân.
Review cause-specific Cox covariate redundancy and model specification.|原因別Cox共変量の重複性とモデル指定を確認してください。|请检查原因别Cox协变量冗余和模型设定。|Revise la redundancia de covariables y la especificación del modelo de Cox por causa.|Examinez la redondance des covariables et la spécification du modèle de Cox par cause.|Prüfen Sie die Redundanz der Kovariaten und die Spezifikation des ursachenspezifischen Cox-Modells.|Xem xét sự dư thừa hiệp biến và đặc tả mô hình Cox theo nguyên nhân.
Review numerical instability in the cause-specific Cox design matrix.|原因別Cox計画行列の数値的不安定性を確認してください。|请检查原因别Cox设计矩阵的数值不稳定性。|Revise la inestabilidad numérica de la matriz de diseño de Cox por causa.|Examinez l’instabilité numérique de la matrice de Cox par cause.|Prüfen Sie die numerische Instabilität der ursachenspezifischen Cox-Designmatrix.|Xem xét tính không ổn định về số của ma trận thiết kế Cox theo nguyên nhân.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
