"""Cluster trial engines and exact dynamic numeric tokens."""
import json
from pathlib import Path
keys=['note_cluster_webpower','note_cluster_design_effect','note_cluster_simulations']
rows={
'en':['Parallel 2-arm continuous cluster randomized trial using WebPower::wp.crt2arm. The app rounds the required total clusters up to balanced clusters per group.','Parallel cluster randomized trial using individual-randomized sample size multiplied by design effect %s = 1 + (m - 1) ICC.','Simulation-based stepped-wedge cluster trial power using a Hussey-Hughes style mixed model with fixed period effects and random cluster intercepts (%s simulations).'],
'ko':['WebPower::wp.crt2arm을 사용하는 평행 2군 연속형 군집 무작위시험입니다. 필요한 총 군집 수를 집단별 군집 수가 같도록 올림합니다.','개인 단위 무작위시험 표본수에 설계효과 %s = 1 + (m - 1) ICC를 곱하는 평행 군집 무작위시험입니다.','고정 기간효과와 무작위 군집 절편을 포함한 Hussey–Hughes 방식 혼합모형으로 단계적 도입 군집시험의 검정력을 시뮬레이션합니다(%s회).'],
'ja':['WebPower::wp.crt2armを用いた平行2群の連続アウトカムのクラスター無作為化試験です。必要な総クラスター数を、群ごとのクラスター数が均等になるよう切り上げます。','個人無作為化試験の標本サイズにデザイン効果%s = 1 + (m - 1) ICCを掛ける平行クラスター無作為化試験です。','固定期間効果とランダムクラスター切片を含むHussey–Hughes型混合モデルによるステップドウェッジ試験のシミュレーション検出力です（%s回）。'],
'zh':['使用WebPower::wp.crt2arm的平行两组连续结局整群随机试验。将所需总群数向上取整，使各组群数均衡。','将个体随机试验样本量乘以设计效应%s = 1 + (m - 1) ICC的平行整群随机试验。','采用包含固定时期效应和随机群截距的Hussey–Hughes型混合模型，模拟阶梯楔形整群试验功效（%s次模拟）。'],
'es':['Ensayo aleatorizado por conglomerados paralelo de dos brazos con resultado continuo usando WebPower::wp.crt2arm. El total requerido de conglomerados se redondea hacia arriba para equilibrarlos por grupo.','Ensayo paralelo aleatorizado por conglomerados con tamaño muestral individual multiplicado por el efecto de diseño %s = 1 + (m - 1) ICC.','Potencia simulada de un ensayo escalonado por conglomerados mediante un modelo mixto de tipo Hussey–Hughes con efectos fijos de período e interceptos aleatorios de conglomerado (%s simulaciones).'],
'fr':['Essai randomisé en grappes parallèle à deux bras avec résultat continu utilisant WebPower::wp.crt2arm. Le nombre total requis de grappes est arrondi vers le haut pour équilibrer les groupes.','Essai randomisé en grappes parallèle avec taille d’échantillon individuelle multipliée par l’effet de plan %s = 1 + (m - 1) ICC.','Puissance simulée d’un essai en grappes en escalier avec un modèle mixte de type Hussey–Hughes, effets fixes de période et intercepts aléatoires de grappe (%s simulations).'],
'de':['Parallele zweiarmige cluster-randomisierte Studie mit kontinuierlichem Endpunkt mittels WebPower::wp.crt2arm. Die erforderliche Gesamtclusterzahl wird auf gleiche Clusterzahlen pro Gruppe aufgerundet.','Parallele cluster-randomisierte Studie mit individuell randomisiertem Stichprobenumfang multipliziert mit dem Designeffekt %s = 1 + (m - 1) ICC.','Simulierte Power einer Stepped-Wedge-Clusterstudie mit einem gemischten Modell nach Hussey–Hughes, festen Periodeneffekten und zufälligen Clusterinterzepten (%s Simulationen).'],
'vi':['Thử nghiệm ngẫu nhiên theo cụm song song hai nhánh với kết quả liên tục bằng WebPower::wp.crt2arm. Tổng số cụm cần thiết được làm tròn lên để cân bằng số cụm mỗi nhóm.','Thử nghiệm ngẫu nhiên theo cụm song song sử dụng cỡ mẫu ngẫu nhiên cá nhân nhân với hiệu ứng thiết kế %s = 1 + (m - 1) ICC.','Công suất mô phỏng của thử nghiệm cụm bậc thang bằng mô hình hỗn hợp kiểu Hussey–Hughes với hiệu ứng thời kỳ cố định và hệ số chặn cụm ngẫu nhiên (%s lần mô phỏng).']}
for lang,values in rows.items():
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
