import json,re
from pathlib import Path
rows='''The Fine-Gray pseudo likelihood-ratio test is non-finite.|Fine-Gray擬似尤度比検定が有限値ではありません。|Fine-Gray伪似然比检验不是有限值。|La prueba de razón de pseudoverosimilitudes de Fine-Gray no es finita.|Le test du rapport de pseudo-vraisemblance de Fine-Gray n’est pas fini.|Der Fine-Gray-Pseudo-Likelihood-Quotienten-Test ist nicht endlich.|Kiểm định tỷ số hợp lý giả Fine-Gray không hữu hạn.
Do not report a non-finite Fine-Gray pseudo likelihood-ratio test; review convergence, sparsity, and the information matrix.|有限値でないFine-Gray擬似尤度比検定を報告せず、収束、データの少なさ、情報行列を検討してください。|不要报告非有限的Fine-Gray伪似然比检验；应审查收敛性、数据稀疏性和信息矩阵。|No informe una prueba de razón de pseudoverosimilitudes de Fine-Gray no finita; revise la convergencia, la escasez de datos y la matriz de información.|Ne rapportez pas un test du rapport de pseudo-vraisemblance de Fine-Gray non fini ; examinez la convergence, la rareté des données et la matrice d’information.|Berichten Sie keinen nicht endlichen Fine-Gray-Pseudo-Likelihood-Quotienten-Test; prüfen Sie Konvergenz, dünn besetzte Daten und die Informationsmatrix.|Không báo cáo kiểm định tỷ số hợp lý giả Fine-Gray không hữu hạn; hãy xem xét sự hội tụ, dữ liệu thưa và ma trận thông tin.
Survival sparse evidence Non-estimable Fine-Gray categorical joint tests:|推定できないFine-Grayカテゴリ変数の同時検定:|无法估计的Fine-Gray分类变量联合检验：|Pruebas conjuntas de variables categóricas de Fine-Gray no estimables:|Tests conjoints de variables catégorielles de Fine-Gray non estimables :|Nicht schätzbare gemeinsame Fine-Gray-Tests kategorialer Variablen:|Các kiểm định đồng thời Fine-Gray cho biến phân loại không thể ước lượng:
Review sparse levels, separation, or a singular covariance matrix and do not report the affected Fine-Gray categorical joint test.|頻度の少ないカテゴリ、分離、または特異な共分散行列を検討し、該当するFine-Grayカテゴリ変数の同時検定を報告しないでください。|审查稀疏类别、分离或奇异协方差矩阵，不要报告受影响的Fine-Gray分类变量联合检验。|Revise los niveles escasos, la separación o una matriz de covarianza singular y no informe la prueba conjunta de variables categóricas de Fine-Gray afectada.|Examinez les modalités peu fréquentes, la séparation ou une matrice de covariance singulière et ne rapportez pas le test conjoint de variables catégorielles de Fine-Gray concerné.|Prüfen Sie schwach besetzte Kategorien, Separation oder eine singuläre Kovarianzmatrix und berichten Sie den betroffenen gemeinsamen Fine-Gray-Test kategorialer Variablen nicht.|Xem xét các mức có ít quan sát, sự phân tách hoặc ma trận hiệp phương sai suy biến và không báo cáo kiểm định đồng thời Fine-Gray cho biến phân loại bị ảnh hưởng.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
