import json
import re
from pathlib import Path

# Full templates keep user names and preformatted numbers outside translation.
rows = '''the model did not converge|モデルが収束しませんでした|模型未收敛|el modelo no convergió|le modèle n’a pas convergé|das Modell ist nicht konvergiert|mô hình không hội tụ
lavaan post-estimation checks failed|lavaanの推定後チェックに失敗しました|lavaan估计后检查失败|fallaron las comprobaciones posteriores a la estimación de lavaan|les vérifications après estimation de lavaan ont échoué|die lavaan-Prüfungen nach der Schätzung sind fehlgeschlagen|kiểm tra sau ước lượng của lavaan thất bại
model degrees of freedom are invalid (df = %s)|モデルの自由度が無効です（df = %s）|模型自由度无效（df = %s）|los grados de libertad del modelo no son válidos (df = %s)|les degrés de liberté du modèle ne sont pas valides (df = %s)|die Modellfreiheitsgrade sind ungültig (df = %s)|bậc tự do của mô hình không hợp lệ (df = %s)
negative residual variances: %s|負の残差分散：%s|负残差方差：%s|varianzas residuales negativas: %s|variances résiduelles négatives : %s|negative Residualvarianzen: %s|phương sai phần dư âm: %s
negative latent variances: %s|負の潜在変数分散：%s|负潜变量方差：%s|varianzas latentes negativas: %s|variances latentes négatives : %s|negative latente Varianzen: %s|phương sai biến tiềm ẩn âm: %s
residual covariance matrix is not positive semidefinite (minimum eigenvalue = %s)|残差共分散行列が半正定値ではありません（最小固有値 = %s）|残差协方差矩阵不是半正定矩阵（最小特征值 = %s）|la matriz de covarianzas residuales no es semidefinida positiva (valor propio mínimo = %s)|la matrice de covariance résiduelle n’est pas semi-définie positive (valeur propre minimale = %s)|die Residualkovarianzmatrix ist nicht positiv semidefinit (kleinster Eigenwert = %s)|ma trận hiệp phương sai phần dư không nửa xác định dương (giá trị riêng nhỏ nhất = %s)
latent covariance matrix is not positive semidefinite (minimum eigenvalue = %s)|潜在変数共分散行列が半正定値ではありません（最小固有値 = %s）|潜变量协方差矩阵不是半正定矩阵（最小特征值 = %s）|la matriz de covarianzas latentes no es semidefinida positiva (valor propio mínimo = %s)|la matrice de covariance latente n’est pas semi-définie positive (valeur propre minimale = %s)|die latente Kovarianzmatrix ist nicht positiv semidefinit (kleinster Eigenwert = %s)|ma trận hiệp phương sai biến tiềm ẩn không nửa xác định dương (giá trị riêng nhỏ nhất = %s)
residual covariance matrix is near singular or on the boundary (minimum eigenvalue = %s)|残差共分散行列が特異に近いか境界上にあります（最小固有値 = %s）|残差协方差矩阵接近奇异或处于边界（最小特征值 = %s）|la matriz de covarianzas residuales es casi singular o está en el límite (valor propio mínimo = %s)|la matrice de covariance résiduelle est presque singulière ou à la frontière (valeur propre minimale = %s)|die Residualkovarianzmatrix ist nahezu singulär oder liegt auf der Grenze (kleinster Eigenwert = %s)|ma trận hiệp phương sai phần dư gần suy biến hoặc ở biên (giá trị riêng nhỏ nhất = %s)
latent covariance matrix is near singular or on the boundary (minimum eigenvalue = %s)|潜在変数共分散行列が特異に近いか境界上にあります（最小固有値 = %s）|潜变量协方差矩阵接近奇异或处于边界（最小特征值 = %s）|la matriz de covarianzas latentes es casi singular o está en el límite (valor propio mínimo = %s)|la matrice de covariance latente est presque singulière ou à la frontière (valeur propre minimale = %s)|die latente Kovarianzmatrix ist nahezu singulär oder liegt auf der Grenze (kleinster Eigenwert = %s)|ma trận hiệp phương sai biến tiềm ẩn gần suy biến hoặc ở biên (giá trị riêng nhỏ nhất = %s)
parameter-estimate covariance matrix is not positive semidefinite (minimum eigenvalue = %s)|パラメータ推定値の共分散行列が半正定値ではありません（最小固有値 = %s）|参数估计协方差矩阵不是半正定矩阵（最小特征值 = %s）|la matriz de covarianzas de las estimaciones de parámetros no es semidefinida positiva (valor propio mínimo = %s)|la matrice de covariance des estimations des paramètres n’est pas semi-définie positive (valeur propre minimale = %s)|die Kovarianzmatrix der Parameterschätzungen ist nicht positiv semidefinit (kleinster Eigenwert = %s)|ma trận hiệp phương sai của ước lượng tham số không nửa xác định dương (giá trị riêng nhỏ nhất = %s)
parameter-estimate covariance matrix is near singular (minimum eigenvalue = %s)|パラメータ推定値の共分散行列が特異に近い状態です（最小固有値 = %s）|参数估计协方差矩阵接近奇异（最小特征值 = %s）|la matriz de covarianzas de las estimaciones de parámetros es casi singular (valor propio mínimo = %s)|la matrice de covariance des estimations des paramètres est presque singulière (valeur propre minimale = %s)|die Kovarianzmatrix der Parameterschätzungen ist nahezu singulär (kleinster Eigenwert = %s)|ma trận hiệp phương sai của ước lượng tham số gần suy biến (giá trị riêng nhỏ nhất = %s)
one or more absolute latent correlations are at least 1|絶対値が1以上の潜在変数相関があります|存在绝对值大于或等于1的潜变量相关|una o más correlaciones latentes tienen un valor absoluto de al menos 1|une ou plusieurs corrélations latentes ont une valeur absolue supérieure ou égale à 1|mindestens eine latente Korrelation hat einen Absolutwert von mindestens 1|có tương quan giữa các biến tiềm ẩn với giá trị tuyệt đối từ 1 trở lên
Potentially inadmissible solution: %s. Interpret fit, AVE, CR, and validity results with caution.|不適解の可能性があります：%s。適合度、AVE、CR、妥当性の結果は慎重に解釈してください。|可能存在不当解：%s。请谨慎解释拟合度、AVE、CR和效度结果。|Solución potencialmente inadmisible: %s. Interprete con cautela los resultados de ajuste, AVE, CR y validez.|Solution potentiellement inadmissible : %s. Interprétez avec prudence les résultats d’ajustement, d’AVE, de CR et de validité.|Möglicherweise unzulässige Lösung: %s. Interpretieren Sie Modellfit, AVE, CR und Validitätsergebnisse mit Vorsicht.|Nghiệm có thể không chấp nhận được: %s. Hãy thận trọng khi diễn giải độ phù hợp, AVE, CR và kết quả về tính giá trị.
residual covariance condition number = %s|残差共分散行列の条件数 = %s|残差协方差矩阵条件数 = %s|número de condición de la covarianza residual = %s|nombre de condition de la covariance résiduelle = %s|Konditionszahl der Residualkovarianzmatrix = %s|số điều kiện của ma trận hiệp phương sai phần dư = %s
latent covariance condition number = %s|潜在変数共分散行列の条件数 = %s|潜变量协方差矩阵条件数 = %s|número de condición de la covarianza latente = %s|nombre de condition de la covariance latente = %s|Konditionszahl der latenten Kovarianzmatrix = %s|số điều kiện của ma trận hiệp phương sai biến tiềm ẩn = %s
parameter-estimate covariance condition number = %s|パラメータ推定値の共分散行列の条件数 = %s|参数估计协方差矩阵条件数 = %s|número de condición de la covarianza de las estimaciones de parámetros = %s|nombre de condition de la covariance des estimations des paramètres = %s|Konditionszahl der Kovarianzmatrix der Parameterschätzungen = %s|số điều kiện của ma trận hiệp phương sai của ước lượng tham số = %s
Numerically ill-conditioned solution: %s. Small data or specification changes may produce unstable estimates.|数値的に悪条件の解です：%s。データやモデル指定のわずかな変更により推定値が不安定になる可能性があります。|数值病态解：%s。数据或模型设定的微小变化可能导致估计值不稳定。|Solución numéricamente mal condicionada: %s. Pequeños cambios en los datos o la especificación pueden producir estimaciones inestables.|Solution numériquement mal conditionnée : %s. De petits changements des données ou de la spécification peuvent produire des estimations instables.|Numerisch schlecht konditionierte Lösung: %s. Kleine Änderungen der Daten oder Modellspezifikation können zu instabilen Schätzungen führen.|Nghiệm có điều kiện số kém: %s. Thay đổi nhỏ trong dữ liệu hoặc đặc tả mô hình có thể làm các ước lượng không ổn định.'''

for i, language in enumerate(['ja', 'zh', 'es', 'fr', 'de', 'vi'], 1):
    path = Path('i18n') / (language + '.json')
    data = json.loads(path.read_text(encoding='utf-8'))
    for row in rows.splitlines():
        fields = row.split('|')
        assert len(fields) == 7
        assert fields[i].count('%s') == fields[0].count('%s')
        key = 'analysis.ui.' + re.sub(r'[^a-z0-9]+', '_', fields[0].lower()).strip('_')
        data['translations'][key] = fields[i]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
