import json,re
from pathlib import Path
rows='''Interest events =|関心イベント数 =|目标事件数 =|Eventos de interés =|Événements d’intérêt =|Interessierende Ereignisse =|Số biến cố quan tâm =
Competing events =|競合イベント数 =|竞争事件数 =|Eventos competitivos =|Événements concurrents =|Konkurrierende Ereignisse =|Số biến cố cạnh tranh =
Zero-event group-cause cells:|イベントがない集団・原因の組合せ:|无事件的组别与原因组合：|Combinaciones de grupo y causa sin eventos:|Combinaisons de groupe et cause sans événement :|Kombinationen aus Gruppe und Ursache ohne Ereignisse:|Các tổ hợp nhóm và nguyên nhân không có biến cố:
Group-cause cells with fewer than 5 events:|イベント数が5件未満の集団・原因の組合せ:|事件少于5个的组别与原因组合：|Combinaciones de grupo y causa con menos de 5 eventos:|Combinaisons de groupe et cause avec moins de 5 événements :|Kombinationen aus Gruppe und Ursache mit weniger als 5 Ereignissen:|Các tổ hợp nhóm và nguyên nhân có ít hơn 5 biến cố:
Emphasize uncertainty in interest-event estimates and regression coefficients.|関心イベントの推定値と回帰係数の不確実性を強調してください。|应强调目标事件估计值和回归系数的不确定性。|Destaque la incertidumbre en las estimaciones del evento de interés y los coeficientes de regresión.|Soulignez l’incertitude des estimations de l’événement d’intérêt et des coefficients de régression.|Betonen Sie die Unsicherheit der Schätzungen für das interessierende Ereignis und der Regressionskoeffizienten.|Nhấn mạnh sự không chắc chắn của ước lượng biến cố quan tâm và hệ số hồi quy.
Review sparsity of competing-event CIFs and cause-specific comparisons.|競合イベントCIFと原因別比較におけるデータの少なさを検討してください。|应审查竞争事件CIF和原因别比较中的数据稀疏性。|Revise la escasez de datos en las CIF de eventos competitivos y las comparaciones por causa.|Examinez la rareté des données pour les CIF d’événements concurrents et les comparaisons par cause.|Prüfen Sie die geringe Datenbasis der CIFs konkurrierender Ereignisse und ursachenspezifischer Vergleiche.|Xem xét tính thưa thớt của dữ liệu trong CIF biến cố cạnh tranh và so sánh theo nguyên nhân.
Information for the affected group-cause CIF and group comparison is limited; report event counts and confidence intervals and interpret regression estimates cautiously.|該当する集団・原因のCIFと集団比較の情報は限られています。イベント数と信頼区間を報告し、回帰推定値を慎重に解釈してください。|相关组别与原因的CIF及组间比较信息有限；应报告事件数和置信区间，并谨慎解释回归估计值。|La información para la CIF y la comparación del grupo y causa afectados es limitada; informe los recuentos de eventos y los intervalos de confianza e interprete las estimaciones de regresión con cautela.|L’information disponible pour la CIF et la comparaison du groupe et de la cause concernés est limitée ; présentez les nombres d’événements et les intervalles de confiance et interprétez les estimations de régression avec prudence.|Die Information zur betroffenen Gruppen-Ursachen-CIF und zum Gruppenvergleich ist begrenzt; berichten Sie Ereigniszahlen und Konfidenzintervalle und interpretieren Sie Regressionsschätzungen vorsichtig.|Thông tin về CIF của tổ hợp nhóm và nguyên nhân liên quan cũng như so sánh nhóm còn hạn chế; báo cáo số biến cố và khoảng tin cậy, đồng thời diễn giải ước lượng hồi quy thận trọng.
Emphasize uncertainty in CIFs, Gray tests, and regression coefficients for sparse group-cause cells.|イベントが少ない集団・原因の組合せでは、CIF、Gray検定、回帰係数の不確実性を強調してください。|对于事件稀少的组别与原因组合，应强调CIF、Gray检验和回归系数的不确定性。|Destaque la incertidumbre en las CIF, las pruebas de Gray y los coeficientes de regresión para combinaciones de grupo y causa con pocos eventos.|Soulignez l’incertitude des CIF, des tests de Gray et des coefficients de régression pour les combinaisons de groupe et cause avec peu d’événements.|Betonen Sie die Unsicherheit von CIFs, Gray-Tests und Regressionskoeffizienten bei ereignisarmen Kombinationen aus Gruppe und Ursache.|Nhấn mạnh sự không chắc chắn của CIF, kiểm định Gray và hệ số hồi quy đối với các tổ hợp nhóm và nguyên nhân có ít biến cố.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for index,row in enumerate(rows.splitlines()):
  f=row.split('|');assert len(f)==7
  if index<4:f[0]='Survival sparse evidence '+f[0]
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
