import json,re
from pathlib import Path
rows='''AVE and reliability %s bootstrap intervals (%s resamples; seed = %s)|AVEと信頼性の%sブートストラップ区間（再標本%s回；seed = %s）|AVE和信度%s自助法区间（重抽样%s次；seed = %s）|Intervalos bootstrap %s de AVE y fiabilidad (%s remuestras; semilla = %s)|Intervalles bootstrap %s d’AVE et de fiabilité (%s rééchantillonnages ; graine = %s)|%s-Bootstrap-Intervalle für AVE und Reliabilität (%s Stichproben; Seed = %s)|Khoảng bootstrap %s cho AVE và độ tin cậy (%s mẫu; seed = %s)
Estimate|推定値|估计值|Estimación|Estimation|Schätzwert|Ước lượng
Intervals use bias-corrected (BC) quantiles.|区間はバイアス補正（BC）分位点を使用します。|区间使用偏差校正（BC）分位数。|Los intervalos usan cuantiles corregidos por sesgo (BC).|Les intervalles utilisent les quantiles corrigés du biais (BC).|Die Intervalle verwenden bias-korrigierte (BC) Quantile.|Khoảng dùng phân vị hiệu chỉnh độ chệch (BC).
Intervals use percentile bootstrap quantiles.|区間はパーセンタイル・ブートストラップ分位点を使用します。|区间使用百分位数自助法分位数。|Los intervalos usan cuantiles bootstrap percentiles.|Les intervalles utilisent les quantiles du bootstrap percentile.|Die Intervalle verwenden Perzentil-Bootstrap-Quantile.|Khoảng dùng phân vị bootstrap percentile.
The selected AVE/CR formula uses model-implied parameters.|選択したAVE/CR式はモデルが含意するパラメータを使用します。|所选AVE/CR公式使用模型隐含参数。|La fórmula AVE/CR seleccionada usa parámetros implícitos en el modelo.|La formule AVE/CR choisie utilise les paramètres impliqués par le modèle.|Die gewählte AVE/CR-Formel verwendet modellimplizierte Parameter.|Công thức AVE/CR đã chọn dùng tham số hàm ý bởi mô hình.
The selected AVE/CR formula uses standardized loadings.|選択したAVE/CR式は標準化負荷量を使用します。|所选AVE/CR公式使用标准化载荷。|La fórmula AVE/CR seleccionada usa cargas estandarizadas.|La formule AVE/CR choisie utilise les saturations standardisées.|Die gewählte AVE/CR-Formel verwendet standardisierte Ladungen.|Công thức AVE/CR đã chọn dùng tải chuẩn hóa.'''
data_rows=[r.split('|') for r in rows.splitlines()]
notes='''AVE, CR, Cronbach's alpha, and omega are|AVE、CR、Cronbachのalpha、omegaは点推定です。区間推定が必要な場合は分析オプションでAVE/信頼性ブートストラップCIを選択してください。|AVE、CR、Cronbach alpha和omega为点估计。如需区间估计，请在分析选项中选择AVE/信度自助法CI。|AVE, CR, alfa de Cronbach y omega son estimaciones puntuales. Seleccione CI bootstrap de AVE/fiabilidad en las opciones si necesita intervalos.|AVE, CR, alpha de Cronbach et oméga sont des estimations ponctuelles. Sélectionnez les IC bootstrap AVE/fiabilité dans les options si des intervalles sont nécessaires.|AVE, CR, Cronbachs Alpha und Omega sind Punktschätzungen. Wählen Sie AVE/Reliabilitäts-Bootstrap-KI in den Optionen, wenn Intervalle benötigt werden.|AVE, CR, alpha Cronbach và omega là ước lượng điểm. Chọn CI bootstrap AVE/độ tin cậy trong tùy chọn nếu cần khoảng ước lượng.
AVE/reliability bootstrap intervals are being|AVE/信頼性ブートストラップ区間をバックグラウンドで計算しています。完了すると結果表が自動更新されます。|正在后台计算AVE/信度自助法区间。完成后结果表将自动更新。|Los intervalos bootstrap de AVE/fiabilidad se calculan en segundo plano. La tabla se actualizará automáticamente al finalizar.|Les intervalles bootstrap AVE/fiabilité sont calculés en arrière-plan. Le tableau sera actualisé automatiquement à la fin.|AVE/Reliabilitäts-Bootstrap-Intervalle werden im Hintergrund berechnet. Die Tabelle wird nach Abschluss automatisch aktualisiert.|Khoảng bootstrap AVE/độ tin cậy đang được tính nền. Bảng sẽ tự cập nhật khi hoàn tất.
The AVE/reliability bootstrap was stopped|AVE/信頼性ブートストラップはユーザーの要求で停止しました。点推定と基本モデルの結果は引き続き利用できます。|AVE/信度自助法已按用户要求停止。点估计和基础模型结果仍然可用。|El usuario detuvo el bootstrap de AVE/fiabilidad. Las estimaciones puntuales y los resultados del modelo base siguen disponibles.|Le bootstrap AVE/fiabilité a été arrêté par l’utilisateur. Les estimations ponctuelles et les résultats du modèle de base restent disponibles.|Der AVE/Reliabilitäts-Bootstrap wurde vom Benutzer gestoppt. Punktschätzungen und Basismodellergebnisse bleiben verfügbar.|Bootstrap AVE/độ tin cậy đã dừng theo yêu cầu người dùng. Ước lượng điểm và kết quả mô hình cơ sở vẫn còn.
AVE/reliability bootstrap intervals could|利用可能な推定値が得られた再標本がなかったため、AVE/信頼性ブートストラップ区間を推定できませんでした。|由于没有重抽样产生可用估计，无法估计AVE/信度自助法区间。|No se pudieron estimar intervalos bootstrap de AVE/fiabilidad porque ninguna remuestra produjo estimaciones utilizables.|Les intervalles bootstrap AVE/fiabilité n’ont pas pu être estimés car aucun rééchantillonnage n’a produit d’estimations utilisables.|AVE/Reliabilitäts-Bootstrap-Intervalle konnten nicht geschätzt werden, da keine Stichprobe brauchbare Schätzungen lieferte.|Không thể ước lượng khoảng bootstrap AVE/độ tin cậy vì không mẫu nào tạo được ước lượng dùng được.
Intervals use case resampling.|区間はケース再標本化を使用します。この出力のMcDonaldのomega totalは、CRと同じ適合済み同族測定モデルの得点算出式に従います。|区间使用个案重抽样。本输出的McDonald omega total采用与CR相同的拟合同类测量模型计分公式。|Los intervalos usan remuestreo de casos. En esta salida, omega total de McDonald sigue la misma fórmula congeneric ajustada que CR.|Les intervalles utilisent le rééchantillonnage des cas. Dans cette sortie, l’oméga total de McDonald suit la même formule de score congénérique ajustée que CR.|Die Intervalle verwenden Fall-Resampling. McDonalds Omega total folgt hier derselben angepassten kongenerischen Scoring-Formel wie CR.|Khoảng dùng lấy mẫu lại trường hợp. Trong đầu ra này, omega total của McDonald theo cùng công thức chấm điểm congeneric đã khớp như CR.
BCa unavailable means|BCa unavailableは、その統計量のバイアス補正またはジャックナイフ加速度を計算できなかったことを意味します。有効反復数を増やすか、報告にはパーセンタイルCIを検討してください。|BCa unavailable表示无法计算该统计量的偏差校正或刀切法加速度。请增加有效重复次数，或考虑使用百分位数CI报告。|BCa unavailable indica que no se pudo calcular la corrección de sesgo o la aceleración jackknife para ese estadístico; aumente las réplicas válidas o use CI percentiles.|BCa unavailable signifie que la correction du biais ou l’accélération jackknife n’a pas pu être calculée pour cette statistique ; augmentez les répétitions valides ou utilisez des IC percentiles.|BCa unavailable bedeutet, dass Bias-Korrektur oder Jackknife-Beschleunigung für diese Statistik nicht berechnet werden konnte. Erhöhen Sie gültige Wiederholungen oder verwenden Sie Perzentil-KI.|BCa unavailable nghĩa là không tính được hiệu chỉnh độ chệch hoặc gia tốc jackknife cho thống kê đó; tăng số lần lặp hợp lệ hoặc dùng CI percentile.
† marks an estimate|†は推定値または区間が許容範囲[0, 1]を超えることを示します。報告のために区間を切り詰めず、モデルの許容性、標本の不安定性、項目共分散構造、失敗した再標本を確認してください。|†标记估计值或区间超出允许的[0, 1]系数范围。不要为报告而截断区间；应检查模型可接受性、样本不稳定性、题项协方差结构和失败的重抽样。|† marca una estimación o intervalo fuera de [0, 1]. No trunque el intervalo para informar; investigue admisibilidad, inestabilidad muestral, covarianzas de ítems y remuestras fallidas.|† signale une estimation ou un intervalle hors de [0, 1]. Ne tronquez pas l’intervalle pour le rapport ; examinez l’admissibilité, l’instabilité de l’échantillon, les covariances des items et les rééchantillonnages échoués.|† markiert eine Schätzung oder ein Intervall außerhalb [0, 1]. Kürzen Sie Intervalle nicht für die Berichterstattung; prüfen Sie Modellzulässigkeit, Stichprobeninstabilität, Itemkovarianzen und fehlgeschlagene Wiederholungen.|† đánh dấu ước lượng hoặc khoảng ngoài [0, 1]. Không cắt khoảng để báo cáo; hãy kiểm tra tính chấp nhận được của mô hình, bất ổn mẫu, hiệp phương sai mục và các mẫu thất bại.
Some resamples failed the same|一部の再標本は主CFAと同じ収束・分散・共分散行列・自由度・潜在相関の許容性検査を通過しなかったか、統計量を算出できませんでした。有効反復数が要求数より大幅に少ない場合は慎重に解釈してください。|部分重抽样未通过与主CFA相同的收敛、方差、协方差矩阵、自由度和潜在相关可接受性检查，或未产生统计量。有效次数明显低于请求次数时，请谨慎解释区间。|Algunas remuestras fallaron las mismas comprobaciones de convergencia, varianza, matriz de covarianzas, gl y correlaciones latentes que el CFA principal, o no produjeron estadísticas. Interprete con cautela si las réplicas válidas son mucho menos que las solicitadas.|Certains rééchantillonnages ont échoué aux mêmes contrôles de convergence, variance, covariance, ddl et corrélations latentes que la CFA principale, ou n’ont pas produit de statistiques. Interprétez prudemment si le nombre valide est nettement inférieur au nombre demandé.|Einige Stichproben bestanden die Konvergenz-, Varianz-, Kovarianzmatrix-, df- und latenten Korrelationsprüfungen der Haupt-CFA nicht oder lieferten keine Statistik. Interpretieren Sie Intervalle vorsichtig, wenn deutlich weniger gültige als angeforderte Wiederholungen vorliegen.|Một số mẫu không qua các kiểm tra hội tụ, phương sai, ma trận hiệp phương sai, df và tương quan tiềm ẩn như CFA chính, hoặc không cho thống kê. Diễn giải thận trọng khi số lần hợp lệ thấp hơn đáng kể số yêu cầu.
Caution indicates|Cautionは要求した再標本の50%以上80%未満だけで統計量を算出できたことを示します。パーセンタイル限界は不安定とみなし、有効反復数を併記してください。|Caution表示请求重抽样中仅50%至不足80%产生了该统计量。百分位数界限可能不稳定，请报告有效重复次数。|Caution indica que entre el 50% y menos del 80% de las remuestras produjeron el estadístico. Considere inestables los límites percentiles e informe las réplicas válidas.|Caution indique que 50 % à moins de 80 % des rééchantillonnages ont produit la statistique. Considérez les limites percentiles comme instables et indiquez le nombre valide.|Caution bedeutet, dass 50% bis unter 80% der Stichproben die Statistik lieferten. Behandeln Sie Perzentilgrenzen als instabil und berichten Sie die Zahl gültiger Wiederholungen.|Caution nghĩa là từ 50% đến dưới 80% số mẫu cho thống kê. Xem giới hạn percentile là không ổn định và báo cáo số lần hợp lệ.
Unreliable indicates|Unreliableは要求した再標本の50%未満だけで統計量を算出できたことを示します。表示分位点は診断用であり、妥当な信頼区間として報告しないでください。まず収束・許容性・疎なカテゴリ・モデル指定の問題を解決してください。|Unreliable表示不足50%的请求重抽样产生了统计量。显示的分位数仅供诊断，不应作为可靠置信区间报告；请先解决收敛、可接受性、稀疏类别或模型设定问题。|Unreliable indica que menos del 50% de las remuestras produjeron el estadístico. Los cuantiles son solo diagnósticos, no intervalos defendibles; resuelva primero problemas de convergencia, admisibilidad, categorías escasas o especificación.|Unreliable indique que moins de 50 % des rééchantillonnages ont produit la statistique. Les quantiles sont uniquement diagnostiques, pas des IC défendables ; résolvez d’abord les problèmes de convergence, admissibilité, catégories rares ou spécification.|Unreliable bedeutet, dass weniger als 50% der Stichproben die Statistik lieferten. Die Quantile dienen nur der Diagnose, nicht als belastbare KI; beheben Sie zuerst Konvergenz-, Zulässigkeits-, seltene Kategorie- oder Spezifikationsprobleme.|Unreliable nghĩa là dưới 50% số mẫu cho thống kê. Các phân vị chỉ để chẩn đoán, không phải khoảng tin cậy có cơ sở; trước hết giải quyết vấn đề hội tụ, tính chấp nhận được, hạng mục thưa hoặc đặc tả.'''
source=Path('R/setup_custom_model_canvas_structural_render_reliability_bootstrap.R').read_text(encoding='utf-8');sources=re.findall(r'tr\("([^"]+)"',source)
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
