import json,re
from pathlib import Path
rows='''Specific indirect effects by path|経路別の特定間接効果|各路径的特定间接效应|Efectos indirectos específicos por ruta|Effets indirects spécifiques par chemin|Spezifische indirekte Effekte nach Pfad|Tác động gián tiếp riêng theo đường dẫn
Total indirect effects|総間接効果|总间接效应|Efectos indirectos totales|Effets indirects totaux|Gesamte indirekte Effekte|Tổng tác động gián tiếp
Total effects|総効果|总效应|Efectos totales|Effets totaux|Gesamteffekte|Tổng tác động
Bootstrap is still in progress. Point estimates are retained, but Boot SE, CI, t, and p are not reported until completion.|ブートストラップは実行中です。点推定値は保持しますが、完了までBoot SE、CI、t、pは表示しません。|自助法仍在运行。保留点估计值，但完成前不报告Boot SE、CI、t和p。|El bootstrap sigue en curso. Se conservan las estimaciones puntuales, pero Boot SE, IC, t y p no se informan hasta finalizar.|Le bootstrap est en cours. Les estimations ponctuelles sont conservées, mais Boot SE, IC, t et p ne sont pas affichés avant la fin.|Der Bootstrap läuft noch. Punktschätzungen bleiben erhalten; Boot SE, KI, t und p werden erst nach Abschluss berichtet.|Bootstrap đang chạy. Giữ nguyên ước lượng điểm nhưng chưa báo cáo Boot SE, CI, t và p cho đến khi hoàn tất.
Bootstrap execution failed. Point estimates are retained, but Boot SE, CI, t, and p are not reported.|ブートストラップの実行に失敗しました。点推定値は保持しますが、Boot SE、CI、t、pは表示しません。|自助法执行失败。保留点估计值，但不报告Boot SE、CI、t和p。|Falló la ejecución del bootstrap. Se conservan las estimaciones puntuales, pero no se informan Boot SE, IC, t ni p.|L’exécution du bootstrap a échoué. Les estimations ponctuelles sont conservées, mais Boot SE, IC, t et p ne sont pas affichés.|Die Bootstrap-Ausführung ist fehlgeschlagen. Punktschätzungen bleiben erhalten; Boot SE, KI, t und p werden nicht berichtet.|Bootstrap thất bại. Giữ nguyên ước lượng điểm nhưng không báo cáo Boot SE, CI, t và p.
Bootstrap was canceled by the user. Point estimates are retained, but Boot SE, CI, t, and p are not reported.|ユーザーがブートストラップを中止しました。点推定値は保持しますが、Boot SE、CI、t、pは表示しません。|用户取消了自助法。保留点估计值，但不报告Boot SE、CI、t和p。|El usuario canceló el bootstrap. Se conservan las estimaciones puntuales, pero no se informan Boot SE, IC, t ni p.|Le bootstrap a été annulé par l’utilisateur. Les estimations ponctuelles sont conservées, mais Boot SE, IC, t et p ne sont pas affichés.|Der Bootstrap wurde vom Benutzer abgebrochen. Punktschätzungen bleiben erhalten; Boot SE, KI, t und p werden nicht berichtet.|Người dùng đã hủy bootstrap. Giữ nguyên ước lượng điểm nhưng không báo cáo Boot SE, CI, t và p.
Fewer than %s%% of requested resamples passed the whole-draw statistic contract, so Boot SE, CI, t, and p are not reported.|要求した再標本のうち統計量全体の要件を満たした割合が%s%%未満のため、Boot SE、CI、t、pは表示しません。|满足整组统计量要求的重抽样少于请求次数的%s%%，因此不报告Boot SE、CI、t和p。|Menos del %s%% de las remuestras solicitadas cumplió los requisitos del conjunto completo de estadísticas; no se informan Boot SE, IC, t ni p.|Moins de %s%% des rééchantillonnages demandés ont satisfait aux exigences de l’ensemble des statistiques ; Boot SE, IC, t et p ne sont pas affichés.|Weniger als %s%% der angeforderten Stichproben erfüllten die Anforderungen an den gesamten Statistiksatz; Boot SE, KI, t und p werden nicht berichtet.|Dưới %s%% số mẫu yêu cầu đáp ứng yêu cầu của toàn bộ thống kê, nên không báo cáo Boot SE, CI, t và p.
Bootstrap inference is unavailable (status: %s). Point estimates are retained.|ブートストラップ推論を利用できません（状態：%s）。点推定値は保持します。|自助法推断不可用（状态：%s）。保留点估计值。|La inferencia bootstrap no está disponible (estado: %s). Se conservan las estimaciones puntuales.|L’inférence bootstrap est indisponible (état : %s). Les estimations ponctuelles sont conservées.|Bootstrap-Inferenz ist nicht verfügbar (Status: %s). Punktschätzungen bleiben erhalten.|Không có suy luận bootstrap (trạng thái: %s). Giữ nguyên ước lượng điểm.
Bootstrap was not requested, so only the point estimate β is shown. Boot SE, 95% CI, t, p, and BH-adjusted p are reported after bootstrap.|ブートストラップが要求されていないため、点推定値βのみを表示します。Boot SE、95% CI、t、p、BH調整pはブートストラップ実行後に報告します。|未请求自助法，因此仅显示点估计β。Boot SE、95% CI、t、p及BH校正p在自助法运行后报告。|No se solicitó bootstrap; solo se muestra la estimación puntual β. Boot SE, IC del 95%, t, p y p ajustado por BH se informan después del bootstrap.|Le bootstrap n’a pas été demandé ; seule l’estimation ponctuelle β est affichée. Boot SE, IC à 95%, t, p et p ajusté par BH sont rapportés après le bootstrap.|Es wurde kein Bootstrap angefordert; daher wird nur die Punktschätzung β angezeigt. Boot SE, 95%-KI, t, p und BH-adjustiertes p werden nach dem Bootstrap berichtet.|Chưa yêu cầu bootstrap nên chỉ hiển thị ước lượng điểm β. Boot SE, CI 95%, t, p và p hiệu chỉnh BH được báo cáo sau bootstrap.
Status: %s. Valid resamples: %s/%s (timeouts %s, estimation failures %s, nonconvergence %s, inadmissible solutions %s, statistic-contract failures %s, execution failures %s, cancellations %s).|状態：%s。有効再標本：%s/%s（時間切れ%s、推定失敗%s、非収束%s、不適解%s、統計量要件不適合%s、実行失敗%s、中止%s）。|状态：%s。有效重抽样：%s/%s（超时%s、估计失败%s、未收敛%s、不允许解%s、统计量要求不满足%s、执行失败%s、取消%s）。|Estado: %s. Remuestras válidas: %s/%s (tiempo agotado %s, fallos de estimación %s, no convergencia %s, soluciones inadmisibles %s, incumplimiento de requisitos estadísticos %s, fallos de ejecución %s, cancelaciones %s).|État : %s. Rééchantillonnages valides : %s/%s (délais dépassés %s, échecs d’estimation %s, non-convergence %s, solutions inadmissibles %s, exigences statistiques non satisfaites %s, échecs d’exécution %s, annulations %s).|Status: %s. Gültige Stichproben: %s/%s (Zeitüberschreitungen %s, Schätzfehler %s, Nichtkonvergenz %s, unzulässige Lösungen %s, verletzte Statistikanforderungen %s, Ausführungsfehler %s, Abbrüche %s).|Trạng thái: %s. Mẫu hợp lệ: %s/%s (hết thời gian %s, lỗi ước lượng %s, không hội tụ %s, nghiệm không chấp nhận %s, không đạt yêu cầu thống kê %s, lỗi thực thi %s, hủy %s).
Globally non-positive-definite PLSc resamples retained after all local-equation and downstream checks: %s.|すべての局所方程式と後続検査を通過して保持された、全体では非正定値のPLSc再標本：%s。|通过所有局部方程及后续检查后保留的全局非正定PLSc重抽样：%s。|Remuestras PLSc globalmente no definidas positivas conservadas tras superar todas las verificaciones de ecuaciones locales y posteriores: %s.|Rééchantillonnages PLSc globalement non définis positifs conservés après toutes les vérifications des équations locales et ultérieures : %s.|Global nicht positiv definite PLSc-Stichproben, die nach allen lokalen Gleichungs- und Folgeprüfungen beibehalten wurden: %s.|Số mẫu PLSc không xác định dương toàn cục được giữ lại sau khi vượt qua mọi kiểm tra phương trình cục bộ và kiểm tra tiếp theo: %s.
Direct, specific indirect, total indirect, and total effects are distinct estimands. BH adjustment is calculated within each table using unique hypotheses only. Type-7 percentile CIs and plus-one two-sided empirical sign p values use only resamples that pass the whole-draw statistic contract.|直接効果、特定間接効果、総間接効果、総効果は異なる推定対象です。BH調整は各表の重複しない仮説のみで計算します。type-7パーセンタイルCIとplus-one両側経験的符号p値は、統計量全体の要件を満たした再標本のみを使用します。|直接、特定间接、总间接及总效应是不同的估计目标。BH校正在各表内仅使用不重复假设计算。type-7百分位CI及plus-one双侧经验符号p值仅使用满足整组统计量要求的重抽样。|Los efectos directos, indirectos específicos, indirectos totales y totales son estimandos distintos. El ajuste BH se calcula en cada tabla con hipótesis únicas. Los IC percentiles tipo 7 y los valores p de signo empíricos bilaterales plus-one usan solo remuestras que cumplen los requisitos del conjunto completo de estadísticas.|Les effets directs, indirects spécifiques, indirects totaux et totaux sont des estimandes distinctes. L’ajustement BH est calculé dans chaque tableau avec des hypothèses uniques. Les IC percentiles de type 7 et les valeurs p empiriques bilatérales de signe plus-one utilisent uniquement les rééchantillonnages satisfaisant aux exigences de l’ensemble des statistiques.|Direkte, spezifische indirekte, gesamte indirekte und Gesamteffekte sind unterschiedliche Schätzgrößen. Die BH-Korrektur verwendet je Tabelle nur eindeutige Hypothesen. Typ-7-Perzentil-KI und zweiseitige empirische Plus-one-Vorzeichen-p-Werte verwenden nur Stichproben, die alle Statistikanforderungen erfüllen.|Tác động trực tiếp, gián tiếp riêng, tổng gián tiếp và tổng tác động là các đại lượng ước lượng khác nhau. Hiệu chỉnh BH được tính trong từng bảng với các giả thuyết không trùng lặp. CI phân vị loại 7 và giá trị p dấu thực nghiệm hai phía plus-one chỉ dùng mẫu đáp ứng yêu cầu của toàn bộ thống kê.'''
rows += '\nBH-adjusted p|BH調整p|BH校正p|p ajustado por BH|p ajusté par BH|BH-adjustiertes p|p hiệu chỉnh BH'
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  assert f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
