import json,re
from pathlib import Path
rows='''Survival sparse evidence Cause-specific Schoenfeld review signals:|原因別Schoenfeld検討シグナル:|原因别Schoenfeld审查信号：|Señales de revisión de Schoenfeld por causa:|Signaux de Schoenfeld à examiner par cause :|Ursachenspezifische Schoenfeld-Prüfsignale:|Dấu hiệu Schoenfeld cần xem xét theo nguyên nhân:
Survival sparse evidence Cause-specific influential coefficient rows =|原因別の影響力を検討する係数行数 =|原因别需审查影响力的系数行数 =|Filas de coeficientes influyentes por causa =|Lignes de coefficients influents par cause =|Ursachenspezifische einflussreiche Koeffizientenzeilen =|Số dòng hệ số có ảnh hưởng theo nguyên nhân =
Review Schoenfeld residual plots and prespecified time interactions. Do not reject proportional hazards automatically from a small p-value alone.|Schoenfeld残差図と事前指定の時間交互作用を検討してください。小さなp値だけで比例ハザード仮定を自動的に棄却しないでください。|请检查Schoenfeld残差图和预先指定的时间交互作用。不要仅凭较小的p值自动否定比例风险假设。|Revise los gráficos de residuos de Schoenfeld y las interacciones temporales preespecificadas. No rechace automáticamente los riesgos proporcionales solo por un valor p pequeño.|Examinez les graphiques des résidus de Schoenfeld et les interactions temporelles préspécifiées. Ne rejetez pas automatiquement l’hypothèse des risques proportionnels sur la seule base d’une petite valeur p.|Prüfen Sie Schoenfeld-Residuenplots und vorab festgelegte Zeitinteraktionen. Verwerfen Sie die Proportional-Hazards-Annahme nicht automatisch allein aufgrund eines kleinen p-Werts.|Xem xét đồ thị phần dư Schoenfeld và tương tác thời gian được chỉ định trước. Không tự động bác bỏ giả định nguy cơ tỷ lệ chỉ vì giá trị p nhỏ.
Review observations exceeding the heuristic DFBETAS threshold in inclusion/exclusion sensitivity analyses.|経験的なDFBETAS閾値を超える観測値について、含めた場合と除外した場合の感度分析で検討してください。|对超过经验DFBETAS阈值的观测值，进行纳入与排除的敏感性分析。|Revise las observaciones que superan el umbral heurístico de DFBETAS mediante análisis de sensibilidad con inclusión y exclusión.|Examinez les observations dépassant le seuil heuristique de DFBETAS dans des analyses de sensibilité avec inclusion et exclusion.|Prüfen Sie Beobachtungen oberhalb der heuristischen DFBETAS-Schwelle in Sensitivitätsanalysen mit und ohne diese Beobachtungen.|Xem xét các quan sát vượt ngưỡng DFBETAS theo kinh nghiệm bằng phân tích độ nhạy khi đưa vào và loại ra.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
