import json,re
from pathlib import Path
rows='''Censoring stratum|検閲層|删失层|Estrato de censura|Strate de censure|Zensierungsstratum|Tầng kiểm duyệt
Review reason|検討理由|审查原因|Motivo de revisión|Motif de l’examen|Prüfgrund|Lý do xem xét
All analysis records|全分析観測値|全部分析观测值|Todos los registros analizados|Toutes les observations analysées|Alle analysierten Beobachtungen|Tất cả quan sát phân tích
Fewer than 10 analysis records|分析観測値が10件未満|分析观测值少于10个|Menos de 10 registros analizados|Moins de 10 observations analysées|Weniger als 10 analysierte Beobachtungen|Ít hơn 10 quan sát phân tích
No censored observations|検閲観測値なし|无删失观测值|Sin observaciones censuradas|Aucune observation censurée|Keine zensierten Beobachtungen|Không có quan sát bị kiểm duyệt
Fewer than 5 censored observations|検閲観測値が5件未満|删失观测值少于5个|Menos de 5 observaciones censuradas|Moins de 5 observations censurées|Weniger als 5 zensierte Beobachtungen|Ít hơn 5 quan sát bị kiểm duyệt
Censoring-distribution estimation|検閲分布の推定|删失分布估计|Estimación de la distribución de censura|Estimation de la distribution de censure|Schätzung der Zensierungsverteilung|Ước lượng phân phối kiểm duyệt
The censoring distribution was estimated separately within %s using crr(cengroup=...). This variable should be prespecified from the design, not selected from observed p-values.|検閲分布はcrr(cengroup=...)を用いて%s内で別々に推定しました。この変数は観測p値から選ばず、研究デザインに基づいて事前指定する必要があります。|删失分布使用crr(cengroup=...)在%s内分别估计。该变量应根据研究设计预先指定，而非根据观测p值选择。|La distribución de censura se estimó por separado dentro de %s mediante crr(cengroup=...). Esta variable debe preespecificarse según el diseño, no seleccionarse a partir de valores p observados.|La distribution de censure a été estimée séparément au sein de %s avec crr(cengroup=...). Cette variable doit être préspécifiée selon le plan d’étude, et non choisie à partir des valeurs p observées.|Die Zensierungsverteilung wurde innerhalb von %s mit crr(cengroup=...) getrennt geschätzt. Diese Variable sollte anhand des Studiendesigns vorab festgelegt und nicht anhand beobachteter p-Werte ausgewählt werden.|Phân phối kiểm duyệt được ước lượng riêng trong %s bằng crr(cengroup=...). Biến này cần được chỉ định trước theo thiết kế, không chọn dựa trên giá trị p quan sát được.
One censoring distribution was estimated across the analysis sample. Fine-Gray validity requires independent censoring conditional on the modeled structure; consider prespecified cengroup strata when censoring distributions differ across known groups.|分析標本全体で1つの検閲分布を推定しました。Fine-Grayの妥当性にはモデル構造を条件とする独立検閲が必要です。既知の集団間で検閲分布が異なる場合は事前指定のcengroup層を検討してください。|在整个分析样本中估计了一个删失分布。Fine-Gray的有效性要求在给定模型结构下独立删失；若已知组别的删失分布不同，应考虑预先指定的cengroup分层。|Se estimó una distribución de censura para toda la muestra analizada. La validez de Fine-Gray requiere censura independiente condicionada a la estructura modelada; considere estratos cengroup preespecificados si las distribuciones difieren entre grupos conocidos.|Une distribution de censure a été estimée pour tout l’échantillon analysé. La validité de Fine-Gray exige une censure indépendante conditionnellement à la structure modélisée ; envisagez des strates cengroup préspécifiées si les distributions diffèrent entre groupes connus.|Eine Zensierungsverteilung wurde für die gesamte Analysestichprobe geschätzt. Fine-Gray setzt unabhängige Zensierung bedingt auf die Modellstruktur voraus; erwägen Sie vorab festgelegte cengroup-Strata, wenn sich Zensierungsverteilungen zwischen bekannten Gruppen unterscheiden.|Một phân phối kiểm duyệt được ước lượng trên toàn bộ mẫu phân tích. Tính hợp lệ của Fine-Gray đòi hỏi kiểm duyệt độc lập có điều kiện theo cấu trúc mô hình; cân nhắc các tầng cengroup chỉ định trước khi phân phối kiểm duyệt khác nhau giữa các nhóm đã biết.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
