"""Merge calculator status keys; executed by the shared-dictionary owner."""
import json
from pathlib import Path
keys = ['no_data', 'loaded', 'variable', 'outputs', 'hint8', 'metabolic']
rows = {
'en': ['No data file is open.', 'Loaded %s: %s variables, %s rows.', 'Calculated %s for %s rows. The variable is available in analysis menus.', 'Calculated %s for %s rows. The variables are available in analysis menus.', 'Calculated %s for %s rows. Missing/invalid item rows: %s. The score variable is available in analysis menus.', 'Calculated metabolic_count and metabolic_syndrome for %s rows. Metabolic syndrome: %s. Missing diagnosis: %s. The variables are available in analysis menus.'],
'ko': ['열린 데이터 파일이 없습니다.', '%s 불러옴: 변수 %s개, %s행.', '%s 계산 완료: %s행. 분석 메뉴에서 이 변수를 사용할 수 있습니다.', '%s 계산 완료: %s행. 분석 메뉴에서 이 변수들을 사용할 수 있습니다.', '%s 계산 완료: %s행. 문항 결측/유효하지 않은 행: %s개. 분석 메뉴에서 점수 변수를 사용할 수 있습니다.', '%s행의 metabolic_count 및 metabolic_syndrome 계산 완료. 대사증후군: %s명. 진단 결측: %s명. 분석 메뉴에서 이 변수들을 사용할 수 있습니다.'],
'ja': ['データファイルが開かれていません。', '%sを読み込みました：%s変数、%s行。', '%sを%s行について計算しました。分析メニューでこの変数を使用できます。', '%sを%s行について計算しました。分析メニューでこれらの変数を使用できます。', '%sを%s行について計算しました。項目が欠測または無効な行：%s。分析メニューで得点変数を使用できます。', '%s行のmetabolic_countとmetabolic_syndromeを計算しました。メタボリックシンドローム：%s人。診断欠測：%s人。分析メニューでこれらの変数を使用できます。'],
'zh': ['尚未打开数据文件。', '已加载%s：%s个变量，%s行。', '已为%s计算%s行。可在分析菜单中使用此变量。', '已为%s计算%s行。可在分析菜单中使用这些变量。', '已为%s计算%s行。条目缺失或无效的行数：%s。可在分析菜单中使用得分变量。', '已为%s行计算metabolic_count和metabolic_syndrome。代谢综合征：%s人。诊断缺失：%s人。可在分析菜单中使用这些变量。'],
'es': ['No hay ningún archivo de datos abierto.', 'Se cargó %s: %s variables, %s filas.', 'Se calculó %s para %s filas. La variable está disponible en los menús de análisis.', 'Se calculó %s para %s filas. Las variables están disponibles en los menús de análisis.', 'Se calculó %s para %s filas. Filas con ítems ausentes o no válidos: %s. La variable de puntuación está disponible en los menús de análisis.', 'Se calcularon metabolic_count y metabolic_syndrome para %s filas. Síndrome metabólico: %s. Diagnóstico ausente: %s. Las variables están disponibles en los menús de análisis.'],
'fr': ['Aucun fichier de données n’est ouvert.', '%s chargé : %s variables, %s lignes.', '%s calculé pour %s lignes. La variable est disponible dans les menus d’analyse.', '%s calculé pour %s lignes. Les variables sont disponibles dans les menus d’analyse.', '%s calculé pour %s lignes. Lignes avec items manquants ou non valides : %s. La variable de score est disponible dans les menus d’analyse.', 'metabolic_count et metabolic_syndrome calculés pour %s lignes. Syndrome métabolique : %s. Diagnostic manquant : %s. Les variables sont disponibles dans les menus d’analyse.'],
'de': ['Keine Datendatei ist geöffnet.', '%s geladen: %s Variablen, %s Zeilen.', '%s für %s Zeilen berechnet. Die Variable ist in den Analysemenüs verfügbar.', '%s für %s Zeilen berechnet. Die Variablen sind in den Analysemenüs verfügbar.', '%s für %s Zeilen berechnet. Zeilen mit fehlenden oder ungültigen Items: %s. Die Scorevariable ist in den Analysemenüs verfügbar.', 'metabolic_count und metabolic_syndrome für %s Zeilen berechnet. Metabolisches Syndrom: %s. Fehlende Diagnose: %s. Die Variablen sind in den Analysemenüs verfügbar.'],
'vi': ['Chưa mở tệp dữ liệu nào.', 'Đã tải %s: %s biến, %s hàng.', 'Đã tính %s cho %s hàng. Có thể sử dụng biến này trong các menu phân tích.', 'Đã tính %s cho %s hàng. Có thể sử dụng các biến này trong các menu phân tích.', 'Đã tính %s cho %s hàng. Số hàng có mục bị thiếu hoặc không hợp lệ: %s. Có thể sử dụng biến điểm trong các menu phân tích.', 'Đã tính metabolic_count và metabolic_syndrome cho %s hàng. Hội chứng chuyển hóa: %s. Thiếu chẩn đoán: %s. Có thể sử dụng các biến này trong các menu phân tích.'],
}
for lang, values in rows.items():
    path = Path('i18n') / (lang + '.json')
    data = json.loads(path.read_text(encoding='utf-8'))
    data['translations'].update({'calculator.status.'+key: value for key,value in zip(keys, values)})
    path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
