"""GEE/GLMM/LMM formula prose; preserve source expressions."""
import json
from pathlib import Path
keys='gee_binary gee_supplied gee_change gee_parameter gee_means glmm_binary glmm_count glmm_gaussian lmm_spss lmm_glimmpse lmm_simple'.split()
en=["Cohen's h = 2 asin(sqrt(p1)) - 2 asin(sqrt(p2)); planning effect = h / sqrt(design effect).","Uses supplied Cohen's d.","Cohen's d = [(post - pre) group 1 - (post - pre) group 2] / common outcome SD.","Cohen's d = GEE group x time parameter estimate B / common outcome SD.","Cohen's d = (estimated mean group 1 - estimated mean group 2) / common outcome SD.","Binary logit GLMM: log(OR) = B, OR = exp(B), approximate latent-scale d = log(OR) * sqrt(3) / pi. For probabilities, odds ratio and Cohen's h are both reported.","Count GLMM with log link: log(IRR) = B, IRR = exp(B). For rates, rate ratio = rate1 / rate2.","Gaussian identity-link mixed model: Cohen's d = fixed-effect coefficient B / residual SD.","Omnibus partial eta squared = F * df_effect / (F * df_effect + df_error). Optional pairwise Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).","Standardized change effect = last-minus-first mean contrast / residual SD; planning effect = d * sqrt(m / design effect).","Repeated-measures planning effect = standardized fixed effect * sqrt(m / [1 + (m - 1)ICC])."]
# Mathematical variable names remain identical to the original explanation.
expr=["Cohen's h = 2 asin(sqrt(p1)) - 2 asin(sqrt(p2))",'',"Cohen's d = [(post - pre) group 1 - (post - pre) group 2] / common outcome SD","Cohen's d = GEE group x time parameter estimate B / common outcome SD","Cohen's d = (estimated mean group 1 - estimated mean group 2) / common outcome SD",'log(OR) = B, OR = exp(B)','log(IRR) = B, IRR = exp(B)',"Cohen's d = fixed-effect coefficient B / residual SD",'F * df_effect / (F * df_effect + df_error)','last-minus-first mean contrast / residual SD','standardized fixed effect * sqrt(m / [1 + (m - 1)ICC])']
rows={'en':en,
'ko':[f'{expr[0]}; 설계용 효과크기 = h / sqrt(design effect).',"입력한 Cohen's d를 사용합니다.",f'변화량 대비: {expr[2]}.',f'집단×시점 모수 추정값의 표준화: {expr[3]}.',f'추정평균 대비: {expr[4]}.',f"이분형 로짓 GLMM: {expr[5]}, 잠재척도 근사 d = log(OR) * sqrt(3) / pi. 확률을 입력하면 오즈비와 Cohen's h를 모두 보고합니다.",f'로그 연결 계수형 GLMM: {expr[6]}. 발생률의 경우 발생률비 = rate1 / rate2.',f'정규분포 항등 연결 혼합모형: {expr[7]}.',f"전체 검정의 부분 에타제곱 = {expr[8]}. 선택적 쌍별 비교의 Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).",f'표준화 변화 효과 = {expr[9]}; 설계용 효과크기 = d * sqrt(m / design effect).',f'반복측정 설계용 효과크기 = {expr[10]}.'],
'ja':[f'{expr[0]}; 計画用効果量 = h / sqrt(design effect)。',"入力されたCohen's dを使用します。",f'変化量の対比：{expr[2]}。',f'群×時点パラメータ推定値の標準化：{expr[3]}。',f'推定平均の対比：{expr[4]}。',f"二値ロジットGLMM：{expr[5]}、潜在尺度の近似d = log(OR) * sqrt(3) / pi。確率の場合はオッズ比とCohen's hを報告します。",f'対数リンクのカウントGLMM：{expr[6]}。発生率の場合、発生率比 = rate1 / rate2。',f'正規分布・恒等リンクの混合モデル：{expr[7]}。',f"全体検定の偏イータ二乗 = {expr[8]}。任意のペア比較のCohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij)。",f'標準化変化効果 = {expr[9]}; 計画用効果量 = d * sqrt(m / design effect)。',f'反復測定の計画用効果量 = {expr[10]}。'],
'zh':[f'{expr[0]}; 设计用效应量 = h / sqrt(design effect)。',"使用输入的Cohen's d。",f'变化量对比：{expr[2]}。',f'组别×时间参数估计值标准化：{expr[3]}。',f'估计均值对比：{expr[4]}。',f"二项logit GLMM：{expr[5]}，潜在尺度近似d = log(OR) * sqrt(3) / pi。输入概率时，同时报告优势比和Cohen's h。",f'对数连接计数GLMM：{expr[6]}。对于发生率，发生率比 = rate1 / rate2。',f'正态分布恒等连接混合模型：{expr[7]}。',f"整体检验偏η平方 = {expr[8]}。可选两两比较的Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij)。",f'标准化变化效应 = {expr[9]}; 设计用效应量 = d * sqrt(m / design effect)。',f'重复测量设计用效应量 = {expr[10]}。'],
'es':[f'{expr[0]}; efecto para planificación = h / sqrt(design effect).',"Se usa el d de Cohen proporcionado.",f'Contraste de cambios: {expr[2]}.',f'Estandarización del parámetro grupo × tiempo: {expr[3]}.',f'Contraste de medias estimadas: {expr[4]}.',f"GLMM logit binario: {expr[5]}, d aproximado en escala latente = log(OR) * sqrt(3) / pi. Para probabilidades, se informan la razón de momios y h de Cohen.",f'GLMM de conteo con enlace log: {expr[6]}. Para tasas, razón de tasas = rate1 / rate2.',f'Modelo mixto gaussiano con enlace identidad: {expr[7]}.',f"Eta cuadrado parcial global = {expr[8]}. Comparación por pares opcional: Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).",f'Efecto de cambio estandarizado = {expr[9]}; efecto para planificación = d * sqrt(m / design effect).',f'Efecto para planificar medidas repetidas = {expr[10]}.'],
'fr':[f'{expr[0]}; effet de planification = h / sqrt(design effect).',"Le d de Cohen fourni est utilisé.",f'Contraste des changements : {expr[2]}.',f'Standardisation du paramètre groupe × temps : {expr[3]}.',f'Contraste des moyennes estimées : {expr[4]}.',f"GLMM logit binaire : {expr[5]}, d approximatif sur l’échelle latente = log(OR) * sqrt(3) / pi. Pour les probabilités, le rapport des cotes et le h de Cohen sont présentés.",f'GLMM de comptage avec lien logarithmique : {expr[6]}. Pour les taux, rapport des taux = rate1 / rate2.',f'Modèle mixte gaussien avec lien identité : {expr[7]}.',f"Êta carré partiel global = {expr[8]}. Comparaison par paires facultative : Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).",f'Effet de changement standardisé = {expr[9]}; effet de planification = d * sqrt(m / design effect).',f'Effet pour planifier des mesures répétées = {expr[10]}.'],
'de':[f'{expr[0]}; Planungseffekt = h / sqrt(design effect).',"Das eingegebene Cohens d wird verwendet.",f'Änderungskontrast: {expr[2]}.',f'Standardisierung des Gruppe-×-Zeit-Parameters: {expr[3]}.',f'Kontrast geschätzter Mittelwerte: {expr[4]}.',f'Binäres Logit-GLMM: {expr[5]}, approximatives d auf latenter Skala = log(OR) * sqrt(3) / pi. Bei Wahrscheinlichkeiten werden Odds Ratio und Cohens h berichtet.',f'Zählwert-GLMM mit Log-Link: {expr[6]}. Bei Raten gilt Ratenverhältnis = rate1 / rate2.',f'Gaußsches gemischtes Modell mit Identitätslink: {expr[7]}.',f"Globales partielles Eta-Quadrat = {expr[8]}. Optionaler paarweiser Vergleich: Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).",f'Standardisierter Änderungseffekt = {expr[9]}; Planungseffekt = d * sqrt(m / design effect).',f'Planungseffekt für Messwiederholungen = {expr[10]}.'],
'vi':[f'{expr[0]}; hiệu ứng dùng để lập kế hoạch = h / sqrt(design effect).',"Sử dụng d của Cohen đã nhập.",f'Tương phản thay đổi: {expr[2]}.',f'Chuẩn hóa ước lượng tham số nhóm × thời điểm: {expr[3]}.',f'Tương phản trung bình ước lượng: {expr[4]}.',f'GLMM logit nhị phân: {expr[5]}, d xấp xỉ trên thang tiềm ẩn = log(OR) * sqrt(3) / pi. Với xác suất, báo cáo cả tỷ số odds và h của Cohen.',f'GLMM dữ liệu đếm với liên kết log: {expr[6]}. Với tỷ suất, tỷ số tỷ suất = rate1 / rate2.',f'Mô hình hỗn hợp Gaussian với liên kết đồng nhất: {expr[7]}.',f"Eta bình phương riêng phần tổng thể = {expr[8]}. So sánh từng cặp tùy chọn: Cohen's dz = mean difference / sqrt(Var_i + Var_j - 2Cov_ij).",f'Hiệu ứng thay đổi chuẩn hóa = {expr[9]}; hiệu ứng dùng để lập kế hoạch = d * sqrt(m / design effect).',f'Hiệu ứng dùng để lập kế hoạch đo lặp = {expr[10]}.']}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+key:value for key,value in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
