import json,re
from pathlib import Path
rows='''Survival sparse evidence Influential coefficient rows =|影響度の検討対象となる係数行数 =|需审查影响的系数行数 =|Filas de coeficientes influyentes =|Lignes de coefficients influents =|Zeilen mit einflussreichen Koeffizienten =|Số hàng hệ số có ảnh hưởng =
Survival sparse evidence No events in strata:|イベントがない層:|无事件的层：|Estratos sin eventos:|Strates sans événement :|Strata ohne Ereignisse:|Các tầng không có biến cố:
Survival sparse evidence Fewer than 5 events in strata:|イベントが5件未満の層:|事件少于5例的层：|Estratos con menos de 5 eventos:|Strates avec moins de 5 événements :|Strata mit weniger als 5 Ereignissen:|Các tầng có dưới 5 biến cố:
Review rows exceeding the heuristic standardized DFBETAS threshold in sensitivity analyses.|標準化DFBETASが経験的な閾値を超える行を感度分析で検討してください。|在敏感性分析中审查标准化DFBETAS超过经验阈值的行。|Revise en los análisis de sensibilidad las filas que superen el umbral heurístico de DFBETAS estandarizados.|Examinez dans les analyses de sensibilité les lignes dépassant le seuil heuristique des DFBETAS standardisés.|Prüfen Sie in Sensitivitätsanalysen die Zeilen, die den heuristischen Schwellenwert standardisierter DFBETAS überschreiten.|Xem xét các hàng vượt ngưỡng kinh nghiệm của DFBETAS chuẩn hóa trong phân tích độ nhạy.
Review baseline-hazard estimation and partial-likelihood contribution for event-free strata and limit interpretation.|イベントがない層について、ベースラインハザードの推定と部分尤度への寄与を検討し、解釈を限定してください。|审查无事件层的基线风险估计和部分似然贡献，并限制解释。|Revise la estimación del riesgo basal y la contribución a la verosimilitud parcial de los estratos sin eventos y limite la interpretación.|Examinez l’estimation du risque de base et la contribution à la vraisemblance partielle des strates sans événement et limitez l’interprétation.|Prüfen Sie die Schätzung der Baseline-Hazard und den Beitrag zur partiellen Likelihood für ereignisfreie Strata und schränken Sie die Interpretation ein.|Xem xét ước lượng nguy cơ nền và đóng góp vào hợp lý riêng phần của các tầng không có biến cố, đồng thời giới hạn diễn giải.
Review coefficient and stratum-specific baseline-hazard instability in sparse-event strata.|イベントが少ない層では、係数と層別ベースラインハザードの不安定性を検討してください。|审查事件稀少层中系数和层特异性基线风险的不稳定性。|Revise la inestabilidad de los coeficientes y del riesgo basal específico de cada estrato en los estratos con pocos eventos.|Examinez l’instabilité des coefficients et du risque de base propre à chaque strate dans les strates avec peu d’événements.|Prüfen Sie die Instabilität der Koeffizienten und der stratumsspezifischen Baseline-Hazard in Strata mit wenigen Ereignissen.|Xem xét tính không ổn định của hệ số và nguy cơ nền riêng theo tầng trong các tầng có ít biến cố.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
