import json,re
from pathlib import Path
rows='''Passed|通過|通过|Superado|Validé|Bestanden|Đạt
Identical indicators and model specification|同一の指標とモデル指定|相同的指标与模型设定|Indicadores y especificación del modelo idénticos|Indicateurs et spécification du modèle identiques|Identische Indikatoren und Modellspezifikation|Chỉ báo và đặc tả mô hình giống nhau
Identical missing-data and standardization treatment|同一の欠測データ処理と標準化|相同的缺失数据处理与标准化|Tratamiento de datos faltantes y estandarización idénticos|Traitement des données manquantes et standardisation identiques|Identische Behandlung fehlender Daten und Standardisierung|Xử lý dữ liệu thiếu và chuẩn hóa giống nhau
Identical PLS algorithm and settings|同一のPLSアルゴリズムと設定|相同的PLS算法与设置|Algoritmo y configuración PLS idénticos|Algorithme et paramètres PLS identiques|Identischer PLS-Algorithmus und identische Einstellungen|Thuật toán và thiết lập PLS giống nhau
One shared canvas snapshot supplies %s constructs and %s indicators to every group fit.|共通のキャンバススナップショットが、各集団の適合に%s個の構成概念と%s個の指標を提供します。|同一画布快照为每组拟合提供%s个构念和%s个指标。|Una misma instantánea del lienzo proporciona %s constructos y %s indicadores para el ajuste de cada grupo.|Un même instantané du canevas fournit %s construits et %s indicateurs pour l’ajustement de chaque groupe.|Ein gemeinsamer Canvas-Snapshot liefert %s Konstrukte und %s Indikatoren für jede Gruppenanpassung.|Một ảnh chụp trạng thái sơ đồ chung cung cấp %s cấu trúc và %s chỉ báo cho việc ước lượng từng nhóm.
Every pair uses seminr::mean_replacement in group and pooled fits; the pair-pooled mean and SD define the common Step 2/3 score scale.|各集団対は集団別および統合適合でseminr::mean_replacementを使用します。集団対を統合した平均とSDが、ステップ2・3の共通スコア尺度を定義します。|每个组对在组内及合并拟合中使用seminr::mean_replacement；组对合并数据的均值和SD定义第2、3步的共同得分尺度。|Cada par utiliza seminr::mean_replacement en los ajustes de grupo y combinados; la media y la SD combinadas del par definen la escala común de puntuación de los pasos 2 y 3.|Chaque paire utilise seminr::mean_replacement pour les ajustements par groupe et regroupés ; la moyenne et l’écart-type (SD) regroupés de la paire définissent l’échelle commune des scores des étapes 2 et 3.|Jedes Paar verwendet seminr::mean_replacement in Gruppen- und gepoolten Anpassungen; der gepoolte Mittelwert und die SD des Paars definieren die gemeinsame Skala der Werte in Schritt 2 und 3.|Mỗi cặp dùng seminr::mean_replacement khi ước lượng theo nhóm và gộp; trung bình và SD gộp của cặp xác định thang điểm chung ở bước 2 và 3.
Every fit uses run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS') with the shared production settings.|すべての適合は、共通の実行設定でrun_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS')を使用します。|每次拟合均采用共同运行设置，调用run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS')。|Todos los ajustes utilizan run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS') con la configuración de ejecución compartida.|Tous les ajustements utilisent run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS') avec les paramètres d’exécution communs.|Jede Anpassung verwendet run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS') mit den gemeinsamen Ausführungseinstellungen.|Mỗi lần ước lượng dùng run_structural_canvas_analysis(..., analysis_type='plssem', estimator='PLS') với các thiết lập thực thi chung.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7 and f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
