"""Proportion/chi-square/correlation method prose; formulas retained."""
import json
from pathlib import Path
keys='note_proportion_transform note_w_categories note_phi note_w_planning note_point_biserial note_pearson note_cohens_q note_r_squared note_r_f'.split()
rows={
'en':["Proportion effect sizes are calculated from two proportions; Cohen's h uses the arcsine-square-root transformation.","Cohen's w is calculated from observed and expected category proportions.","Phi = sqrt(chi-square / N); for a 2x2 table, phi equals Cohen's w.","Cohen's w = sqrt(chi-square / N) for goodness-of-fit or contingency chi-square effect-size planning.","For a two-group contrast, point-biserial r can be converted to Cohen's d as d = 2r / sqrt(1 - r^2).","Pearson r is reported directly; Fisher's z = atanh(r).","Cohen's q is the difference between two Fisher-z transformed correlations.","For a single predictor, r = sqrt(R-squared); the sign is not identifiable from R-squared alone.","For a one-degree-of-freedom effect, r = sqrt(F / [F + df_error])."],
'ko':["비율 효과크기는 두 비율에서 계산합니다; Cohen의 h는 제곱근-아크사인 변환을 사용합니다.","Cohen의 w는 관측 및 기대 범주 비율에서 계산합니다.","Phi = sqrt(chi-square / N); 2x2 표에서 phi는 Cohen의 w와 같습니다.","적합도 또는 분할표 카이제곱 효과크기 계획에서 Cohen's w = sqrt(chi-square / N)입니다.","두 집단 대비에서 점이연 상관 r을 Cohen의 d로 변환할 수 있습니다: d = 2r / sqrt(1 - r^2).","Pearson r을 직접 보고합니다; Fisher's z = atanh(r).","Cohen의 q는 Fisher z로 변환한 두 상관계수의 차이입니다.","예측변수가 하나이면 r = sqrt(R-squared)입니다; R제곱만으로 부호를 알 수는 없습니다.","자유도 1인 효과에서 r = sqrt(F / [F + df_error])입니다."],
'ja':["比率の効果量は2つの比率から計算します; Cohenのhには平方根・逆正弦変換を使用します。","Cohenのwは観測されたカテゴリ比率と期待比率から計算します。","Phi = sqrt(chi-square / N); 2x2表ではphiはCohenのwと等しくなります。","適合度または分割表のカイ二乗効果量の計画ではCohen's w = sqrt(chi-square / N)です。","2群の対比では点双列相関rをCohenのdに変換できます：d = 2r / sqrt(1 - r^2)。","Pearson rを直接報告します; Fisher's z = atanh(r)。","CohenのqはFisher zに変換した2つの相関の差です。","予測変数が1つの場合、r = sqrt(R-squared)です; R二乗だけでは符号を特定できません。","自由度1の効果ではr = sqrt(F / [F + df_error])です。"],
'zh':["比例效应量根据两个比例计算; Cohen h使用反正弦平方根变换。","Cohen w根据观测和期望类别比例计算。","Phi = sqrt(chi-square / N); 对2x2表，phi等于Cohen w。","适合度或列联表卡方效应量规划中，Cohen's w = sqrt(chi-square / N)。","两组对比中，可将点二列相关r转换为Cohen d：d = 2r / sqrt(1 - r^2)。","直接报告Pearson r; Fisher's z = atanh(r)。","Cohen q是两个经Fisher z变换的相关系数之差。","单个预测变量时，r = sqrt(R-squared); 仅凭R平方无法确定符号。","自由度为1的效应中，r = sqrt(F / [F + df_error])。"],
'es':["Los tamaños del efecto de proporciones se calculan a partir de dos proporciones; h de Cohen usa la transformación arcoseno de la raíz cuadrada.","La w de Cohen se calcula a partir de las proporciones observadas y esperadas de las categorías.","Phi = sqrt(chi-square / N); en una tabla 2x2, phi equivale a w de Cohen.","Para planificar el efecto chi-cuadrado de bondad de ajuste o contingencia, Cohen's w = sqrt(chi-square / N).","En un contraste de dos grupos, r biserial puntual puede convertirse a d de Cohen: d = 2r / sqrt(1 - r^2).","Se informa directamente r de Pearson; Fisher's z = atanh(r).","La q de Cohen es la diferencia entre dos correlaciones transformadas a z de Fisher.","Para un solo predictor, r = sqrt(R-squared); el signo no puede identificarse únicamente a partir de R cuadrado.","Para un efecto de un grado de libertad, r = sqrt(F / [F + df_error])."],
'fr':["Les tailles d’effet de proportions sont calculées à partir de deux proportions; le h de Cohen utilise la transformation arcsinus de la racine carrée.","Le w de Cohen est calculé à partir des proportions observées et attendues des catégories.","Phi = sqrt(chi-square / N); pour un tableau 2x2, phi est égal au w de Cohen.","Pour planifier la taille d’effet d’un chi-deux d’ajustement ou de contingence, Cohen's w = sqrt(chi-square / N).","Pour un contraste à deux groupes, le r point-bisérial peut être converti en d de Cohen : d = 2r / sqrt(1 - r^2).","Le r de Pearson est rapporté directement; Fisher's z = atanh(r).","Le q de Cohen est la différence entre deux corrélations transformées en z de Fisher.","Pour un seul prédicteur, r = sqrt(R-squared); le signe ne peut pas être déterminé à partir du seul R carré.","Pour un effet à un degré de liberté, r = sqrt(F / [F + df_error])."],
'de':["Anteils-Effektgrößen werden aus zwei Anteilen berechnet; Cohens h verwendet die Arkussinus-Wurzel-Transformation.","Cohens w wird aus beobachteten und erwarteten Kategorieanteilen berechnet.","Phi = sqrt(chi-square / N); bei einer 2x2-Tabelle entspricht Phi Cohens w.","Für die Effektgrößenplanung von Anpassungs- oder Kontingenz-Chi-Quadrat-Tests gilt Cohen's w = sqrt(chi-square / N).","Bei einem Zweigruppenkontrast lässt sich das punktbiseriale r in Cohens d umrechnen: d = 2r / sqrt(1 - r^2).","Pearsons r wird direkt berichtet; Fisher's z = atanh(r).","Cohens q ist die Differenz zweier Fisher-z-transformierter Korrelationen.","Bei einem einzelnen Prädiktor gilt r = sqrt(R-squared); das Vorzeichen lässt sich allein aus R-Quadrat nicht bestimmen.","Für einen Effekt mit einem Freiheitsgrad gilt r = sqrt(F / [F + df_error])."],
'vi':["Kích thước hiệu ứng tỷ lệ được tính từ hai tỷ lệ; h của Cohen dùng phép biến đổi arcsin căn bậc hai.","w của Cohen được tính từ tỷ lệ quan sát và kỳ vọng của các nhóm.","Phi = sqrt(chi-square / N); với bảng 2x2, phi bằng w của Cohen.","Khi lập kế hoạch hiệu ứng chi bình phương về độ phù hợp hoặc bảng chéo, Cohen's w = sqrt(chi-square / N).","Trong tương phản hai nhóm, có thể đổi tương quan điểm nhị phân r thành d của Cohen: d = 2r / sqrt(1 - r^2).","Báo cáo trực tiếp r của Pearson; Fisher's z = atanh(r).","q của Cohen là chênh lệch giữa hai tương quan đã biến đổi z của Fisher.","Với một biến dự báo, r = sqrt(R-squared); không thể xác định dấu chỉ từ R bình phương.","Với hiệu ứng có một bậc tự do, r = sqrt(F / [F + df_error])."]}
for lang,values in rows.items():
 assert len(values)==len(keys)
 path=Path('i18n')/(lang+'.json');data=json.loads(path.read_text(encoding='utf-8'))
 data['translations'].update({'sample_size.result.'+k:v for k,v in zip(keys,values)})
 path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
