import json,re
from pathlib import Path
rows='''Causal-interpretation boundary|인과해석 경계|因果解釈の限界|因果解释边界|Límites de la interpretación causal|Limites de l’interprétation causale|Grenzen der kausalen Interpretation|Giới hạn diễn giải nhân quả
This analysis does not establish causal identification. Interpret path coefficients and indirect effects as theory-directed statistical associations. Significant coefficients, bootstrap intervals, or good fit alone do not establish causality or temporal precedence.|현재 분석은 인과식별을 확립하지 않으므로 경로계수와 간접효과를 이론에 의해 방향을 정한 통계적 연관으로 해석하십시오. 유의한 계수, bootstrap 신뢰구간 또는 좋은 적합도만으로 인과성이나 시간적 선행성이 성립하지 않습니다.|この分析は因果識別を確立しません。パス係数と間接効果は、理論で方向を定めた統計的関連として解釈してください。有意な係数、ブートストラップ区間、良好な適合度だけでは因果性や時間的先行性は確立しません。|本分析不建立因果识别。请将路径系数和间接效应解释为理论指定方向的统计关联。仅凭显著系数、自助法区间或良好拟合不能确立因果关系或时间先后。|Este análisis no establece identificación causal. Interprete los coeficientes de ruta y efectos indirectos como asociaciones estadísticas orientadas por la teoría. Los coeficientes significativos, intervalos bootstrap o buen ajuste por sí solos no establecen causalidad ni precedencia temporal.|Cette analyse n’établit pas l’identification causale. Interprétez les coefficients de chemin et effets indirects comme des associations statistiques orientées par la théorie. Des coefficients significatifs, intervalles bootstrap ou un bon ajustement ne suffisent pas à établir causalité ou antériorité temporelle.|Diese Analyse stellt keine kausale Identifikation her. Interpretieren Sie Pfadkoeffizienten und indirekte Effekte als theoretisch gerichtete statistische Zusammenhänge. Signifikante Koeffizienten, Bootstrap-Intervalle oder gute Anpassung allein belegen weder Kausalität noch zeitliche Vorrangigkeit.|Phân tích này không xác lập nhận dạng nhân quả. Diễn giải hệ số đường dẫn và tác động gián tiếp như liên hệ thống kê được lý thuyết định hướng. Chỉ riêng hệ số có ý nghĩa, khoảng bootstrap hoặc độ phù hợp tốt không xác lập quan hệ nhân quả hay thứ tự thời gian.
Assumption|인과식별 가정|因果識別の仮定|因果识别假设|Supuesto de identificación causal|Hypothèse d’identification causale|Annahme zur kausalen Identifikation|Giả định nhận dạng nhân quả
Recorded|현재 기록|現在の記録|当前记录|Registro actual|État consigné|Aktueller Nachweis|Ghi nhận hiện tại
Consequence|보고상 제한|報告上の制約|报告限制|Limitación del informe|Limite du rapport|Einschränkung der Berichterstattung|Giới hạn báo cáo
Temporal ordering / study design|시간적 순서 / 연구 설계|時間的順序／研究デザイン|时间顺序／研究设计|Orden temporal / diseño del estudio|Ordre temporel / plan d’étude|Zeitliche Reihenfolge / Studiendesign|Thứ tự thời gian / thiết kế nghiên cứu
No unmeasured exposure-outcome confounding|측정하지 않은 노출-결과 교란이 없음|未測定の曝露・結果間交絡がない|无未测量的暴露与结果混杂|Ausencia de confusión no medida entre exposición y resultado|Absence de confusion non mesurée entre exposition et résultat|Keine ungemessene Konfundierung zwischen Exposition und Ergebnis|Không có nhiễu chưa đo giữa phơi nhiễm và kết quả
Causal treatment/exposure identification|처치·노출의 인과효과 식별|処置・曝露の因果識別|处理／暴露的因果识别|Identificación causal del tratamiento/exposición|Identification causale du traitement/de l’exposition|Kausale Identifikation von Behandlung/Exposition|Nhận dạng nhân quả của can thiệp/phơi nhiễm
Sequential ignorability for mediation|매개효과의 순차적 무교란 가정|媒介効果の逐次無交絡仮定|中介效应的序贯可忽略性|Ignorabilidad secuencial para la mediación|Ignorabilité séquentielle pour la médiation|Sequenzielle Ignorierbarkeit für Mediation|Giả định không nhiễu tuần tự cho trung gian
Not collected by this workflow|이 분석 절차에서 수집하지 않음|この分析手順では収集しない|本分析流程未收集|No recogido en este flujo de análisis|Non recueilli par cette procédure|In diesem Ablauf nicht erhoben|Không được thu thập trong quy trình này
Not established by SEM fit|SEM 적합도로 확립되지 않음|SEM適合度では確立しない|SEM拟合不能确立|No establecido por el ajuste SEM|Non établi par l’ajustement SEM|Durch SEM-Anpassung nicht belegt|Không được xác lập bởi độ phù hợp SEM
Not established by directed paths|방향성 경로로 확립되지 않음|有向パスでは確立しない|有向路径不能确立|No establecido por las rutas dirigidas|Non établi par les chemins orientés|Durch gerichtete Pfade nicht belegt|Không được xác lập bởi đường dẫn có hướng
Not established; indirect chain detected|확립되지 않음; 간접 경로가 확인됨|未確立；間接経路を検出|未确立；检测到间接路径|No establecido; se detectó una cadena indirecta|Non établi ; chaîne indirecte détectée|Nicht belegt; indirekte Kette erkannt|Chưa xác lập; phát hiện chuỗi gián tiếp
Not assessed; no indirect chain detected|평가하지 않음; 간접 경로가 확인되지 않음|未評価；間接経路なし|未评估；未检测到间接路径|No evaluado; no se detectó cadena indirecta|Non évalué ; aucune chaîne indirecte détectée|Nicht bewertet; keine indirekte Kette erkannt|Chưa đánh giá; không phát hiện chuỗi gián tiếp
Do not infer temporal or causal direction from path arrows alone.|경로 화살표만으로 시간적·인과적 방향을 추론하지 마십시오.|パスの矢印だけから時間的・因果的方向を推論しないでください。|不要仅凭路径箭头推断时间或因果方向。|No infiera dirección temporal ni causal solo a partir de las flechas.|N’inférez pas de direction temporelle ou causale à partir des seules flèches.|Leiten Sie zeitliche oder kausale Richtung nicht allein aus Pfadpfeilen ab.|Không suy ra hướng thời gian hoặc nhân quả chỉ từ mũi tên đường dẫn.
Fit indices, bootstrap intervals, and significant coefficients do not remove confounding bias.|적합도 지수, 부트스트랩 구간과 유의한 계수가 교란 편향을 제거하지는 않습니다.|適合度指標、ブートストラップ区間、有意な係数は交絡バイアスを除去しません。|拟合指标、自助法区间和显著系数不能消除混杂偏倚。|Los índices de ajuste, intervalos bootstrap y coeficientes significativos no eliminan el sesgo de confusión.|Les indices d’ajustement, intervalles bootstrap et coefficients significatifs n’éliminent pas le biais de confusion.|Anpassungsindizes, Bootstrap-Intervalle und signifikante Koeffizienten beseitigen keine Konfundierungsverzerrung.|Chỉ số phù hợp, khoảng bootstrap và hệ số có ý nghĩa không loại bỏ sai lệch do nhiễu.
Report coefficients as theory-directed associations unless identification is justified externally.|외부 근거로 인과식별을 정당화하지 않는 한 계수는 이론에 의해 방향을 정한 연관으로 보고하십시오.|外部の根拠で識別を正当化しない限り、係数は理論で方向を定めた関連として報告してください。|除非有外部依据支持因果识别，否则将系数报告为理论指定方向的关联。|Informe los coeficientes como asociaciones orientadas por la teoría, salvo que la identificación se justifique externamente.|Rapportez les coefficients comme des associations orientées par la théorie, sauf justification externe de l’identification.|Berichten Sie Koeffizienten als theoretisch gerichtete Zusammenhänge, sofern die Identifikation nicht extern begründet ist.|Báo cáo hệ số như liên hệ được lý thuyết định hướng, trừ khi nhận dạng được biện minh bằng căn cứ bên ngoài.
Describe the indirect effect as an associational decomposition unless temporal order and mediator/outcome confounding assumptions are justified.|시간적 순서와 매개변수·결과의 교란 가정을 정당화하지 않는 한 간접효과는 연관의 분해로 설명하십시오.|時間的順序と媒介変数・結果の交絡に関する仮定を正当化しない限り、間接効果は関連の分解として説明してください。|除非时间顺序及中介／结果混杂假设得到支持，否则将间接效应描述为关联分解。|Describa el efecto indirecto como una descomposición de asociaciones, salvo que se justifiquen el orden temporal y los supuestos de confusión del mediador/resultado.|Décrivez l’effet indirect comme une décomposition d’associations, sauf justification de l’ordre temporel et des hypothèses de confusion du médiateur/résultat.|Beschreiben Sie den indirekten Effekt als Zerlegung eines Zusammenhangs, sofern zeitliche Reihenfolge und Konfundierungsannahmen für Mediator/Ergebnis nicht begründet sind.|Mô tả tác động gián tiếp như phân rã liên hệ, trừ khi thứ tự thời gian và giả định về nhiễu của biến trung gian/kết quả được biện minh.
No mediation-specific claim is indicated by the current path graph.|현재 경로도에는 매개효과에 관한 별도 주장을 뒷받침하는 경로가 없습니다.|現在のパス図では媒介効果に特有の主張は示されません。|当前路径图不支持中介效应特定论断。|El diagrama actual no indica ninguna afirmación específica de mediación.|Le diagramme actuel n’indique aucune affirmation spécifique de médiation.|Das aktuelle Pfaddiagramm legt keine mediationsspezifische Aussage nahe.|Sơ đồ đường dẫn hiện tại không chỉ ra kết luận riêng về trung gian.'''
data_rows=[r.split('|') for r in rows.splitlines()]
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],2):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in data_rows:
  assert len(row)==8
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row[0].lower()).strip('_')]=row[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
