import json,re
from pathlib import Path
rows='''Declare observation independence and sampling structure in the Estimation options before analysis: independent cross-sectional, clustered/multilevel, complex survey, or longitudinal/repeated measures.	分析前に推定オプションで観測の独立性と標本構造を指定してください：独立した横断データ、クラスタ・多階層、複雑標本、または縦断・反復測定。	分析前请在估计选项中指定观测独立性和抽样结构：独立横断面、聚类/多层、复杂抽样或纵向/重复测量。	Antes del análisis, declare la independencia de las observaciones y la estructura muestral en las opciones de estimación: transversal independiente, conglomerados/multinivel, encuesta compleja o longitudinal/medidas repetidas.	Avant l’analyse, déclarez l’indépendance des observations et la structure d’échantillonnage dans les options d’estimation : transversale indépendante, en grappes/multiniveau, enquête complexe ou longitudinale/mesures répétées.	Geben Sie vor der Analyse in den Schätzoptionen die Unabhängigkeit der Beobachtungen und die Stichprobenstruktur an: unabhängiger Querschnitt, Cluster/Mehrebenen, komplexe Stichprobe oder Längsschnitt/Messwiederholung.	Trước khi phân tích, khai báo tính độc lập của quan sát và cấu trúc lấy mẫu trong tùy chọn ước lượng: cắt ngang độc lập, cụm/đa cấp, khảo sát phức tạp hoặc dọc/đo lặp.
This canvas engine cannot analyze clustered or multilevel data. Use multilevel SEM or cluster-robust estimation that accounts for cluster dependence.	このキャンバスエンジンではクラスタ・多階層データを分析できません。クラスタ内の依存性を考慮した多階層SEMまたはクラスタ頑健推定を使用してください。	此画布引擎无法分析聚类或多层数据。请使用考虑群内依赖性的多层SEM或聚类稳健估计。	Este motor no puede analizar datos agrupados o multinivel. Use SEM multinivel o estimación robusta por conglomerados que considere la dependencia intragrupo.	Ce moteur ne peut pas analyser les données en grappes ou multiniveaux. Utilisez un SEM multiniveau ou une estimation robuste par grappe tenant compte de la dépendance intragrappe.	Diese Engine kann keine Cluster- oder Mehrebenendaten analysieren. Verwenden Sie Mehrebenen-SEM oder clusterrobuste Schätzung, die Clusterabhängigkeit berücksichtigt.	Bộ máy này không thể phân tích dữ liệu cụm hoặc đa cấp. Hãy dùng SEM đa cấp hoặc ước lượng vững theo cụm có xét sự phụ thuộc trong cụm.
This canvas engine cannot analyze complex survey data. Use survey SEM that accounts for sampling weights, strata, and primary sampling units.	このキャンバスエンジンでは複雑標本データを分析できません。標本重み、層、一次抽出単位を考慮した調査SEMを使用してください。	此画布引擎无法分析复杂抽样数据。请使用考虑抽样权重、分层和初级抽样单位的调查SEM。	Este motor no puede analizar datos de encuestas complejas. Use SEM para encuestas que considere pesos muestrales, estratos y unidades primarias de muestreo.	Ce moteur ne peut pas analyser les données d’enquêtes complexes. Utilisez un SEM pour enquêtes tenant compte des poids, strates et unités primaires d’échantillonnage.	Diese Engine kann keine komplexen Stichprobendaten analysieren. Verwenden Sie Survey-SEM, das Stichprobengewichte, Schichten und primäre Stichprobeneinheiten berücksichtigt.	Bộ máy này không thể phân tích dữ liệu khảo sát phức tạp. Hãy dùng SEM khảo sát có xét trọng số, tầng và đơn vị lấy mẫu sơ cấp.
This canvas engine cannot analyze longitudinal or repeated-measures data. Use longitudinal SEM that accounts for within-person dependence and longitudinal measurement structure.	このキャンバスエンジンでは縦断・反復測定データを分析できません。個人内依存性と縦断測定構造を考慮した縦断SEMを使用してください。	此画布引擎无法分析纵向或重复测量数据。请使用考虑个体内依赖性和纵向测量结构的纵向SEM。	Este motor no puede analizar datos longitudinales o de medidas repetidas. Use SEM longitudinal que considere la dependencia intraindividual y la estructura de medición longitudinal.	Ce moteur ne peut pas analyser les données longitudinales ou à mesures répétées. Utilisez un SEM longitudinal tenant compte de la dépendance intra-individuelle et de la structure de mesure longitudinale.	Diese Engine kann keine Längsschnitt- oder Messwiederholungsdaten analysieren. Verwenden Sie Längsschnitt-SEM, das intraindividuelle Abhängigkeit und longitudinale Messstruktur berücksichtigt.	Bộ máy này không thể phân tích dữ liệu dọc hoặc đo lặp. Hãy dùng SEM dọc có xét sự phụ thuộc trong cá nhân và cấu trúc đo lường dọc.
Analysis was not run because the selected sampling design is unsupported by the current canvas estimation engine.	選択した標本設計は現在のキャンバス推定エンジンで未対応のため、分析を実行しませんでした。	所选抽样设计不受当前画布估计引擎支持，因此未运行分析。	No se ejecutó el análisis porque el motor actual no admite el diseño muestral seleccionado.	L’analyse n’a pas été exécutée car le moteur actuel ne prend pas en charge le plan d’échantillonnage sélectionné.	Die Analyse wurde nicht ausgeführt, da die aktuelle Engine das gewählte Stichprobendesign nicht unterstützt.	Không chạy phân tích vì bộ máy ước lượng hiện tại không hỗ trợ thiết kế lấy mẫu đã chọn.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
