import json,re
from pathlib import Path
rows='''PLS bootstrap status: %s; valid resamples: %s/%s. The minimum reporting ratio is %s%%; CIs and test statistics are suppressed below it.|PLSブートストラップ状態：%s；有効再標本：%s/%s。最低報告割合は%s%%で、未満の場合CIと検定統計量を表示しません。|PLS自助法状态：%s；有效重抽样：%s/%s。最低报告比例为%s%%；低于该值时不显示CI和检验统计量。|Estado bootstrap PLS: %s; remuestras válidas: %s/%s. La proporción mínima es %s%%; por debajo se omiten los IC y estadísticos de prueba.|État du bootstrap PLS : %s ; rééchantillonnages valides : %s/%s. Le ratio minimal est %s%% ; en dessous, les IC et statistiques de test sont masqués.|PLS-Bootstrap-Status: %s; gültige Stichproben: %s/%s. Der Mindestanteil beträgt %s%%; darunter werden KI und Teststatistiken ausgeblendet.|Trạng thái bootstrap PLS: %s; mẫu hợp lệ: %s/%s. Tỷ lệ báo cáo tối thiểu là %s%%; dưới mức này không hiển thị CI và thống kê kiểm định.
Insufficient|不十分|不足|Insuficiente|Insuffisant|Unzureichend|Không đủ
Failed|失敗|失败|Fallido|Échec|Fehlgeschlagen|Thất bại
Canceled|中止|取消|Cancelado|Annulé|Abgebrochen|Đã hủy
Detail: %s|詳細：%s|详情：%s|Detalle: %s|Détail : %s|Detail: %s|Chi tiết: %s'''
data_rows=[r.split('|') for r in rows.splitlines()]
notes='''Construct type, measurement mode|構成概念の種類、測定モード、各指標の証拠としての役割は、本表の数値を簡潔に示すため下の補助表に記載します。|构念类型、测量模式和指标的证据作用列于下方辅助表，以保持主数值表简洁。|El tipo de constructo, modo de medida y papel de la evidencia se presentan en la tabla suplementaria para mantener concisa la tabla numérica principal.|Le type de construit, le mode de mesure et le rôle des éléments probants figurent dans le tableau complémentaire afin de garder le tableau numérique principal concis.|Konstrukttyp, Messmodus und Evidenzrolle stehen in der Ergänzungstabelle, damit die numerische Haupttabelle übersichtlich bleibt.|Loại cấu trúc, chế độ đo lường và vai trò bằng chứng được trình bày trong bảng bổ sung để bảng số liệu chính ngắn gọn.
For a reflective common factor|反映型共通因子の標準PLS信頼性、AVE、HTMTはMode A得点代理変数の診断であり、共分散ベース因子モデルの証拠ではありません。反映型合成変数では合成得点の診断としてのみ解釈します。形成型合成変数に内的一貫性、AVE、HTMTは適用しません。|反映式共同因子的标准PLS信度、AVE和HTMT诊断的是Mode A分数代理变量，而非协方差因子模型的证据。反映式复合变量仅作复合分数诊断解释；形成式复合变量不适用内部一致性、AVE和HTMT。|Para un factor común reflectivo, la fiabilidad PLS estándar, AVE y HTMT diagnostican un sustituto de puntuación Mode A, no aportan evidencia de un modelo factorial basado en covarianzas. En compuestos reflectivos son solo diagnósticos del score compuesto. Consistencia interna, AVE y HTMT no se aplican a compuestos formativos.|Pour un facteur commun réflexif, la fiabilité PLS standard, AVE et HTMT diagnostiquent un score proxy Mode A, sans établir un modèle factoriel fondé sur les covariances. Pour un composite réflexif, ce sont uniquement des diagnostics du score composite. Cohérence interne, AVE et HTMT ne s’appliquent pas aux composites formatifs.|Bei reflektiven gemeinsamen Faktoren diagnostizieren Standard-PLS-Reliabilität, AVE und HTMT einen Mode-A-Score-Proxy; sie liefern keine Evidenz für ein kovarianzbasiertes Faktormodell. Bei reflektiven Kompositen sind sie nur Diagnosen des Kompositscores. Interne Konsistenz, AVE und HTMT gelten nicht für formative Komposite.|Với nhân tố chung phản xạ, độ tin cậy PLS chuẩn, AVE và HTMT chẩn đoán điểm đại diện Mode A, không cung cấp bằng chứng mô hình nhân tố dựa trên hiệp phương sai. Với biến tổng hợp phản xạ, chỉ diễn giải như chẩn đoán điểm tổng hợp. Không áp dụng nhất quán nội tại, AVE và HTMT cho biến tổng hợp cấu thành.
PLS bootstrap columns cover|PLSブートストラップ列は直接パス、総効果・間接効果、HTMT、外部負荷量・重みに対応します。この統計量全体が有限で構造も一致する再標本だけを有効とします。|PLS自助法列涵盖直接路径、总效应和间接效应、HTMT、外部载荷及权重。仅当整套统计量均有限且结构一致时，重抽样才有效。|Las columnas bootstrap PLS cubren rutas directas, efectos totales e indirectos, HTMT, cargas y pesos externos. Una remuestra es válida solo si todo ese conjunto es finito y estructuralmente consistente.|Les colonnes bootstrap PLS couvrent chemins directs, effets totaux et indirects, HTMT, saturations et poids externes. Un rééchantillonnage n’est valide que si cet ensemble complet est fini et structurellement cohérent.|PLS-Bootstrap-Spalten umfassen direkte Pfade, Gesamt- und indirekte Effekte, HTMT, äußere Ladungen und Gewichte. Eine Stichprobe gilt nur als gültig, wenn alle diese Statistiken endlich und strukturell konsistent sind.|Cột bootstrap PLS gồm đường trực tiếp, tổng tác động và tác động gián tiếp, HTMT, tải và trọng số ngoài. Mẫu chỉ hợp lệ khi toàn bộ thống kê này hữu hạn và nhất quán về cấu trúc.'''
s=Path('R/setup_custom_model_canvas_structural_render_validity.R').read_text(encoding='utf-8');sources=re.findall(r'tr\("([^"]+)"',s)
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
