import json,re
from pathlib import Path
rows='''Guide for Table %s: HTMT detailed criteria|表%sのガイド：HTMT詳細基準|表%s指南：HTMT详细标准|Guía de la tabla %s: criterios HTMT detallados|Guide du tableau %s : critères HTMT détaillés|Leitfaden zu Tabelle %s: detaillierte HTMT-Kriterien|Hướng dẫn bảng %s: tiêu chí HTMT chi tiết
Criterion|基準|标准|Criterio|Critère|Kriterium|Tiêu chí
CI method|CI算出法|CI方法|Método del IC|Méthode de l’IC|KI-Methode|Phương pháp KTC
95% CI lower|95% CI 下限|95% CI 下限|95% CI inferior|95% CI inférieure|95% CI Untergrenze|95% CI dưới
95% CI upper|95% CI 上限|95% CI 上限|95% CI superior|95% CI supérieure|95% CI Obergrenze|95% CI trên
Validity-table guide: HTMT detailed criteria|妥当性表ガイド：HTMT詳細基準|效度表指南：HTMT详细标准|Guía de la tabla de validez: criterios HTMT detallados|Guide du tableau de validité : critères HTMT détaillés|Leitfaden zur Validitätstabelle: detaillierte HTMT-Kriterien|Hướng dẫn bảng giá trị: tiêu chí HTMT chi tiết
HTMT %s bootstrap confidence intervals (%s resamples; seed = %s)|HTMT %sブートストラップ信頼区間（再標本%s回；seed = %s）|HTMT %s自助法置信区间（重抽样%s次；seed = %s）|Intervalos bootstrap HTMT %s (%s remuestras; semilla = %s)|Intervalles bootstrap HTMT %s (%s rééchantillonnages ; graine = %s)|HTMT-%s-Bootstrap-Konfidenzintervalle (%s Stichproben; Seed = %s)|Khoảng tin cậy bootstrap HTMT %s (%s mẫu; seed = %s)
Below reference|参考値未満|低于参考值|Por debajo de la referencia|Sous la référence|Unter Referenzwert|Dưới mức tham khảo
Review needed|確認が必要|需要检查|Requiere revisión|Examen nécessaire|Prüfung erforderlich|Cần xem xét
At least two indicators per factor are required|各因子に少なくとも2つの指標が必要です|每个因子至少需要两个指标|Se requieren al menos dos indicadores por factor|Au moins deux indicateurs par facteur sont nécessaires|Mindestens zwei Indikatoren pro Faktor sind erforderlich|Mỗi nhân tố cần ít nhất hai chỉ báo
Cross-loaded indicators prevent standard HTMT calculation|交差負荷指標のため標準HTMTを計算できません|交叉载荷指标导致无法计算标准HTMT|Las cargas cruzadas impiden calcular el HTMT estándar|Les saturations croisées empêchent le calcul HTMT standard|Kreuzladungen verhindern die Standard-HTMT-Berechnung|Chỉ báo tải chéo ngăn tính HTMT chuẩn
Indicator correlations are unavailable|指標相関を利用できません|指标相关不可用|Correlaciones de indicadores no disponibles|Corrélations des indicateurs indisponibles|Indikatorkorrelationen nicht verfügbar|Không có tương quan chỉ báo
Within-factor correlations are insufficient|因子内相関が不十分です|因子内相关不足|Correlaciones intrafactor insuficientes|Corrélations intrafactorielles insuffisantes|Korrelationen innerhalb des Faktors unzureichend|Tương quan trong nhân tố không đủ
BCa unavailable|BCa利用不可|BCa不可用|BCa no disponible|BCa indisponible|BCa nicht verfügbar|BCa không khả dụng
Upper < threshold|上限 < 基準|上限 < 阈值|Superior < umbral|Limite supérieure < seuil|Obergrenze < Schwelle|Cận trên < ngưỡng
Upper < 1|上限 < 1|上限 < 1|Superior < 1|Limite supérieure < 1|Obergrenze < 1|Cận trên < 1
One-sided 95% upper|片側95%上限|单侧95%上限|Límite superior unilateral del 95%|Limite supérieure unilatérale à 95 %|Einseitige 95%-Obergrenze|Cận trên một phía 95%
The %s interval is based on case resampling.|%s区間はケース再標本化に基づきます。|%s区间基于个案重抽样。|El intervalo %s se basa en remuestreo de casos.|L’intervalle %s repose sur le rééchantillonnage des cas.|Das %s-Intervall basiert auf Fall-Resampling.|Khoảng %s dựa trên lấy mẫu lại các trường hợp.
BCa uses leave-one-out jackknife acceleration.|BCaはleave-one-outジャックナイフ加速度を使用します。|BCa使用逐一删除刀切法加速度。|BCa usa aceleración jackknife dejando un caso fuera.|BCa utilise l’accélération jackknife en retirant un cas à la fois.|BCa verwendet die Leave-one-out-Jackknife-Beschleunigung.|BCa dùng gia tốc jackknife loại từng trường hợp.
Polychoric correlations are re-estimated in each resample.|各再標本でポリコリック相関を再推定します。|在每个重抽样中重新估计多分相关。|Las correlaciones policóricas se reestiman en cada remuestra.|Les corrélations polychoriques sont réestimées dans chaque rééchantillonnage.|Polychorische Korrelationen werden in jeder Stichprobe neu geschätzt.|Tương quan polychoric được ước lượng lại trong mỗi mẫu.'''
data_rows=[r.split('|') for r in rows.splitlines()]
notes='''HTMT is not currently|多集団標本統計のHTMTは現在表示しません。|当前不显示多组样本统计的HTMT。|Actualmente no se muestra HTMT para estadísticas muestrales multigrupo.|HTMT n’est actuellement pas affiché pour les statistiques d’échantillons multigroupes.|HTMT wird für Mehrgruppen-Stichprobenstatistiken derzeit nicht angezeigt.|Hiện không hiển thị HTMT cho thống kê mẫu đa nhóm.
HTMT uses absolute|HTMTは項目相関の絶対値を使用します。選択した閾値未満の値は「参考値未満」と表示しますが、これだけで弁別的妥当性が認められるわけではありません。|HTMT使用题项相关的绝对值。低于所选阈值的值标为“低于参考值”，但这并不单独证明区分效度。|HTMT usa correlaciones absolutas entre ítems. Los valores bajo el umbral se marcan «Por debajo de la referencia», lo que no acredita por sí solo validez discriminante.|HTMT utilise les corrélations absolues entre items. Les valeurs sous le seuil sont marquées «Sous la référence», ce qui ne suffit pas à établir la validité discriminante.|HTMT verwendet absolute Itemkorrelationen. Werte unter der Schwelle werden als „Unter Referenzwert“ markiert; dies allein belegt keine diskriminante Validität.|HTMT dùng trị tuyệt đối tương quan mục. Giá trị dưới ngưỡng được ghi “Dưới mức tham khảo”, nhưng riêng điều này không chứng minh giá trị phân biệt.
For ordered indicators, HTMT|順序尺度指標では、HTMTはlavaanのポリコリック潜在反応相関を使用します。|对于有序指标，HTMT使用lavaan的多分潜在反应相关。|Con indicadores ordinales, HTMT usa las correlaciones policóricas de respuesta latente de lavaan.|Pour les indicateurs ordinaux, HTMT utilise les corrélations polychoriques de réponse latente de lavaan.|Bei ordinalen Indikatoren verwendet HTMT die polychorischen latenten Antwortkorrelationen von lavaan.|Với chỉ báo thứ bậc, HTMT dùng tương quan phản hồi tiềm ẩn polychoric của lavaan.
HTMT point estimates|HTMT点推定は記述的指標です。区間推定が必要な場合は分析オプションでHTMTブートストラップCIを選択してください。|HTMT点估计是描述性指标。如需区间估计，请在分析选项中选择HTMT自助法CI。|Las estimaciones puntuales HTMT son descriptivas. Seleccione CI bootstrap HTMT en las opciones si necesita intervalos.|Les estimations ponctuelles HTMT sont descriptives. Sélectionnez les IC bootstrap HTMT dans les options si des intervalles sont nécessaires.|HTMT-Punktschätzungen sind deskriptiv. Wählen Sie HTMT-Bootstrap-KI in den Analyseoptionen, wenn Intervalle benötigt werden.|Ước lượng điểm HTMT mang tính mô tả. Chọn CI bootstrap HTMT trong tùy chọn phân tích khi cần khoảng ước lượng.
'Upper < threshold' uses|「上限 < 基準」は選択した.85/.90基準に対する片側95%信頼上限を使用します。「上限 < 1」は両側95%区間が1を除外するかを示します。これらは点推定基準とは分けて報告します。|“上限 < 阈值”使用所选.85/.90标准的单侧95%置信上限。“上限 < 1”表示双侧95%区间是否排除1。这些判断与点估计标准分开报告。|«Superior < umbral» usa el límite superior unilateral del 95% para el criterio .85/.90. «Superior < 1» indica si el intervalo bilateral del 95% excluye 1. Se informan por separado del criterio puntual.|«Limite supérieure < seuil» utilise la limite supérieure unilatérale à 95 % pour le critère .85/.90. «Limite supérieure < 1» indique si l’intervalle bilatéral à 95 % exclut 1. Ces critères sont rapportés séparément du critère ponctuel.|„Obergrenze < Schwelle“ verwendet die einseitige 95%-Obergrenze für das gewählte .85/.90-Kriterium. „Obergrenze < 1“ zeigt, ob das zweiseitige 95%-Intervall 1 ausschließt. Diese Angaben werden getrennt vom Punktschätzkriterium berichtet.|“Cận trên < ngưỡng” dùng cận trên tin cậy một phía 95% cho tiêu chí .85/.90 đã chọn. “Cận trên < 1” cho biết khoảng hai phía 95% có loại trừ 1 hay không. Các tiêu chí này được báo cáo riêng với tiêu chí ước lượng điểm.'''
source=Path('R/setup_custom_model_canvas_structural_render_htmt.R').read_text(encoding='utf-8');sources=re.findall(r'tr\("([^"]+)"',source)
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
