import json,re
from pathlib import Path
rows='''Choose either all structural paths or selected structural paths as the comparison scope.	比較範囲として全構造経路または選択した構造経路を選んでください。	请选择所有结构路径或选定结构路径作为比较范围。	Elija todas las trayectorias estructurales o las seleccionadas como ámbito de comparación.	Choisissez tous les chemins structurels ou les chemins sélectionnés comme périmètre de comparaison.	Wählen Sie alle oder ausgewählte Strukturpfade als Vergleichsumfang.	Chọn tất cả đường dẫn cấu trúc hoặc các đường dẫn đã chọn làm phạm vi so sánh.
Select at least one structural path to compare in selected-path mode.	選択経路モードでは、比較する構造経路を1つ以上選択してください。	在选定路径模式下，请至少选择一条要比较的结构路径。	Seleccione al menos una trayectoria estructural para comparar en el modo de trayectorias seleccionadas.	Sélectionnez au moins un chemin structurel à comparer en mode chemins sélectionnés.	Wählen Sie im Modus für ausgewählte Pfade mindestens einen Strukturpfad zum Vergleich.	Trong chế độ đường dẫn đã chọn, hãy chọn ít nhất một đường dẫn cấu trúc để so sánh.
The current model has no latent-to-latent structural path available for multi-group comparison.	現在のモデルには、多群比較に使用できる潜在変数間の構造経路がありません。	当前模型没有可用于多组比较的潜变量间结构路径。	El modelo actual no tiene trayectorias estructurales entre variables latentes disponibles para comparación multigrupo.	Le modèle actuel ne contient aucun chemin structurel entre variables latentes disponible pour une comparaison multigroupe.	Das aktuelle Modell enthält keinen Strukturpfad zwischen latenten Variablen für einen Mehrgruppenvergleich.	Mô hình hiện tại không có đường dẫn cấu trúc giữa các biến tiềm ẩn để so sánh đa nhóm.
Selected structural paths are missing or no longer valid in the current canvas. Select the paths again.	選択した構造経路が現在のキャンバスにないか、無効になっています。経路を再選択してください。	选定结构路径在当前画布中缺失或已失效。请重新选择路径。	Las trayectorias seleccionadas faltan o ya no son válidas en el lienzo actual. Vuelva a seleccionarlas.	Les chemins sélectionnés sont absents ou ne sont plus valides dans le canevas actuel. Sélectionnez-les à nouveau.	Ausgewählte Strukturpfade fehlen oder sind auf der aktuellen Zeichenfläche nicht mehr gültig. Wählen Sie die Pfade erneut.	Đường dẫn cấu trúc đã chọn bị thiếu hoặc không còn hợp lệ trên vùng vẽ hiện tại. Hãy chọn lại đường dẫn.
Duplicate structural paths or path IDs prevent resolving the selected paths. Remove duplicates and select the paths again.	構造経路または経路IDの重複により選択経路を確定できません。重複を削除し、再選択してください。	重复的结构路径或路径ID导致无法确定选定路径。请删除重复项并重新选择路径。	Las trayectorias o sus identificadores duplicados impiden resolver la selección. Elimine los duplicados y vuelva a seleccionar las trayectorias.	Des chemins structurels ou identifiants en double empêchent de résoudre la sélection. Supprimez les doublons et sélectionnez à nouveau les chemins.	Doppelte Strukturpfade oder Pfad-IDs verhindern die Zuordnung der ausgewählten Pfade. Entfernen Sie Duplikate und wählen Sie die Pfade erneut.	Đường dẫn cấu trúc hoặc ID trùng lặp khiến không thể xác định các đường dẫn đã chọn. Hãy xóa mục trùng và chọn lại đường dẫn.
The group-difference test was stopped because selected-path equality constraints changed model degrees of freedom by an unexpected amount. Check the selected paths and model constraints.	選択経路の等値制約によるモデル自由度の変化が予想と異なるため、群間差検定を停止しました。選択経路とモデル制約を確認してください。	选定路径的相等约束导致模型自由度变化与预期不符，因此已停止组间差异检验。请检查选定路径和模型约束。	Se detuvo la prueba de diferencias entre grupos porque las restricciones de igualdad de las trayectorias seleccionadas cambiaron los grados de libertad de forma inesperada. Revise las trayectorias y las restricciones del modelo.	Le test de différences entre groupes a été arrêté car les contraintes d’égalité sur les chemins sélectionnés ont modifié les degrés de liberté de façon inattendue. Vérifiez les chemins et les contraintes du modèle.	Der Gruppenunterschiedstest wurde gestoppt, weil Gleichheitsrestriktionen der ausgewählten Pfade die Modellfreiheitsgrade unerwartet veränderten. Prüfen Sie die ausgewählten Pfade und Modellrestriktionen.	Đã dừng kiểm định khác biệt nhóm vì ràng buộc bằng nhau của đường dẫn đã chọn làm thay đổi bậc tự do ngoài dự kiến. Hãy kiểm tra đường dẫn đã chọn và ràng buộc mô hình.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for line in rows.splitlines():
  f=line.split('\t');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
