import json
from pathlib import Path
keys=['strata_count','cluster_count','spline_numeric','spline_unique','tv_numeric','tv_unique']
rows={
'en':['Stratified Cox regression requires at least two observed strata in the analysis sample.','Cluster-robust Cox regression requires at least two observed clusters in the analysis sample.','Cox spline modeling requires a numeric continuous covariate.','The spline covariate has too few distinct values for the requested degrees of freedom.','Time-varying coefficient Cox requires a numeric continuous covariate.','The time-varying coefficient covariate has too few distinct values.'],
'ko':['층화 Cox 회귀분석에는 분석 표본에서 관측된 층이 둘 이상 필요합니다.','군집 강건 Cox 회귀분석에는 분석 표본에서 관측된 군집이 둘 이상 필요합니다.','Cox 스플라인 모형에는 숫자형 연속 공변량이 필요합니다.','스플라인 공변량의 고유값 수가 요청한 자유도에 비해 부족합니다.','시간가변 계수 Cox 모형에는 숫자형 연속 공변량이 필요합니다.','시간가변 계수 공변량의 고유값 수가 부족합니다.'],
'ja':['層別Cox回帰には、分析標本で観測された層が2つ以上必要です。','クラスター頑健Cox回帰には、分析標本で観測されたクラスターが2つ以上必要です。','Coxスプラインモデルには数値型の連続共変量が必要です。','スプライン共変量の異なる値の数が、指定された自由度に対して不足しています。','時間変動係数Coxモデルには数値型の連続共変量が必要です。','時間変動係数の共変量の異なる値の数が不足しています。'],
'zh':['分层 Cox 回归要求分析样本中至少有两个已观测到的层。','聚类稳健 Cox 回归要求分析样本中至少有两个已观测到的聚类。','Cox 样条建模需要数值型连续协变量。','样条协变量的不同取值数量不足以支持所请求的自由度。','时变系数 Cox 模型需要数值型连续协变量。','时变系数协变量的不同取值数量不足。'],
'es':['La regresión de Cox estratificada requiere al menos dos estratos observados en la muestra analizada.','La regresión de Cox robusta por grupos requiere al menos dos grupos observados en la muestra analizada.','El modelo de Cox con splines requiere una covariable numérica continua.','La covariable spline tiene muy pocos valores distintos para los grados de libertad solicitados.','El modelo de Cox con coeficiente dependiente del tiempo requiere una covariable numérica continua.','La covariable con coeficiente dependiente del tiempo tiene muy pocos valores distintos.'],
'fr':['La régression de Cox stratifiée nécessite au moins deux strates observées dans l’échantillon analysé.','La régression de Cox robuste par groupes nécessite au moins deux groupes observés dans l’échantillon analysé.','Le modèle de Cox avec spline nécessite une covariable numérique continue.','La covariable spline comporte trop peu de valeurs distinctes pour les degrés de liberté demandés.','Le modèle de Cox à coefficient variant dans le temps nécessite une covariable numérique continue.','La covariable à coefficient variant dans le temps comporte trop peu de valeurs distinctes.'],
'de':['Eine stratifizierte Cox-Regression erfordert mindestens zwei beobachtete Strata in der Analysestichprobe.','Eine clusterrobuste Cox-Regression erfordert mindestens zwei beobachtete Cluster in der Analysestichprobe.','Die Cox-Spline-Modellierung erfordert eine numerische kontinuierliche Kovariate.','Die Spline-Kovariate hat für die angeforderten Freiheitsgrade zu wenige unterschiedliche Werte.','Ein Cox-Modell mit zeitvariablem Koeffizienten erfordert eine numerische kontinuierliche Kovariate.','Die Kovariate mit zeitvariablem Koeffizienten hat zu wenige unterschiedliche Werte.'],
'vi':['Hồi quy Cox phân tầng cần ít nhất hai tầng được quan sát trong mẫu phân tích.','Hồi quy Cox vững theo cụm cần ít nhất hai cụm được quan sát trong mẫu phân tích.','Mô hình Cox spline cần một hiệp biến liên tục dạng số.','Hiệp biến spline có quá ít giá trị khác nhau so với bậc tự do yêu cầu.','Mô hình Cox có hệ số thay đổi theo thời gian cần một hiệp biến liên tục dạng số.','Hiệp biến có hệ số thay đổi theo thời gian có quá ít giá trị khác nhau.'],
}
for lang,values in rows.items():
 p=Path('i18n')/(lang+'.json');obj=json.loads(p.read_text(encoding='utf-8'))
 obj['translations'].update({'survival.input_error.'+k:v for k,v in zip(keys,values)})
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
