import json, re
from pathlib import Path

rows = '''Reporting checklist and interpretation guide|報告チェックリストと解釈ガイド|报告检查清单与解释指南|Lista de verificación del informe y guía de interpretación|Liste de contrôle du rapport et guide d’interprétation|Berichtscheckliste und Interpretationshilfe|Danh sách kiểm tra báo cáo và hướng dẫn diễn giải
Thresholds are heuristic screening rules, not automatic analysis-quality pass/fail criteria.|閾値は経験的なスクリーニング基準であり、分析の質の合否を自動的に判定する基準ではありません。|阈值是经验性筛查规则，不是自动判定分析质量是否合格的标准。|Los umbrales son reglas heurísticas de detección, no criterios automáticos para aprobar o rechazar la calidad del análisis.|Les seuils sont des règles heuristiques de dépistage, et non des critères automatiques de validation de la qualité de l’analyse.|Schwellenwerte sind heuristische Prüfregeln, keine automatischen Kriterien für das Bestehen oder Nichtbestehen einer Qualitätsprüfung der Analyse.|Các ngưỡng là quy tắc sàng lọc theo kinh nghiệm, không phải tiêu chí tự động xác định chất lượng phân tích đạt hay không đạt.
Median potential follow-up uses reverse Kaplan–Meier with censoring as the event. A high censoring proportion is not itself evidence of bias; the censoring mechanism requires separate review.|潜在的追跡期間の中央値は、打ち切りをイベントとする逆Kaplan–Meier法で推定します。打ち切り割合が高いこと自体はバイアスの証拠ではなく、打ち切り機構を別途検討する必要があります。|潜在随访时间中位数使用将删失视为事件的反向Kaplan–Meier法估计。删失比例高本身并不构成偏倚证据；需要单独审查删失机制。|La mediana del seguimiento potencial se estima mediante Kaplan–Meier inverso, considerando la censura como evento. Una proporción elevada de censura no constituye por sí sola evidencia de sesgo; el mecanismo de censura requiere una revisión independiente.|La médiane du suivi potentiel est estimée par Kaplan–Meier inversé, en considérant la censure comme événement. Une forte proportion de censure ne constitue pas en soi une preuve de biais ; le mécanisme de censure doit être examiné séparément.|Die mediane potenzielle Nachbeobachtungszeit wird mit umgekehrtem Kaplan–Meier geschätzt, wobei Zensierungen als Ereignisse gelten. Ein hoher Zensierungsanteil ist allein kein Beleg für eine Verzerrung; der Zensierungsmechanismus muss gesondert geprüft werden.|Trung vị thời gian theo dõi tiềm năng được ước tính bằng Kaplan–Meier đảo ngược, coi kiểm duyệt là biến cố. Tỷ lệ kiểm duyệt cao tự nó không phải bằng chứng về sai lệch; cơ chế kiểm duyệt cần được xem xét riêng.
This checklist helps prevent reporting omissions; it does not automatically establish design validity or causality.|このチェックリストは報告の漏れを防ぐための補助であり、研究デザインの妥当性や因果関係を自動的に確定するものではありません。|此检查清单有助于防止报告遗漏，但不会自动确认研究设计的有效性或因果关系。|Esta lista ayuda a evitar omisiones en el informe; no establece automáticamente la validez del diseño ni la causalidad.|Cette liste aide à éviter les omissions dans le rapport ; elle n’établit pas automatiquement la validité du plan d’étude ni la causalité.|Diese Checkliste hilft, Berichtslücken zu vermeiden; sie belegt nicht automatisch die Validität des Studiendesigns oder Kausalität.|Danh sách này giúp tránh bỏ sót nội dung báo cáo; nó không tự động xác lập tính hợp lệ của thiết kế nghiên cứu hoặc quan hệ nhân quả.'''

for i, lang in enumerate(['ja','zh','es','fr','de','vi'], 1):
    p = Path('i18n') / (lang + '.json')
    data = json.loads(p.read_text(encoding='utf-8'))
    for row in rows.splitlines():
        fields = row.split('|')
        assert len(fields) == 7
        key = 'analysis.ui.' + re.sub(r'[^a-z0-9]+', '_', fields[0].lower()).strip('_')
        data['translations'][key] = fields[i]
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
