import json,re
from pathlib import Path
rows='''Survival sparse evidence Valid adjusted-survival bootstrap replicates =|調整済み生存曲線の有効ブートストラップ反復数 =|调整生存曲线的有效自助法重复次数 =|Réplicas bootstrap válidas de supervivencia ajustada =|Réplications bootstrap valides de survie ajustée =|Gültige Bootstrap-Wiederholungen für adjustiertes Überleben =|Số lần lặp bootstrap hợp lệ của sống còn đã hiệu chỉnh =
Survival sparse evidence Valid adjusted-survival bootstrap ratio =|調整済み生存曲線の有効ブートストラップ反復割合 =|调整生存曲线的有效自助法重复比例 =|Proporción de réplicas bootstrap válidas de supervivencia ajustada =|Proportion de réplications bootstrap valides de survie ajustée =|Anteil gültiger Bootstrap-Wiederholungen für adjustiertes Überleben =|Tỷ lệ lần lặp bootstrap hợp lệ của sống còn đã hiệu chỉnh =
Survival sparse evidence Events at tied times =|同時点に発生したイベントの割合 =|同一时间发生的事件比例 =|Eventos en tiempos empatados =|Événements survenant aux mêmes temps =|Ereignisse zu gebundenen Zeitpunkten =|Tỷ lệ biến cố tại các thời điểm trùng nhau =
Do not report the adjusted-survival bootstrap intervals because fewer than 80% of requested replicates were valid.|要求した反復の80%未満しか有効でなかったため、調整済み生存曲線のブートストラップ区間を報告しないでください。|有效重复次数不足请求次数的80%，因此不要报告调整生存曲线的自助法区间。|No informe los intervalos bootstrap de supervivencia ajustada porque menos del 80% de las réplicas solicitadas fueron válidas.|Ne rapportez pas les intervalles bootstrap de survie ajustée, car moins de 80% des réplications demandées étaient valides.|Berichten Sie keine Bootstrap-Intervalle für adjustiertes Überleben, da weniger als 80% der angeforderten Wiederholungen gültig waren.|Không báo cáo khoảng bootstrap của sống còn đã hiệu chỉnh vì dưới 80% số lần lặp yêu cầu là hợp lệ.
Review causes of replicate loss (sparse groups or convergence failures) and report both requested and valid replicates.|反復が失われた原因（少数の集団や収束失敗）を検討し、要求した反復数と有効な反復数の両方を報告してください。|审查重复失效的原因（稀疏组或收敛失败），并同时报告请求次数和有效次数。|Revise las causas de pérdida de réplicas (grupos escasos o fallos de convergencia) e informe tanto las réplicas solicitadas como las válidas.|Examinez les causes de perte de réplications (groupes peu fournis ou échecs de convergence) et indiquez les nombres de réplications demandées et valides.|Prüfen Sie Ursachen ausgefallener Wiederholungen (schwach besetzte Gruppen oder Konvergenzfehler) und berichten Sie sowohl angeforderte als auch gültige Wiederholungen.|Xem xét nguyên nhân mất lần lặp (nhóm có ít quan sát hoặc lỗi hội tụ) và báo cáo cả số lần lặp yêu cầu lẫn số lần hợp lệ.
With substantial tied events, consider sensitivity comparison with Efron or an exact method appropriate to the study design.|同時点のイベントが多い場合、Efron法や研究デザインに適した正確法との感度比較を検討してください。|同一时间发生的事件较多时，考虑与Efron法或适合研究设计的精确法进行敏感性比较。|Con muchos eventos empatados, considere una comparación de sensibilidad con Efron o con un método exacto apropiado para el diseño del estudio.|En présence de nombreux événements simultanés, envisagez une comparaison de sensibilité avec Efron ou une méthode exacte adaptée au plan d’étude.|Erwägen Sie bei vielen zeitgleichen Ereignissen einen Sensitivitätsvergleich mit Efron oder einer zum Studiendesign passenden exakten Methode.|Khi có nhiều biến cố trùng thời điểm, cân nhắc so sánh độ nhạy với Efron hoặc phương pháp chính xác phù hợp với thiết kế nghiên cứu.'''
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for row in rows.splitlines():
  f=row.split('|');assert len(f)==7
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
