import json,re
from pathlib import Path
rows='''MI modification history|MI修正履歴|MI修改历史|Historial de modificaciones MI|Historique des modifications MI|MI-Modifikationsverlauf|Lịch sử điều chỉnh MI
Not provided|未入力|未提供|No proporcionado|Non fourni|Nicht angegeben|Chưa cung cấp
Validation status: |検証状態：|验证状态：|Estado de validación: |État de validation : |Validierungsstatus: |Trạng thái kiểm định: 
MI holdout validation|MIホールドアウト検証|MI留出验证|Validación MI con muestra reservada|Validation MI sur échantillon réservé|MI-Holdout-Validierung|Kiểm định MI trên mẫu giữ lại
Exploration N = %s; reserved validation N = %s.|探索標本 N = %s；予約検証標本 N = %s。|探索样本 N = %s；预留验证样本 N = %s。|N de exploración = %s; N reservado para validación = %s.|N d’exploration = %s ; N réservé pour validation = %s.|Explorations-N = %s; reserviertes Validierungs-N = %s.|N khám phá = %s; N dành riêng để kiểm định = %s.
Exploration rows = %s; reserved validation rows = %s; validation N used = %s; split seed = %s.|探索行数 = %s；予約検証行数 = %s；使用した検証 N = %s；分割シード = %s。|探索行数 = %s；预留验证行数 = %s；实际验证 N = %s；划分种子 = %s。|Filas de exploración = %s; filas reservadas = %s; N de validación utilizado = %s; semilla de partición = %s.|Lignes d’exploration = %s ; lignes réservées = %s ; N de validation utilisé = %s ; graine de partition = %s.|Explorationszeilen = %s; reservierte Validierungszeilen = %s; verwendetes Validierungs-N = %s; Aufteilungs-Seed = %s.|Số hàng khám phá = %s; số hàng dành riêng để kiểm định = %s; N kiểm định đã dùng = %s; seed chia mẫu = %s.
Validation-sample change: modified minus original|検証標本の変化：修正モデル − 元のモデル|验证样本变化：修改模型减原模型|Cambio en la muestra de validación: modificado menos original|Changement dans l’échantillon de validation : modifié moins original|Änderung in der Validierungsstichprobe: modifiziert minus ursprünglich|Thay đổi trên mẫu kiểm định: mô hình điều chỉnh trừ mô hình gốc
Not applicable|該当なし|不适用|No aplicable|Sans objet|Nicht zutreffend|Không áp dụng
Exploratory - independent validation not performed|探索的：独立検証未実施|探索性：未进行独立验证|Exploratorio: sin validación independiente|Exploratoire : validation indépendante non réalisée|Explorativ: keine unabhängige Validierung|Mang tính khám phá: chưa kiểm định độc lập
Exploratory - reserved holdout not yet evaluated|探索的：予約ホールドアウト未評価|探索性：尚未评估预留样本|Exploratorio: muestra reservada aún no evaluada|Exploratoire : échantillon réservé non encore évalué|Explorativ: reservierte Holdout-Stichprobe noch nicht ausgewertet|Mang tính khám phá: chưa đánh giá mẫu giữ lại
Exploratory - holdout evaluation inconclusive (inadmissible model)|探索的：ホールドアウト評価は結論不能（不適解）|探索性：留出评估无定论（不当模型）|Exploratorio: evaluación reservada no concluyente (modelo inadmisible)|Exploratoire : évaluation réservée non concluante (modèle inadmissible)|Explorativ: Holdout-Auswertung nicht eindeutig (unzulässiges Modell)|Mang tính khám phá: đánh giá mẫu giữ lại chưa kết luận được (mô hình không chấp nhận được)
Exploratory - evaluated once in a prespecified reserved holdout; inspect all changes|探索的：事前指定の予約ホールドアウトで1回評価済み。すべての変化を確認してください|探索性：已在预先指定的留出样本中评估一次；请检查所有变化|Exploratorio: evaluado una vez en una muestra reservada preespecificada; revise todos los cambios|Exploratoire : évalué une fois sur un échantillon réservé prédéfini ; examinez tous les changements|Explorativ: einmal in einer vorab festgelegten Holdout-Stichprobe ausgewertet; alle Änderungen prüfen|Mang tính khám phá: đã đánh giá một lần trên mẫu giữ lại định trước; xem xét mọi thay đổi'''
notes='''MI, EPC, and cumulative fit values|MI、EPC、累積適合度は経路選択時点の値です。各パラメータを自由化した実質的な理由を根拠欄に記録してください。|MI、EPC和累积拟合度为选择路径时的数值。应在依据中记录释放各参数的实质性理由。|MI, EPC y el ajuste acumulado corresponden al momento de seleccionar la trayectoria. La justificación debe documentar el motivo sustantivo para liberar cada parámetro.|MI, EPC et l’ajustement cumulé sont ceux disponibles lors de la sélection du chemin. La justification doit consigner la raison substantielle de libérer chaque paramètre.|MI, EPC und kumulierter Fit entsprechen dem Zeitpunkt der Pfadauswahl. Die Begründung sollte den inhaltlichen Grund für die Freigabe jedes Parameters dokumentieren.|MI, EPC và độ phù hợp tích lũy là các giá trị khi chọn đường dẫn. Phần giải thích cần ghi cơ sở thực chất cho việc ước lượng tự do từng tham số.
MI-driven modifications are exploratory|MIによる修正は探索的であり、独立標本で交差検証する必要があります。|MI驱动的修改具有探索性，应在独立样本中交叉验证。|Las modificaciones basadas en MI son exploratorias y deben validarse de forma cruzada en una muestra independiente.|Les modifications fondées sur MI sont exploratoires et doivent faire l’objet d’une validation croisée sur un échantillon indépendant.|MI-basierte Modifikationen sind explorativ und sollten an einer unabhängigen Stichprobe kreuzvalidiert werden.|Điều chỉnh dựa trên MI mang tính khám phá và cần được kiểm định chéo trên mẫu độc lập.
MI candidates and all currently displayed CFA estimates|MI候補と現在表示されているCFA推定値は探索標本のみに基づきます。MI経路の適用後に検証結果が表示されます。|MI候选项和当前显示的所有CFA估计仅基于探索样本。应用MI路径后将显示验证结果。|Los candidatos MI y todas las estimaciones CFA mostradas se basan solo en la muestra de exploración. Los resultados de validación aparecerán tras aplicar una trayectoria MI.|Les candidats MI et toutes les estimations CFA affichées reposent uniquement sur l’échantillon d’exploration. Les résultats de validation apparaîtront après l’application d’un chemin MI.|MI-Kandidaten und alle angezeigten CFA-Schätzungen beruhen nur auf der Explorationsstichprobe. Validierungsergebnisse erscheinen nach Anwendung eines MI-Pfads.|Các ứng viên MI và mọi ước lượng CFA đang hiển thị chỉ dựa trên mẫu khám phá. Kết quả kiểm định sẽ xuất hiện sau khi áp dụng đường dẫn MI.
One or both validation-sample models failed|検証標本の一方または両方のモデルが、主CFAと同じ完全な解の許容性チェックを通過しませんでした。検証標本の変化統計と正式な差の検定は表示しません。この修正が再現されたと解釈しないでください。|验证样本中的一个或两个模型未通过与主CFA相同的完整可接受性检查。验证样本变化统计和正式差异检验不予显示；不得将该修改视为已重复验证。|Uno o ambos modelos de validación no superaron las mismas comprobaciones completas de admisibilidad que el CFA principal. Se suprimen los cambios estadísticos y la prueba formal de diferencias; la modificación no debe considerarse replicada.|Un ou les deux modèles de validation ont échoué aux mêmes contrôles complets d’admissibilité que la CFA principale. Les statistiques de changement et le test formel de différence sont masqués ; la modification ne doit pas être considérée comme reproduite.|Eines oder beide Validierungsmodelle haben die vollständigen Zulässigkeitsprüfungen der Haupt-CFA nicht bestanden. Änderungsstatistiken und formaler Differenztest werden unterdrückt; die Modifikation darf nicht als repliziert gelten.|Một hoặc cả hai mô hình trên mẫu kiểm định không vượt qua đầy đủ các kiểm tra tính chấp nhận được như CFA chính. Thống kê thay đổi và kiểm định chênh lệch chính thức bị ẩn; không được xem điều chỉnh này là đã tái lập.
The MI path was selected only in the exploration sample.|MI経路は探索標本のみで選択しました。上表は予約検証標本で両モデルを独立に再推定した結果です。適合度改善の再現は安定性を支持しますが、実質的な根拠の代わりにはなりません。再現しなければ標本固有の修正である可能性が高くなります。|MI路径仅在探索样本中选择。上表在预留验证样本中独立重新拟合两个模型。拟合改善的重复出现支持稳定性，但不能替代实质性依据；未能重复则提示修改可能具有样本特异性。|La trayectoria MI se seleccionó solo en la muestra de exploración. La tabla reajusta ambos modelos de forma independiente en la muestra reservada. Reproducir la mejora del ajuste respalda la estabilidad, pero no sustituye la justificación sustantiva; no reproducirla indica una probable modificación específica de la muestra.|Le chemin MI a été choisi uniquement dans l’échantillon d’exploration. Le tableau réestime indépendamment les deux modèles sur l’échantillon réservé. La reproduction d’un meilleur ajustement soutient la stabilité sans remplacer la justification substantielle ; son absence indique une probable modification propre à l’échantillon.|Der MI-Pfad wurde nur in der Explorationsstichprobe ausgewählt. Die Tabelle schätzt beide Modelle unabhängig in der reservierten Validierungsstichprobe neu. Eine replizierte Fitverbesserung stützt die Stabilität, ersetzt aber keine inhaltliche Begründung; fehlende Replikation deutet auf eine stichprobenspezifische Modifikation hin.|Đường dẫn MI chỉ được chọn trong mẫu khám phá. Bảng khớp lại độc lập cả hai mô hình trên mẫu kiểm định dành riêng. Việc tái lập cải thiện độ phù hợp hỗ trợ tính ổn định nhưng không thay thế cơ sở thực chất; không tái lập được cho thấy điều chỉnh có thể chỉ đặc trưng cho mẫu.
The validation sample is now unblinded and locked.|検証標本は開示され、ロックされました。この分割での追加MI変更は無効です。別の修正モデルを評価するには、新たに選んだ分割シードで新しい分析を開始してください。|验证样本现已揭示并锁定。此划分不再允许进一步MI修改；要评估其他修改模型，请用新选的划分种子开始新分析。|La muestra de validación ya está revelada y bloqueada. Se deshabilitan más cambios MI en esta partición; inicie un análisis nuevo con otra semilla de partición para evaluar un modelo modificado diferente.|L’échantillon de validation est désormais dévoilé et verrouillé. Les modifications MI supplémentaires sont désactivées pour cette partition ; démarrez une nouvelle analyse avec une nouvelle graine pour évaluer un autre modèle modifié.|Die Validierungsstichprobe ist jetzt offengelegt und gesperrt. Weitere MI-Änderungen sind für diese Aufteilung deaktiviert; starten Sie zur Prüfung eines anderen modifizierten Modells eine neue Analyse mit neu gewähltem Aufteilungs-Seed.|Mẫu kiểm định đã được mở và khóa. Không cho phép thêm thay đổi MI trên lần chia này; hãy bắt đầu phân tích mới với seed chia mẫu mới để đánh giá mô hình điều chỉnh khác.'''
source=Path('R/setup_custom_model_canvas_structural_render_mi.R').read_text(encoding='utf-8')
sources=re.findall(r'tr\("([^"]+)"',source)
data_rows=[row.split('|') for row in rows.splitlines()]
extra='''Justification|根拠|依据|Justificación|Justification|Begründung|Cơ sở
N used|使用N|使用N|N utilizado|N utilisé|Verwendetes N|N đã dùng
Admissibility reasons|解の許容性に関する理由|可接受性原因|Motivos de admisibilidad|Raisons d’admissibilité|Zulässigkeitsgründe|Lý do về tính chấp nhận được
Both validation models admissible|両検証モデルが許容可能|两个验证模型均可接受|Ambos modelos de validación son admisibles|Les deux modèles de validation sont admissibles|Beide Validierungsmodelle sind zulässig|Cả hai mô hình kiểm định đều chấp nhận được
Suppressed because one or both validation models are inadmissible|一方または両方の検証モデルが不適解のため非表示|因一个或两个验证模型不当而不予显示|Omitido porque uno o ambos modelos de validación son inadmisibles|Masqué car un ou les deux modèles de validation sont inadmissibles|Unterdrückt, da eines oder beide Validierungsmodelle unzulässig sind|Ẩn vì một hoặc cả hai mô hình kiểm định không chấp nhận được'''
data_rows.extend(row.split('|') for row in extra.splitlines())
for row in notes.splitlines():
 f=row.split('|');matches=[s for s in sources if s.startswith(f[0])];assert len(matches)==1
 f[0]=matches[0];data_rows.append(f)
for i,lang in enumerate(['ja','zh','es','fr','de','vi'],1):
 p=Path('i18n')/(lang+'.json');data=json.loads(p.read_text(encoding='utf-8'))
 for f in data_rows:
  assert len(f)==7 and f[0].count('%s')==f[i].count('%s')
  data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',f[0].lower()).strip('_')]=f[i]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=Path('i18n/ko.json');data=json.loads(p.read_text(encoding='utf-8'))
for row,translation in zip(extra.splitlines(),['수정 근거','사용 N','허용성 사유','두 검증 모형 모두 허용 가능','한 모형 또는 두 검증 모형이 허용 불가능하여 표시하지 않음']):
 data['translations']['analysis.ui.'+re.sub(r'[^a-z0-9]+','_',row.split('|')[0].lower()).strip('_')]=translation
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
