# Actual GEE/GLMM/LMM effect-size wrappers for shared export verification.
out<-'tmp/mixed-effect-formula-i18n';dir.create(out,recursive=TRUE,showWarnings=FALSE)
g<-list(effect_size_gee_sd_mode='direct',effect_size_gee_sd='1',effect_size_gee_mean1='0.5',effect_size_gee_mean2='0',effect_size_gee_pre_mean1='0',effect_size_gee_post_mean1='0.5',effect_size_gee_pre_mean2='0.1',effect_size_gee_post_mean2='0.2',effect_size_gee_coefficient='0.4',effect_size_gee_d='0.5',effect_size_gee_p1='0.5',effect_size_gee_p2='0.65')
b<-list(effect_size_glmm_coefficient='0.5',effect_size_glmm_binary_scale='coefficient',effect_size_glmm_count_scale='coefficient',effect_size_glmm_sd='1')
l<-list(effect_size_lmm_lmm_design='two_group_repeated',effect_size_lmm_effect='0.3',effect_size_lmm_time_points='3',effect_size_lmm_icc='0.3',effect_size_lmm_group1_means='0, 0.2, 0.4',effect_size_lmm_group2_means='0, 0.1, 0.8',effect_size_lmm_residual_sd='1',effect_size_lmm_f_statistic='28.061',effect_size_lmm_df_effect='3',effect_size_lmm_df_error='23.057',effect_size_lmm_mean_difference='0.824',effect_size_lmm_variance_i='0.326',effect_size_lmm_variance_j='0.199',effect_size_lmm_covariance_ij='0.117',effect_size_lmm_rho='0.5',effect_size_lmm_correlation_structure='exchangeable')
designs<-c('binary_props','continuous_d','continuous_change_means','continuous_parameter_b','continuous_followup_means','binary_logit','count_log','continuous_gaussian','spss_output','glimmpse_vectors','simple_fixed')
results<-c(lapply(designs[1:5],function(design)effect_size_gee_calculate(modifyList(g,list(effect_size_gee_design=design)))),lapply(designs[6:8],function(design)effect_size_glmm_calculate(modifyList(b,list(effect_size_glmm_design=design)))),lapply(designs[9:11],function(design)effect_size_lmm_calculate(modifyList(l,list(effect_size_lmm_design=design)))))
formula_keys<-paste0('sample_size.result.',c('gee_binary','gee_supplied','gee_change','gee_parameter','gee_means','glmm_binary','glmm_count','glmm_gaussian','lmm_spss','lmm_glimmpse','lmm_simple'))
tokens<-list(c('2 asin(sqrt(p1)) - 2 asin(sqrt(p2))','h / sqrt(design effect)'),character(), '[(post - pre) group 1 - (post - pre) group 2] / common outcome SD','GEE group x time parameter estimate B / common outcome SD','(estimated mean group 1 - estimated mean group 2) / common outcome SD',c('log(OR) = B','OR = exp(B)','log(OR) * sqrt(3) / pi'),c('log(IRR) = B','IRR = exp(B)','rate1 / rate2'),'fixed-effect coefficient B / residual SD',c('F * df_effect / (F * df_effect + df_error)','mean difference / sqrt(Var_i + Var_j - 2Cov_ij)'),c('last-minus-first mean contrast / residual SD','d * sqrt(m / design effect)'),'standardized fixed effect * sqrt(m / [1 + (m - 1)ICC])')
for(lang in c('en','ko','ja','zh','es','fr','de','vi'))for(i in seq_along(tokens)) {
 value<-statedu_t(formula_keys[[i]],lang,fallback='')
 stopifnot(nzchar(value),all(vapply(tokens[[i]],grepl,logical(1),x=value,fixed=TRUE)))
}
for(i in seq_along(results))if(!is.null(results[[i]]$error)||!identical(results[[i]]$formula_note,statedu_t(formula_keys[[i]],'en')))stop('Unexpected branch ',designs[[i]],': ',results[[i]]$error,' / ',results[[i]]$formula_note)
cat('PASS 11 actual GEE/GLMM/LMM formula branches and math tokens x 8 languages\n')
