# 13 descriptions; hidden reliability variants are core-only fixtures.
out<-'tmp/design-formula-i18n';dir.create(out,recursive=TRUE,showWarnings=FALSE)
cinputs<-list(effect_size_cluster_effect='0.5',effect_size_cluster_p1='0.65',effect_size_cluster_p2='0.5',effect_size_cluster_size='20',effect_size_cluster_icc='0.05',effect_size_cluster_periods='5')
pinputs<-list(effect_size_precision_estimate='5',effect_size_precision_half_width='0.1',effect_size_precision_sd='2',effect_size_precision_proportion='0.5',effect_size_precision_r='0.3')
sinputs<-list(effect_size_sem_df='20',effect_size_sem_null_rmsea='0.05',effect_size_sem_alternative_rmsea='0.08',effect_size_sem_parameter='0.3',effect_size_sem_latent_variables='3',effect_size_sem_measured_variables='9',effect_size_sem_structural_paths='3',effect_size_sem_free_parameters='20',effect_size_sem_expected_loading='0.7',effect_size_sem_expected_path='0.3',effect_size_sem_complexity='moderate')
core_reliability<-function(design){r<-sample_size_effect_size_reliability(design,reliability=.8,reference=.6,items=5,categories=2,sd_difference=2);d<-sample_size_method_details('effect_reliability',r);r$formula_note<-d$formula;r$references<-d$references;r}
designs<-c('parallel_binary','stepped_wedge','parallel_continuous','mean','proportion','correlation','alpha-core','icc-core','kappa','bland_altman-core','rmsea','parameter','complexity')
results<-c(lapply(designs[1:3],function(d)effect_size_cluster_calculate(modifyList(cinputs,list(effect_size_cluster_design=d)))),lapply(designs[4:6],function(d)effect_size_precision_calculate(modifyList(pinputs,list(effect_size_precision_parameter=d)))),list(core_reliability('alpha'),core_reliability('icc'),effect_size_reliability_calculate(list(effect_size_reliability_design='kappa',effect_size_reliability_value='0.8',effect_size_reliability_categories='2')),core_reliability('bland_altman')),lapply(designs[11:13],function(d)effect_size_sem_calculate(modifyList(sinputs,list(effect_size_sem_design=d)))))
formula_keys<-paste0('sample_size.result.',c('cluster_binary','cluster_stepped','cluster_continuous','precision_mean','precision_proportion','precision_correlation','reliability_alpha','reliability_icc','reliability_kappa','reliability_agreement','sem_rmsea','sem_parameter','sem_complexity'))
tokens<-list('h / sqrt(1 + (m - 1)ICC)','d / sqrt([1 + (m - 1)ICC] * periods / [periods - 1])','d / sqrt(1 + (m - 1)ICC)','desired mean CI half-width / SD','desired proportion CI half-width / sqrt(p[1 - p])','r +/- desired raw-r half-width',c('alpha - reference alpha','log(1 - alpha)'),'ICC - reference ICC',character(),'mean difference +/- 1.96 * SD of paired differences',c('alternative RMSEA - null RMSEA','df * (RMSEA_alt^2 - RMSEA_null^2)'),"Fisher's z = atanh(parameter)",character())
for(lang in c('en','ko','ja','zh','es','fr','de','vi'))for(i in seq_along(tokens)){
 value<-statedu_t(formula_keys[i],lang,fallback='');stopifnot(nzchar(value),all(vapply(tokens[[i]],grepl,logical(1),x=value,fixed=TRUE)))
}
for(i in seq_along(results))if(!is.null(results[[i]]$error)||!identical(results[[i]]$formula_note,statedu_t(formula_keys[i],'en')))stop('Unexpected result: ',designs[i],' ',results[[i]]$error)
stopifnot(isTRUE(all.equal(results[[3]]$planning_effect_size,.5/sqrt(1.95))),isTRUE(all.equal(results[[2]]$planning_effect_size,.5/sqrt(1.95*5/4))),isTRUE(all.equal(results[[4]]$standardized_half_width,.05)),isTRUE(all.equal(results[[5]]$standardized_half_width,.2)),isTRUE(all.equal(results[[7]]$reliability_difference,.2)),isTRUE(all.equal(results[[9]]$observed_agreement,.9)),isTRUE(all.equal(results[[10]]$loa_total_width,7.84)),isTRUE(all.equal(results[[11]]$ncp_difference_per_n,20*(.08^2-.05^2))),isTRUE(all.equal(results[[12]]$fisher_z,atanh(.3))))
cat('PASS 13 formula branches (10 UI wrappers, 3 core-only reliability variants), eight-language tokens and reference calculations\n')
