Sys.setlocale('LC_CTYPE','English_United States.utf8');Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
dir.create('tmp/meta-draft',recursive=TRUE,showWarnings=FALSE)
langs<-c('en','ko','ja','zh','es','fr','de','vi')
keys<-c('reset','add_title','edit_title','save','cancel','moderator_help','study_id','study_name','publication_year','outcome','predictor','included','moderator_categorical','moderator_continuous','format','direction','positive','reverse')
jsonlite::write_json(setNames(lapply(langs,function(lang)setNames(lapply(keys,function(key)meta_ui_text(key,lang)),keys)),langs),'tmp/meta-draft/labels.json',auto_unbox=TRUE)
ui<-fluidPage(selectInput('test_language','Language',c('en','ko','ja','zh','es','fr','de','vi'),'ko'),meta_analysis_tab_panel('ko'))
server<-function(input,output,session)register_meta_server(input,output,session,app_language_fn=function()input$test_language %||% 'ko')
shiny::runApp(shinyApp(ui,server),host='127.0.0.1',port=8876,launch.browser=FALSE)
