Sys.setlocale('LC_ALL','Korean_Korea.utf8')
source('R/app_bootstrap.R',encoding='UTF-8')
load_app_packages(check=FALSE);source_app_modules();options(statedu.app_language='ko')
out<-'outputs/spss_phase22_20260906';dir.create(out,showWarnings=FALSE)
set.seed(20260908)
d<-data.frame(group=factor(sample(c('대조군','실험군'),240,TRUE)),response=factor(sample(c('아니오','예'),240,TRUE)),level=ordered(sample(1:4,240,TRUE)),site=factor(sample(paste0('기관',1:12),240,TRUE)))
info<-data.frame(name=names(d),measurement=c('binary','binary','ordered','category'),var_label=c('집단','응답','수준','기관'))
make<-function(data=d,row='group',col='response',extra=list())prepare_crosstab_results(data,row,col,variable_info=info,options=modifyList(list(row_percent=TRUE,total_n=TRUE),extra))
cases<-list(basic=make(),all_percent=make(extra=list(column_percent=TRUE,total_percent=TRUE)),split=make(extra=list(split_count_percent=TRUE,column_percent=TRUE,total_percent=TRUE)),trend=make(row='level',extra=list(trend=TRUE)),wide=make(col='site',extra=list(split_count_percent=TRUE)))
m<-d;m[1:9,1]<-NA;m[10:13,2]<-NA;cases$missing<-make(m)
s<-data.frame(group=factor(c(rep('대조군',9),rep('실험군',3))),response=factor(c(rep('아니오',8),'예','아니오','예','예')));cases$sparse<-make(s)
cases$multiple<-list(make(),make(row='level'),make(col='site'),make(row='level',col='site'))
for(name in names(cases)) {
 r<-cases[[name]];folder<-file.path(out,name);dir.create(folder,showWarnings=FALSE)
 write_crosstab_results_html(r,file.path(folder,'result.html'))
 html<-paste(readLines(file.path(folder,'result.html'),encoding='UTF-8'),collapse='\n')
 a<-xml2::read_html(as.character(htmltools::renderTags(crosstab_results_ui(r))$html));b<-xml2::read_html(html)
 cells<-function(doc)vapply(xml2::xml_find_all(doc,'.//table//th|.//table//td'),result_html_text,character(1))
 stopifnot(identical(cells(a),cells(b)))
 e<-list(title='Crosstab',html=html,saved_at='2026-09-06')
 write_crosstab_results_pdf(r,file.path(folder,'result.pdf'))
 save_crosstab_excel_file(r,file.path(folder,'result.xlsx'))
 write_result_collection_docx(list(e),file.path(folder,'result.docx'))
 tables<-result_entry_tables(e)
 expected<-list(tables=lapply(tables,function(t)list(title=t$title,orientation=t$orientation,notes=t$notes,cells=lapply(t$screen$cells,function(c)c(c,list(value=t$screen$values[c$row,c$col]))))),images=list())
 jsonlite::write_json(expected,file.path(folder,'expected.json'),auto_unbox=TRUE)
 cat(name,length(tables),'tables; screen/HTML matched\n')
}
