Sys.setlocale('LC_ALL','Korean_Korea.utf8')
source('R/app_bootstrap.R',encoding='UTF-8')
load_app_packages(check=FALSE); source_app_modules()
options(statedu.app_language='ko')
out<-'outputs/spss_phase21_20260906';dir.create(out,showWarnings=FALSE)
set.seed(20260907);z<-rnorm(120)
d<-as.data.frame(sapply(1:12,function(i)z+rnorm(120,sd=.5+i/10)));names(d)<-paste0('x',1:12)
make<-function(data,method='pearson',extra=list(),measure=rep('continuous',ncol(data))) {
 info<-data.frame(name=names(data),measurement=measure,var_label=paste('변수',seq_along(data)))
 prepare_correlation_results(data,names(data),variable_info=info,options=modifyList(list(continuous_method=method,reason=TRUE,p_ci=TRUE,significance_levels=TRUE),extra))
}
cases<-list(pearson=make(d[1:3]),spearman=make(d[1:3],'spearman'),auto=make(d[1:3],'auto'),wide=make(d),plots=make(d[1:3],extra=list(scatter_plot=TRUE,matrix_plot=TRUE)))
m<-d[1:4];m[1:7,1]<-NA;m[8:11,3]<-NA;cases$missing<-make(m)
mixed<-data.frame(continuous=d$x1,ordered=as.integer(cut(d$x2,c(-Inf,-.5,.5,Inf))),binary=as.numeric(d$x3>0),nominal=factor(rep(c('A','B','C'),40)))
cases$mixed<-make(mixed,measure=c('continuous','ordered','binary','category'))
cases$kendall<-make(d[1:3],'kendall')
for(name in names(cases)) {
 r<-cases[[name]];folder<-file.path(out,name);dir.create(folder,showWarnings=FALSE)
 write_correlation_results_html(r,file.path(folder,'result.html'))
 html<-paste(readLines(file.path(folder,'result.html'),encoding='UTF-8'),collapse='\n')
 a<-xml2::read_html(as.character(htmltools::renderTags(correlation_results_ui(r))$html));b<-xml2::read_html(html)
 cells<-function(doc)vapply(xml2::xml_find_all(doc,'.//table//th|.//table//td'),result_html_text,character(1))
 stopifnot(identical(cells(a),cells(b)))
 e<-list(title='Correlation',html=html,saved_at='2026-09-06')
 write_correlation_results_pdf(r,file.path(folder,'result.pdf'))
 save_correlation_excel_file(r,file.path(folder,'result.xlsx'))
 write_result_collection_docx(list(e),file.path(folder,'result.docx'))
 tables<-result_entry_tables(e)
 expected<-list(tables=lapply(tables,function(t)list(title=t$title,orientation=t$orientation,notes=t$notes,cells=lapply(t$screen$cells,function(c)c(c,list(value=t$screen$values[c$row,c$col]))))),images=as.list(xml2::xml_attr(xml2::xml_find_all(b,'.//img'),'alt')))
 jsonlite::write_json(expected,file.path(folder,'expected.json'),auto_unbox=TRUE)
 cat(name,length(tables),'tables',length(expected$images),'images; screen/HTML matched\n')
}
