const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.STATEDU_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1550,height:1050}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:3867');await page.waitForFunction(()=>window.Shiny&&Shiny.shinyapp&&Shiny.shinyapp.$socket.readyState===1);
  await page.locator('a[data-value="Split"]').click();
  await page.locator('[data-input-id="scope_split_available"] [data-value="sex"]').click();
  await page.locator('#scope_split_move').click();
  await page.locator('#scope_split_apply').click();
  await page.locator('.navbar-nav a').filter({hasText:/^Frequencies$/}).click();
  await page.locator('#run_frequencies').click();
  await page.waitForFunction(()=>window.stateduSplitSnapshots&&window.stateduSplitSnapshots.frequencies_results,{},{timeout:30000});
  const text=await page.locator('#frequencies_results').innerText();
  assert(text.includes('sex: Male')&&text.includes('sex: Female'),text);
  assert(text.includes('5.50')||text.includes('5.5'),text);
  assert(text.includes('105.50')||text.includes('105.5'),text);
  assert(!await page.locator('#frequencies_results table').filter({hasText:'Female'}).count(),'Split variable must not have its own frequency table');
  const columns=await page.locator('.statedu-split-group table').evaluateAll(tables=>tables.map(t=>Array.from(t.querySelectorAll('th')).map(c=>c.textContent.trim())));
  assert.deepEqual(columns[0],columns[1],'All groups use the same captured output options');
  await page.evaluate(()=>{
    window.scopeOriginalSetInput=Shiny.setInputValue;
    Shiny.setInputValue=function(id,value,options){if(id==='scope_save'){window.scopeSaveRequest=value;return;}return window.scopeOriginalSetInput(id,value,options);};
  });
  await page.locator('#save_frequencies_html_dialog').click();
  assert.deepEqual(await page.evaluate(()=>({outputId:window.scopeSaveRequest.outputId,format:window.scopeSaveRequest.format})),{outputId:'frequencies_results',format:'html'});
  await page.evaluate(()=>{Shiny.setInputValue=window.scopeOriginalSetInput;});
  fs.mkdirSync('tmp/analysis-scope',{recursive:true});
  fs.writeFileSync('tmp/analysis-scope/split.html',await page.evaluate(()=>window.stateduSplitSnapshots.frequencies_results));
  await page.locator('#frequencies_results').screenshot({path:'tmp/analysis-scope/split.png'});
  // Case selection, followed by split, leaves exactly one independent group.
  await page.locator('a[data-value="Cases"]').click();
  await page.locator('[data-input-id="scope_cases_available"] [data-value="sex"]').click();
  await page.locator('#scope_cases_move').click();
  await page.locator('input[name="scope_cases_values"][value="Male"]').check();
  await page.locator('#scope_cases_apply').click();
  await page.locator('.navbar-nav a').filter({hasText:/^Frequencies$/}).click();
  await page.locator('#run_frequencies').click();
  await page.waitForFunction(()=>window.stateduSplitSnapshots.frequencies_results&&!window.stateduSplitSnapshots.frequencies_results.includes('sex: Female'),{},{timeout:30000});
  assert.equal(await page.locator('.statedu-split-group').count(),1);
  await page.locator('a[data-value="Split"]').click();
  await page.locator('#scope_split_clear').click();
  await page.locator('.navbar-nav a').filter({hasText:/^Frequencies$/}).click();
  await page.locator('#run_frequencies').click();
  await page.waitForFunction(()=>!window.stateduSplitSnapshots.frequencies_results);
  await page.waitForFunction(()=>document.querySelector('#frequencies_results').textContent.includes('5.50')&&!document.querySelector('#frequencies_results').textContent.includes('sex: Male'));
  assert(!(await page.locator('#frequencies_results').innerText()).includes('105.50'));
  await page.locator('a[data-value="Cases"]').click();
  await page.locator('#scope_cases_clear').click();
  await page.locator('a[data-value="Split"]').click();
  await page.locator('[data-input-id="scope_split_available"] [data-value="x"]').click();
  await page.locator('#scope_split_move').click();
  await page.locator('#scope_split_upper').fill('100');
  await page.locator('#scope_split_upper_op').selectOption('lt');
  await page.locator('#scope_split_label').fill('Below 100');
  await page.locator('#scope_split_add_condition').click();
  await page.locator('#scope_split_rules').getByText('Below 100',{exact:true}).waitFor();
  await page.locator('#scope_split_upper').fill('');
  await page.locator('#scope_split_lower').fill('100');
  await page.locator('#scope_split_label').fill('100 and above');
  await page.locator('#scope_split_add_condition').click();
  await page.locator('#scope_split_rules').getByText('100 and above',{exact:true}).waitFor();
  await page.locator('.scope-three-block:visible').screenshot({path:'tmp/analysis-scope/three-block.png'});
  await page.locator('#scope_split_apply').click();
  await page.locator('.navbar-nav a').filter({hasText:/^Frequencies$/}).click();
  await page.locator('#run_frequencies').click();
  await page.waitForFunction(()=>window.stateduSplitSnapshots.frequencies_results?.includes('x: 100 and above'),{},{timeout:30000});
  const ranges=await page.locator('#frequencies_results').innerText();
  assert(ranges.includes('5.50')&&ranges.includes('105.50')&&ranges.includes('x: Below 100'),ranges);
  await page.locator('a[data-value="Cases"]').click();
  await page.locator('input[name="scope_cases_mode"][value="expression"]').check();
  await page.locator('#scope_cases_expression').fill('x == "Female"');
  await page.locator('#scope_cases_apply').click();
  await page.locator('.navbar-nav a').filter({hasText:/^Frequencies$/}).click();
  await page.locator('#run_frequencies').click();
  await page.waitForFunction(()=>window.stateduSplitSnapshots.frequencies_results?.includes('x: 100 and above')&&!window.stateduSplitSnapshots.frequencies_results.includes('x: Below 100'),{},{timeout:30000});
  assert.equal(await page.locator('.statedu-split-group').count(),1);
  assert.deepEqual(errors,[]);
  console.log('PASS: real frequency handler, independent group means, displayed snapshots, combined case selection and split');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
