const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.STATEDU_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1500,height:1100},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('tmp/canvas-export-validation/mm.html')).href);
  for(const css of [fs.readFileSync('tmp/canvas-export-validation/bootstrap-path.txt','utf8').trim(),'www/style.css','www/model-canvas/canvas.css'])await page.addStyleTag({path:css});
  for(const file of ['state','layout','shiny-bridge','edges','nodes','dialogs','toolbar','canvas'])await page.addScriptTag({path:`www/model-canvas/${file}.js`});
  await page.evaluate(()=>{window.showSaveFilePicker=undefined;window.showOpenFilePicker=undefined});
  const settingsHeight=()=>page.locator('.structural-selection-settings').evaluate(e=>e.getBoundingClientRect().height);
  const initialHeight=await settingsHeight();
  const getState=()=>page.evaluate(()=>window.StatEduModelCanvas.state.snapshot(document.querySelector('.custom-model-canvas-root').__stateduModelCanvas.state));
  const paper=await page.locator('.custom-model-paper').boundingBox();
  await page.locator('[data-action="addObserved"]').click();
  await page.mouse.click(paper.x+180,paper.y+240);
  await page.mouse.click(paper.x+520,paper.y+248);
  const placed=await getState();assert.equal(placed.nodes.length,2);
  assert.equal(placed.nodes[0].role,'observed');assert.equal(placed.nodes[1].role,'observed');
  assert.equal(placed.nodes[0].y,placed.nodes[1].y,'new variable snaps to the existing row');
  assert.ok(await settingsHeight()>initialHeight+150,'selection expands settings');
  await page.locator('[data-action="select"]').click();
  await page.locator('.custom-model-node').first().click();
  await page.locator('[data-setting-field="label"]').fill('디지털 헬스 리터러시 평균');
  await page.locator('[data-setting-field="label"]').press('Tab');
  await page.locator('[data-action="autoAlign"]').click();
  const expected=await getState();assert.equal(expected.autoAlign,false);
  assert.equal(expected.nodes[0].canvasLabel,'디지털 헬스 리터러시 평균');
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-action="save"]').click();
  const download=await downloadPromise;
  const dir=path.resolve('tmp/mediation-model-roundtrip');fs.mkdirSync(dir,{recursive:true});
  const file=path.join(dir,download.suggestedFilename());await download.saveAs(file);
  assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),expected,'actual downloaded model contains the visible source state');
  await page.locator('[data-action="autoAlign"]').click();
  await page.locator('.custom-model-node').first().click();
  await page.locator('[data-setting-field="label"]').fill('임시 변경');await page.locator('[data-setting-field="label"]').press('Tab');
  const chooserPromise=page.waitForEvent('filechooser');await page.locator('[data-action="load"]').click();
  await (await chooserPromise).setFiles(file);
  await page.waitForFunction(()=>document.querySelector('.custom-model-canvas-root').__stateduModelCanvas.state.nodes[0].canvasLabel==='디지털 헬스 리터러시 평균');
  const reopened=await getState();
  for(const key of ['nodes','edges','canvas','style','autoAlign','gridVisible'])assert.deepEqual(reopened[key],expected[key],`restored ${key}`);
  assert.ok(Math.abs(await settingsHeight()-initialHeight)<1,'deselected settings return to initial height');
  assert.equal(await page.locator('[data-action="autoAlign"]').getAttribute('aria-pressed'),'false');
  assert.equal(await page.locator('.structural-alignment-guide-layer.is-visible').count(),0);
  await page.screenshot({path:path.join(dir,'reopened.png')});
  assert.deepEqual(errors,[]);
  console.log('PASS: actual node placement and row alignment; Korean label editing; downloaded model and file chooser reload; positions/settings preserved; settings expand and shrink');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
