Sys.setlocale('LC_ALL','Korean_Korea.utf8')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
options(statedu.app_language='ko')
out<-'outputs/spss_phase23_20260906';dir.create(out,showWarnings=FALSE)
set.seed(20260909);base<-as.numeric(scale(rnorm(40)))
d<-data.frame(g2=factor(rep(c('대조','실험'),each=60)),g3=factor(rep(c('낮음','중간','높음'),each=40),levels=c('낮음','중간','높음')))
d$ord<-ordered(d$g3)
d$y<-rep(base,3)+rep(c(0,1,2),each=40)
d$hetero<-rep(base,3)*rep(c(1,3,8),each=40)+rep(c(0,1,2),each=40)
for(i in 1:6)d[[paste0('score',i)]]<-d$y+rnorm(120,sd=.2+i/8)
info<-data.frame(name=names(d),measurement=c('binary','category','ordered',rep('continuous',8)),var_label=c('두 집단','세 집단','순서 집단','측정값','이분산 측정값',paste('점수',1:6)))
make<-function(data=d,dep='y',fac='g2',extra=list())prepare_ttest_anova_results(data,dep,fac,variable_info=info,options=modifyList(list(normality_enabled=FALSE,post_hoc=TRUE,post_hoc_method='tukey',show_df=TRUE,mean_sd=TRUE,effect_size=TRUE,ordered_significance=TRUE),extra))
tdata<-d;tdata$y<-rep(as.numeric(scale(rnorm(60))),2)+rep(c(0,1),each=60)
tw<-tdata;tw$y<-tw$y*rep(c(1,7),each=60)
cases<-list(pooled_t=make(tdata),welch_t=make(tw),anova=make(fac='g3'),welch_anova=make(dep='hetero',fac='g3'),nonparametric=make(fac='g3',extra=list(force_nonparametric=TRUE,mean_sd=FALSE,median_iqr=TRUE,nonparametric_post_hoc_method='holm')),trend=make(fac='ord',extra=list(trend_analysis=TRUE)),wide=make(dep=paste0('score',1:6),fac=c('g2','g3')))
m<-d;m$y[1:8]<-NA;cases$missing<-make(m,fac='g3')
for(name in names(cases)) {
 r<-cases[[name]];folder<-file.path(out,name);dir.create(folder,showWarnings=FALSE)
 write_ttest_anova_results_html(r,file.path(folder,'result.html'))
 html<-paste(readLines(file.path(folder,'result.html'),encoding='UTF-8'),collapse='\n')
 a<-xml2::read_html(as.character(htmltools::renderTags(ttest_anova_results_ui(r))$html));b<-xml2::read_html(html)
 cells<-function(doc)vapply(xml2::xml_find_all(doc,'.//table//th|.//table//td'),result_html_text,character(1))
 stopifnot(identical(cells(a),cells(b)))
 e<-list(title='t-test / ANOVA',html=html,saved_at='2026-09-06')
 write_ttest_anova_results_pdf(r,file.path(folder,'result.pdf'))
 save_ttest_anova_excel_file(r,file.path(folder,'result.xlsx'))
 write_result_collection_docx(list(e),file.path(folder,'result.docx'))
 tables<-result_entry_tables(e)
 expected<-list(tables=lapply(tables,function(t)list(title=t$title,orientation=t$orientation,notes=t$notes,cells=lapply(t$screen$cells,function(c)c(c,list(value=t$screen$values[c$row,c$col]))))),images=list())
 jsonlite::write_json(expected,file.path(folder,'expected.json'),auto_unbox=TRUE)
 saveRDS(r,file.path(folder,'analysis.rds'))
 cat(name,length(tables),'tables; screen/HTML matched\n')
}
