# Cache lifecycle and compatibility tests; never modify installed package files.
source('R/utils.R',encoding='UTF-8')
source('R/setup_custom_model_canvas_structural_bootstrap.R',encoding='UTF-8')
options(statedu.isolated_lavaan_bootstrap_worker=TRUE,statedu.internal.sem_metadata_0621=NULL)
suppressPackageStartupMessages(library(lavaan))
ns<-asNamespace('lavaan'); imp<-parent.env(ns)
names_to_check<-c('lav_object_check_version','packageDescription')
envs<-list(ns,imp)
original<-Map(function(n,e)get(n,e,inherits=FALSE),names_to_check,envs)
locks<-mapply(bindingIsLocked,names_to_check,envs)
assert_restored<-function(){
 stopifnot(identical(original,Map(function(n,e)get(n,e,inherits=FALSE),names_to_check,envs)))
 stopifnot(identical(locks,mapply(bindingIsLocked,names_to_check,envs)))
 stopifnot(is.null(getOption('statedu.internal.lavaan_worker_metadata_fast_path_state')))
}
set.seed(15);d<-data.frame(x=rnorm(100));d$y<-.5*d$x+rnorm(100)
fit<-sem('y~x',data=d,estimator='MLR')
before<-parameterEstimates(fit,standardized=TRUE)
for(owner_first in c(TRUE,FALSE)) {
 a<-structural_canvas_lavaan_worker_metadata_fast_path_install()
 b<-structural_canvas_lavaan_worker_metadata_fast_path_install()
 stopifnot(a$applied,b$applied,a$owned,!b$owned)
 check<-get(names_to_check[1],ns);desc<-get(names_to_check[2],imp)
 stopifnot(identical(check(fit),original[[1]](fit)))
 stopifnot(identical(check(list(arbitrary=1)),list(arbitrary=1)))
 oldfit<-fit;oldfit@version<-'0.6-20'
 stopifnot(identical(suppressWarnings(check(oldfit)),suppressWarnings(original[[1]](oldfit))))
 stopifnot(identical(desc('lavaan',fields='Version'),original[[2]]('lavaan',fields='Version')))
 stopifnot(identical(desc('lavaan',fields=c('Version','Title')),original[[2]]('lavaan',fields=c('Version','Title'))))
 stopifnot(identical(desc('stats',fields='Version'),original[[2]]('stats',fields='Version')))
 if(owner_first)a$restore() else b$restore()
 stopifnot(identical(check,get(names_to_check[1],ns)))
 stopifnot(identical(before,parameterEstimates(fit,standardized=TRUE)))
 if(owner_first)b$restore() else a$restore()
 a$restore();b$restore();assert_restored()
}
tryCatch({a<-structural_canvas_lavaan_worker_metadata_fast_path_install();tryCatch(stop('injected'),finally=a$restore())},error=function(e)NULL)
assert_restored()
step<-if(as.character(packageVersion('lavaan'))=='0.6.21')'lav_lavaan_step17_lavaan' else 'lav_step17_lavaan'
saved<-get(step,ns);locked<-bindingIsLocked(step,ns)
if(locked)unlockBinding(step,ns)
assign(step,function(...)NULL,ns);if(locked)lockBinding(step,ns)
bad<-structural_canvas_lavaan_worker_metadata_fast_path_install()
if(locked)unlockBinding(step,ns)
assign(step,saved,ns);if(locked)lockBinding(step,ns)
stopifnot(!bad$applied,grepl('fingerprint',bad$reason));assert_restored()
cat('PASS version fallback, metadata fields, nested leases in both release orders, exception cleanup, lock restoration and fingerprint rejection:',as.character(packageVersion('lavaan')),'\n')
