Sys.setlocale('LC_ALL','Korean_Korea.utf8')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
r<-list(use_hc3=TRUE,use_bootstrap=TRUE,residual_diagnostics=TRUE,bootstrap_ci_method='bias_corrected',hierarchical_step='Model 1',predictors=c('x1','x2'))
note<-regression_sci_note(r,TRUE,FALSE,TRUE)
symbols<-c('HC3 SE =','LLCI =','ULCI =','Tol =','VIF =','d(dᵤ-4-dᵤ) =','z(p) =','χ²(p) =','f² =')
pos<-vapply(symbols,function(x)regexpr(x,note,fixed=TRUE)[[1]],integer(1))
stopifnot(all(pos>0),all(diff(pos)>0),!grepl('Note.',note,fixed=TRUE))
model_notes<-hierarchical_model_note_lines(list(r))
stopifnot(grepl('Model 1 (Bootstrap + HC3 Regression)',model_notes,fixed=TRUE),!grepl('x1|x2',paste(model_notes,collapse=' ')))
cat('PASS: abbreviation order, no Note. prefix, model/method retained, predictor formula omitted.\n')

group <- list(r,modifyList(r,list(use_hc3=FALSE,use_bootstrap=FALSE)))
group_note <- regression_group_sci_note(group,TRUE,FALSE,TRUE)
stopifnot(grepl('HC3 SE =',group_note,fixed=TRUE),grepl('SE = standard error',group_note,fixed=TRUE),grepl('LLCI =',group_note,fixed=TRUE))
models <- readRDS('outputs/spss_phase32_20260906/three_blocks/analysis.rds')
doc <- xml2::read_html(tags_to_html(hierarchical_results_panel(models)))
blocks <- xml2::xml_find_all(doc,".//div[contains(concat(' ',normalize-space(@class),' '),' hierarchical-standard-model-block ')]")
counts <- vapply(blocks,function(block)length(xml2::xml_find_all(block,".//div[contains(concat(' ',normalize-space(@class),' '),' coefficient-note ')]")),integer(1))
stopifnot(identical(unname(counts),c(0L,0L,1L)))
cat('PASS: hierarchical notes appear on final model only; earlier model SE/CI definitions retained.\n')
