const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.STATEDU_PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
for(const type of ['mediation','cfa','cbsem','plssem']){
const page=await b.newPage({viewport:{width:1500,height:1000}});
await page.setContent(fs.readFileSync('tmp/canvas-export-validation/mm.html','utf8'));
await page.addStyleTag({path:'www/model-canvas/canvas.css'});
await page.evaluate(type=>{const r=document.querySelector('.custom-model-canvas-root');r.className='custom-model-canvas-root '+(type==='mediation'?'mediation-moderation-canvas-root':'structural-equation-canvas-root');r.setAttribute('data-analysis-type',type==='mediation'?'':type);r.setAttribute('data-export-dpi','300');window.Shiny={addCustomMessageHandler:()=>{},setInputValue:()=>{}}},type);
for(const f of ['state','layout','shiny-bridge','edges','nodes','dialogs','toolbar','canvas'])await page.addScriptTag({path:`www/model-canvas/${f}.js`});
const result=await page.evaluate(async type=>{const a=window.StatEduModelCanvas,r=document.querySelector('.custom-model-canvas-root'),i=a.canvas.init(r);let s=a.state.snapshot(i.state);s.canvas.widthPx=700;s.canvas.heightPx=420;s.nodes=[{id:'x',name:'X',canvasLabel:'X',role:type==='mediation'?'independent':'latent',x:100,y:150,width:100,height:50,strokeColor:'#123456'},{id:'y',name:'Y',canvasLabel:'Y',role:type==='mediation'?'dependent':'latent',x:450,y:150,width:100,height:50}];s.edges=[{id:'xy',from:'x',to:'y',label:'.45(.012)',significant:true}];s.covariates=[];s.selectedNodeIds=[];s.selectedNodeId=null;s.showLatentStats=false;a.bridge.applyResult({rootId:r.id,source:s,result:s,show:true});await document.fonts.ready;const bytes=async()=>Array.from(new Uint8Array(await (await a.dialogs.exportPng(i)).arrayBuffer()));const clean=await bytes();const nodes=[...i.paper.querySelectorAll('.custom-model-node')];nodes.forEach((n,j)=>{n.classList.add(j?'has-validation-error':'has-validation-warning');n.dataset.validationMessage='Editor validation';const badge=document.createElement('span');badge.className='structural-validation-badge';badge.textContent='▲';n.appendChild(badge)});const before=nodes.map(n=>[n.className,getComputedStyle(n).borderColor,n.outerHTML]);const exported=await bytes();const after=nodes.map(n=>[n.className,getComputedStyle(n).borderColor,n.outerHTML]);return{clean,exported,before,after};},type);
fs.mkdirSync('tmp/validation-badges',{recursive:true});fs.writeFileSync('tmp/validation-badges/'+type+'-clean.png',Buffer.from(result.clean));fs.writeFileSync('tmp/validation-badges/'+type+'-export.png',Buffer.from(result.exported));assert.ok(Buffer.from(result.exported).equals(Buffer.from(result.clean)),`${type}: editor validation changed exported pixels`);assert.deepEqual(result.after,result.before,`${type}: exporting changed the live validation UI`);console.log('PASS',type,'PNG excludes warning/error badges and preserves custom strokes and live feedback');await page.close();
}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
