Sys.setlocale('LC_ALL','Korean_Korea.utf8')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
options(statedu.app_language='ko')
out<-'outputs/spss_phase24_20260906';dir.create(out,showWarnings=FALSE)
set.seed(20260910);x<-rnorm(60);noise<-residuals(lm(rnorm(60)~x))
d<-data.frame(group=factor(rep(c('대조','처치1','처치2'),each=60)),x=rep(x,3),z=rnorm(180))
d$y<-2*d$x+rep(c(0,1,2),each=60)+rep(noise,3)
for(i in 1:6)d[[paste0('score',i)]]<-d$y+rnorm(180,sd=.2)
info<-data.frame(name=names(d),measurement=c('category',rep('continuous',9)),var_label=c('집단','사전 점수','보조 공변량','측정값',paste('점수',1:6)))
make<-function(data=d,dep='y',cov='x',extra=list())prepare_ancova_results(data,dep,'group',cov,variable_info=info,options=modifyList(list(auto_method='warn',normality_enabled=FALSE,show_df=TRUE,mean_se=TRUE,posthoc_method='holm',ordered_significance=TRUE),extra))
interaction<-d;interaction$y<-rep(c(1,3,5),each=60)*d$x+rep(c(0,1,2),each=60)+rep(noise,3)
robust<-d;robust$y<-2*d$x+rep(c(0,1,2),each=60)+rep(noise,3)*rep(c(1,3,7),each=60)
m<-d;m$y[1:7]<-NA;m$x[8:11]<-NA
cases<-list(standard=make(),type3=make(cov=c('x','z'),extra=list(sum_of_squares='type3',mean_se=FALSE,posthoc_method='bonferroni')),ranked=make(extra=list(force_ranked=TRUE)),interaction=make(interaction,extra=list(auto_method='auto')),robust=make(robust,extra=list(auto_method='auto')),plots=make(extra=list(plot_adjusted_means=TRUE,plot_raw_overlay=TRUE,plot_regression_lines=TRUE,plot_linearity_diagnostics=TRUE,influence_sensitivity=TRUE)),wide=make(dep=paste0('score',1:6)),missing=make(m))
selected<-commandArgs(trailingOnly=TRUE)
for(name in if(length(selected)) intersect(names(cases),selected) else names(cases)) {
 r<-cases[[name]];folder<-file.path(out,name);dir.create(folder,showWarnings=FALSE)
 write_ancova_results_html(r,file.path(folder,'result.html'),info)
 html<-paste(readLines(file.path(folder,'result.html'),encoding='UTF-8'),collapse='\n')
 a<-xml2::read_html(as.character(htmltools::renderTags(ancova_results_ui(r,info))$html));b<-xml2::read_html(html)
 cells<-function(doc)vapply(xml2::xml_find_all(doc,'.//table//th|.//table//td'),result_html_text,character(1))
 stopifnot(identical(cells(a),cells(b)))
 e<-list(title='ANCOVA',html=html,saved_at='2026-09-06')
 write_ancova_results_pdf(r,file.path(folder,'result.pdf'),info)
 save_ancova_excel_file(r,file.path(folder,'result.xlsx'),info)
 write_result_collection_docx(list(e),file.path(folder,'result.docx'))
 tables<-result_entry_tables(e)
 expected<-list(tables=lapply(tables,function(t)list(title=t$title,orientation=t$orientation,notes=t$notes,cells=lapply(t$screen$cells,function(c)c(c,list(value=t$screen$values[c$row,c$col]))))),images=as.list(xml2::xml_attr(xml2::xml_find_all(b,'.//img'),'alt')))
 jsonlite::write_json(expected,file.path(folder,'expected.json'),auto_unbox=TRUE);saveRDS(r,file.path(folder,'analysis.rds'))
 cat(name,length(tables),'tables',length(expected$images),'images; screen/HTML matched\n')
}
