Sys.setenv(STATEDU_MODULE_CACHE="false")
source("R/app_bootstrap.R",encoding="UTF-8")
load_app_packages(check=FALSE);source_app_modules()
reject <- function(expr) stopifnot(inherits(tryCatch(force(expr),error=identity),"error"))
x <- c(-2,0,1,2,3,NA_real_)
stopifnot(identical(analysis_scope_expression(x,"x >= 0 & x < 3"),c(FALSE,TRUE,TRUE,TRUE,FALSE,FALSE)))
stopifnot(identical(analysis_scope_expression(x,"!(x %in% c(0, 1))"),c(TRUE,FALSE,FALSE,TRUE,TRUE,FALSE)))
stopifnot(identical(analysis_scope_expression(factor(c("Male","Female",NA)), 'x == "Male"'),c(TRUE,FALSE,FALSE)))
stopifnot(identical(analysis_scope_expression(x,"age <= -2","age"),c(TRUE,FALSE,FALSE,FALSE,FALSE,FALSE)))
for(expr in c('system("echo bad")','x <- 1','x[1] == 0','base::identity(x)','x == 1; x == 2','x + 1','c(x) == 1'))reject(analysis_scope_expression(x,expr))
range <- function(lower=-Inf,upper=Inf,li=TRUE,ui=TRUE,label="range")list(mode="range",lower=lower,upper=upper,lower_inclusive=li,upper_inclusive=ui,label=label)
stopifnot(identical(analysis_scope_rule_mask(x,range(0,2,TRUE,FALSE)),c(FALSE,TRUE,TRUE,FALSE,FALSE,FALSE)))
stopifnot(identical(analysis_scope_rule_mask(x,range(2,2)),c(FALSE,FALSE,FALSE,TRUE,FALSE,FALSE)))
stopifnot(sum(analysis_scope_rule_mask(x,range()))==5L)
reject(analysis_scope_rule_mask(x,range(2,1)));reject(analysis_scope_rule_mask(x,range(2,2,FALSE)))
d <- data.frame(x=x)
rules <- list(range(upper=1,ui=FALSE,label="Low"),range(lower=1,label="High"))
g <- analysis_scope_condition_groups(d,"x",rules)
stopifnot(length(g)==2L,identical(g[[1]]$data$x,c(-2,0)),identical(g[[2]]$data$x,c(1,2,3)))
reject(analysis_scope_condition_groups(d,"x",list(range(upper=1),range(lower=1))))
reject(analysis_scope_condition_groups(d,"missing",rules))
selected <- analysis_scope_filter(d,list(variable="x",rules=list(range(upper=0),range(lower=3))))
stopifnot(identical(selected$x,c(-2,0,3)),nrow(d)==6L)
message("PASS: category expressions, safe grammar, missing values, inclusive/exclusive bounds, exact values, OR selection, independent split groups, overlap rejection")
