root <- normalizePath('dist/electron/win-unpacked/resources/app.asar.unpacked/app',winslash='/')
setwd(root)
.libPaths(R.home('library'))
source('R/app_bootstrap.R');load_app_packages(check=FALSE);source_app_modules()
stopifnot(hierarchical_stat_header_label('beta')=='\u03B2')
stopifnot(grepl('\u0394 R',hierarchical_delta_footer_label(list()),fixed=TRUE))
value <- htmltools::renderTags(result_cell_content('11.875 (1, 294)',column='F(df1,df2)'))$html
stopifnot(grepl('11.875(1,294)',gsub('[[:space:]]+','',xml2::xml_text(xml2::read_html(value))),fixed=TRUE))
d <- data.frame(x=seq_len(20),y=seq_len(20)^2)
r <- prepare_frequencies_results(d,names(d),variable_info=data.frame(name=names(d),measurement='continuous'))
opts <- list(mean_sd=TRUE,min_max=TRUE,median_iqr=TRUE,skew_kurtosis=TRUE)
table <- frequency_continuous_main_table(r,opts)
stopifnot(attr(table,'result_table_orientation')=='portrait',ncol(table)==10)
cat('PASS: packaged beta, delta, RM degrees of freedom and descriptive portrait\n')
