const assert=require('node:assert/strict');const {chromium}=require(process.env.STATEDU_PLAYWRIGHT_MODULE);
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1550,height:1100}});await p.goto('http://127.0.0.1:3870');await p.waitForFunction(()=>window.easyflowReorderLists?.has('frequency_selected'));
const list=p.locator('[data-input-id="frequency_selected"]');await list.waitFor();await list.evaluate(e=>{e.style.setProperty('height','130px','important');e.style.setProperty('min-height','130px','important');e.style.setProperty('max-height','130px','important')});
const a=await list.locator('[data-value="v1"]').boundingBox(),r=await list.boundingBox();await p.mouse.move(a.x+90,a.y+a.height/2);await p.mouse.down();await p.mouse.move(r.x+90,r.y+r.height-5,{steps:15});await p.waitForFunction(()=>{const e=document.querySelector('[data-input-id="frequency_selected"]');return e.scrollTop>=e.scrollHeight-e.clientHeight-1;});await p.mouse.up();await p.waitForFunction(()=>document.querySelector('#order_check').textContent==='v2,v3,v4,v5,v6,v7,v8,v9,v10,v1');
await p.evaluate(()=>Shiny.setInputValue('frequency_selected_reorder',{order:['v2','bogus'],nonce:Date.now()},{priority:'event'}));
await list.locator('[data-value="v2"]').scrollIntoViewIfNeeded();await list.locator('[data-value="v2"]').click();await p.keyboard.down('Control');await list.locator('[data-value="v3"]').click();await p.keyboard.up('Control');
const x=await list.locator('[data-value="v2"]').boundingBox(),box=await list.boundingBox();await p.mouse.move(x.x+80,x.y+x.height/2);await p.mouse.down();await p.mouse.move(box.x+80,box.y+box.height-5,{steps:12});await p.mouse.up();await p.waitForFunction(()=>document.querySelector('#order_check').textContent==='v4,v5,v6,v7,v8,v9,v10,v1,v2,v3');
for(const [v,role] of [['v1','y'],['v2','y']]){await p.locator(`[data-input-id="penalized_regularized_available"] [data-value="${v}"]`).click();await p.locator(`#penalized_regularized_move_${role}`).click();await p.locator(`[data-input-id="penalized_regularized_${role}"] [data-value="${v}"]`).waitFor();}
const yl=p.locator('[data-input-id="penalized_regularized_y"]');await yl.scrollIntoViewIfNeeded();const y1=await yl.locator('[data-value="v1"]').boundingBox(),y2=await yl.locator('[data-value="v2"]').boundingBox();await p.mouse.move(y1.x+70,y1.y+10);await p.mouse.down();await p.mouse.move(y2.x+70,y2.y+y2.height-1,{steps:10});await p.mouse.up();await p.waitForFunction(()=>document.querySelector('[data-input-id="penalized_regularized_y"] .analysis-transfer-option').dataset.value==='v2');console.log('PASS: shared registration, 10-item first-to-last + auto-scroll, multi-select, invalid payload, dependent-variable ordering');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
