Sys.setlocale('LC_CTYPE','English_United States.utf8');Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
out<-'tmp/longitudinal-error-exports';dir.create(out,recursive=TRUE,showWarnings=FALSE)
source('scripts/validate_longitudinal_actual_mi_ipw.R',encoding='UTF-8')
actual_mi_ipw<-fixtures
source('scripts/validate_longitudinal_ipw_fallback_i18n.R',encoding='UTF-8')
source('scripts/validate_longitudinal_weight_summary_i18n.R',encoding='UTF-8')
source('scripts/validate_longitudinal_ipw_names_i18n.R',encoding='UTF-8')
source('scripts/validate_longitudinal_weight_checklist_i18n.R',encoding='UTF-8')
source('scripts/validate_longitudinal_checklist_models_i18n.R',encoding='UTF-8')
source('scripts/validate_longitudinal_auto_count_i18n.R',encoding='UTF-8')
d<-data.frame(y=c(1,3,2,5,4,6),id=rep(1:3,each=2),time=rep(1:2,3),w=c(0,1,1,1,1,1))
result<-prepare_longitudinal_analysis_result(d,'y','id','time',weight='w',weight_type='sampling',model_type='gee',family='gaussian')
skipped<-attr(result,'skipped');stopifnot(is.data.frame(skipped),nrow(skipped)>0)
keys<-names(statedu_translation_table());keys<-keys[grepl('^longitudinal[.](input_error|execution_error|internal_error|selection_error)[.]',keys)]
messages<-vapply(keys,function(k)statedu_t(k,'en'),character(1));messages<-messages[!grepl('%s',messages,fixed=TRUE)&!endsWith(messages,'Details: ')]
probe<-data.frame(Variable=unname(messages),Details=unname(messages),check.names=FALSE)
raw<-'External user <&> %s'
warning_detail<-'engine: User <&> %s; value=-1.20e-09'
warnings<-data.frame(`Dependent variable`='Warning',`Independent variable`='Skipped',N=6,Warning=paste0('R package warning: ',warning_detail),check.names=FALSE)
status_probe<-data.frame(Variable=c('Warning','Skipped'),Status=c('Warning','Skipped'))
mi_error<-statedu_t('longitudinal.input_error.weights','en')
mi_detail<-paste0('imputation 2 weights: ',mi_error,'; imputation 3: ',mi_error)
mi_base<-'Standard mice-based MI sensitivity; pooled across 5 imputed dataset(s) using Rubin-style total variance. The dependent variable had no missing values in the selected MI data. This is not a dedicated multilevel MI engine.'
compound<-c(mi_detail,paste0(mi_base,' Failed fits: ',mi_detail,'.'),paste0('Observation model failed (',mi_error,'); intercept-only IPW was used. Treat this as a weak IPW sensitivity analysis.'))
compound_probe<-data.frame(Variable=compound,Details=compound)
probe<-rbind(probe,data.frame(Variable=raw,Details=raw))
before<-list(result,probe)
norm<-function(x)gsub('[[:space:]\u00a0]+','',paste(x,collapse=''),perl=TRUE)
for(lang in c('en','ko','ja','zh','es','fr','de','vi')) {
 options(statedu.app_language=lang)
 localized_compound<-longitudinal_appendix_table(compound_probe,lang)
 stopifnot(identical(localized_compound[[1]],compound))
 for(value in localized_compound[[2]])stopifnot(grepl(statedu_t('longitudinal.input_error.weights',lang),value,fixed=TRUE))
 if(lang!='en')stopifnot(all(localized_compound[[2]]!=compound))
 expected_mi<-paste(sprintf(statedu_t('longitudinal.mi_failure.weights',lang),'2',statedu_t('longitudinal.input_error.weights',lang)),sprintf(statedu_t('longitudinal.mi_failure.fit',lang),'3',statedu_t('longitudinal.input_error.weights',lang)),sep='; ')
 stopifnot(localized_compound[[2]][1]==expected_mi)
 external_mi<-'imputation 2: User x.1; 3: tolerance 1e-08 (50%)'
 stopifnot(longitudinal_mi_failure_text(external_mi,lang)==external_mi)
 status<-longitudinal_appendix_table(status_probe,lang)
 stopifnot(identical(status[[1]],status_probe[[1]]),identical(unname(status[[2]]),c(statedu_t('longitudinal.warning.warning',lang),statedu_t('longitudinal.warning.skipped',lang))))
 stopifnot(longitudinal_appendix_text(warnings$Warning,lang)==paste0(statedu_t('longitudinal.warning.package_prefix',lang),warning_detail))
 translated<-longitudinal_appendix_table(probe,lang)
 stopifnot(identical(translated[[1]],probe[[1]]),tail(translated[[2]],1)==raw)
 expected_details<-vapply(probe$Details,function(x)longitudinal_input_error_text(simpleError(x),lang),character(1))
 stopifnot(identical(unname(translated[[2]]),unname(expected_details)))
 ui<-tagList(lapply(weight_results,function(result)longitudinal_table_section('Analysis weights',longitudinal_display_weight_summary_table(list(weight_summary=result$summary)))),lapply(ipw_fallback_results,function(result)longitudinal_table_section('IPW diagnostics',result$diagnostics)),lapply(actual_mi_ipw,function(table)longitudinal_table_section('Missing-data sensitivity results',table)),longitudinal_diagnostics_section(warnings,skipped),longitudinal_table_section('Assumption checks',compound_probe),longitudinal_table_section('Assumption checks',status_probe),longitudinal_table_section('Assumption checks',probe),longitudinal_table_section('Coefficients',data.frame(Term='User',B=.125,SE=.025),role='main'))
 ui<-tagList(lapply(ipw_name_tables,function(table)longitudinal_table_section('Analysis weights',table)),ui)
 ui<-tagList(longitudinal_table_section('SCI reporting checklist',weight_checklist),ui)
 ui<-tagList(lapply(checklist_models,function(table)longitudinal_table_section('SCI reporting checklist',table)),ui)
 ui<-tagList(lapply(auto_count_tables,function(table)longitudinal_table_section('Model fit details',table)),ui)
 panel<-xml2::read_html(as.character(ui),encoding='UTF-8')
 main<-xml2::xml_text(xml2::xml_find_all(panel,'//*[contains(@class,"longitudinal-result-panel--main")]'))
 if(lang=='en')baseline<-main else stopifnot(identical(main,baseline))
 stopifnot(identical(before,list(result,probe)))
 cat('PASS appendix:',lang,'known errors localized; user strings and main table preserved\n');flush.console()
 if(!lang %in% c('ko','ja'))next
 html<-as.character(ui);entry<-list(id=paste0('longitudinal-',lang),title='Longitudinal',html=html)
 for(mode in c('current','accumulated')) {
  entries<-if(mode=='current')list(entry)else list(entry,modifyList(entry,list(id='second')))
  stem<-file.path(out,paste(lang,mode,sep='-'))
  write_result_collection_html(entries,paste0(stem,'.html'))
  write_result_collection_docx(entries,paste0(stem,'.docx'))
  save_result_collection_excel_file(entries,paste0(stem,'.xlsx'))
  write_result_collection_pdf(entries,paste0(stem,'.pdf'))
  write_result_collection_hwpx(entries,paste0(stem,'.hwpx'))
  word<-norm(xml2::xml_text(xml2::read_xml(unz(paste0(stem,'.docx'),'word/document.xml'))))
  members<-unzip(paste0(stem,'.hwpx'),list=TRUE)$Name
  hwpx<-norm(vapply(members[grepl('Contents/section[0-9]+[.]xml$',members)],function(s)xml2::xml_text(xml2::read_xml(unz(paste0(stem,'.hwpx'),s))),character(1)))
  wb<-openxlsx::loadWorkbook(paste0(stem,'.xlsx'))
  excel<-norm(unlist(lapply(seq_along(names(wb)),function(i)as.matrix(openxlsx::read.xlsx(wb,sheet=i,colNames=FALSE)))))
  saved<-norm(xml2::xml_text(xml2::read_html(paste0(stem,'.html'))))
  expected_text<-c(xml2::xml_text(xml2::xml_find_all(panel,'//th|//td|//h2|//h3|//h4|//li')))
  for(value in expected_text[nzchar(trimws(expected_text))])for(actual in list(word,hwpx,excel,saved))if(!grepl(norm(value),actual,fixed=TRUE))stop('Missing content: ',value)
  stopifnot(file.info(paste0(stem,'.pdf'))$size>1000,identical(before,list(result,probe)))
  jsonlite::write_json(expected_text,paste0(stem,'-expected.json'))
  cat('PASS export:',lang,mode,'HTML/Word/HWPX/Excel content; PDF generated\n');flush.console()
 }
}
