Sys.setlocale('LC_ALL','Korean_Korea.utf8')
library(shiny)
source('R/utils.R',encoding='UTF-8')
source('R/labels.R',encoding='UTF-8')
source('R/result_export_files.R',encoding='UTF-8')
source('R/result_saved_ui.R',encoding='UTF-8')
Sys.setenv(STATEDU_REPORT_USER='Hidden User',STATEDU_REPORT_ORGANIZATION='Hidden Institution',STATEDU_VERSION='1.3.0')
langs <- statedu_supported_languages()
covers <- lapply(langs,function(lang) {
 options(statedu.app_language=lang)
 for (edition in c('free','development','personal','pro','institution')) {
  Sys.setenv(STATEDU_EDITION=edition)
  html <- tags_to_html(saved_results_report_cover('StatEdu Studio'))
  doc <- xml2::read_html(html)
  stopifnot(xml2::xml_text(xml2::xml_find_first(doc,".//h1"))==statedu_t('report.cover.title',lang))
  stopifnot(xml2::xml_attr(xml2::xml_find_first(doc,".//div[@class='report-cover']"),'lang')==lang)
  if(edition=='free') stopifnot(grepl('StatEdu, Institute of Statistics',html),!grepl('Hidden User|Hidden Institution',html))
 }
 Sys.setenv(STATEDU_EDITION='free')
 saved_results_report_cover('StatEdu Studio')
})
html <- tags_to_html(tags$html(tags$head(tags$meta(charset='UTF-8'),tags$style(HTML(paste0('html,body{margin:0;padding:0;background:white;}',saved_results_report_cover_css(),'@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact;}}')))),tags$body(covers)))
write_pdf_from_html(html,'output/pdf/free-cover-languages.pdf')
cat('PASS: 8 UI languages, 5 editions, free branding and privacy.\n')
