Sys.setenv(STATEDU_MODULE_CACHE="false")
source("R/app_bootstrap.R",encoding="UTF-8")
load_app_packages(check=FALSE);source_app_modules()
d <- data.frame(sex=c("Male","Female","Male","Female",NA), x=c(1,10,3,20,100))
stopifnot(identical(analysis_scope_filter(d,list(variable="sex",values="Male"))$x,c(1,3)))
groups <- analysis_scope_groups(d,"sex")
stopifnot(length(groups)==2L,identical(vapply(groups,function(g) mean(g$data$x),numeric(1)),c(2,15)),nrow(d)==5L)
stopifnot(length(analysis_scope_groups(analysis_scope_filter(d,list(variable="sex",values="Male")),"sex"))==1L)
stopifnot(nrow(analysis_scope_filter(d,list(variable="sex",values="absent")))==0L)
shiny::testServer(function(input,output,session){
  data <- reactiveVal(d)
  scope <- register_analysis_scope(input,output,session,data,function() "en",function() "file1")
  result <- analysis_scope_result_val(NULL)
  job <- analysis_scope_result_val(NULL,job=TRUE)
  calls <- new.env(); calls$values <- list()
  output$demo_results <- renderUI({req(result()); div(h4("Table"),tags$table(tags$tr(tags$td(result()))))})
  run <- function() { values<-scope$dataset();attr(values,"option")<-input$demo_option;calls$values[[length(calls$values)+1L]]<-values;result(mean(values$x)) }
}, {
  session$flushReact()
  session$setInputs(scope_cases_variable="sex",scope_cases_values="Male",scope_cases_apply=1)
  stopifnot(identical(scope$dataset()$x,c(1,3)),nrow(data())==5L)
  session$setInputs(scope_cases_clear=1,scope_split_variable="sex",scope_split_apply=1,demo_option="first")
  isolate(analysis_scope_run(session,"demo",run,"demo_results"))
  session$flushReact(); stopifnot(length(calls$values)==1L,identical(calls$values[[1]]$x,c(1,3)))
  Sys.sleep(.2);session$elapse(250);session$flushReact()
  session$setInputs(demo_option="changed")
  session$setInputs(scope_group_snapshot=list(token=1,groupIndex=1,html="<table><tr><td>2</td></tr></table>",error=""))
  stopifnot(length(calls$values)==2L,identical(calls$values[[2]]$x,c(10,20)))
  stopifnot(identical(attr(calls$values[[2]],"option"),"first"),identical(input$demo_option,"changed"))
  session$setInputs(scope_group_snapshot=list(token=99,groupIndex=2,html="stale",error=""));stopifnot(length(calls$values)==2L)
  Sys.sleep(.2);session$elapse(250);session$flushReact()
  session$setInputs(scope_group_snapshot=list(token=1,groupIndex=2,html="<table><tr><td>15</td></tr></table>",error=""))
  stopifnot(nrow(scope$dataset())==5L)
  # A pending asynchronous job prevents the next group from starting.
  isolate(analysis_scope_run(session,"demo",function(){run();job(list(process="pending"))},"demo_results"))
  Sys.sleep(.2);session$elapse(250);session$flushReact();stopifnot(length(calls$values)==3L)
  job(NULL);session$elapse(250);session$flushReact()
  session$setInputs(scope_cancel=1)
  session$setInputs(scope_group_snapshot=list(token=2,groupIndex=1,html="<p>Completed first group</p>",error=""))
  stopifnot(length(calls$values)==3L,nrow(scope$dataset())==5L)
})
message("PASS: non-destructive case filter; split means; combined conditions; NA exclusion; sequence; stale capture rejection; asynchronous job wait")
for (run_id in c("run", "run_hierarchical")) shiny::testServer(function(input,output,session) {
  data <- data.frame(sex=rep(c("Male","Female"),each=8),x=rep(1:8,2),y=c(2*(1:8)+1,-3*(1:8)+4))
  scope <- register_analysis_scope(input,output,session,function() data,function() "en",function() "file")
  state <- create_analysis_state(session)
  prepared <- function() list(results=list(model=lm(y~x,data=scope$dataset())),jobs=list())
  args <- c(list(input=input,session=session,penalized_result=state$penalized_result,analysis_result=state$analysis_result,
    bootstrap_job=state$bootstrap_job,bootstrap_job_queue=state$bootstrap_job_queue,
    bootstrap_cancel_requested=state$bootstrap_cancel_requested,bootstrap_status=state$bootstrap_status,
    bootstrap_stop_visible=state$bootstrap_stop_visible,bootstrap_manager=list()),
    setNames(list(prepared),if(run_id=="run")"prepare_analysis_result_fn" else "prepare_hierarchical_result_fn"))
  do.call(if(run_id=="run")register_analysis_run_handlers else register_hierarchical_analysis_run_handlers,args)
}, {
  session$flushReact(); session$setInputs(scope_split_variable="sex",scope_split_apply=1)
  do.call(session$setInputs,setNames(list(1L),run_id))
  stopifnot(abs(coef(state$analysis_result()$model)[[2]]-2)<1e-10)
  Sys.sleep(.2);session$elapse(250);session$flushReact()
  session$setInputs(scope_group_snapshot=list(token=1,groupIndex=1,html="<p>Male regression</p>",error=""))
  stopifnot(abs(coef(state$analysis_result()$model)[[2]]+3)<1e-10)
})
message("PASS: ordinary and hierarchical regression run handlers fit independent group slopes")
