Sys.setlocale("LC_CTYPE", "English_United States.utf8")
Sys.setenv(STATEDU_MODULE_CACHE="false")
source("R/app_bootstrap.R",encoding="UTF-8")
load_app_packages(check=FALSE); source_app_modules()
snapshot <- jsonlite::read_json("tmp/canvas-export-validation/mm-arrow-snapshot.json",simplifyVector=FALSE)
spec <- custom_model_canvas_snapshot_spec(snapshot,c("x","m","y","w","c"))
stopifnot(identical(spec$roles$x,"x"),identical(spec$roles$mediators,"m"),identical(spec$roles$y,"y"),identical(spec$roles$w,"w"),identical(spec$roles$covariates,"c"),identical(spec$moderated_paths,"xm"))
legacy <- snapshot
legacy$nodes <- lapply(legacy$nodes,function(node) {node$autoRole <- NULL;node})
stopifnot(identical(spec,custom_model_canvas_snapshot_spec(legacy,c("x","m","y","w","c"))))
stale <- snapshot
stale$nodes <- lapply(stale$nodes,function(node) {node$role <- "dependent";node})
stopifnot(identical(spec,custom_model_canvas_snapshot_spec(stale,c("x","m","y","w","c"))))
fails <- function(snapshot,pattern) stopifnot(grepl(pattern,tryCatch({custom_model_canvas_snapshot_spec(snapshot,c("x","m","y","w","c"),language="en");"NO ERROR"},error=conditionMessage),fixed=TRUE))
empty <- snapshot;empty$nodes[[1]]$unassigned <- TRUE;fails(empty,"empty boxes")
unconnected <- snapshot;unconnected$moderations <- list();fails(unconnected,"unconnected")
cyclic <- snapshot;cyclic$edges <- c(cyclic$edges,list(list(id="cycle",from=snapshot$nodes[[3]]$id,to=snapshot$nodes[[1]]$id)));fails(cyclic,"Cyclic")
serial <- list(nodes=lapply(c("x","m1","m2","y"),function(name) list(id=name,variableId=name,role="observed",autoRole=TRUE,x=match(name,c("y","m2","m1","x")),y=1)),edges=list(list(id="a",from="x",to="m1"),list(id="b",from="m1",to="m2"),list(id="c",from="m2",to="y")),moderations=list(),covariates=character())
serial_spec <- custom_model_canvas_snapshot_spec(serial,c("x","m1","m2","y"))
stopifnot(identical(serial_spec$roles$mediators,c("m1","m2")),identical(serial_spec$mediator_arrangement,"serial"))
multiple <- serial
multiple$nodes <- c(multiple$nodes,list(list(id="y2",variableId="y2",autoRole=TRUE,x=0,y=3)))
multiple$edges <- c(multiple$edges,list(list(id="d",from="m2",to="y2")))
stopifnot(setequal(custom_model_canvas_snapshot_spec(multiple,c("x","m1","m2","y","y2"))$roles$y,c("y","y2")))
message("PASS: browser snapshot -> R specification, legacy equivalence, stale-role inference, disconnected/cycle validation and serial topology independent of positions")
