Sys.setlocale('LC_CTYPE','English_United States.utf8');Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
d<-data.frame(id=rep(1:10,each=3),time=rep(0:2,10),y=1:30,aux=31:60)
info<-data.frame(name=names(d),measurement='continuous')
initial<-normalize_longitudinal_settings(list(variables=list(outcome='y',id='id',time='time'),options=list(model_type='gee',missing_strategy='ipw',ipw_auxiliary='aux')))
shiny::testServer(function(input,output,session){
 restore<-reactiveVal(list(settings=initial))
 module<-register_longitudinal_handlers(input,output,session,function()names(d),function()d,function()info,function()character(),function()NULL,function(){},restore_request_fn=restore)
}, {
 session$flushReact();stopifnot(identical(module$settings()$options$ipw_auxiliary,'aux'))
 session$setInputs(longitudinal_ipw_auxiliary='aux');session$flushReact()
 session$setInputs(longitudinal_ipw_auxiliary=NULL);session$flushReact()
 stopifnot(length(module$settings()$options$ipw_auxiliary)==0)
 session$setInputs(longitudinal_ipw_auxiliary='aux');session$flushReact()
 session$setInputs(longitudinal_missing_strategy='mi');session$flushReact()
 session$setInputs(longitudinal_ipw_auxiliary=NULL);session$flushReact()
 stopifnot(identical(module$settings()$options$ipw_auxiliary,'aux'))
 session$setInputs(longitudinal_missing_strategy='ipw');session$flushReact()
 stopifnot(identical(module$settings()$options$ipw_auxiliary,'aux'))
})
cat('PASS auxiliary restore, explicit clear, reselection, and hidden-control preservation\n')
