invisible(Sys.setlocale("LC_ALL","Korean_Korea.utf8"))
module<-normalizePath("modules/latent_mplus/app",winslash="/")
for(f in c("utils.R","ui_helpers.R","latent_ui.R","app_server.R"))source(file.path(module,"R",f),encoding="UTF-8")
root<-tempfile("latent_best_k_");dir.create(root)
data_path<-file.path(root,"data.csv");write.csv(data.frame(id=1:4,y=1:4),data_path,row.names=FALSE)
setup<-list(data=list(source_file=list(path=data_path),variables=list(list(name="id",measurement="continuous"),list(name="y",measurement="continuous"))),roles=list(id="id",indicator="y"),analysis=list(best_k_rule="hybrid"))
write_latent_dataset_files(root,"automatic",setup)
cfg<-yaml::read_yaml(file.path(root,"data/automatic/config/CFG.yml"))
stopifnot(is.null(cfg$estimation[["best_k"]]),identical(cfg$estimation$best_k_rule,"hybrid"))
setup$analysis$best_k<-3L
write_latent_dataset_files(root,"manual",setup)
cfg<-yaml::read_yaml(file.path(root,"data/manual/config/CFG.yml"))
stopifnot(identical(cfg$estimation[["best_k"]],3L))
cat("PASS: omitted best_k does not partially match best_k_rule; manual selection preserved\n")
