Sys.setlocale('LC_CTYPE','Korean_Korea.utf8');Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
parse_table <- function(html)result_html_table_cells(xml2::xml_find_first(xml2::read_html(html),'//table'))
single <- parse_table('<table class="sample-size-result-table"><tbody><tr><th>Power</th><td>0.800</td></tr></tbody></table>')
multi <- parse_table('<table class="sample-size-result-table"><tbody><tr><th>Design</th><td>Paired t-test</td></tr><tr><th>Power</th><td>0.800</td></tr></tbody></table>')
ordinary <- parse_table('<table><tr><th>Variable</th><th>n</th></tr><tr><td>x</td><td>100</td></tr></table>')
explicit <- parse_table('<table class="sample-size-result-table"><thead><tr><th>Variable</th><th>n</th></tr></thead><tbody><tr><td>x</td><td>100</td></tr></tbody></table>')
stopifnot(single$header_rows==0L,multi$header_rows==0L,ordinary$header_rows==1L,explicit$header_rows==1L,nrow(single$values)==1L,single$values[1,2]=='0.800',multi$values[1,2]=='Paired t-test')
cat('PASS sample-size row labels, single/multiple body rows, ordinary and explicit column headers\n')
