Sys.setlocale('LC_CTYPE','English_United States.utf8')
Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
root<-normalizePath('tmp/survival-settings-persistence',winslash='/',mustWork=TRUE)
original<-read_settings_json_file(file.path(root,'ja.studio'))
stopifnot(!is.null(original$survival))
saved_path<-save_settings_file(initial_dir=root)
stopifnot(length(saved_path)==1L,nzchar(saved_path))
saved<-write_settings_json_file(original,saved_path)
cat('SAVED:',saved$path,'\n')
loaded_path<-open_settings_file()
stopifnot(length(loaded_path)==1L,nzchar(loaded_path))
loaded<-read_settings_json_file(loaded_path)
stopifnot(identical(normalizePath(loaded_path),normalizePath(saved$path)),identical(loaded$app_language,original$app_language),identical(normalize_survival_settings(loaded$survival),normalize_survival_settings(original$survival)))
cat('PASS: native Save/Open dialogs; same file; Japanese language and all KM/Cox/competing options preserved\n')
