Sys.setlocale('LC_CTYPE','English_United States.utf8');Sys.setenv(STATEDU_MODULE_CACHE='false')
source('R/app_bootstrap.R',encoding='UTF-8');load_app_packages(check=FALSE);source_app_modules()
paths <- vapply(1:4,function(i)tempfile(fileext='.csv'),character(1))
for(i in 1:4)write.csv(data.frame(id=c(1,2),Review=c(i*10,i*20)),paths[i],row.names=FALSE)
first <- data.frame(name=c('a.csv','b.csv'),datapath=paths[1:2])
second <- data.frame(name=c('a.csv','b.csv'),datapath=paths[3:4])
server <- function(input,output,session) {
 lang <- reactiveVal('en')
 register_merge_handlers(input,output,session,function(...)TRUE,function()NULL,lang)
}
shiny::testServer(server, {
 session$setInputs(merge_files=first,merge_csv_header=TRUE,merge_mode='variables',merge_id_variable='id',merge_join_type='left',preview_merge_data=0)
 session$flushReact();session$setInputs(preview_merge_data=1)
 stopifnot(!is.null(output$merge_data_message))
 lang('ja');session$flushReact()
 stopifnot(!is.null(output$merge_data_message))
 session$setInputs(merge_files=second)
 stopifnot(is.null(output$merge_data_message))
 session$setInputs(preview_merge_data=2)
 stopifnot(!is.null(output$merge_data_message))
 session$setInputs(merge_join_type='inner')
 stopifnot(is.null(output$merge_data_message))
 session$setInputs(preview_merge_data=3)
 session$setInputs(merge_id_variable='missing')
 stopifnot(is.null(output$merge_data_message))
 cat('PASS: language preserves preview; same-name replacement and edited settings invalidate previous preview\n')
})
unlink(paths)
